### ISSUE TITLE
该如何设置才能让书籍的旧期刊自动归类到Back Issue里?

### ISSUE THREAD

**Issue by convexshiba** [cdhigh/KindleEar#114]
看到MobileRead里说只要title一样就可以...
但是尝试了一下 在Paperwhite1里是不行的..依旧都会显示出来
有没有什么解决办法?

**Comment by WangZhengmao** [comment]
kindle3之后的kindle 应该是可以的，用btsync同步BN65HEIIH6P6YPIN7CJQQ2A6ZDKBAZOYZ试试看看这里的期刊能不能自动归档。

**Comment by mingde816** [comment]
同问如何才能自动归档。。。
理论上说名字一样可以的，但是如果把推送名字改为KindleEar，第二次会自动加上时间戳，比如KindleEar (2016-03-17T20_21_06.811)
日亚上免费的杂志和漫画是可以自动归类的
