### ISSUE TITLE
推送出现UnknownQueueError如何解决？

### ISSUE THREAD

**Issue by zhu327** [cdhigh/KindleEar#122]
2014-10-16 21:22:52.595 /deliver?u=admin 500 260ms 0kb Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.1.17 (KHTML, like Gecko) Version/7.1 Safari/537.85.10 module=default version=1
E 2014-10-16 21:22:52.594 Traceback (most recent call last):
E 2014-10-16 21:22:52.594 File "/base/data/home/apps/s~feedlykindle/1.379188079166852822/lib/web/application.py", line 239, in process
E 2014-10-16 21:22:52.594 return self.handle()
E 2014-10-16 21:22:52.594 File "/base/data/home/apps/s~feedlykindle/1.379188079166852822/lib/web/application.py", line 230, in handle
E 2014-10-16 21:22:52.594 return self._delegate(fn, self.fvars, args)
E 2014-10-16 21:22:52.594 File "/base/data/home/apps/s~feedlykindle/1.379188079166852822/lib/web/application.py", line 420, in _delegate
E 2014-10-16 21:22:52.594 return handle_class(cls)
E 2014-10-16 21:22:52.594 File "/base/data/home/apps/s~feedlykindle/1.379188079166852822/lib/web/application.py", line 396, in handle_class
E 2014-10-16 21:22:52.594 return tocall(*args)
E 2014-10-16 21:22:52.594 File "/base/data/home/apps/s~feedlykindle/1.379188079166852822/apps/View/Deliver.py", line 56, in GET
E 2014-10-16 21:22:52.594 self.queueit(user, book.key().id(), book.separate)
E 2014-10-16 21:22:52.594 File "/base/data/home/apps/s~feedlykindle/1.379188079166852822/apps/View/Deliver.py", line 31, in queueit
E 2014-10-16 21:22:52.594 params=param,target="worker")
E 2014-10-16 21:22:52.594 File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/taskqueue/taskqueue.py", line 2284, in add
E 2014-10-16 21:22:52.594 queue_name=queue_name, transactional=transactional)
E 2014-10-16 21:22:52.594 File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/taskqueue/taskqueue.py", line 1132, in add
E 2014-10-16 21:22:52.594 return self.add_async(queue_name, transactional).get_result()
E 2014-10-16 21:22:52.595 File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 612, in get_result
E 2014-10-16 21:22:52.595 return self.__get_result_hook(self)
E 2014-10-16 21:22:52.595 File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/taskqueue/taskqueue.py", line 1958, in ResultHook
E 2014-10-16 21:22:52.595 raise exception
E 2014-10-16 21:22:52.595 UnknownQueueError

**Comment by Lavande** [comment]
最近因为各种原因重新部署了几次新的kindle ear，但是都必须运行上面的命令才能正常‘deliver now‘。而且现在FAQ里没有关于internal server error的解决方法阿，还是搜了这个repo才找到这个issue的……
