### ISSUE TITLE
喷嚏图卦是不是挂了？

### ISSUE THREAD

**Issue by ipepys** [cdhigh/KindleEar#154]
这几天都没有收到推送

**Comment by lixingcong** [comment]
我的从12月28号到今天2号都nonews....
网页版的可以打开，就是不能推送
http://dapenti.com/blog/blog.asp?subjectid=70&name=xilei
难道api被封了？？

**Comment by lixingcong** [comment]
http://www.pentitugua.com/rss.xml

**Comment by cdhigh** [comment]
在1.20.14修正。

**Comment by lixingcong** [comment]
其实我不明白为啥直接添加rss源会推送nonews:
http://www.pentitugua.com/rss.xml
而你在1.20.14版中改动几行就OK了。。。。
能简单解释一下原理吗

**Comment by cdhigh** [comment]
因为喷嚏图啩的RSS里面的日期信息设置不符合各项国际标准，导致日期解析出错，所以直接添加RSS推送时要同时在“设置”页面下面的“自定义RSS设置”的选项“最旧文章”设置为“不限制”，但是这样会将RSS中的所有历史文章都一并抓取，会导致书籍过大。
而py文件的设置不管日期，仅抓取最新一篇文章。
所以还是在py文件中修改，然后合并入推送文件比较好。
