### ISSUE TITLE
今天没收到推送，怎么查原因？

### ISSUE THREAD

**Issue by zxq1002** [cdhigh/KindleEar#156]
推送日志里也没记录，出现过几次了

**Comment by cdhigh** [comment]
打开GAE后台，查看logs，如果看不懂，就贴上来。

**Comment by zxq1002** [comment]
![image](https://cloud.githubusercontent.com/assets/9085824/5789171/b04ad16e-9e9a-11e4-939f-69b3e1d5ff6d.jpg)

**Comment by cdhigh** [comment]
拷贝文字出来吧，下面看不到了，接下来的才是更重要的。

**Comment by zxq1002** [comment]
專案
KindleEar
總覽
權限
計費功能與設定
API 和驗證
API
憑證
同意畫面
推送
監控
追蹤項目
紀錄
資訊主頁與快訊
原始碼
運算
網路相關設定
儲存空間
巨量資料
支援
需要協助嗎？
隱私權與條款 
全部展開 App Engine  worker  1 (預設)  任何紀錄層級 到： 2015-01-16 (06:54:21) HKT   
 
2015-01-16 已掃描：2014-12-22 (07:10:16) - 2014-12-22 (07:10:16)
 A 07:10:16.806 2014-12-22  200 0 B 29ms /_ah/stop
2014-12-23
 I 06:40:09.699 2014-12-23  404 123 B 1360ms /_ah/start
 W 06:43:44.579 2014-12-23  200 140 B 217206ms /worker?u=admin&id=5105650963054592%2C5714163003293696%2C5722646637445120
 A 07:13:45.375 2014-12-23  200 0 B 36ms /_ah/stop
2014-12-24
 I 06:40:23.255 2014-12-24  404 123 B 1948ms /_ah/start
 W 06:42:43.216 2014-12-24  200 140 B 142003ms /worker?u=admin&id=5105650963054592%2C5714163003293696%2C5722646637445120
 A 07:12:43.983 2014-12-24  200 0 B 37ms /_ah/stop
 I 23:46:16.991 2014-12-24  404 123 B 1503ms /_ah/start
 W 23:47:39.896 2014-12-24  200 113 B 85338ms /url2book?to=zxq1002%40kindle.cn&u=admin&urls=https%3A%2F%2Fprogit2.s3.amazonaws.com%2Fzh%2F2014-12-11-cdfe5%2Fprogit-zh.215.mobi%7Chttps%3A%2F%2Fprogit2.s3.amazonaws.com%2Fen%2F2014-12-22-6528f%2Fprogit-en.240.mobi&tz=8&lng=zh-cn&keepimage=1&type=Download&subject=Pro+Git+%E7%AC%AC%E4%BA%8C%E7%89%88
2014-12-25
 A 00:17:40.895 2014-12-25  200 0 B 28ms /_ah/stop
 I 00:44:34.442 2014-12-25  404 123 B 1135ms /_ah/start
 W 00:45:26.839 2014-12-25  200 113 B 53551ms /url2book?to=zxq1002%40kindle.cn&u=admin&urls=https%3A%2F%2Fprogit2.s3.amazonaws.com%2Fen%2F2014-12-22-6528f%2Fprogit-en.240.mobi&tz=8&lng=zh-cn&keepimage=1&type=Download&subject=Pro+git+2nd
 A 01:15:27.723 2014-12-25  200 0 B 34ms /_ah/stop
 I 06:40:30.646 2014-12-25  404 123 B 1200ms /_ah/start
 W 06:42:38.120 2014-12-25  200 140 B 129444ms /worker?u=admin&id=5105650963054592%2C5714163003293696%2C5722646637445120
 A 07:12:39.080 2014-12-25  200 0 B 25ms /_ah/stop
2014-12-26
 I 06:40:38.791 2014-12-26  404 123 B 1682ms /_ah/start
 E 06:41:49.218 2014-12-26  500 135 B 73055ms /worker?u=admin&id=5105650963054592%2C5676830073815040%2C5714163003293696%2C5720147234914304%2C5722646637445120
 E 06:43:49.759 2014-12-26  500 135 B 60515ms /worker?u=admin&id=5105650963054592%2C5676830073815040%2C5714163003293696%2C5720147234914304%2C5722646637445120
 E 06:46:49.565 2014-12-26  500 135 B 59770ms /worker?u=admin&id=5105650963054592%2C5676830073815040%2C5714163003293696%2C5720147234914304%2C5722646637445120
 A 07:16:50.182 2014-12-26  200 0 B 42ms /_ah/stop
 I 22:47:47.651 2014-12-26  404 123 B 1310ms /_ah/start
 A 22:48:18.378 2014-12-26  200 134 B 32658ms /url2book?to=zxq1002%40kindle.cn&u=admin&urls=http%3A%2F%2Fdoc.gitlab.com%2Fce%2Fworkflow%2Fworkflow.html%7Chttp%3A%2F%2Fdoc.gitlab.com%2Fce%2Fworkflow%2Fproject_features.html%7Chttp%3A%2F%2Fdoc.gitlab.com%2Fce%2Fworkflow%2Fauthorization_for_merge_requests.html%7Chttp%3A%2F%2Fdoc.gitlab.com%2Fce%2Fworkflow%2Fgroups.html%7Chttp%3A%2F%2Fdoc.gitlab.com%2Fce%2Fworkflow%2Flabels.html%7Chttp%3A%2F%2Fdoc.gitlab.com%2Fce%2Fworkflow%2Fgitlab_flow.html%7Chttp%3A%2F%2Fdoc.gitlab.com%2Fce%2Fworkflow%2Fnotifications.html%7Chttp%3A%2F%2Fdoc.gitlab.com%2Fce%2Fworkflow%2Fmigrating_from_svn.html&tz=8&lng=zh-cn&keepimage=1&type=mobi&subject=GitLab+Documenta
 A 23:18:19.048 2014-12-26  200 0 B 33ms /_ah/stop
2014-12-27
 I 06:40:47.396 2014-12-27  404 123 B 1289ms /_ah/start
 W 06:44:01.803 2014-12-27  200 140 B 196279ms /worker?u=admin&id=5105650963054592%2C5714163003293696%2C5722646637445120%2C5741031244955648
 A 07:14:01.978 2014-12-27  200 0 B 30ms /_ah/stop
2014-12-28
 I 06:40:55.913 2014-12-28  404 123 B 1491ms /_ah/start
 W 06:42:28.414 2014-12-28  200 140 B 94767ms /worker?u=admin&id=5105650963054592%2C5714163003293696%2C5722646637445120
 A 07:12:29.086 2014-12-28  200 0 B 32ms /_ah/stop
2014-12-29
 I 06:41:05.025 2014-12-29  404 123 B 1205ms /_ah/start
 W 06:42:27.392 2014-12-29  200 140 B 84443ms /worker?u=admin&id=5105650963054592%2C5714163003293696%2C5722646637445120
 A 07:12:28.085 2014-12-29  200 0 B 37ms /_ah/stop
2014-12-30
 I 06:41:12.820 2014-12-30  404 123 B 1637ms /_ah/start
 W 06:43:44.492 2014-12-30  200 140 B 153961ms /worker?u=admin&id=5105650963054592%2C5714163003293696%2C5722646637445120
2014-12-31
 I 06:41:21.467 2014-12-31  404 123 B 1750ms /_ah/start
 W 06:43:26.490 2014-12-31  200 140 B 127683ms /worker?u=admin&id=5105650963054592%2C5714163003293696%2C5722646637445120
2015-01-01
 I 06:41:34.967 2015-01-01  404 123 B 1620ms /_ah/start
 W 06:43:55.766 2015-01-01  200 140 B 143000ms /worker?u=admin&id=5105650963054592%2C5714163003293696%2C5722646637445120
 A 07:13:56.690 2015-01-01  200 0 B 47ms /_ah/stop
2015-01-02
 I 06:41:42.606 2015-01-02  404 123 B 1537ms /_ah/start
 E 06:42:14.891 2015-01-02  500 135 B 34665ms /worker?u=admin&id=5105650963054592%2C5676830073815040%2C5714163003293696%2C5720147234914304%2C5722646637445120
 E 06:43:44.738 2015-01-02  500 135 B 29814ms /worker?u=admin&id=5105650963054592%2C5676830073815040%2C5714163003293696%2C5720147234914304%2C5722646637445120
 E 06:46:17.419 2015-01-02  500 135 B 32607ms /worker?u=admin&id=5105650963054592%2C5676830073815040%2C5714163003293696%2C5720147234914304%2C5722646637445120
 E 06:52:19.503 2015-01-02  500 135 B 122030ms /worker?u=admin&id=5105650963054592%2C5676830073815040%2C5714163003293696%2C5720147234914304%2C5722646637445120
 A 07:22:19.767 2015-01-02  200 0 B 37ms /_ah/stop
2015-01-03
 I 06:41:50.609 2015-01-03  404 123 B 1367ms /_ah/start
 W 06:43:19.677 2015-01-03  200 140 B 90921ms /worker?u=admin&id=5105650963054592%2C5714163003293696%2C5722646637445120%2C5741031244955648
 A 07:13:20.757 2015-01-03  200 0 B 36ms /_ah/stop
2015-01-04
 I 06:41:58.475 2015-01-04  404 123 B 1747ms /_ah/start
 W 06:43:38.565 2015-01-04  200 140 B 102916ms /worker?u=admin&id=5105650963054592%2C5714163003293696%2C5722646637445120
 A 07:13:39.260 2015-01-04  200 0 B 8ms /_ah/stop
2015-01-05
 I 06:42:04.290 2015-01-05  404 123 B 1420ms /_ah/start
 W 06:43:26.083 2015-01-05  200 140 B 84170ms /worker?u=admin&id=5105650963054592%2C5714163003293696%2C5722646637445120
 A 07:13:26.291 2015-01-05  200 0 B 16ms /_ah/stop
 I 22:37:30.793 2015-01-05  404 123 B 1963ms /_ah/start
 A 22:37:41.377 2015-01-05  200 134 B 13509ms /url2book?to=zxq1002%40kindle.cn&u=admin&urls=http%3A%2F%2Fvelocity.apache.org%2Fengine%2Fdevel%2Fdeveloper-guide.html&tz=8&lng=zh-cn&keepimage=1&type=mobi&subject=Velocity+Develop
 A 23:07:42.359 2015-01-05  200 0 B 9ms /_ah/stop
2015-01-06
 I 06:42:55.893 2015-01-06  404 123 B 1247ms /_ah/start
 W 06:44:19.351 2015-01-06  200 140 B 85274ms /worker?u=admin&id=5105650963054592%2C5714163003293696%2C5722646637445120
 A 07:14:20.373 2015-01-06  200 0 B 10ms /_ah/stop
2015-01-07
 I 06:43:04.138 2015-01-07  404 123 B 1591ms /_ah/start
 W 06:46:09.292 2015-01-07  200 140 B 187702ms /worker?u=admin&id=5105650963054592%2C5714163003293696%2C5722646637445120
 A 07:16:10.300 2015-01-07  200 0 B 10ms /_ah/stop
2015-01-08
 I 06:43:20.590 2015-01-08  404 123 B 1814ms /_ah/start
 W 06:47:28.651 2015-01-08  200 140 B 250339ms /worker?u=admin&id=5105650963054592%2C5714163003293696%2C5722646637445120
2015-01-09
 I 06:43:33.146 2015-01-09  404 123 B 1920ms /_ah/start
 E 06:45:46.025 2015-01-09  500 135 B 135763ms /worker?u=admin&id=5105650963054592%2C5676830073815040%2C5714163003293696%2C5720147234914304%2C5722646637445120
 E 06:48:35.496 2015-01-09  500 135 B 109394ms /worker?u=admin&id=5105650963054592%2C5676830073815040%2C5714163003293696%2C5720147234914304%2C5722646637445120
 E 06:52:09.397 2015-01-09  500 135 B 93794ms /worker?u=admin&id=5105650963054592%2C5676830073815040%2C5714163003293696%2C5720147234914304%2C5722646637445120
 A 07:22:10.216 2015-01-09  200 0 B 26ms /_ah/stop
2015-01-10
 I 06:43:39.833 2015-01-10  404 123 B 1497ms /_ah/start
 W 06:46:10.848 2015-01-10  200 140 B 153523ms /worker?u=admin&id=5105650963054592%2C5714163003293696%2C5722646637445120%2C5741031244955648
 A 07:16:11.294 2015-01-10  200 0 B 40ms /_ah/stop
2015-01-11
 I 06:43:48.737 2015-01-11  404 123 B 1563ms /_ah/start
 W 06:45:06.698 2015-01-11  200 140 B 80403ms /worker?u=admin&id=5105650963054592%2C5714163003293696%2C5722646637445120
 A 07:15:07.473 2015-01-11  200 0 B 33ms /_ah/stop
2015-01-12
 I 06:43:56.446 2015-01-12  404 123 B 1581ms /_ah/start
 A 06:44:52.872 2015-01-12  200 140 B 58953ms /worker?u=admin&id=5105650963054592%2C5714163003293696%2C5722646637445120
 A 07:14:53.260 2015-01-12  200 0 B 61ms /_ah/stop
2015-01-13
 I 06:44:03.203 2015-01-13  404 123 B 1569ms /_ah/start
 W 06:46:17.352 2015-01-13  200 140 B 135756ms /worker?u=admin&id=5105650963054592%2C5714163003293696%2C5722646637445120
 A 07:16:17.872 2015-01-13  200 0 B 45ms /_ah/stop
2015-01-14
 I 06:44:13.006 2015-01-14  404 123 B 1383ms /_ah/start
 W 06:46:51.138 2015-01-14  200 140 B 160563ms /worker?u=admin&id=5105650963054592%2C5714163003293696%2C5722646637445120
 A 07:16:51.957 2015-01-14  200 0 B 43ms /_ah/stop
2015-01-15
 I 06:44:21.685 2015-01-15  404 123 B 1590ms /_ah/start
 W 06:46:43.351 2015-01-15  200 140 B 144125ms /worker?u=admin&id=5105650963054592%2C5714163003293696%2C5722646637445120
 A 07:16:43.757 2015-01-15  200 0 B 42ms /_ah/stop
2015-01-16
 I 06:44:35.027 2015-01-16  404 123 B 2046ms /_ah/start
 E 06:47:37.968 2015-01-16  500 135 B 186062ms /worker?u=admin&id=5105650963054592%2C5676830073815040%2C5714163003293696%2C5720147234914304%2C5722646637445120
 E 06:50:27.953 2015-01-16  500 135 B 109931ms /worker?u=admin&id=5105650963054592%2C5676830073815040%2C5714163003293696%2C5720147234914304%2C5722646637445120
 E 06:54:21.989 2015-01-16  500 135 B 114031ms /worker?u=admin&id=5105650963054592%2C5676830073815040%2C5714163003293696%2C5720147234914304%2C5722646637445120
0.1.0.2 - - [15/Jan/2015:14:54:21 -0800] "GET /worker?u=admin&id=5105650963054592%2C5676830073815040%2C5714163003293696%2C5720147234914304%2C5722646637445120 HTTP/1.1" 500 135 "http://kindleear-zxq.appspot.com/deliver" "AppEngine-Google; (+http://code.google.com/appengine)" "worker.kindleear-zxq.appspot.com" ms=114031 cpu_ms=28383 cpm_usd=0.006446 queue_name=deliverqueue1 task_name=73620166413679029351 instance=0 app_engine_release=1.9.17
W 06:54:19.443 fetch img failed(err:404):data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFMAAAAaCAMAAAD8O5CWAAAB41BMVEUyUnmOpL5NeKXm5uZaeJfEzdc8aJb/9bgamtucZMi8ZKao08X4WIstltmcVCc6XG0t9Og7Vpf5k6WX17lLCTpLiTu+BNcJVCYYVPj8zT2eFdireDm7W4w89GfbOmtMRzotA9a5rMzMzo7PBuiKY1WoJZdJRJhL1dfaFKbJI7ZZNyjq5+m7hBY4pAXoLAy9ZEeq6Wqr5pjLNSldRDdqqEnrydw+Y/bZ1+q9bO1t/d4+hKcZt7lbOuv9Q4XomLtt5ie5hKjM5llsW1w9RphqTEz91FaI5tjK5Qa4tHfrSdrL7d3d1JZolSb5JTmdnv7+96jqZkgqNhjrt9mrzO2OVIZIY5W4Kuvs+UqL9vhZ2gssiDocV1kbCImrC+ydWZv+R7ptBQc5uCla1aep69zt5wnchac5yjxuikt8xajL3k6e9Lh8I2VXs6YY1He65AcKB7lL1QktDV3eaCoMShr79jfZqFsNp/nsJSe5y1vdZBa5dffqFnlMC0vcjb4Obm7/dSnN5snMt1krN6qNRShrdScpR0i6ZHbprJ1eRtg5uBl7I/ZpHw8va8xc7O3uaMnbNxh6KMpsWUtd6csMW4wMqSqMKDrtaVvuOUq8Tf5ex7lKVSfKZalL1fhKpql8Jkkr7/KE794AAAAoXRSTlP/ALGggoYAAANsSURBVEiJtZX7UxJRFIBFhbXQoBQjU5RwKRSEUkBMwRFRIEkQxTREpWlSU3d8oDNqzmhFkjLSZD7GqeFP7Zx72Qej/eLYN3cuu+fe8+3Zw8KW5G+fknx+uOzGGIaBa5zDr0puTmRzc23tbY9arT4YNYjOsiewthjTaof8fqOxtzeTyYXDyeTU8bFGEwyuN1LWg8GgRqM5nppKJsPhcC6XyaRSKaOx5gfS40OrodhZsliNtAEgR/z+UChkFIGzkB+ApbGxMS0AeyGlOQps9ljBenB0jVMwKpWoAGV5AUEbUiqVuENwtg2idM1r9fnUo0dFTlitrKyEnQOAyWT6ipS/EwDvV4qpyNoGUrM5GrV7rXJeis5FIAZGi8VChA+BWYDItrefAVSMQViDS5rw0hYLJFVWa/e7u7ujMiJd5Z0swV1gqZgWgGGkEdzEMG43TYvFYkP7ZrNddp4Ap2uVd7rpNobktkhQUBiGlQTRC5HDQ9olUyiUksl+nZ/PydUuV90qddLiYBvLMIJHoReBJZgxuLW19Q2YhQj0ApoSiUT6+5u/5ycnJvzonL3gjjpLcE2LAgEDFqcTidMWDsesCo4KC29hLmi4jdG2UEgHo9DL+vr65+Pj3u9Xt/ubtfFwgI66S1RH0sGh7OKPxMOOI5jyYXwFKrmO7HkVmYmJnK545OTk6x8lzj5pjn5ZDJY5spQkQrpoN2gHR54kMlM5JKfstms1UXuXcE3jRMSOhimgzb4nwOaU2iy4jCFVYbvZBMJuZp+R3qnk3QPa0AbzDaapxMMOj5ML4gFcBzJA2c5GNPpdVTKDdTphGWVSkUeN5vNBrNOp2PZAIwA/aBHNIx7cIYMDtHrZ3Oo1CQS8NR3FZ5PYuwAQGiDvADy9CokDuu4DbcXrC9BmA5PNaCyjv8dSY1S3UcpReKAaFVx/aCM14yj0pUXnRKjRHdXikQssYIzkm5tjdc0olJtEJwdtErBKPgeiQheqRXzLtHY/YYoL/JFTlFZEKJoRYT3FqxCB0pb46C0Nwh/SoJzefn+l/n5+b6+vr29pqbPnZ0bGx5P7dmZw/GB4HA4pqdraz2eqqrT05mZmaam9/f+7OyMjDw22wGZV47/yNJ3HP99i1WSItvb21/zwHH7Ci1Vev+2F2bAPq6Wvo7+07v49vkLMNgkbyIQ0y8AAAAASUVORK5CYII=
W 06:54:20.023 fetch img failed(err:404):data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFMAAAAaCAMAAAD8O5CWAAAB41BMVEUyUnmOpL5NeKXm5uZaeJfEzdc8aJb/9bgamtucZMi8ZKao08X4WIstltmcVCc6XG0t9Og7Vpf5k6WX17lLCTpLiTu+BNcJVCYYVPj8zT2eFdireDm7W4w89GfbOmtMRzotA9a5rMzMzo7PBuiKY1WoJZdJRJhL1dfaFKbJI7ZZNyjq5+m7hBY4pAXoLAy9ZEeq6Wqr5pjLNSldRDdqqEnrydw+Y/bZ1+q9bO1t/d4+hKcZt7lbOuv9Q4XomLtt5ie5hKjM5llsW1w9RphqTEz91FaI5tjK5Qa4tHfrSdrL7d3d1JZolSb5JTmdnv7+96jqZkgqNhjrt9mrzO2OVIZIY5W4Kuvs+UqL9vhZ2gssiDocV1kbCImrC+ydWZv+R7ptBQc5uCla1aep69zt5wnchac5yjxuikt8xajL3k6e9Lh8I2VXs6YY1He65AcKB7lL1QktDV3eaCoMShr79jfZqFsNp/nsJSe5y1vdZBa5dffqFnlMC0vcjb4Obm7/dSnN5snMt1krN6qNRShrdScpR0i6ZHbprJ1eRtg5uBl7I/ZpHw8va8xc7O3uaMnbNxh6KMpsWUtd6csMW4wMqSqMKDrtaVvuOUq8Tf5ex7lKVSfKZalL1fhKpql8Jkkr7/KE794AAAAoXRSTlP/ALGggoYAAANsSURBVEiJtZX7UxJRFIBFhbXQoBQjU5RwKRSEUkBMwRFRIEkQxTREpWlSU3d8oDNqzmhFkjLSZD7GqeFP7Zx72Qej/eLYN3cuu+fe8+3Zw8KW5G+fknx+uOzGGIaBa5zDr0puTmRzc23tbY9arT4YNYjOsiewthjTaof8fqOxtzeTyYXDyeTU8bFGEwyuN1LWg8GgRqM5nppKJsPhcC6XyaRSKaOx5gfS40OrodhZsliNtAEgR/z+UChkFIGzkB+ApbGxMS0AeyGlOQps9ljBenB0jVMwKpWoAGV5AUEbUiqVuENwtg2idM1r9fnUo0dFTlitrKyEnQOAyWT6ipS/EwDvV4qpyNoGUrM5GrV7rXJeis5FIAZGi8VChA+BWYDItrefAVSMQViDS5rw0hYLJFVWa/e7u7ujMiJd5Z0swV1gqZgWgGGkEdzEMG43TYvFYkP7ZrNddp4Ap2uVd7rpNobktkhQUBiGlQTRC5HDQ9olUyiUksl+nZ/PydUuV90qddLiYBvLMIJHoReBJZgxuLW19Q2YhQj0ApoSiUT6+5u/5ycnJvzonL3gjjpLcE2LAgEDFqcTidMWDsesCo4KC29hLmi4jdG2UEgHo9DL+vr65+Pj3u9Xt/ubtfFwgI66S1RH0sGh7OKPxMOOI5jyYXwFKrmO7HkVmYmJnK545OTk6x8lzj5pjn5ZDJY5spQkQrpoN2gHR54kMlM5JKfstms1UXuXcE3jRMSOhimgzb4nwOaU2iy4jCFVYbvZBMJuZp+R3qnk3QPa0AbzDaapxMMOj5ML4gFcBzJA2c5GNPpdVTKDdTphGWVSkUeN5vNBrNOp2PZAIwA/aBHNIx7cIYMDtHrZ3Oo1CQS8NR3FZ5PYuwAQGiDvADy9CokDuu4DbcXrC9BmA5PNaCyjv8dSY1S3UcpReKAaFVx/aCM14yj0pUXnRKjRHdXikQssYIzkm5tjdc0olJtEJwdtErBKPgeiQheqRXzLtHY/YYoL/JFTlFZEKJoRYT3FqxCB0pb46C0Nwh/SoJzefn+l/n5+b6+vr29pqbPnZ0bGx5P7dmZw/GB4HA4pqdraz2eqqrT05mZmaam9/f+7OyMjDw22wGZV47/yNJ3HP99i1WSItvb21/zwHH7Ci1Vev+2F2bAPq6Wvo7+07v49vkLMNgkbyIQ0y8AAAAASUVORK5CYII=
W 06:54:20.634 fetch img failed(err:404):data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFMAAAAaCAMAAAD8O5CWAAAB41BMVEUyUnmOpL5NeKXm5uZaeJfEzdc8aJb/9bgamtucZMi8ZKao08X4WIstltmcVCc6XG0t9Og7Vpf5k6WX17lLCTpLiTu+BNcJVCYYVPj8zT2eFdireDm7W4w89GfbOmtMRzotA9a5rMzMzo7PBuiKY1WoJZdJRJhL1dfaFKbJI7ZZNyjq5+m7hBY4pAXoLAy9ZEeq6Wqr5pjLNSldRDdqqEnrydw+Y/bZ1+q9bO1t/d4+hKcZt7lbOuv9Q4XomLtt5ie5hKjM5llsW1w9RphqTEz91FaI5tjK5Qa4tHfrSdrL7d3d1JZolSb5JTmdnv7+96jqZkgqNhjrt9mrzO2OVIZIY5W4Kuvs+UqL9vhZ2gssiDocV1kbCImrC+ydWZv+R7ptBQc5uCla1aep69zt5wnchac5yjxuikt8xajL3k6e9Lh8I2VXs6YY1He65AcKB7lL1QktDV3eaCoMShr79jfZqFsNp/nsJSe5y1vdZBa5dffqFnlMC0vcjb4Obm7/dSnN5snMt1krN6qNRShrdScpR0i6ZHbprJ1eRtg5uBl7I/ZpHw8va8xc7O3uaMnbNxh6KMpsWUtd6csMW4wMqSqMKDrtaVvuOUq8Tf5ex7lKVSfKZalL1fhKpql8Jkkr7/KE794AAAAoXRSTlP/ALGggoYAAANsSURBVEiJtZX7UxJRFIBFhbXQoBQjU5RwKRSEUkBMwRFRIEkQxTREpWlSU3d8oDNqzmhFkjLSZD7GqeFP7Zx72Qej/eLYN3cuu+fe8+3Zw8KW5G+fknx+uOzGGIaBa5zDr0puTmRzc23tbY9arT4YNYjOsiewthjTaof8fqOxtzeTyYXDyeTU8bFGEwyuN1LWg8GgRqM5nppKJsPhcC6XyaRSKaOx5gfS40OrodhZsliNtAEgR/z+UChkFIGzkB+ApbGxMS0AeyGlOQps9ljBenB0jVMwKpWoAGV5AUEbUiqVuENwtg2idM1r9fnUo0dFTlitrKyEnQOAyWT6ipS/EwDvV4qpyNoGUrM5GrV7rXJeis5FIAZGi8VChA+BWYDItrefAVSMQViDS5rw0hYLJFVWa/e7u7ujMiJd5Z0swV1gqZgWgGGkEdzEMG43TYvFYkP7ZrNddp4Ap2uVd7rpNobktkhQUBiGlQTRC5HDQ9olUyiUksl+nZ/PydUuV90qddLiYBvLMIJHoReBJZgxuLW19Q2YhQj0ApoSiUT6+5u/5ycnJvzonL3gjjpLcE2LAgEDFqcTidMWDsesCo4KC29hLmi4jdG2UEgHo9DL+vr65+Pj3u9Xt/ubtfFwgI66S1RH0sGh7OKPxMOOI5jyYXwFKrmO7HkVmYmJnK545OTk6x8lzj5pjn5ZDJY5spQkQrpoN2gHR54kMlM5JKfstms1UXuXcE3jRMSOhimgzb4nwOaU2iy4jCFVYbvZBMJuZp+R3qnk3QPa0AbzDaapxMMOj5ML4gFcBzJA2c5GNPpdVTKDdTphGWVSkUeN5vNBrNOp2PZAIwA/aBHNIx7cIYMDtHrZ3Oo1CQS8NR3FZ5PYuwAQGiDvADy9CokDuu4DbcXrC9BmA5PNaCyjv8dSY1S3UcpReKAaFVx/aCM14yj0pUXnRKjRHdXikQssYIzkm5tjdc0olJtEJwdtErBKPgeiQheqRXzLtHY/YYoL/JFTlFZEKJoRYT3FqxCB0pb46C0Nwh/SoJzefn+l/n5+b6+vr29pqbPnZ0bGx5P7dmZw/GB4HA4pqdraz2eqqrT05mZmaam9/f+7OyMjDw22wGZV47/yNJ3HP99i1WSItvb21/zwHH7Ci1Vev+2F2bAPq6Wvo7+07v49vkLMNgkbyIQ0y8AAAAASUVORK5CYII=
E 06:54:21.987 Traceback (most recent call last):
E 06:54:21.987   File "/base/data/home/apps/s~kindleear-zxq/worker:1.380656047361739477/lib/web/application.py", line 239, in process
E 06:54:21.987     return self.handle()
E 06:54:21.987   File "/base/data/home/apps/s~kindleear-zxq/worker:1.380656047361739477/lib/web/application.py", line 230, in handle
E 06:54:21.987     return self._delegate(fn, self.fvars, args)
E 06:54:21.987   File "/base/data/home/apps/s~kindleear-zxq/worker:1.380656047361739477/lib/web/application.py", line 420, in _delegate
E 06:54:21.987     return handle_class(cls)
顯示更多  全部顯示
 A 07:24:23.292 2015-01-16  200 0 B 39ms /_ah/stop
2015-01-17
 I 06:44:47.169 2015-01-17  404 123 B 1399ms /_ah/start
 W 06:48:13.368 2015-01-17  200 140 B 208666ms /worker?u=admin&id=5105650963054592%2C5714163003293696%2C5722646637445120%2C5741031244955648
 A 07:18:13.970 2015-01-17  200 0 B 42ms /_ah/stop
2015-01-18
 I 06:44:54.368 2015-01-18  404 123 B 1658ms /_ah/start
 W 06:45:39.937 2015-01-18  200 140 B 48273ms /worker?u=admin&id=5105650963054592%2C5714163003293696%2C5722646637445120
 A 07:15:40.375 2015-01-18  200 0 B 67ms /_ah/stop

**Comment by cdhigh** [comment]
“
E 06:54:21.987 return handle_class(cls)
顯示更多 全部顯示
”

请点击显示更多，然后再贴出新显示的内容，真正的出错地方还没有贴上来。

**Comment by zxq1002** [comment]
E 06:54:21.987 Traceback (most recent call last):
    E 06:54:21.987 File "/base/data/home/apps/s~kindleear-zxq/worker:1.380656047361739477/lib/web/application.py", line 239, in process
    E 06:54:21.987 return self.handle()
    E 06:54:21.987 File "/base/data/home/apps/s~kindleear-zxq/worker:1.380656047361739477/lib/web/application.py", line 230, in handle
    E 06:54:21.987 return self._delegate(fn, self.fvars, args)
    E 06:54:21.987 File "/base/data/home/apps/s~kindleear-zxq/worker:1.380656047361739477/lib/web/application.py", line 420, in _delegate
    E 06:54:21.987 return handle_class(cls)
    E 06:54:21.987 File "/base/data/home/apps/s~kindleear-zxq/worker:1.380656047361739477/lib/web/application.py", line 396, in handle_class
    E 06:54:21.987 return tocall(*args)
    E 06:54:21.987 File "/base/data/home/apps/s~kindleear-zxq/worker:1.380656047361739477/apps/Work/Worker.py", line 127, in GET
    E 06:54:21.987 for sec_or_media, url, title, content, brief, thumbnail in book.Items(opts,user):
    E 06:54:21.987 File "/base/data/home/apps/s~kindleear-zxq/worker:1.380656047361739477/books/base.py", line 316, in Items
    E 06:54:21.987 urls = self.ParseFeedUrls()
    E 06:54:21.988 File "/base/data/home/apps/s~kindleear-zxq/worker:1.380656047361739477/books/weixinbase.py", line 39, in ParseFeedUrls
    E 06:54:21.988 content = json.loads(content)
    E 06:54:21.988 File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/json/__init__.py", line 338, in loads
    E 06:54:21.988 return _default_decoder.decode(s)
    E 06:54:21.988 File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/json/decoder.py", line 365, in decode
    E 06:54:21.988 obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    E 06:54:21.988 File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/json/decoder.py", line 381, in raw_decode
    E 06:54:21.988 obj, end = self.scan_once(s, idx)
    E 06:54:21.988 ValueError: Unterminated string starting at: line 1 column 1547 (char 1546)
A 07:24:23.292 2015-01-16  200       0 B    39ms /_ah/stop
  0.1.0.3 - - [15/Jan/2015:15:24:23 -0800] "GET /_ah/stop HTTP/1.1" 200 0 - - "0.1.worker.kindleear-zxq.appspot.com" ms=39 cpu_ms=0 instance=0 app_engine_release=1.9.17

**Comment by cdhigh** [comment]
对于微信公众号的推送，是热心网友提交的实现，我一直没有时间去整理，现在也暂时没有时间去完全解决此问题，不过我帮忙你忽略此异常，然后先正常推送其他的文章吧。
