### ISSUE TITLE
微信，小道消息收不到？是不是那个模版失效了？

### ISSUE THREAD

**Issue by angel126** [cdhigh/KindleEar#157]
微信，小道消息收不到？是不是那个模版失效了？

**Comment by cdhigh** [comment]
@angel126 用了新版了吗？ 解决了没有？

**Comment by angel126** [comment]
能发一份新版本给我试试吗？zhang.feiz@gmail.com

**Comment by cdhigh** [comment]
github可以直接下载

**Comment by angel126** [comment]
重新下了MASTER，小道消息可以了。
我用小道消息模版改了个例子，不能用，能帮忙看看什么原因吗？
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from weixinbase import WeixinBook

def getBook():
    return wechanger

class wechanger(WeixinBook):
    title                 = u'微信公众号：改变自己'
    description           = u'一起来,每天改变一点点!'
    language              = 'zh-cn'
    feed_encoding         = "utf-8"
    page_encoding         = "utf-8"
    oldest_article        = 7
    deliver_days = ['Friday']
    feeds = [
            (u'改变自己', 'http://weixin.sogou.com/gzh?openid=oIWsFt2UezFNv7A6nD0z1PyDTO2g')
            ]

**Comment by kongdeyuan** [comment]
有问题可以反映问题呢，等待解决，别光催啊。作者也是人，作者也不容易。。实在着急的不行了给作者些钱改一下吧。
2015年2月4日 下午10:08于 "angel126" <notifications@github.com>写道：

**Comment by cdhigh** [comment]
不能用要先看后台的logs有什么错误，看不懂就贴上来。

**Comment by angel126** [comment]
抱歉，在请教一下后台LOG怎么看呢

**Comment by angel126** [comment]
奇怪了，把    deliver_days = ['Friday'] 投递日期去掉就正常了。不知道什么原因？帮忙看看？

#!/usr/bin/env python
# -*- coding:utf-8 -*-
from weixinbase import WeixinBook

def getBook():
    return ITInfo

class ITInfo(WeixinBook):
    title                 = u'微信公众号：技术类'
    description           = u'聚合微信公众号：高端存储知识，EMC易安信中国技术社区，思杰Citrix，KVM虚拟化实践等。'
    language              = 'zh-cn'
    feed_encoding         = "utf-8"
    page_encoding         = "utf-8"
    oldest_article        = 7
    deliver_days = ['Friday']
    feeds = [
            (u'高端存储知识', 'http://weixin.sogou.com/gzh?openid=oIWsFt5tSBUJLA0t3DGyBTm-G5d0'),
            (u'EMC易安信中国技术社区', 'http://weixin.sogou.com/gzh?openid=oIWsFt6-iK4-ZU5TzilqrbDrqus4'),
            (u'思杰Citrix', 'http://weixin.sogou.com/gzh?openid=oIWsFt51SRdgGyZfEovPxFBRP5gE'),
			(u'KVM虚拟化实践', 'http://weixin.sogou.com/gzh?openid=oIWsFtx0JATnWpAABJFJ0WObMaz0'),
			(u'chinastor', 'http://weixin.sogou.com/gzh?openid=oIWsFt0NyDskM-FeB2GbLgN-eM5U'),
            (u'裕文虚拟化与信息安全', 'http://weixin.sogou.com/gzh?openid=oIWsFt_6T1MhCrpID2drk8iewJkA')
            ]


2015-02-08 21:25:13.110 Book 'BussinessInfo' import failed : unexpected indent (BussinessInfo.py, line 15)
I 2015-02-08 21:25:14.126 This request caused a new process to be started for your application, and thus caused your application code to be loaded for the first time. This requ

**Comment by cdhigh** [comment]
缩进问题，看是不是使用了TAB键缩进？

**Comment by angel126** [comment]
问题解决。多谢
