### ISSUE TITLE
改用fivefilter来提取全文

### ISSUE THREAD

**Issue by cerebellum92** [cdhigh/KindleEar#163]
我自定的rss源常常会有无法提取全文的问题（使用内建的isfulltext功能），
有时则是会文不对题，所以我想找替代方案。
我发现fivefilter的全文提取比instapaper还有readability 都好用，
我是程序的门外汉
请问我可以直接把base.py内的384行
http://www.instapaper.com/m?u=%s
改成
http://ftr.fivefilters.org/makefulltextfeed.php?
来实现我要的功能吗？
另外我该如何设置以下两个选项呢？
fulltext_by_readability = True
fulltext_by_instapaper = False
谢谢！

**Comment by cdhigh** [comment]
自定义rss全部使用内置的readability模块提取正文内容。

如果你写一个py文件，可以选择使用哪个方法提取。
可以改instapaper为fivefilters，然后设置
fulltext_by_readability = False
fulltext_by_instapaper = True

**Comment by cerebellum92** [comment]
谢谢你！
我原本以为自定义是使用base.py这个文件。
所以我应该在book里新建一个.py文件
里面设置
fulltext_by_readability = False
fulltext_by_instapaper = True
让instapaper 模块生效

然后把base.py里面instapaper的网址改成fivefilters的网址就可以了吗？

**Comment by cdhigh** [comment]
是这样的

**Comment by lqzh1987** [comment]
本人小白，不知提问者成功没有

**Comment by cerebellum92** [comment]
成功了，就是照着我说的那个方式就可以，不过要注意官方提供的网站只能转出前三篇文章，所以我是自架fivefilter来转全文的。这方法有个缺点，就算是自架fivefilter，像我设定一次转30篇文章，如果失败了（还满常失败的），整个rss seed就没有文章了。另一个软件kindlereader则是先读取rss中每篇文章的连结，然后一篇一篇的送给fivefilter转全文，这样就算其中一篇文章转全文失败了，也不至于整个seed都失败。有在用fivefilter的应该知道我在说什么。原本我想试着实做这个功能到kindleear，可是我不熟python加上太忙，就没去管他。有兴趣的可以试试！

**Comment by lqzh1987** [comment]
def fetcharticle(self, url, opener, decoder):
        #每个URL都增加一个后缀full=y，如果有分页则自动获取全部分页
        url += '?full=y'
        return BaseFeedBook.fetcharticle(self,url,opener,decoder)

看上去有用，不过，用在路透社网站的分页上，2、3页还是不显示！

**Comment by cdhigh** [comment]
因为FT中文网提供此功能，所以能用，其他的网站可以参考Aisixiang.py自己获取其他分页。
内置的书籍选择不是因为它优秀，而是它能演示某种内置书籍的特殊用法，基本上每个内置书籍文件均是如此。
如果没有特殊的处理，则直接将地址填写在“自定义RSS”中即可。

**Comment by lqzh1987** [comment]
自定义的也不可以全文输出，而且大部分的全文输出网站我都试过了，唯一可以的就是fivefilter但是又只有3个，我再研究研究吧，谢谢了

**Comment by cerebellum92** [comment]
会写程式的话，自定义是可以读到分页的。
fivefilter是可以自架的，用AWS免费的服务自己架一个就行。
