### ISSUE TITLE
creating sections in a rss

### ISSUE THREAD

**Issue by fuyaka** [cdhigh/KindleEar#164]
Hi
it might be not related to kindlear. I guess kindlear creates sections(toc) on mobi for each rss you  add. I create rss xml file manually by combining different feeds. Is it possible create multiple sections for one rss?

**Comment by cdhigh** [comment]
I will not consider this requirement, but here is a solution:
books/base.py -> line 237:
<code>section, url = feed[0], feed[1]</code>
You can generate multiple sections by change variable "section".
For example:
<code>url = feed[1]
if feed[0].startswith(''something"):
    section = feed[0][9:]
else:
    section = feed[0]
</code>

**Comment by fuyaka** [comment]
yes, after I gave  second thoughts about it, i found it is not that usefull :)
