### ISSUE TITLE
passing rss titles to toc 

### ISSUE THREAD

**Issue by fuyaka** [cdhigh/KindleEar#166]
I have rss feed items as:
```
<item>
<title>Murat Belge - Siyasette popülizm</title>
<link>
http://www.taraf.com.tr/yazarlar/siyasette-populizm/
</link>
<description>
desc
</description>
<guid isPermaLink="true">
http://www.taraf.com.tr/yazarlar/siyasette-populizm/
</guid>
<pubDate>2015-2-03 00:00:00</pubDate>
</item>
```
if I add this to kinddleear, toc title would be "Siyasette popülizm - Taraf Gazetesi". I guess it is because kindleear reads from page title which is <title>Siyasette popülizm - Taraf Gazetesi</title> . is there anyway to pass this rss titles to toc?

**Comment by cdhigh** [comment]
For general purpose, priority of title in page is higher, if has not title in page, the title in rss would be used.

You can use title in rss always if you change the code youself:
books/base.py -> line 341:
    if not title: title = ftitle
changed to:
    title = ftitle

**Comment by fuyaka** [comment]
thanks, i appreciated!
