### ISSUE TITLE
如何批量删除自定义RSS？

### ISSUE THREAD

**Issue by Lavande** [cdhigh/KindleEar#167]
刚刚手贱从OPML里导入了几百个RSS……
都是微信公众号 http://www.inoreader.com/reader/api/0/bundle/opml/0014cd635cd5
再次打开订阅页面的时候吓傻了，估计这个推给kindle要爆炸……
但是每个RSS旁边有一个删除，现在是几百个，怎样批量删除呢？

**Comment by cdhigh** [comment]
在gae后台删除吧，找找，很好找的。

**Comment by Lavande** [comment]
删掉了。。。不过不知道后来误删了什么，一直出错。。。现在重新部署了一个

**Comment by SuperstarSage** [comment]
请问在后台怎么删除，存放地址是什么

**Comment by cdhigh** [comment]
在数据存储 | 实体。
选择种类为 Feed 即可，删掉自己不需要的。

**Comment by SuperstarSage** [comment]
请问是在google cloud platform后台吗，我并没有找到 数据存储 | 实体。请问如何才能找到，或者能否提供截图或者地址
