### ISSUE TITLE
关于全文获取的问题.

### ISSUE THREAD

**Issue by zh1428** [cdhigh/KindleEar#168]
一个FEED  我点FULLTEXT的时候 能显示章节名， 但是不能全文获取。
不选fulltext的时候倒是能全文获取.  但是每个章节都同名.   这要咋整啊?  
我FEED是用FEED43自己做的。 是没做好还是咋的?

http://feed43.com/5815362072476767.xml

**Comment by cdhigh** [comment]
你做的这个feed根本没有输出全文信息，当然不能勾选fulltext选项了。

至于你说的每个章节都同名的问题就是KindleEar的问题了，因为网络上的文章大部分的标题都很长，里面有一大堆的冗余信息（比如网站名，网站推广之类的），所以KindleEar尝试“智能”提取原标题里面最可能的真实标题字符出来，一般来说，大部分网站都是可行的，使用效果也不错，但是因为算法比较简单，总会有一些网站搞不定。

既然如此，我在设置页面增加一个选项吧，如果feed里面的标题是正确的，则你可以选择使用feed里面的标题，而不去“智能”提取网页标题了。

可以使用1.20.16版本，并且设置标题来源为feed。

**Comment by zh1428** [comment]
Thz

在 2015-02-09 10:47:58，cdhigh <notifications@github.com> 写道：


你做的这个feed根本没有输出全文信息，当然不能勾选fulltext选项了。

至于你说的每个章节都同名的问题就是KindleEar的问题了，因为网络上的文章大部分的标题都很长，里面有一大堆的冗余信息（比如网站名，网站推广之类的），所以KindleEar尝试“智能”提取原标题里面最可能的真实标题字符出来，一般来说，大部分网站都是可行的，使用效果也不错，但是因为算法比较简单，总会有一些网站搞不定。

既然如此，我在设置页面增加一个选项吧，如果feed里面的标题是正确的，则你可以选择使用feed里面的标题，而不去“智能”提取网页标题了。

可以使用1.20.16版本，并且设置标题来源为feed。
