### ISSUE TITLE
微信公众号的文章标题错误

### ISSUE THREAD

**Issue by Lavande** [cdhigh/KindleEar#169]
比如我要抓这个号
(u'大象公会', 'http://weixin.sogou.com/gzh?openid=oIWsFt4bBmJKomRWR5Uo39-rX9mE'),
假设抓回了近期5篇文章，那么打开之后会发现5篇文章的标题全都是“大象公会”，而每篇文章原先的真正标题是啥不知道……

**Comment by lixingcong** [comment]
同意 我也是微信抓取文章都是统一标题
version: 1.20.14

**Comment by angel126** [comment]
是呀，有这个问题出现

**Comment by cdhigh** [comment]
可以升级1.20.16版本，并且设置标题来源为feed。

**Comment by angel126** [comment]
并且设置标题来源为feed? 这个怎么理解呀？不太懂。。。

**Comment by cdhigh** [comment]
升级后设置界面增加一个选项，你升级后就知道了。

**Comment by angel126** [comment]
可以了。。多谢。。
