### ISSUE TITLE
怎样将需要推送的微信公众号添加自己的kindleear？

### ISSUE THREAD

**Issue by jxmlingyun** [cdhigh/KindleEar#170]
我按照小道消息公众号的模板写了一个，放在了文件夹”books“里面，部署好以后在“我的订阅”里面找不到，无法订阅。请教一下作者，这是什么问题？多谢了

下面是我写世相公众号的脚本
#!/usr/bin/env python
# -*- coding:utf-8 -*-

from weixinbase import WeixinBook

def getBook():
    return Shixiang

class Shixiang(WeixinBook):
    title               = u'微信公众号：世相'
    description         = u'倡导有物质基础的精神生活，文章兼顾见识与审美，也许长，但必定值得耐心阅读。'
    language            = 'zh-cn'
    feed_encoding       = "utf-8"
    page_encoding       = "utf-8"
    coverfile           = 'cv_shixiang.jpg'
    oldest_article        = 3
    feeds = [
    		(u'世相', 'http://weixin.sogou.com/gzh?openid=oIWsFtw5n0i6dF5-8JyyrnsSgosU')
    		]

**Comment by cdhigh** [comment]
看后台logs，十有八九是文件编码或缩进问题。
文件编码必须是无BOM的UTF8格式，python使用缩进进行程序结构的判断，还有，缩进要统一，如果有的行使用空格缩进，有的行使用TAB，则一般都会出问题，而且不容易发现。

**Comment by jxmlingyun** [comment]
前面的问题已经解决，在“我的订阅”里面已经有我自己写的books了。多谢
