### ISSUE TITLE
国内打不开，除了谷歌apps，还有别的好方法么？

### ISSUE THREAD

**Issue by zzzz438** [cdhigh/KindleEar#172]
反向代理的话效果怎么样？会不会影响到别的？

**Comment by cdhigh** [comment]
如果你无法顺利翻墙，则此App不适合你。
只有KindleEar网页需要翻墙，推送是不需要的，所以不管你用什么方法，都不会影响到推送。

**Comment by zzzz438** [comment]
好吧，谢谢，我的已经部署成功，但是每次都要翻墙还是觉得有点不爽快，本来也想搭建好给几个朋友用的，看来没办法了。
非常感谢你的答复。

**Comment by webbill** [comment]
使用 yourappname.appsp0t.com 试试，不用翻墙
