### ISSUE TITLE
抓狂的“还没有投递过”

### ISSUE THREAD

**Issue by LiuR** [cdhigh/KindleEar#174]
仁兄，按照部署步骤一步一步的来，但仍旧是部署不成功，一共有两种情况，创建的第一个gae  admin登入后显示的都是internal server error  ，创建的的二个gae 可正常登入，可以设置，一切都好就是永远的还没有投递过；创建了第三个gae还是依然的internal server error，现已抓狂，还望赐教。

**Comment by cdhigh** [comment]
python appcfg.py update_queues KindleEar/

**Comment by felixye** [comment]
在osx，怎么找到 appcfg.py?

**Comment by cmLighters** [comment]
楼主，这个python appcfg.py update_queues KindleEar/ 在你的FAQ和README中都没有出现啊，这个是不是必须的步骤？

**Comment by cdhigh** [comment]
出问题才需要手工执行这些代码，理论上是不需要的。
osx中如果在launcher中添加符号链接（我忘了具体名字）就可以直接在终端中执行此命令了。
