### ISSUE TITLE
problem with title from setting

### ISSUE THREAD

**Issue by fuyaka** [cdhigh/KindleEar#176]
thanks for adding this to settings but seemingly it doesnt work propery. I created this rss via pyrss2gen
 http://rssyazar.appspot.com/rss/B6014D20432C it still reads title from the link of the content. isnt the rss link proper?

**Comment by cdhigh** [comment]
I tested your link, that feature is ok.

Please save your configure first and click "Deliver now".

**Comment by fuyaka** [comment]
I created a new app engine and it works now as it was supposed to work. but it is strange because my old updated kindleear application cant get the titles. is it possible to reset my old project? I mean delete everything,datastore entities etc

**Comment by cdhigh** [comment]
You can try change the setting and save, then change back and save again.
if no solved, you can delete all datastore entities.
