### ISSUE TITLE
strange problem in parsing

### ISSUE THREAD

**Issue by fuyaka** [cdhigh/KindleEar#177]
I got two fresh problems :) this is the rss  I work with http://rssdeneme.appspot.com/rss/ACA7DD72D944  which contains this article http://rssdeneme.appspot.com/eksi/F4EDFE6191DE4C5
the problem is kindleear ignores some texts eg. http://i.imgur.com/EPmz8qM.jpg  there was a text below "2)". and the second problem is if there is a link inside this article, it goes to the next line before and after  http://i.imgur.com/Tz7J6Ax.jpg .is there anyway to solve this? or any work around

**Comment by cdhigh** [comment]
A module of KindleEar named 'Readability' did something wrong.
my suggestion is put your rss into a py file and set variable 
fulltext_by_readability = False
