### ISSUE TITLE
拜托谁帮忙做个明报的py文件。

### ISSUE THREAD

**Issue by liangzhdp** [cdhigh/KindleEar#178]
自定义RSS输出不是全文，自己学写py，投递状态都是nonews，后台log，提示是book不存在，谁帮忙做个？谢谢。

每日明報 RSS 連結
要聞http://news.mingpao.com/rss/pns/s00001.xml
港聞http://news.mingpao.com/rss/pns/s00002.xml
社評‧筆陣http://news.mingpao.com/rss/pns/s00003.xml
觀點http://news.mingpao.com/rss/pns/s00012.xml
中國http://news.mingpao.com/rss/pns/s00013.xml
國際http://news.mingpao.com/rss/pns/s00014.xml
副刊http://news.mingpao.com/rss/pns/s00005.xml
作家專欄http://news.mingpao.com/rss/pns/s00018.xml
深度報道http://news.mingpao.com/rss/pns/s00285.xml
偵查報道http://news.mingpao.com/rss/pns/s00287.xml

**Comment by cdhigh** [comment]
抱歉，我现在精力有限，不提供定制内置书籍服务，不过我之前看到在豆瓣还是哪里有热心网友提供付费定制服务，你可以找找。

**Comment by liangzhdp** [comment]
好吧，我找找看，有谁提供有偿服务的也可留个言。
