### ISSUE TITLE
Something wrong with uploading the app

### ISSUE THREAD

**Issue by cdmask** [cdhigh/KindleEar#179]
![image](https://cloud.githubusercontent.com/assets/11484898/6655123/cdac4d94-cb29-11e4-87d1-59caa342796d.png)
卡在 getting current resource limits.
卡很久然后出现下面的
![kindle](https://cloud.githubusercontent.com/assets/11484898/6655154/71fa6d94-cb2b-11e4-9ea2-4a154391c8da.PNG)
新手求助！

**Comment by cdhigh** [comment]
先确定翻墙服务是否正常，是否启用了两步密码验证服务（需要关闭或添加app密码）。

**Comment by cdmask** [comment]
我是开着goagent翻墙的，没有启用两步验证服务。

**Comment by cdmask** [comment]
解决了！不是不能输入，而是输入了，显示本来就是黑的。。用了vpngate解决了

**Comment by cdmask** [comment]
新的问题，又来了。上传成功之后，点不进去
![image](https://cloud.githubusercontent.com/assets/11484898/6660966/7732b2f8-cbdf-11e4-9c8e-50a2d0bf27ca.png)
