### ISSUE TITLE
请指点一下，怎么自定义投递文章的样式

### ISSUE THREAD

**Issue by jxmlingyun** [cdhigh/KindleEar#181]
请指点一下，如果我想改变一下投递文章样式，在什么地方可以更改？

**Comment by NeverAlone** [comment]
Are you sure this website is okay? 发自网易邮箱大师 在2015年03月21日 16:51 ，jxmlingyun写道： 请指点一下，如果我想改变一下投递文章样式，在什么地方可以更改？ — Reply to this email directly or view it on GitHub.

**Comment by cdhigh** [comment]
不明白你说的什么样式。
不过如果你自己写py书籍，可以通过属性 extra_css 加入一些CSS样式。
