### ISSUE TITLE
How to deploy KindleEar on personal VPS?

### ISSUE THREAD

**Issue by ddqp** [cdhigh/KindleEar#186]
It's a great job for kindlers!
I own a VPS, can install any linux, how can I deploy it on my VPS?

thanks,
DDQP

**Comment by cdhigh** [comment]
之前已经有一个应用Kindlereader，因为不能部署在GAE上我才开发的KindleEar，如果你要部署在VPS上，可以考虑kindlereader

**Comment by ddqp** [comment]
好的，非常感谢！！
