### ISSUE TITLE
怎么样分别设置不同内容的发送时间？？

### ISSUE THREAD

**Issue by cdmask** [cdhigh/KindleEar#187]
请问一下怎么样设置custom rss 的发放时间，比如Harvard Business Review 的rss要设置成一个星期一次？

**Comment by cdhigh** [comment]
对于自定义RSS，仅有一个投递时间，如果需要多个时间，可以考虑新建几个账号，每个账号一个时间，或者自己写一个py书籍文件，则可以自己定义推送时间，参见faq。
