### ISSUE TITLE
是不是163邮箱导致投递无效？

### ISSUE THREAD

**Issue by zzzz438** [cdhigh/KindleEar#188]
点击现在投递，然后等待后，收不到文章。
我的谷歌帐号，是用163邮箱，也就是说，页面提示我将****@163.com加入亚马逊信任邮件列表，我也加了，但是收不到投递。
我的意思是，后台不会有我的163邮箱密码，那是怎么用***@163.com的邮件投递过去的？
是不是这里的问题呢？
阿里ACE我也弄了个，大神以后会不会考虑修改几个国内版？

**Comment by cdhigh** [comment]
至于是否是163的问题，你可以将推送邮件随便改成其他邮箱，看是否成功，如果不成功，则是部署的问题，请看后台GAE的log错误信息确定是什么错误。

国内版我是不考虑的，国内公司人品太差，看不上。
