### ISSUE TITLE
本来用得好好地 不知道为什么推送内容突然成了乱码！

### ISSUE THREAD

**Issue by jiaohon** [cdhigh/KindleEar#189]
用FAQ提供的方法 将 pageencoding  修改成 GBK
但是推送一次后 又自动变成了 ISO 8859 而这个8859是个乱码....

**Comment by jiaohon** [comment]
汗！ 写这个 ISSUE 的时候才发现 appid 没改过来.  已经修改了  麻烦大神close 吧!

**Comment by jiaohon** [comment]
为什么我PageEncoding 改成GBK 后又自动恢复原状了?

**Comment by cdhigh** [comment]
pageencoding 这个玩意是历史遗留问题，如果采用完全自动判断，应该不需要这个东东了，除非你的网页够变态，是哪个网页？

还有，首先要确认你的config.py的两个开关的状态：
ALWAYS_CHAR_DETECT
TRUST_ENCODING_IN_HEADER_OR_META

**Comment by jiaohon** [comment]
ALWAYS_CHAR_DETECT  这一项为true 
TRUST_ENCODING_IN_HEADER_OR_META   为false

怎么修改？ 修改后是重新上传么?

**Comment by cdhigh** [comment]
ALWAYS_CHAR_DETECT改成False吧，至于TRUST_ENCODING_IN_HEADER_OR_META的值，影响不大，可以维持现状，改成True效率高一些。
改了以后，重新上传即可。
