### ISSUE TITLE
请问一下这几天的喷嚏图挂怎么一直推送的都是29号的内容

### ISSUE THREAD

**Issue by jjhhh464** [cdhigh/KindleEar#190]
RT
换了账号也不行

**Comment by cdhigh** [comment]
因为他不更新，所以推送了当然是29号的啦，碰到类似这个问题时建议先确认“源头”。
当然，也是其RSS中的日期标识不符合任何一个国际规范，导致日期解析出错，而KindleEar又不会单独给他写一个解析规则，所以只能取巧，每天仅推送最新一个，这样就导致如果其不更新，就会推送老的内容。
