### ISSUE TITLE
一直都是出错，能登陆但不能投递。

### ISSUE THREAD

**Issue by pingpz** [cdhigh/KindleEar#195]
E 22:19:03.013 2015-05-11  500     135 B   8.92s /worker?u=admin&id=5101298819006464%2C5629499534213120%2C5634472569470976%2C5664248772427776%2C5720147234914304
  0.1.0.2 - - [11/May/2015:07:19:03 -0700] "GET /worker?u=admin&id=5101298819006464%2C5629499534213120%2C5634472569470976%2C5664248772427776%2C5720147234914304 HTTP/1.1" 500 135 "http://jkin450.appspot.com/deliver?u=admin" "AppEngine-Google; (+http://code.google.com/appengine)" "worker.jkin450.appspot.com" ms=8923 cpu_ms=8090 cpm_usd=0.000265 queue_name=deliverqueue1 task_name=3697977375078542037 instance=0 app_engine_release=1.9.20
    E 22:19:03.005 Traceback (most recent call last):
    E 22:19:03.005 File "/base/data/home/apps/s~jkin450/worker:1.384226108982571307/lib/web/application.py", line 239, in process
    E 22:19:03.005 return self.handle()
    E 22:19:03.005 File "/base/data/home/apps/s~jkin450/worker:1.384226108982571307/lib/web/application.py", line 230, in handle
    E 22:19:03.005 return self._delegate(fn, self.fvars, args)
    E 22:19:03.005 File "/base/data/home/apps/s~jkin450/worker:1.384226108982571307/lib/web/application.py", line 420, in _delegate
    E 22:19:03.005 return handle_class(cls)
    E 22:19:03.005 File "/base/data/home/apps/s~jkin450/worker:1.384226108982571307/lib/web/application.py", line 396, in handle_class
    E 22:19:03.005 return tocall(*args)
    E 22:19:03.005 File "/base/data/home/apps/s~jkin450/worker:1.384226108982571307/apps/Work/Worker.py", line 127, in GET

**Comment by pingpz** [comment]
一直搞不明白，为什么重新update了，但是用户数据一直被保留了。比如admin的密码一直是我修改过的密码。怎么样能完全重置app呀？

**Comment by cdhigh** [comment]
E 22:19:03.005 File "/base/data/home/apps/s~jkin450/worker:1.384226108982571307/apps/Work/Worker.py", line 127, in GET
在这一行之后应该还有一些异常信息，请一并贴上来。
update只会更新程序，而不会删除数据，数据库和程序是分离的，如果要删除数据库，可以在GAE后台操作。

**Comment by pingpz** [comment]
以下是今天早上出来的错误信息，我设定了8点投递的，谢谢你的回复。
I 07:55:05.394 2015-05-12  404     123 B   1.97s /_ah/start
  0.1.0.3 - - [11/May/2015:16:55:05 -0700] "GET /_ah/start HTTP/1.1" 404 123 - - "0.1.worker.jkin450.appspot.com" ms=1970 cpu_ms=2103 cpm_usd=0.000014 loading_request=1 instance=0 app_engine_release=1.9.20
    I 07:55:05.393 This request caused a new process to be started for your application, and thus caused your application code to be loaded for the first time. This request may thus take longer and use more CPU than a typical request for your application.
E 07:55:14.820 2015-05-12  500     135 B  12.56s /worker?u=admin&id=5101298819006464%2C5629499534213120
  0.1.0.2 - - [11/May/2015:16:55:14 -0700] "GET /worker?u=admin&id=5101298819006464%2C5629499534213120 HTTP/1.1" 500 135 "http://jkin450.appspot.com/deliver" "AppEngine-Google; (+http://code.google.com/appengine)" "worker.jkin450.appspot.com" ms=12557 cpu_ms=8318 cpm_usd=0.000265 queue_name=deliverqueue1 task_name=63057857215780507541 pending_ms=3130 instance=0 app_engine_release=1.9.20
    E 07:55:14.814 Traceback (most recent call last):
    E 07:55:14.814 File "/base/data/home/apps/s~jkin450/worker:1.384226108982571307/lib/web/application.py", line 239, in process
    E 07:55:14.814 return self.handle()
    E 07:55:14.814 File "/base/data/home/apps/s~jkin450/worker:1.384226108982571307/lib/web/application.py", line 230, in handle
    E 07:55:14.814 return self._delegate(fn, self.fvars, args)
    E 07:55:14.814 File "/base/data/home/apps/s~jkin450/worker:1.384226108982571307/lib/web/application.py", line 420, in _delegate
    E 07:55:14.814 return handle_class(cls)
    E 07:55:14.814 File "/base/data/home/apps/s~jkin450/worker:1.384226108982571307/lib/web/application.py", line 396, in handle_class
    E 07:55:14.814 return tocall(*args)
    E 07:55:14.814 File "/base/data/home/apps/s~jkin450/worker:1.384226108982571307/apps/Work/Worker.py", line 127, in GET
E 07:56:23.719 2015-05-12  500     135 B   8.81s /worker?u=admin&id=5101298819006464%2C5629499534213120
  0.1.0.2 - - [11/May/2015:16:56:23 -0700] "GET /worker?u=admin&id=5101298819006464%2C5629499534213120 HTTP/1.1" 500 135 "http://jkin450.appspot.com/deliver" "AppEngine-Google; (+http://code.google.com/appengine)" "worker.jkin450.appspot.com" ms=8806 cpu_ms=8077 cpm_usd=0.000265 queue_name=deliverqueue1 task_name=63057857215780507541 instance=0 app_engine_release=1.9.20
    E 07:56:23.711 Traceback (most recent call last):
    E 07:56:23.711 File "/base/data/home/apps/s~jkin450/worker:1.384226108982571307/lib/web/application.py", line 239, in process
    E 07:56:23.711 return self.handle()
    E 07:56:23.711 File "/base/data/home/apps/s~jkin450/worker:1.384226108982571307/lib/web/application.py", line 230, in handle
    E 07:56:23.711 return self._delegate(fn, self.fvars, args)
    E 07:56:23.711 File "/base/data/home/apps/s~jkin450/worker:1.384226108982571307/lib/web/application.py", line 420, in _delegate
    E 07:56:23.711 return handle_class(cls)
    E 07:56:23.711 File "/base/data/home/apps/s~jkin450/worker:1.384226108982571307/lib/web/application.py", line 396, in handle_class
    E 07:56:23.711 return tocall(*args)
    E 07:56:23.711 File "/base/data/home/apps/s~jkin450/worker:1.384226108982571307/apps/Work/Worker.py", line 127, in GET
E 07:58:32.406 2015-05-12  500     135 B   8.67s /worker?u=admin&id=5101298819006464%2C5629499534213120
  0.1.0.2 - - [11/May/2015:16:58:32 -0700] "GET /worker?u=admin&id=5101298819006464%2C5629499534213120 HTTP/1.1" 500 135 "http://jkin450.appspot.com/deliver" "AppEngine-Google; (+http://code.google.com/appengine)" "worker.jkin450.appspot.com" ms=8669 cpu_ms=8168 cpm_usd=0.000265 queue_name=deliverqueue1 task_name=63057857215780507541 instance=0 app_engine_release=1.9.20
    E 07:58:32.399 Traceback (most recent call last):
    E 07:58:32.399 File "/base/data/home/apps/s~jkin450/worker:1.384226108982571307/lib/web/application.py", line 239, in process
    E 07:58:32.399 return self.handle()
    E 07:58:32.399 File "/base/data/home/apps/s~jkin450/worker:1.384226108982571307/lib/web/application.py", line 230, in handle
    E 07:58:32.399 return self._delegate(fn, self.fvars, args)
    E 07:58:32.399 File "/base/data/home/apps/s~jkin450/worker:1.384226108982571307/lib/web/application.py", line 420, in _delegate
    E 07:58:32.400 return handle_class(cls)
    E 07:58:32.400 File "/base/data/home/apps/s~jkin450/worker:1.384226108982571307/lib/web/application.py", line 396, in handle_class
    E 07:58:32.400 return tocall(*args)
    E 07:58:32.400 File "/base/data/home/apps/s~jkin450/worker:1.384226108982571307/apps/Work/Worker.py", line 127, in GET
E 08:02:42.193 2015-05-12  500     135 B   9.72s /worker?u=admin&id=5101298819006464%2C5629499534213120
  0.1.0.2 - - [11/May/2015:17:02:42 -0700] "GET /worker?u=admin&id=5101298819006464%2C5629499534213120 HTTP/1.1" 500 135 "http://jkin450.appspot.com/deliver" "AppEngine-Google; (+http://code.google.com/appengine)" "worker.jkin450.appspot.com" ms=9723 cpu_ms=8440 cpm_usd=0.000427 queue_name=deliverqueue1 task_name=63057857215780507541 instance=0 app_engine_release=1.9.20
    E 08:02:42.183 Traceback (most recent call last):
    E 08:02:42.183 File "/base/data/home/apps/s~jkin450/worker:1.384226108982571307/lib/web/application.py", line 239, in process
    E 08:02:42.183 return self.handle()
    E 08:02:42.184 File "/base/data/home/apps/s~jkin450/worker:1.384226108982571307/lib/web/application.py", line 230, in handle
    E 08:02:42.184 return self._delegate(fn, self.fvars, args)
    E 08:02:42.184 File "/base/data/home/apps/s~jkin450/worker:1.384226108982571307/lib/web/application.py", line 420, in _delegate
    E 08:02:42.184 return handle_class(cls)
    E 08:02:42.184 File "/base/data/home/apps/s~jkin450/worker:1.384226108982571307/lib/web/application.py", line 396, in handle_class
    E 08:02:42.184 return tocall(*args)
    E 08:02:42.184 File "/base/data/home/apps/s~jkin450/worker:1.384226108982571307/apps/Work/Worker.py", line 127, in GET
A 08:32:43.092 2015-05-12  200       0 B    34ms /_ah/stop
  0.1.0.3 - - [11/May/2015:17:32:43 -0700] "GET /_ah/stop HTTP/1.1" 200 0 - - "0.1.worker.jkin450.appspot.com" ms=34 cpu_ms=1 instance=0 app_engine_release=1.9.20

**Comment by cdhigh** [comment]
原来在那一行之后没有更多的错误信息了，暂时无法确定原因。

你用的是你自己写的推送书籍文件？

**Comment by pingpz** [comment]
不是的，都是里面勾选的，还有就是在自定义里面加了http://wallstreetcn.com/rss.xml这个华尔街见闻的。

**Comment by pingpz** [comment]
我现在把用记数据清掉了他又可以投递了，但还没有加自定义的RSS，一点一点试。

**Comment by pingpz** [comment]
127后面还有，还要点show all呢。哈哈。
E 10:33:59.015 2015-05-12  500     135 B  11.08s /worker?u=admin&id=5101298819006464%2C5629499534213120%2C5634472569470976%2C5664248772427776
  0.1.0.2 - - [11/May/2015:19:33:59 -0700] "GET /worker?u=admin&id=5101298819006464%2C5629499534213120%2C5634472569470976%2C5664248772427776 HTTP/1.1" 500 135 "http://jkin450.appspot.com/deliver?u=admin" "AppEngine-Google; (+http://code.google.com/appengine)" "worker.jkin450.appspot.com" ms=11078 cpu_ms=9048 cpm_usd=0.000474 queue_name=deliverqueue1 task_name=50106411326680464541 instance=0 app_engine_release=1.9.20
    E 10:33:59.007 Traceback (most recent call last):
    E 10:33:59.007 File "/base/data/home/apps/s~jkin450/worker:1.384226108982571307/lib/web/application.py", line 239, in process
    E 10:33:59.007 return self.handle()
    E 10:33:59.007 File "/base/data/home/apps/s~jkin450/worker:1.384226108982571307/lib/web/application.py", line 230, in handle
    E 10:33:59.007 return self._delegate(fn, self.fvars, args)
    E 10:33:59.007 File "/base/data/home/apps/s~jkin450/worker:1.384226108982571307/lib/web/application.py", line 420, in _delegate
    E 10:33:59.008 return handle_class(cls)
    E 10:33:59.008 File "/base/data/home/apps/s~jkin450/worker:1.384226108982571307/lib/web/application.py", line 396, in handle_class
    E 10:33:59.008 return tocall(*args)
    E 10:33:59.008 File "/base/data/home/apps/s~jkin450/worker:1.384226108982571307/apps/Work/Worker.py", line 127, in GET
    E 10:33:59.008 for sec_or_media, url, title, content, brief, thumbnail in book.Items(opts,user):
    E 10:33:59.008 File "/base/data/home/apps/s~jkin450/worker:1.384226108982571307/books/base.py", line 337, in Items
    E 10:33:59.008 for title, imgurl, imgfn, content, brief, thumbnail in readability(article,url,opts,user):
    E 10:33:59.008 File "/base/data/home/apps/s~jkin450/worker:1.384226108982571307/books/base.py", line 822, in readability_by_soup
    E 10:33:59.008 self.soupprocessex(soup)
    E 10:33:59.008 File "/base/data/home/apps/s~jkin450/worker:1.384226108982571307/books/wsj.py", line 71, in soupprocessex
    E 10:33:59.008 firstdiv = content.find('div')
    E 10:33:59.008 AttributeError: 'NoneType' object has no attribute 'find'

**Comment by cdhigh** [comment]
华尔街日报这个书籍的bug，可能其网站改版了，我记录下来了，待升级。
暂不推送此rss即可。
如果要现在用，可以如下修改，然后重新上传：
打开wsj.py，找到soupprocessex，然后按如下修改，注意对齐：
<code>
def soupprocessex(self, soup):
        ' 将首字div变成b '
        content = soup.find('div',attrs={'id':'A'})
        if content:
            firstdiv = content.find('div')
            if firstdiv and firstdiv.string and len(firstdiv.string) == 1:
                b = soup.new_tag('b')
                b.string = firstdiv.string
                firstdiv.replace_with(b)
</code>

**Comment by pingpz** [comment]
谢谢
