### ISSUE TITLE
也不提示错误一直这样传不上去 是为啥?

### ISSUE THREAD

**Issue by jiaohon** [cdhigh/KindleEar#198]
11:26 AM Scanning files on local disk.
11:26 AM Cloning 11 static files.
11:26 AM Cloning 366 application files.
11:26 AM Compilation starting.
11:26 AM Compilation completed.
11:26 AM Starting deployment.
11:26 AM Checking if deployment succeeded.
11:26 AM Deployment successful.
11:26 AM Checking if updated app version is serving.
11:26 AM Completed update of app: jiaohonkindle, version: 1
11:26 AM Uploading index definitions.
11:26 AM Uploading cron entries.
11:26 AM Uploading task queue entries.
11:26 AM Uploading dispatch entries.

D:\kindleear_uploader>goto end

D:\kindleear_uploader>pause
请按任意键继续. . .

**Comment by cdhigh** [comment]
没错误就表示成功了

**Comment by jiaohon** [comment]
goto end 然后跳到  pause  也是成功了么?

**Comment by cdhigh** [comment]
你的网站已经成功，可以正常打开的。
