### ISSUE TITLE
能否添加多选框进行操作

### ISSUE THREAD

**Issue by enneaa** [cdhigh/KindleEar#199]
每次删除订阅或添加订阅每个条目都要点一下，而且每点一下都会刷新页面，很不方便

**Comment by cdhigh** [comment]
个人软件我暂时就不打算费那么大精力做这些不是特别需要的功能了，
话说这样选择也是实现最简单的方式，当时有过方案抉择，也想过的，不过考虑有谁有事没事去大量删除呢？对于内容了，一般初期可能会改改，但一般一段时间后，设定后就很难的改变了。
我几个月了，都没有上网站一次呢。

**Comment by cdhigh** [comment]
我已经在1.22上实现了AJAX页面，可以添加订阅或删除订阅不需要全部刷新页面，你可以试一下。
