### ISSUE TITLE
能否让kindleear抓取rss源一天累计的所有条目？

### ISSUE THREAD

**Issue by enneaa** [cdhigh/KindleEar#202]
有的源一次只提供10个条目，但是一天累计下来有30个条目。现在kindleear只能抓到10个条目，能否让kindleear抓取一天累计的所有条目？

**Comment by cdhigh** [comment]
请参考FAQ

**Comment by enneaa** [comment]
在FAQ中只找到了一天推送多次的方法，有没有办法让kindleear一天抓取多次但只推送一次？

**Comment by cdhigh** [comment]
没有办法，KindleEar没有在服务器上暂存抓取的内容，抓取后必须马上推送。
