### ISSUE TITLE
无法抓取微信公众号文章，RSS 正常。

### ISSUE THREAD

**Issue by wavierwister** [cdhigh/KindleEar#203]
无法抓取微信公众号文章，RSS 正常，持续已有20多天。谢谢回复。

**Comment by ouwenxxing** [comment]
我来回答吧：
微信公众号现在获取连接变了，除了需要openid外，多加了一个 AES 加密 。我看了一下每个公众号的AES都不一样（那是当然的）。

具体可以看js脚本是879行
        if ("true" == enabled) {
            url = url+"&"+window.aes;
        }

so现在当然不行了。

**Comment by wavierwister** [comment]
谢谢解答 :)

**Comment by lei286394973** [comment]
这个key现在是一个星期更新一次。   不过现在搜狗启用反爬虫了，一个ip一天感觉不到100次 就会有验证码出现
