### ISSUE TITLE
Dev环境下执行推送显示Task task1 failed to execute. This task will retry in 120.000 seconds

### ISSUE THREAD

**Issue by ouwenxxing** [cdhigh/KindleEar#204]
想在本地跑一下KindleEar，但不知道为什么推送任务在队列里无法执行。
具体log:

INFO     2015-06-04 23:04:16,986 module.py:790] default: "GET /worker?id=4925812092436480%2C5275456790069248&u=admin HTTP/1.1" 404 9
WARNING  2015-06-04 23:04:16,986 taskqueue_stub.py:1977] Task task1 failed to execute. This task will retry in 60.000 seconds

作者能否给点提示呢？

**Comment by cdhigh** [comment]
我之前是可以在本地调试的，可能是对应ID的书籍有问题？
你可以直接在浏览器中输入
本地调试服务器IP:WORKER模块端口/worker?id=4925812092436480%2C5275456790069248&u=admin
试试，看是什么异常。

**Comment by ouwenxxing** [comment]
response返回的代码是404。
页面显示:
Not found

你所指的worker模块端口，应该是启动的端口8080吧？
也就是说task是能被执行的，只是反回的代码是404然后被判定没执行成功。

我试了几本书也一样。

我是用eclipse + pydev调试的

**Comment by cdhigh** [comment]
如果页面模块是8080的话，一般worker模块端口为8081，你试一下。

**Comment by ouwenxxing** [comment]
INFO     2015-06-06 08:36:35,078 api_server.py:190] Starting API server at: http://localhost:2932
INFO     2015-06-06 08:36:35,140 dispatcher.py:192] Starting module "default" running at: http://localhost:8080
INFO     2015-06-06 08:36:35,151 admin_server.py:118] Starting admin server at: http://localhost:8000

启动时就监听了这3个端口。。
只有8080端口404反应
API端口返回这个
{app_id: dev~kindleear, rtok: '0'}

**Comment by cdhigh** [comment]
那说明worker模块还没启动，
启动module-worker.yaml

**Comment by ouwenxxing** [comment]
怎么启动来着，要加什么参数？

我现在是
dev_appserver.py KindleEar/

**Comment by cdhigh** [comment]
dev_appserver.py 加两个yaml文件名即可

**Comment by ouwenxxing** [comment]
成功了，谢谢！

**Comment by loyalwong** [comment]
搞了好几天，终于参考这个解决了
