### ISSUE TITLE
请问如何修改合并为一本书的封面？

### ISSUE THREAD

**Issue by javenfeng** [cdhigh/KindleEar#207]
请问如何修改合并为一本书的封面？合并为一本书后，使之始终显示一张自定义的封面图。谢谢。是config.py 里的DEFAULT_COVER_BV 吗？

**Comment by javenfeng** [comment]
解决了。那么如何将此图片作为合并书籍的扉页（点击打开后的第一页就是封面）呢？

**Comment by cdhigh** [comment]
好像杂志模式没有扉页吧？
杂志模式打开后就是目录，如果要扉页，要普通书籍格式，然后书籍中第一个项目为图片即可，要修改代码。

**Comment by javenfeng** [comment]
谢谢，那请问如何自动归档呢？我的都没有自动归档。

**Comment by cdhigh** [comment]
#114
这个现在还没有搞清楚，不过清楚的一点就是Calibre生成的书籍也无法归档，而KindleEar用的是Calibre的代码。
以前我用Kindle3，是可以自动归档的，换KindleTouch之后就无法归档了，应该是Amazon修改了什么规则。
