### ISSUE TITLE
自定义微信订阅号书籍上传后未出现在列表中

### ISSUE THREAD

**Issue by wavierwister** [cdhigh/KindleEar#212]
自定义的微信订阅号书籍上传后未出现在列表中，不知是何原因。

#!/usr/bin/env python
# -*- coding:utf-8 -*-
from weixinbase import WeixinBook

def getBook():
    return MyWeixin

class MyWeixin(WeixinBook):
    title                 = u'法语公众号'
    description           = u'沪江法语，法语翻译之友，CRI法语在线'
    language              = 'fr'
    feed_encoding         = "utf-8"
    page_encoding         = "utf-8"
    oldest_article        = 1
    feeds = [
            (u'沪江法语', 'http://weixin.sogou.com/gzh?openid=oIWsFt84wRNz2ibcTDEQs1S_1ZfQ'),
            (u'CRI法语在线', 'http://weixin.sogou.com/gzh?openid=oIWsFt9t5d69wfW5ogk95eXt8XpU'),
            (u'法语翻译之友', 'http://weixin.sogou.com/gzh?openid=oIWsFt-1oY6bGMs2L46hUcEdevHQ')
            ]

**Comment by cdhigh** [comment]
python是通过缩进进行语法分析的，而且对文件的编码比较敏感，请确认，并且通过后台的LOGS错误信息定位具体问题。

**Comment by wavierwister** [comment]
![2015-7-4_13-32-48](https://cloud.githubusercontent.com/assets/6317089/8506637/32a5740e-2251-11e5-938c-29131a00c87b.png)

文件可能没有问题，因为没有改动文件，在昨天更新之前一直是会出现在列表中的。详见截图。谢谢回复 :)

**Comment by wavierwister** [comment]
对了，我所说的“出现在列表中”指的是出现在网站订阅列表中，并非是出现在 Kindle 中。如图。
![2015-7-4_13-36-11](https://cloud.githubusercontent.com/assets/6317089/8506641/b64e2d0a-2251-11e5-885d-aa1435cf6e95.png)

**Comment by cdhigh** [comment]
不是让你查看后台的logs吗？

**Comment by wavierwister** [comment]
啊，抱歉，我以为没订阅成功的书籍 logs 不会记录呢。
错误内容如下：
Book 'French' import failed : unexpected indent (weixinbase.py, line 31)
似乎是 weixinbase.py 的 第 31 行的缩进问题？
请问应该怎样修改呢？谢谢解答。

**Comment by cdhigh** [comment]
是的，这个异常不是你的书籍的问题，是weixinbase.py的31行，是升级引入的问题，待升级解决。
你可以先在31行前加一个空格，对齐下面一行即可。

**Comment by wavierwister** [comment]
谢谢作者，辛苦了~！

**Comment by zhu327** [comment]
我只是尝试解决下，最近翻不了墙，也没有测试，所以有问题，先说声抱歉

**Comment by zhu327** [comment]
我都是先更新https://github.com/zhu327/rss这个，然后再顺手更新下KindleEar
