### ISSUE TITLE
有时间的话，大神把“登陆”改成“登录”吧

### ISSUE THREAD

**Issue by javenfeng** [cdhigh/KindleEar#216]
一点微不足道的小细节，嘿嘿。
我有一个小问题，是否可以将首页蓝框里的“分享自由~”替换成刷新随机名言呢，如果可以的话请问怎么实现？

**Comment by javenfeng** [comment]
老大是否考虑考虑建个讨论群组或是QQ群呢？这样的话，能免去许多新手疑问不说，也给老大减轻负担了。

**Comment by cdhigh** [comment]
谢谢，登陆登录确实没有注意，抽时间修正。
至于首页的“文案”嘛，你知道的，“技术狗”一般都不是好的“文案狗”，如果谁有好的文案，可以提给我看看，择优替换就是。
改成随机名言的想法嘛，我觉得也未尝不可，但是名言选择的问题就是更大的问题了，也不容易。
技术实现倒是小事。

**Comment by cdhigh** [comment]
已在1.20.20改正。
