### ISSUE TITLE
繁体中文的书籍无法显示在列表中

### ISSUE THREAD

**Issue by cerebellum92** [cdhigh/KindleEar#218]
我照著教学制作了一本书籍，不过却无法显示在列表中，后台也没有报错。
后来发现可能是因为我用了繁体中文当成 title的关系。
只要将下面繁体字的部份改成简体字就可以正常显示于列表中，也可以订阅。
虽然不影响使用，还是想问问是否有解？
谢谢！

#!/usr/bin/env python
# -*- coding:utf-8 -*-
from base import BaseFeedBook

def getBook():
    return YahooNews 

class YahooNews(BaseFeedBook):
    title                 = u'奇摩新聞'
    description           = u'奇摩新聞'
    oldest_article        = 1
    max_articles_per_feed = 30
    language              = 'zh-TW'
    feed_encoding         = "utf-8"
    page_encoding         = "utf-8"
    mastheadfile          = "mh_kimo.gif"
    coverfile             = "cv_kimo.jpg"
    fulltext_by_readability = False
    fulltext_by_instapaper = False
    network_timeout       = 120
    feeds = [
            (u'社會', 'https://tw.news.yahoo.com/rss/society'),
           ]

**Comment by cdhigh** [comment]
不会，繁体是不影响的，unicode支持的，
肯定是其他错误导致，请附上后台的logs 信息，看是什么原因导入书籍出错。

**Comment by cerebellum92** [comment]
好的，我再试试。
请问
language = 'zh-TW'
这个会影响title 的编码吗？
另外我看过log，有另一本书(Xiaodaonews)的错误，不过没有这一本的，所以很好奇是什么原因。

**Comment by cdhigh** [comment]
language仅做为mobi/epub的元信息，用于查词典自动选择对应语种的词典，或其他用处。
编码是计算机的内部概念，language是语种，两者毫无直接关联。

xiaodaonews的导入错误在1.20.20中已经修正。

还有，如果你是繁体用户，可以删除你不需要的内置书籍，不会影响其他功能。

**Comment by cerebellum92** [comment]
我发现原因了，原来是书籍标题不能与自定义RSS的书籍标题重覆。
不过书籍标题之间有重覆则没有关系
另外我也看简体，所以内置书籍也很好！
谢谢！

**Comment by cdhigh** [comment]
书籍之间也不能重复，即使没有报错，根据加载顺序的不同，仅第一本书籍生效。

**Comment by cerebellum92** [comment]
我是看到有两本知乎日报，可是没注意原来一本用的是繁体的報！
谢谢！学习了！
