### ISSUE TITLE
请问有人尝试在AppScale跑起KindleEar吗?

### ISSUE THREAD

**Issue by zhu327** [cdhigh/KindleEar#219]
最近有个想法,做一个Docker镜像搭建AppScale环境,然后把KindleEar部署在AppScale上面,分享这个Docker镜像,就可以在灵雀云,DaoCloud这样的CaaS平台上享受Kindle推送服务了,也不需要翻墙.所以来问问,还没开始弄.

**Comment by javenfeng** [comment]
需要移植吧？
我是利用Nginx反向代理实现免翻墙的，供你参考。

**Comment by zhu327** [comment]
看了一下估计AppScale跑不起KindleEar,不支持modules

**Comment by cdhigh** [comment]
在上传了代码之后，
除了使用Nginx反向代理实现免翻墙之外，可以直接将appspot中的o（字母o）改成0（数字零）访问你的网站，详见FAQ。
