### ISSUE TITLE
推送微信公众号失败

### ISSUE THREAD

**Issue by fqx** [cdhigh/KindleEar#220]
推送记录里面显示nonews
后台Log：Failure in pushing book '微信公众号：小道消息' : local variable 'eqs' referenced before assignment
1.20.21

**Comment by cdhigh** [comment]
这是因为偶尔连接超时导致异常，在下个版本修复，不过你可以通过 <https://diy-devz.rhcloud.com> 将微信公众号转rss来订阅，这个网站的作者就是实现KindleEar微信订阅功能的技术大牛，而且其网站由他本人维护，更新更频繁，更稳定，强烈推荐。

**Comment by fqx** [comment]
这个作者已经表明这个demo不能用于生成新的RSS了，必须自己搭，而我看了一下自己搭平台比较复杂。

**Comment by cdhigh** [comment]
如果微信封堵IP多次访问，用KindleEar也是一样的，你搭建的KindleEar应用和其他人搭建的KindleEar应用都是同一个IP，会更快被封堵，还不如自己搭建一个呢。
