### ISSUE TITLE
中亚无法推送生成的mobi格式

### ISSUE THREAD

**Issue by luckykong** [cdhigh/KindleEar#225]
顺利部署了最新版，gappp上也生成了推送文档，但是最后收到了中亚发的无法推送的回信。

》》》》》》
尊敬的客户，

您从2015年8月15日15:16 发出的如下文档无法发送到您指定的Kindle上：
* KV-G(2015-08-15_22-48).mobi

Kindle个人文档服务目前只能转换并发送以下类型的文档：
Microsoft Word (.doc, .docx) 
RTF文件(.rtf) 
HTML(.htm, .html)
TXT文件(.txt) 
Zip, x-zip压缩文件
Mobi格式电子书 

JPEG (.jpg), GIF (.gif), Bitmap (.bmp) 和 PNG (.png) 格式的图片。
Adobe PDF (.pdf)文档可维持原文件格式，发送至您的Kindle。

Adobe PDF (.pdf)文档可转换为Kindle格式发送，目前处于试用阶段。

如上述格式的文档未成功发送，请确认文档是否受到密码保护或被加密。特别说明，目前最新的Kindle支持读取受密码保护的PDF文档。

以附件形式发送个人文档时的使用提示：
每个附件文档大小应在50MB以下（压缩到ZIP文件中之前）
邮件的附件数不能超过25个

要了解发送个人文档至Kindle的更多信息，请访问帮助页面：
http://www.amazon.cn/Kindledocuments/

如您需要人工协助，欢迎拨打客服电话 4008170100(国内客户) 或 +86-22-59677408(国际客户)

真诚地，
亚马逊Kindle客服

该邮件仅用于自动发送相关说明及通知，请勿回复。

进入Kindle商店选购

如果您有更多有关Kindle的问题，请访问亚马逊Kindle帮助中心
Kindle帮助中心提供常见问题解答，以及亚马逊Kindle客服专员的联系方式。
如需联系亚马逊Kindle客服，请点击帮助页面【联系我们】按钮，客服人员将通过电话或电子邮件与您取得联系。
》》》》》》

但是如果把生成的mobi通过数据线传到kv里，可以正常打开。
换用别的邮箱手工发送，也收到中亚的同样的回信。

上网搜了一下，有种说法是 calibre中新的mobi格式，其实是azw3格式的。转换的时候要选择“旧”的mobi格式才是真正的mobi，才能推送。。
想问问是这个原因么？应该如何解决这个问题？

**Comment by cdhigh** [comment]
这个我无法解答，我不用中亚，而且kindleear生成的是“旧”的mobi格式，没有使用azw3，所以推送应该是没有问题的。
而且之前也有网友反馈可以用于中亚推送，所以无法确定你碰到的是什么问题。

**Comment by luckykong** [comment]
好奇怪。我后来换用美亚账号推送，依然收到了同样的回复，也是无法发送。。囧
我上传一下生成的文件，你试试能不能推送到你账号，可以么~
链接: http://pan.baidu.com/s/1i3GSEDR 密码: kufg

**Comment by luckykong** [comment]
用calibre将文档再次转换成mobi，文件大小变小了一些。直接传到kindle上能看。但是使用邮件推送，依然不行，还是提示我格式不支持。。悲催

**Comment by cdhigh** [comment]
我试了，也无法推送你生成的文件，是不是有什么非法或amazon不允许的内容啊：）
删掉一些订阅或换其他订阅源看看？

calibre再次转换时文件当然会变小一些，因为kindleear跑的环境限制，无法压缩源文件，而calibre是可以在本机压缩的。

**Comment by luckykong** [comment]
更换订阅源我试过了。订阅的都是默认的列表里的东西。
先后试过 华尔街日报，The Economist, FT中文网, 喷嚏图卦 ,知乎日报 ,糗事百科,知乎日報。都是同样的无法推送。
有个稍微过分的请求，能不能在你的 ear上给我建个用户，我用来测试一下，看看能不能正常推送。测试完你可以删掉我。 
或着能不能麻烦你再重新用uploader的方式部署一个新应用，试试能不能推送。

**Comment by cdhigh** [comment]
试一下吧，账号密码都是test

**Comment by luckykong** [comment]
额，不好意思，问一下，demo网站是什么？
我是直接搜到这个项目的，没有看到你的介绍~

**Comment by luckykong** [comment]
ok,我随便选了一个ft中文，点了立即推送，试试看能不能收到

**Comment by luckykong** [comment]
好奇怪。在你的上面正常使用，没有问题。
我又重新部署了一下我的app，然后也能正常使用了。。囧
这个事情太诡异了。
那就算解决了，我关掉这个comment

**Comment by luckykong** [comment]
最后再补充一点，后来又实验了几次，发现可能是标题格式的问题。
我选择”标题 月/日“的格式，就无法推送，选择”标题“或者”标题 英文月 日“就可以推送。
或许就是标题里的符号的问题吧

**Comment by cdhigh** [comment]
好像是这样，不过因为有不少网友用kindleear推送至多看，所以还不能去掉此设置，等合适的时候我将其加入faq吧
