### ISSUE TITLE
请问可以添加一个中文传媒精选的订阅吗？

### ISSUE THREAD

**Issue by jjhhh464** [cdhigh/KindleEar#226]
狗耳朵里面提供的中文传媒精选的RSS用不了。我自己也找了一下关于中文传媒精选的东西实在太少了。

**Comment by cdhigh** [comment]
是中文传媒精选这个网站打不开了，所以不管是谁都推送不了，不过如果以后其恢复了，我倒是可以🏠一个。

**Comment by jjhhh464** [comment]
嗯。但是在狗耳朵上面有时候也可以收到推送，不知道他那个是怎么弄的

**Comment by cdhigh** [comment]
狗耳朵不会无中生有，总要有源头，那说明中文传媒精选网站不稳定。

**Comment by jjhhh464** [comment]
哦
希望kindleear以后能添加上来。谢谢！
