### ISSUE TITLE
升级到最新版本后发现不显示默认封面图片了

### ISSUE THREAD

**Issue by runbing** [cdhigh/KindleEar#227]
cdhigh 兄，又来叨扰。

我是最近两天在 Windows 下用 kindleear_uploader 上传的，今天收到推送却发现原来能正常显示的封面图片 cv_default.jpg 没有显示。

我把推送到 Kindle 的 AZW 格式文件拖放到 Calibre 软件中，发现封面图片却是显示的 mh_default.gif 这张图片。转换成 EPUB 格式并编辑，发现资源里面也没有 cv_default.jpg 这张图片。请问这是咋回事儿？和上传或者配置有关系吗？

**Comment by cdhigh** [comment]
我不知道你是从哪个版本升级过来的，如果是封面问题，可能是1.20.1新增的拼接各封面图片特性导致。
可以参考faq的“如何修改多本书籍合并后的封面？”条目看看。
大体来说，多个书籍合并推送使用DEFAULT_COVER_BV指定的封面，如果不指定，则自动动态生成一个拼接图。

如果不显示图，可能是DEFAULT_COVER_BV指定的图片不存在或非法，试一下单独推送一本书看看？

**Comment by runbing** [comment]
感谢解答。

升级前的版本大概是一年前的了。按照 FAQ 中的提示修改后，发现确实是 DEFAULT_COVER_BV 设置的问题，我将其值 None 改为 cv_bound.jpg（和 cv_default.jpg 相同的图片）就又显示封面图片了。

这么说，当配置默认为 DEFAULT_COVER_BV =  None 时，自动拼接封面图片的新功能没能生效？

**Comment by cdhigh** [comment]
你看看后台logs有没有什么错误信息。
拼接图片功能我一直在用，每天封面不一样会有点点新鲜感，打开书籍前点心情好一点：）

**Comment by runbing** [comment]
谢谢如此用心。:)

日志里倒是没有什么错误，只有几个可能是订阅源失效导致的抓取错误 fetch rss failed(502)。忽然想到，我用的都是自定义的 RSS 源，没有使用程序自带的那些订阅，我看程序自带的订阅都有各自的封面图片资源，是不是这个原因导致自定义的 RSS 源没封面图片可拼，所以程序就直接留空了。

**Comment by cdhigh** [comment]
你找到了KindleEar的一个bug，这种情况下应该要用默认图片的，不应该留空的。

过两天修改。

**Comment by runbing** [comment]
有劳啦。坐等更新。XD
