### ISSUE TITLE
自定義書籍下載到Kindle後,出現[無法啟動選定應用程序,請重試.]

### ISSUE THREAD

**Issue by DaimonBaby** [cdhigh/KindleEar#229]
這個是模仿大大的,但是就是不行,會出現標題上的錯誤.求解

#!/usr/bin/env python
# -*- coding:utf-8 -*-
from base import BaseFeedBook

def getBook():
    return macaodaily

class macaodaily(BaseFeedBook):
    title                 = u'澳門日報'
    language              = 'zh-tw'
    feed_encoding         = "utf-8"
    page_encoding         = "utf-8"
    mastheadfile          = "mh_macaodaily.gif"
    coverfile             = "macaodaily.jpg"
    network_timeout       = 150
    oldest_article        = 0
    feeds = [
            (u'澳聞版', u'http://snufkinto.appspot.com/rss/macaodaily?pagecat=macao',True),
            (u'要聞港聞版', u'http://snufkinto.appspot.com/rss/macaodaily?pagecat=foreign',True),
            (u'經濟版', u'http://snufkinto.appspot.com/rss/macaodaily?pagecat=finance',True),
            (u'體育版', u'http://snufkinto.appspot.com/rss/macaodaily?pagecat=sport',True),
            (u'娛樂版', u'http://snufkinto.appspot.com/rss/macaodaily?pagecat=entertain',True),
            (u'副刊及其他版', u'http://snufkinto.appspot.com/rss/macaodaily?pagecat=misc',True)
            ]

**Comment by ipepys** [comment]
请问你是部署什么程序在app engine 上生成这个rss的？好像澳门日报本身没有提供RSS

**Comment by DaimonBaby** [comment]
不是我 部署的，我是网上找的，不过看了澳门日报的源代码，也不会很难，等这个APP失效了，到时候自己再用JAVA 做出抓取网页信息生成APP就可以了。
2015年9月4日 下午3:07，"ipepys" <notifications@github.com>写道：

**Comment by DaimonBaby** [comment]
现在有能用的就懒得自己做了。
2015年9月4日 下午3:07，"ipepys" <notifications@github.com>写道：
