### ISSUE TITLE
為什麼自動投遞時不時就會出現[over quota]

### ISSUE THREAD

**Issue by DaimonBaby** [cdhigh/KindleEar#231]
我看過,文件也不大,才6M多,但是就時不時會出現over quota,進入後臺看,差很多才到免費配額呀.
手動投遞就不會出現這個情況,真是奇怪

**Comment by cdhigh** [comment]
后台logs有记录具体的超配额原因，你看看，如果不清楚就贴上来。

**Comment by cdhigh** [comment]
还有，出现这个错误后你的推送能否收到，也就是说软件自动会重试，不知重试后能否发出。

**Comment by DaimonBaby** [comment]
谢谢，我截图了，是出现在早上的时候，因为报纸没出RRS，所以就不显示了，不然会和谐的。

**Comment by DaimonBaby** [comment]
![1](https://cloud.githubusercontent.com/assets/14035954/9699721/a4bc4d88-541f-11e5-91f1-3c071420dad7.PNG)
![2](https://cloud.githubusercontent.com/assets/14035954/9699723/a8c7a08a-541f-11e5-9819-e5a9ec4bd733.PNG)

**Comment by cdhigh** [comment]
你提供的logs截图是default模块的，所以无法知道worker模块的异常信息，不过从你的推送记录看，是先推了一个15.7MB和210.6KB的邮件后才出现overquota的。
根据google提供的免费quota清单（https://cloud.google.com/appengine/docs/quotas#Mail），
我猜是超了附件流量突发限制：10 MB/minute。
你可以试一下将queue.yaml中的rate改成“1/m”看看，修改后设置为每分钟最多处理一个任务，应该不会超邮件附件的流量突发限制，你可以试一下。

**Comment by DaimonBaby** [comment]
好的，谢谢您的帮助
2015年9月5日 下午11:15，"cdhigh" <notifications@github.com>写道：

**Comment by DaimonBaby** [comment]
那个一分钟一个任务好像不行，昨晚看了，还是同一时间执行了几次任务，我已经修改过而且上传了。
你说的那个日志我已经截图了，但是就是没有案发时间那段记录，奇怪了，而且多了一堆奇怪的UIL，给你看看，什么999111的，我都没有输入过进去。
![3](https://cloud.githubusercontent.com/assets/14035954/9703888/56a8749c-54c3-11e5-93d9-7c37f98ab8f5.PNG)
![4](https://cloud.githubusercontent.com/assets/14035954/9703889/5aff9f5c-54c3-11e5-98fd-a5593eb8958a.PNG)
![5](https://cloud.githubusercontent.com/assets/14035954/9703892/609c642c-54c3-11e5-82af-a2e381061ea3.PNG)
![6](https://cloud.githubusercontent.com/assets/14035954/9703893/6410fb22-54c3-11e5-98a0-921d4c3f984f.PNG)

**Comment by cdhigh** [comment]
你现在是http网络流量超了，免费额度是22 MB/Min，估计你的rss里面图片太多太大导致。
在有新的解决方案前，
你可以先再建一个账号，将书籍或rss分散一下。

**Comment by DaimonBaby** [comment]
谢谢您的回复，我回去试试

**Comment by DaimonBaby** [comment]
其实能否将那个错误重试设定到5分钟后重试呢？那个错误重试是在那个文件里面实现的方法？我回去研究研究，谢谢

**Comment by cdhigh** [comment]
你可以尝试一下，文件lib/urlopener.py

**Comment by DaimonBaby** [comment]
謝謝,我直接在這裡等兩分鐘算了,反正又不趕時間.
                cnt = 0
                while cnt < self.maxFetchCount:
                    time.sleep(120)
                    try:

**Comment by DaimonBaby** [comment]
.........原來這個循環會執行很多次....
在這裡加等待會等很久,現在改為程序開頭就等一等了

**Comment by mangococo** [comment]
你好,请问在程序开始添加延时,这里说的开始是哪个位置？谢谢
