### ISSUE TITLE
微信获取文档是不是又不行了？

### ISSUE THREAD

**Issue by angel126** [cdhigh/KindleEar#232]
最近都收不到文章，推送都是显示0.，管理是否正常？

**Comment by cdhigh** [comment]
我不用微信，也无法提供此特性的技术支持。

**Comment by angel126** [comment]
哦哦，我看了帮助里面有微信公众号订阅指南，发现例子不能用了，我自己修改的也不能用了。

**Comment by cdhigh** [comment]
既然你看了faq，应该也知道了，对于微信这个封闭的体系来说，只能一直和它做猫和老鼠的游戏，需要不停的升级去应付，
此特性是网友友情支持实现的，
而且我又不用微信，所以我更无法提供技术支持了。
有待其他网友更新或pull request才可以。
