### ISSUE TITLE
如何在vps上运行

### ISSUE THREAD

**Issue by WangZhengmao** [cdhigh/KindleEar#233]

**Comment by cdhigh** [comment]
装个linux，直接运行linux版本的calibre

**Comment by WangZhengmao** [comment]
低配的vps不想用vnc如何使用命令行运行

**Comment by cdhigh** [comment]
试一下这个吧，用了部分kindleear代码，但是可以部署在vps上，

https://github.com/ynhacler/Redkindle

**Comment by WangZhengmao** [comment]
3Q 然而我用的centos

**Comment by cdhigh** [comment]
没有本质的区别， 理解了部署方案和步骤，centos也可以部署的。
