### ISSUE TITLE
最近两次发送被亚马逊拒绝了，请问下可能是什么原因？

### ISSUE THREAD

**Issue by zxq1002** [cdhigh/KindleEar#234]
尊敬的客户，

您从2015年9月20日22:39 发出的如下文档无法发送到您指定的Kindle上：
* Kindle RSS订阅推送(2015-09-21_06-38).mobi

Kindle个人文档服务目前只能转换并发送以下类型的文档：
Microsoft Word (.doc, .docx) 
RTF文件(.rtf) 
HTML(.htm, .html)
TXT文件(.txt) 
Zip, x-zip压缩文件
Mobi格式电子书 

JPEG (.jpg), GIF (.gif), Bitmap (.bmp) 和 PNG (.png) 格式的图片。
Adobe PDF (.pdf)文档可维持原文件格式，发送至您的Kindle。

Adobe PDF (.pdf)文档可转换为Kindle格式发送，目前处于试用阶段。

如上述格式的文档未成功发送，请确认文档是否受到密码保护或被加密。特别说明，目前最新的Kindle支持读取受密码保护的PDF文档。

以附件形式发送个人文档时的使用提示：
每个附件文档大小应在50MB以下（压缩到ZIP文件中之前）
邮件的附件数不能超过25个

要了解发送个人文档至Kindle的更多信息，请访问帮助页面：
http://www.amazon.cn/Kindledocuments/

如您需要人工协助，欢迎拨打客服电话 4008170100(国内客户) 或 +86-22-59677408(国际客户)

真诚地，
亚马逊Kindle客服

**Comment by wavierwister** [comment]
出现同样的问题……

**Comment by lijsh** [comment]
也出现同样的问题……

**Comment by cdhigh** [comment]
这个我不确定，
只有之前的一个网友反馈如果标题设置为月/日 格式后无法推送，
如果不是这个原因，我就不知道了，我现在还没有碰到过此问题。

**Comment by ibrother** [comment]
@zxq1002 查看推送日志看看文件大小，kindle的文档推送服务似乎对有些文件名有问题
