### ISSUE TITLE
可以在其他平台是部署吗？

### ISSUE THREAD

**Issue by WuHuaJi0** [cdhigh/KindleEar#238]
readme里提到了再gae部署的方法，如果我现在国内的云平台部署，例如：新浪云应用，是否能方便部署呢？

**Comment by javenfeng** [comment]
作者还没有推出在其他平台部署的版本，不过有一个叫Redkindle的推送网站是在本站的基础上改的，你可以去看看。他是部署在了VPS上了。作者的意思是需要移植。

**Comment by WuHuaJi0** [comment]
好的，多谢 :D
