### ISSUE TITLE
请问自制的book怎么更新到gae上？

### ISSUE THREAD

**Issue by fdulezi** [cdhigh/KindleEar#239]
放在book文件夹下，用了vacuum_indexes再update_indexes，订阅网页里也看不到新的book

**Comment by cdhigh** [comment]
一般是你的py文件有误，打开后台看看异常信息。

**Comment by chengshuyi** [comment]
@fdulezi 我和你一样，本地测试无误，用gcloud上传无法更新，我觉得应该需要重启gae，但是我不会。请问这个问题你现在解决了吗？
