### ISSUE TITLE
Instructions for server (droplet) installation (as GAE is no longer free)

### ISSUE THREAD

**Issue by dx486** [cdhigh/KindleEar#240]
Google App Engine is no longer a free service. Therefore some information on the [web site of Kindle's Ear](https://kindleear.appspot.com/static/faq_en.html#needserver) is not valid now. 

Could you please update its web site?

Could you please kindly explain how users can run Kindle's Ear on their own servers in the instructions at Kindle's Ear's web site? Information for inexperienced users would be highly appreciated.

**Comment by cdhigh** [comment]
GAE is not a free service, but has free quotas, you dont need to pay a penny to deploy and run KindleEar.
