### ISSUE TITLE
请教，杂志的网格模式下的图片显示问题

### ISSUE THREAD

**Issue by runbing** [cdhigh/KindleEar#241]
cdhigh 兄，

这个问题非 KindleEar 使用相关的问题，一直没有找到解决方法，所以想请教您一下。如果您熟悉的话可以指点一下，如果不熟悉可以略过。

最近我在手动制作杂志，生成杂志的时候会用到一个 ncx 文件，这个文件中的代码可以控制列表显示的内容，就像 KindleEar 推送后打开那样：

![2](https://cloud.githubusercontent.com/assets/488066/10789290/75e89478-7db7-11e5-9b65-a5617e3447a5.jpg)

代码内容如下：

```
<navPoint playOrder="6" class="article" id="item-004">
	<navLabel>
		<text>亚马逊已经成为美国电子书大战的赢家？</text>
	</navLabel>
	<content src="../html/004.html" />
	<mbp:meta name="description">亚马逊的市场份额的占有率可能比以前所认为的要高得多，全美 74% 的电子书都是通过 Kindle 商店销售的。其余的电子书竞争对手持有的市场份额如此之小，很难给 Kindle 商店带来什么真正的竞争。</mbp:meta>
	<mbp:meta name="author">Runbing</mbp:meta>
</navPoint>
```

但是我发现在使用 KindleEar 推送杂志时，在网格目录格式下，标题下面都有一张图片：

![1](https://cloud.githubusercontent.com/assets/488066/10789299/88bb40aa-7db7-11e5-97e2-7cc63c8d92f2.jpg)

但是我试着翻 KindleEar 的代码，试图找到插入图片的相关代码，无果。所以想要向您请教一下，是否留意过可以控制显示这个图片的代码？

**Comment by cdhigh** [comment]
apps/utils.py中的InsertToc()
或者你也可以将mobi解包，就可以看ncx了。

**Comment by runbing** [comment]
谢谢指点。

我用 KindleUnpack 或 mobiUnpack 解包 mobi，但是得到的 ncx 文件只能看到标题代码，其它如 description 和 author 等这种放在 <mbp:meta> 标签里的元素都没被正确解析出来。

在 apps/utils.py 中可以看到 ncx 文件应该是由下面这行代码生成的：

```
    #Generate NCX TOC for Kindle
    po = 1 
    toc = oeb.toc.add(unicode(oeb.metadata.title[0]), oeb.spine[0].href, id='periodical', klass='periodical', play_order=po)
    po += 1
    for ncx in ncx_toc:
        if ncx[0] == 'section':
            sectoc = toc.add(unicode(ncx[1]), ncx[2], klass='section', play_order=po, id='Main-section-%d'%po, toc_thumbnail=toc_thumbnails[ncx[4]] if GENERATE_TOC_THUMBNAIL and ncx[4] else None)
        elif sectoc:
            sectoc.add(unicode(ncx[1]), ncx[2], description=ncx[3] if ncx[3] else None, klass='article', play_order=po, id='article-%d'%po, toc_thumbnail=toc_thumbnails[ncx[4]] if GENERATE_TOC_THUMBNAIL and ncx[4] else None)
        po += 1
```

其中 description 是控制摘要的，现在能实现，代码是：

```
<mbp:meta name="description">这里是摘要内容。</mbp:meta>
```

代码里的 toc_thumbnail=toc_thumbnails[ncx[4]] 应该就是控制缩略图显示的，但是我尝试使用下面的代码，仍然没有生效：

```
<mbp:meta name="toc_thumbnail">../image/003-thumb.jpg</mbp:meta>
```

不过知道是不是写错了。如果有一个生成好 ncx 文件但是没有打包好 mobi 文件的源代码就好了。根据关键词搜了一天也没找到啥结果。囧……

**Comment by cdhigh** [comment]
这个问题我现在也没有解决方案，估计要你自己搜索解决了。

**Comment by runbing** [comment]
好的，我再找找看。还是谢谢你的解答。:)

**Comment by OhiyoX** [comment]
> 好的，我再找找看。还是谢谢你的解答。:)
> 

请问这个问题解决了吗？能否告知一下toc_thumbnail怎么用
