### ISSUE TITLE
求助。。。send  failed

### ISSUE THREAD

**Issue by zytomorrow** [cdhigh/KindleEar#245]
今天早上突然出现的 send  failed....没有出现错误日志。。。。是由于今天的文件过大了吗？
![2](https://cloud.githubusercontent.com/assets/16175551/12134411/0f6a5ea4-b46a-11e5-8e27-87e78abd491c.png)
![1](https://cloud.githubusercontent.com/assets/16175551/12134413/0f92fb2a-b46a-11e5-938d-02e4ef60d92e.png)

**Comment by cdhigh** [comment]
你自己写的dbsp书籍出错导致，缩进有误。

**Comment by zytomorrow** [comment]
嗯。。。这个问题我发现了。。。今天进去把这个book修改了。。。这是20多天的之前上传的。。。这个错误持续了这么久，今天修改了。。。今天的那个推送失败貌似不是这个book的问题

**Comment by cdhigh** [comment]
你给的后台logs只有default模块的，要看worker模块才行。

**Comment by zytomorrow** [comment]
![222](https://cloud.githubusercontent.com/assets/16175551/12160697/887b7e80-b529-11e5-822e-a4bc3ae931d3.png)这是那个logs。。。没看懂失败原因

**Comment by cdhigh** [comment]
这个异常是gae 本身的bug，可能文件过大偶然触发的也有可能，但是文件过大不一定会触发此bug。
你再看看过几天还有没有此异常？

**Comment by zytomorrow** [comment]
嗯啦。。。除了那一次推送失败其余推送都很好。。。非常感谢，kindleear这个服务真的挺好用
