### ISSUE TITLE
无法自动投递，只可以手动推送。gae管理页worker模块里内容为空。

### ISSUE THREAD

**Issue by shadowascetic** [cdhigh/KindleEar#246]
按照github上的步骤来的，手动添加和运行help.py添加都试过。
每次部署最后都要手动更新索引
更新索引完后，都能手动推送，但是都不能自动推送。
gae管理业worker module里内容是空的。
试了好几遍了，求救！谢谢！

**Comment by shadowascetic** [comment]
![qq 20160106160108](https://cloud.githubusercontent.com/assets/16571463/12138392/83e5c5e2-b493-11e5-8fc4-280c414a9eb8.png)

**Comment by cdhigh** [comment]
能手动推送说明worker模块是好的，如不能自动推送，则在后台看cron jobs启动了没有

**Comment by shadowascetic** [comment]
@cdhigh 你好 我看了下gae下的cron jobs 没有启动，点进去就进入新版gae界面了，找了很久都没有找到哪里可以开启这个cron jobs ，求详细 谢啦~

**Comment by cdhigh** [comment]
感觉没有部署完整，可以试一下手动执行以下命令：
python appcfg.py update_cron KindleEar/
python appcfg.py update_queues KindleEar/
python appcfg.py update_dispatch KindleEar/

在FAQ中都有说明。

**Comment by shadowascetic** [comment]
@cdhigh 这些命令都执行完后试了试还是不行，gae里多了个dispatch选项，但cron 还是未启动状态。faq页全是html完整代码，看了下没有找到。。。我又把faq里的代码复制用editplus编辑另存为html文件，用各个浏览器打开都是乱码。
求进一步指教。。。cron仍未启动成功

**Comment by shadowascetic** [comment]
@cdhigh faq页存html忘了改文字编码格式了，可以看了。这次我有严格按照教程和faq里的说法重新建了一个，但是cron还是灰的。。。

**Comment by cdhigh** [comment]
cron灰是什么意思，没有cron项还是cron项没有启动？
你用什么系统部署的？
试过uploader吗？

**Comment by shadowascetic** [comment]
@cdhigh 额，是说cron项没有启动。我用的win10部署的，还没用uploader。
不过我在之前改动的基础上又把推送文章的时间限制从无限制改到了3天为止，居然就可以自动推了！
谢啦！
