### ISSUE TITLE
在其他rss阅读器上完整显示的feed，但通过kindleear推送却只有标题。求解

### ISSUE THREAD

**Issue by shadowascetic** [cdhigh/KindleEar#247]
订阅feed：
【知乎专栏订阅】：
http://zhuanlan-rss.songchenwen.com/rss/wusuobuneng,zhangnini11,PatrickZhang,ESDesign,energyer
我在inoreader订阅器上订阅这条feed能完整显示内容，但是通过kindleear推送到kindle上却只有文章标题。
求解，求测试，谢谢！

**Comment by cdhigh** [comment]
此RSS是全文RSS，在订阅时请勾选“isfulltext”即可，我试了没问题，正常订阅推送。

如果不勾选“isfulltext”，则KindleEar需要连接上zhihu.com来抓取网页内容，而zhihu几年前就开始封锁了GAE的IP段访问，所以无法获取到内容，除非你将其写成内置书籍形式，然后使用转发器。

**Comment by shadowascetic** [comment]
@cdhigh 成功！谢谢！这工具太强大了！赞！
