### ISSUE TITLE
最近几天收不到投递，投递日志状态wrong SRC_EMAIL

### ISSUE THREAD

**Issue by lpfphilip** [cdhigh/KindleEar#248]
gmail和 kindle推送邮箱全都填写正确，worker模块显示UNAUTHORIZED_SENDER，请问该如何解决

**Comment by lpfphilip** [comment]
![qq 20160109101529](https://cloud.githubusercontent.com/assets/15854908/12213789/f28314f0-b6b9-11e5-8c68-64f99cf6d2ab.jpg)
![qq 20160109095801](https://cloud.githubusercontent.com/assets/15854908/12213790/f2865732-b6b9-11e5-8ef5-9d404ad2dae4.jpg)

**Comment by cdhigh** [comment]
到Gae后台的settings页面，看看email已经授权的账号里面有没有的的发送账号，如果没有就添加。

**Comment by lpfphilip** [comment]
成功了，谢谢您

**Comment by zytomorrow** [comment]
同样出现了这个错误。。。那个setting页面 的email设定是指这个吗。。。。
![Uploading QQ截图20160112230339.png…]()。。。

**Comment by zytomorrow** [comment]
![qq 20160112230339](https://cloud.githubusercontent.com/assets/16175551/12267667/2bf49cdc-b984-11e5-9124-0b24d25a3437.png)  同样遇到了这个问题。。。email设定是指这个吗。。。

**Comment by zytomorrow** [comment]
谢谢。。。我用gmail邮箱替换了这两个默认的email就可以正常推送了。。。但是不知道这个问题的产生原因

**Comment by cdhigh** [comment]
我也不知道为何你的email会被修改，可能是GAE后台的BUG吧。

**Comment by zytomorrow** [comment]
嗯。。。谢谢解答

**Comment by nietulong** [comment]
我的Dashboard是灰色的，点不了哦，不知道怎么回事 @cdhigh

**Comment by cdhigh** [comment]
是不是中间有删除线？
不怕，你点它就行了。

**Comment by nietulong** [comment]
我点Dashboard之后，它就转到新版gae管理界面去啦。https://console.cloud.google.com/  @cdhigh

**Comment by cdhigh** [comment]
这不就是我要说的吗，新版的，功能一样。

**Comment by imhzr** [comment]
你好在哪里设置 email  新版后台 没有找到设置的地方啊 @cdhigh

**Comment by 858876586** [comment]
在“APP 引擎”中的“设置”页面，在“应用设置”标签项下点击【修改】按钮，在“Email API 获得授权的发件人”这一项里填入你的 Gmail 地址，点击【保存】按钮，确保保存成功。
---kindle伴侣
