### ISSUE TITLE
分享方式能不能添加分享到Pocket

### ISSUE THREAD

**Issue by enneaa** [cdhigh/KindleEar#249]
如题，稍后阅读服务 Pocket 用的挺多的，要是能支持分享到 Pocket 就好了，多谢。

**Comment by cdhigh** [comment]
我之前开发的时候Pocket还不够流行，当时Google reader刚刚关闭，Pocket等类似这些软件也刚刚起步，不过现在可以考虑添加进去。

**Comment by enneaa** [comment]
翘首以盼，Pocket多平台支持，还可通过ifttt联接众多服务，相当好用。

**Comment by cdhigh** [comment]
V1.21已经添加此功能，请试用，有BUG请反馈。

**Comment by cdhigh** [comment]
v1.21.1增加了保存至Instapaper功能。

**Comment by cdhigh** [comment]
这个功能仅是在KindleEar上碰到好的文章后发送至Pocket。
至于说反向的同步功能：Pocket的文章列表推送至KindleEar。

我本来打算也一并开发的，但是后来发现Pocket本身就提供RSS订阅源功能，在“隐私控制”里面可以找到每个人的专有RSS地址，将其关闭密码保护，然后添加至KIndleEar即可，这样在其他平台上添加到Pocket的新文章也可以合并后推送至KindleEar再仔细阅读。

一正一反的同步，我爱死这个功能了！

**Comment by enneaa** [comment]
太赞了，非常好用，多谢开发者
