### ISSUE TITLE
关于订阅无法推送的问题

### ISSUE THREAD

**Issue by wong2843** [cdhigh/KindleEar#253]
你好，我已经订阅了知乎日报，可是从1月21号开始就开始无法推送了，在这之前都是正常推送的。点了手动推送也无法推送，查看了日志都是（no news）,不知道现在为什么，请问这个如何解决呢？

**Comment by wong2843** [comment]
你好，我已经订阅了知乎日报，可是从1月21号开始就开始无法推送了，在这之前都是正常推送的。点了手动推送也无法推送，查看了日志都是（no news）,不知道现在为什么，请问这个如何解决呢？

**Comment by cdhigh** [comment]
最近用的人太多，heroku上的免费转发器有流量限制，应付不了了，我刚去heroku重设了一下。
heroku上的转发器是我搭建免费提供给网友用来抓取知乎，和翻墙提供“归档分享”功能的，我在FAQ中也说明了，建议有余力的都自己搭建，以便留出更多资源给那些不懂技术的同学使用。

建议你自己搭建一个，代码都有了 <https://github.com/cdhigh/forwarder> ，很简单的，在heroku上申请一个账号就可以根据提示搭建了。
对你而言，自己的转发器是一劳永逸的。

从现在的流量使用情况看，我的heroku转发器可能会不定时罢工，也会影响你的使用的。

**Comment by mingde816** [comment]
@cdhigh 你好，我按照你的教程在heroku上尝试搭建了，但是最后一步git push heroku master的时候，老是上传失败。
直接关联GitHub也是一样。错误如下，请大神解决。
 !     Push rejected, no Cedar-supported app detected
HINT: This occurs when Heroku cannot detect the buildpack
      to use for this application automatically.
See https://devcenter.heroku.com/articles/buildpacks
