### ISSUE TITLE
I don't get articles from all rss sources

### ISSUE THREAD

**Issue by mgarciate** [cdhigh/KindleEar#256]
Hi, I've added some custom rss sources to Kindleear from the webpage and I just receive some of them. I mean, from some sources I get all the articles, from others I get nothing. For example, it happens with this feed from [Lifehacker](http://feeds.gawker.com/lifehacker/vip) which is quite famous. I can send a book through Calibre setting the same url. Any idea? I don't get any information looking at the GAE log. Thanks!

**Comment by cdhigh** [comment]
KindleEar supports only RSS/ATOM format. but the link you give in issue is HTML format,
you can append a query string 'format=xml' to the link, for example:

<http://feeds.gawker.com/lifehacker/vip?format=xml>

**Comment by mgarciate** [comment]
@cdhigh Now, it works like a charm, thanks a lot!
