### ISSUE TITLE
投递失败：wrong SRC_EMAIL

### ISSUE THREAD

**Issue by TuringKi** [cdhigh/KindleEar#260]
请问我投递一直报wrong SRC_EMAIL错误是怎么回事？
我的邮箱地址应该是设置正确了的啊。。。。

**Comment by TuringKi** [comment]
已经解决。。。
“到Gae后台的Settings页面，看看 已经授权的Email列表里面有没有你的发送邮箱地址，如果没有就添加即可。”

**Comment by jm-huang** [comment]
您好，请问需要添加哪个 Email 到授权地址里面啊？是不是 kindleear 的邮件地址啊？请问是多少啊？谢谢
