### ISSUE TITLE
Deployment successful - but logs show wrong src_email

### ISSUE THREAD

**Issue by winterland25** [cdhigh/KindleEar#261]
My deployment of kindleear was successful and I have updated the src_email in the config.py file. But each time the deliver happens, I get in the application logs - 'wrong SRC_EMAIL'
The developer console logs in the end show:

NeedIndexError: The index for this query is not ready to serve. See the Datastore Indexes page in the Admin Console
The suggested index for this query is:
- kind: Feed
properties:
 - name: book
- name: time

I tried updating indexes, but that didnt help. In the Datastore indexes, it shows that this Index is serving.
Thoughts?

**Comment by cdhigh** [comment]
I though that google changed some default settings for GAE projects, many users got error 'wrong SRC_EMAIL' recently, and this issue never happened before.
Please follows:
Go to <https://console.developers.google.com/appengine/settings>, in 'Settings' | 'Application settings' page, add your email into field 'Email API authorized senders'.

For Index error you had met, I have no idea, please ensure that index.yaml is right firstly, or you may deploy the project again?

**Comment by winterland25** [comment]
Thanks this worked! I think the deployment instructions need to be modified to add this step.
