### ISSUE TITLE
自动推送始终不成功 - nonews

### ISSUE THREAD

**Issue by imhlq** [cdhigh/KindleEar#262]
cron任务没问题，log中有每次推送的记录，但是自动推送的都显示nonews收不到，附件大小显示0，手动推送都是ok能收到。
怎么办。

**Comment by cdhigh** [comment]
附上后台worker模块的logs

**Comment by imhlq** [comment]
![baidushurufa_2016-2-18_15-40-25](https://cloud.githubusercontent.com/assets/10741526/13136621/107c6b26-d656-11e5-83b4-0b4a6defa34b.png)

**Comment by cdhigh** [comment]
自动推送任务和返回值都是正常的，没有什么问题。
应该就是你的RSS源或任务设置的问题。
1.确保RSS源正常，或换其他源看看
2.尝试将最旧文章设置为 不限制 看看
