### ISSUE TITLE
請問一下有辦法直接取用calibre的recipe嗎?

### ISSUE THREAD

**Issue by ZlllC** [cdhigh/KindleEar#263]
如題。還是說須要一些語法上的轉換? coding我不太熟, 但有教學的話, 簡單的都可以照著寫。

p.s. 這個APP真的很棒, 家裏的小server壞了,可以省下買raspberry pi 跑calibre的開銷。

**Comment by cdhigh** [comment]
不能直接用，因为我没有完整的实现calibre的功能，除非是简单的recipe，没有特别的处理。
对应的recipe属性我都是用calibre原先定义的名字，所以，简单的recipe，你熟悉一下就应该可以转换过来。
你可以参考books目录下的文件，base.py是基类，包含了所有的属性，其他的文件都是定制的，每个都是某方面的典型范例，我选择内置书籍不是因为其内容好坏或格调高下，而是其能演示某种内置书籍的编写技巧。

**Comment by ZlllC** [comment]
謝啦！我自己來鑽研一下，有不懂再請教！
