### ISSUE TITLE
某些RSS需要登陆帐号密码，作者能再讲的详细一些吗？

### ISSUE THREAD

**Issue by JJERRYY** [cdhigh/KindleEar#264]
我想拿狗耳朵的已经生成的内容直接但RSS用  像这样 http://www.dogear.cn/read/5

但是需要登陆，然后作者FAQ里的内容看不大懂啊！
是在books 目录下新建一个.py文件  然后这样填吗
```
needs_subscription =True
login_url          =http://www.dogear.cn/u/login
```
上传之后貌似没用啊

另外个问题，GAE应该怎么上传？
我之前用uploader搭建的，现在只要在那个目录里改文件然后再上传一次吗？
还是需要下载GAE SDK 
能说的详细些吗？
谢谢！

**Comment by cdhigh** [comment]
有几个需要澄清的地方：
1.  KINDLEEAR仅支持RSS/ATOM格式的XML订阅源，而htp://www.dogear.cn/read/5是HTML格式的，无法直接做为订阅源，如果需要，你自己需要用python来解读获取其文章列表。
2. “需要登录”的意思是获取文章时需要登录，而不是获取订阅源时需要登录，你现在这样的用法相当于获取订阅源都需要登录，当然不行了。

最后一个上传问题不知为何很多人都有疑惑，第一次怎么上传以后就怎么上传就好了，修改文件就再次上传，不管用uploader还是GAE SDK。
而其实uploader只是将GAE SDK简单封一层皮而已，核心都是一样的。

**Comment by JJERRYY** [comment]
了解了！谢谢回复。发自网易邮箱大师
            在2016年02月23日 18:00，cdhigh 写道:有几个需要澄清的地方：
1.  KINDLEEAR仅支持RSS/ATOM格式的XML订阅源，而htp://www.dogear.cn/read/5是HTML格式的，无法直接做为订阅源，如果需要，你自己需要用python来解读获取其文章列表。
2. “需要登录”的意思是获取文章时需要登录，而不是获取订阅源时需要登录，你现在这样的用法相当于获取订阅源都需要登录，当然不行了。

最后一个上传问题不知为何很多人都有疑惑，第一次怎么上传以后就怎么上传就好了，修改文件就再次上传，不管用uploader还是GAE SDK。
而其实uploader只是将GAE SDK简单封一层皮而已，核心都是一样的。
