### ISSUE TITLE
可否将不支持Atom的网站输出Atom？

### ISSUE THREAD

**Issue by StrollStars** [cdhigh/KindleEar#265]
请问下可否将不支持Atom的网站输出Atom，如将微信订阅号输出成Atom，以方便RSS阅读器订阅？

**Comment by cdhigh** [comment]
嗯，看看FAQ如何？

**Comment by StrollStars** [comment]
3Q，不过https://diy-devz.rhcloud.com/似乎无法访问，即使翻了也不能。

**Comment by cdhigh** [comment]
作者在其github上不是说了吗？由于微信强大的反爬虫机制，需要这个服务的要自己搭建，你可以试一下KindleEar内置的机制是否还可用，我不用微信，不提供更多咨询服务

**Comment by StrollStars** [comment]
谢谢
