### ISSUE TITLE
请问能否设置行距？

### ISSUE THREAD

**Issue by Yzhao26** [cdhigh/KindleEar#266]
您好。推送的文章行距有点小，读起来很费劲。如何自己修改？谢谢~

**Comment by cdhigh** [comment]
如果是内置的“书籍”，则可以通过extra_css自己设置排版参数，如果是“自定义RSS”，则使用Kindle默认排版参数。
如果是你自己的订阅源，可以添加一个py文件到books目录下，设置extra_css，重新上传即可。

**Comment by ZlllC** [comment]
路過問一下, 雪球今日話題的feed: [http://xueqiu.com/hots/topic/rss](url)
似乎用內置“书籍”或自訂的都無法成功獲取, 是否他本身的的rss格式有問題?

**Comment by cdhigh** [comment]
如果想继续订阅雪球，请自己搭建转发器
，包括知乎也一样。
<https://github.com/cdhigh/Forwarder>
