### ISSUE TITLE
有没有可能在您的狗耳朵官网再添加一个订阅百度贴吧帖子抓取的订阅？

### ISSUE THREAD

**Issue by kkkpc** [cdhigh/KindleEar#267]
作者你好，我是忠实的狗耳朵年付用户，用了多年后效果非常好。感谢您伟大的狗耳朵网站。
想问下狗耳朵官网能否再增加个类似于现在微信公众号及知乎分栏的这种方式，用户只需输入所需贴吧名字即可订阅
--------
贴吧可以参考贴吧wap版，比起原版贴吧好抓取：
简版地址：http://tieba.baidu.com/mo/
举例surface pro贴吧：http://tieba.baidu.com/mo/q---0D1F4671F6FAE885DDF2F6F03A8435FF%3AFG%3D1--1-3-0--2--wapp_1397411781944_396/m?kw=surfacepro&lp=1030
---------------
我用feed43.com来写规则烧制RSS规则举例：
surfacepro贴吧RSS输出地址：http://www.feed43.com/surfaceproba.xml

在FEED43烧录里的具体规则如下：
Item (repeatable) Search Pattern处填写
`<div class="i"><a href="{%}&amp;{*}pinf=1_2_0">{%}</a>`

不过效果不够好，因为我只写了抓取贴吧帖子标题规则，没把原帖URL以及帖子里内容包括楼层规则写进去。

仅供作者添加此功能时做思路参考。

**Comment by cdhigh** [comment]
你问错地方了，狗耳朵和KindleEar完全不相干
