### ISSUE TITLE
部署完成后无法推送

### ISSUE THREAD

**Issue by 1703011** [cdhigh/KindleEar#269]
部署完成之后无法推送。
检查了instance_class，没有看到instance_class，不过看到一个trueinstance_class，值本来就是B4。
看了一下日志，对照你以前回复的别的issue应该为“404”错误，“部署时仅部署了default模块，而没有部署worker模块。”，但是我应该如何解决呢？用的是uploader部署的。
谢谢！

![image](https://cloud.githubusercontent.com/assets/4069144/13555901/49d9bbca-e381-11e5-8080-a40a36c3d881.png)

**Comment by cdhigh** [comment]
是worker模块部署不成功导致。
可以试一下再次执行uploader部署，多执行几次都没问题的。
假如你已经安装了python和Gae sdk，也可以执行   
python.exe appcfg.py update module-worker.yaml   
单独部署worker模块。

**Comment by 1703011** [comment]
好的，已经成功了，非常感谢。
还有几个小问题，不过我先使用几天，确认不是我自己不会用或者设置的问题再来问你。
你这个项目接受捐款吗？看了一圈没有找到允许捐款的地方。
再次感谢你的帮助！
cdhigh <notifications@github.com>于2016年3月6日 周日下午1:49写道：

**Comment by cdhigh** [comment]
这个项目本身是我自己的需要，做好了以后想方便更多的人，就开源出来了。
不过你的建议也好，我看过几天是否可以开一个捐款界面，看是否能赚几瓶啤酒喝~

**Comment by 1703011** [comment]
你开了捐款界面我第一个给你买一瓶啤酒：D

用了几天有几个问题：
1.不知道是否可以修改行间距？行间距设置为最宽，却依旧比amazon上购买的书籍行间距小很多。

2.是否可以长图自动分段？比如http://www.iwgc.cn/list/4211，狗耳朵推送会把长图自动分段，并且首尾重复一些像素保证每一句话都可以完整的显示在某一屏，kindleear会把整张长图显示在一页里。
还有两个具体的小问题：
1.rss获取的透明背景图片，kindle上显示背景为黑色
比如图片http://iwgc.cn/getimg/http://mmbiz.qpic.cn/mmbiz/RiacFDBX14xBOeYeFUoYGet1b9PicYxeNxSJMk0146rA9b885RZNl8YrwbB9fuYjd6QfJNtoXp9xOZalAE0l9RGQ/640?wx_fmt=png
我没有验证图片背景是白色还是透明，但是似乎觉得图片背景是透明才可能有这些问题。
2.rss：http://rss.iwgc.cn/rss/494-f5823a80ed52208ce0c474c6cce801602072
中标题为“在北美，哪些爆款家具是留学生活必备的？你肯定都买过”，rss网页上可以看到正文内容
推送内容却是：
北美留学生日报,留学生自己发声的媒体,中国最大的独立留学新媒体.讲述留学生自己的故事,分享有趣而真实的留学生活,发布客观真实的留学资讯,中立、真实、有味道!官方网站:www.CollegeDaily.cn

非常感谢你能花时间回复我！

**Comment by cdhigh** [comment]
1 如果你增加一个py文件到books目录，可以设置其extra_css属性，支持大部分的CSS3标准。
关于长图切割，之前我已经做了一个很简陋的试验：在糗事百科中将长图切割再组合，切割后不组合应该也能做到，等过段时间不忙再考虑考虑。
3 黑色背景的图片我从来没有碰到过，可以试一下将config.py中的COLOR_TO_GRAY设置为False看看。
4 手机上网，暂时无法确认，等电脑上网才能确认。不过文章正文提取本身就难通过一个算法就适配所有网页，可能有部分网页提取错误，在‘分享’里面的Open in brower就是提供一个补救手段。

**Comment by 1703011** [comment]
谢谢！我回去研究一下你说的py文件，可能不会的还需要请教你。

我弄到现在还有不少问题，比如有的源有时候重复推送，有时候又是正常的。有的源间歇性不推送，有些源一直不推送，都完全不知道应该如何解决。

**Comment by 1703011** [comment]
好的吧我放弃了T_T。推送的问题太多了，不知道应该从何开始解决。
还是非常感谢你之前的回答和你开源这个项目帮助别人！
