### ISSUE TITLE
OverQuotaError

### ISSUE THREAD

**Issue by wantanmee** [cdhigh/KindleEar#272]
你好，在推送什么值得买的文章时，后台worker log会提示OverQuotaError：

![image](https://cloud.githubusercontent.com/assets/8599519/13632280/d5537624-e623-11e5-9a36-8358b71dac07.png)

12:45:54.052
OverQuotaError in url [http://am.zdmimg.com/201603/03/56d7d1bc83162.jpg_e600.jpg], retry after 1 minute.

**Comment by cdhigh** [comment]
Gae免费账号有突发流量限制，每分钟不能超过20m，所以kindleear碰到这个瓶颈则延时一分钟后再次尝试，你这种情况正常，一分钟后网页获取成功了。

**Comment by cdhigh** [comment]
因为我面对的是“极客”，所以我在设计中和代码中尽量不要隐藏太多信息，有时候会给不清楚的用户造成一些疑惑。
比如这个错误信息其实不重要，但是我还是将其记录下来了。

**Comment by wantanmee** [comment]
谢谢你的回复~ KindleEar那边一直提示send failed，那看来我收不到推送是因为第二条错误原因？
12:47:19.375
sendmail to ***@kindle.cn failed:The request to API call mail.Send() was too large..<<class 'google.appengine.runtime.apiproxy_errors.RequestTooLargeError'>>

**Comment by cdhigh** [comment]
文件太大了，发不出去

**Comment by wantanmee** [comment]
请问邮件附件大小的上限是多少？我试了一下，26M 的能发成功，29.8M 以上的就不成功了。这个可以通过修改 `config.py` 里面的图片大小来压缩大小吗？

**Comment by cdhigh** [comment]
差不多二十几兆，我以前研究过，不过忘了具体值。
可以修改图片大小缩小尺寸，或将订阅源拆分，或修改每个RSS允许抓取的文章数，
