### ISSUE TITLE
导入订阅列表返回到 /advimport 出现internal server error

### ISSUE THREAD

**Issue by kylinpoet** [cdhigh/KindleEar#273]
![2016-03-21_231345](https://cloud.githubusercontent.com/assets/6766883/13923172/75f756aa-efba-11e5-8f5c-9f171226be8d.png)

**Comment by cdhigh** [comment]
要不你将你导入的文件发到我的邮箱？
cdhigh@sohu.com

**Comment by cdhigh** [comment]
是因为导入的链接中有中文，python解码出错，在下个版本修改，很快发布。

PS：KindleEar无法支持你导入的这么多订阅源，即使能正常下载，生成的文件也会很大，根本发送不出去。

**Comment by kylinpoet** [comment]
收到，谢谢，幸苦了
