### ISSUE TITLE
books 如何在本地进行测试？

### ISSUE THREAD

**Issue by miaowm5** [cdhigh/KindleEar#274]
编辑了 books 下的 py 文件之后，想在本地测试一下是否能够成功生成想要的书籍，请问应该如何操作？

**Comment by cdhigh** [comment]
安装GAE SDK，它就有一个本地调试环境，用它打开kindleear工程，然后在launcher的 extra flags里面加入 module-worker.yaml，就可以调试了，或也可以使用dev_appserver.py打开本地工程app.yaml/module-worker.yaml，一样的，我都是使用dev_appserver.py，至于将生成的书籍发送处理，有多种方法，要不你就建本机SMTP调试服务器，要不就使用sendmail（移植于linux）方案。
我用的是本机SMTP调试服务器方案。
如果嫌麻烦的话，还是上传到GOOGLE服务器吧，多上传几次多调试几次就好。
好像限额是一天1000次上传还是多少，足够你用的。

**Comment by miaowm5** [comment]
好的，谢谢，我还是上传调试吧 :joy:

**Comment by runbing** [comment]
@cdhigh 大神，因为我想修改一下前端，所以试图使用 Launcher 本地调试 KindleEar，按照你说的配置倒是可以访问了。但是页面显示“not found”，Log 中显示：

```INFO     2016-04-28 15:11:45,813 module.py:787] worker: "GET / HTTP/1.1" 404 9```

这是怎么回事儿呢？还需要设置什么地方吗？

**Comment by cdhigh** [comment]
worker模块和default模块的端口地址是不一样的，你输入了worker模块的端口号而出错。

**Comment by runbing** [comment]
@cdhigh 原来如此，感谢点拨，已搞定。
