### ISSUE TITLE
Kindle Paperwhite 每個feed最多顯示20編文章(articles)

### ISSUE THREAD

**Issue by qoolala** [cdhigh/KindleEar#275]
Kindle Paperwhite 每個feed最多顯示20編文章(articles)文章 ?

**Comment by cdhigh** [comment]
软件默认的是每个源最大30篇文章，在base.py里面定义，如果是自己写的py书籍，可以随便定义。

但不是20篇，如果是20篇的话，说明是网站每天只更新20篇。

**Comment by qoolala** [comment]
應該不是網站問題，好幾個rss源都是這樣。
rss源: http://www.hksilicon.com/articlerss

**Comment by cdhigh** [comment]
碰到这种情况你自己先数一下不就清楚了吗？这种情况就不需要发issue了
明显feed源里面就20篇文章
