### ISSUE TITLE
抓取网站的时候有办法设置请求头的 Accept-Language 吗？

### ISSUE THREAD

**Issue by miaowm5** [cdhigh/KindleEar#276]
在抓取 pixiv 的 RSS 的时候发现其会根据 Accept-Language 返回不同的内容，因为这些内容除了语言以外其他都是相同的，所以能够设置 Accept-Language 来过滤掉不想要的语言的内容吗？

**Comment by cdhigh** [comment]
这个需求估计非常特别，不单很少很少人用，而且尽管你要用，也就是这个网站，
目前KindleEar发送页面请求时没有附加 Accept-Language 标签，目前KindleEar仅定义了这几个 HTML头标签：
User-Agent ：用于保证网站返回的是PC端页面
Accept ：让网站不压缩网页内容（这是KindleEar开发之处因GAE架构限制，CPU一次任务的限时有限，用带宽换取CPU时间的措施，现在的GAE版本和KindleEar的架构基本上保证CPU资源足够，此标签其实意义不大了，不过暂时不想去改）
Referer：反 “反盗链” 的图片抓取
Cookie：网站登录使用

如果你要修改，可以修改lib/urlopener.py里面的_getHeaders()

**Comment by miaowm5** [comment]
好的……谢谢…… :joy:
