### ISSUE TITLE
抓取的网页含有特殊字符时会乱码？

### ISSUE THREAD

**Issue by miaowm5** [cdhigh/KindleEar#277]
尝试抓取 2ch中文网 的页面内容，结果发现抓取下来的文章有的正常有的乱码，

![screenshot_2016_03_24t08_39_41 0758](https://cloud.githubusercontent.com/assets/7985604/14005219/4f917d04-f19c-11e5-8b17-012a77c1ea99.png)

正常的文章：
http://2chcn.com/69595/
乱码的文章：
http://2chcn.com/69550/
http://2chcn.com/69474/

检查的时候发现乱码的文章 head 部分都有特殊字符：
```html
<meta name="keywords" content="搞笑图, 搞笑图片, 搞笑照片, " /><meta name="description" content="522：名無しさん＠そうだドライブへ行こう：2016/03/03(木) 19:11:15.61 ID:zcUIOY0A.net来源：2ch.sc2ch：你们来贴搞笑的图片吧（1）2ch：你们来贴搞笑的图片吧（2）525：名無��" />
```
```html
<meta name="description" content="中国で実際に生活していると、おもしろ画像、笑える画像、ハプニング画像、びっくり画像、ありえない画像、じわじわくる画像がたまっていきます！！
在中国实际生活，就会�" />
```

是这个原因造成实际抓取时的乱码的吗？

**Comment by cdhigh** [comment]
碰到这种情况，可以试着将config.py里面的 TRUST_ENCODING_IN_HEADER_OR_META设置为True，如果本身已经是True了，可以设置为False看看，
还有ALWAY_CHARDET设置为False。

**Comment by miaowm5** [comment]
原本为 True，设置为 False 之后问题仍然存在……

后台有相应的问题记录：
```
19:58:09.538
Decoded by buffered encoding(ISO-8859-2): [http://2chcn.com/69697/]
19:58:41.265
Decoded (ISO-8859-2) by chardet: [http://2chcn.com/69690/]
19:58:50.908
Decoded (ISO-8859-2) by chardet: [http://2chcn.com/69624/]
19:59:03.962
Decoded (ISO-8859-2) by chardet: [http://2chcn.com/69626/]
19:59:17.853
Decoded (ISO-8859-2) by chardet: [http://2chcn.com/69550/]
```

**Comment by cdhigh** [comment]
你可以打开 lib/autodecoder.py，找到57/62/67行，
将
`return content.decode(encoding_m)`
改成
`return content.decode(encoding_m, 'ignore')`

将
`return content.decode(encoding_h)`
改成
`return content.decode(encoding_h, 'ignore')`

附原因分析：
真实的原因是2chcn网站本身有问题，其真实使用的编码是utf-8，但是可能其网站程序的一些BUG，返回的部分字符不是UTF-8编码的，
KindleEar先使用其声明的utf-8进行解码，出错，然后就尝试使用chardet模块（基于开源的Firefox编码自动探测模块修改而来）判断其网页编码，判断结果是ISO-8859-2(可信度不高，只有0.7)，但是解码没有错误，所以KindleEar就使用了ISO-8859-2编码做为最终编码。

当然，为何浏览器能正常浏览，你要知道，浏览器是多庞大的体系，其鲁棒性当然不是一般的强大，或者是我对于其他网站的编码声明过于谨慎的态度导致了此问题，暂时拿不准按此修改后，实际的乱码会减小还是增多，所以暂时不会合并到正式版本。

**Comment by cdhigh** [comment]
我又再次测试了一下，估计能解决你这个问题，因为其网站返回的HTTP头和网页的HTML头都声明了utf-8，这样就好办一些了，毕竟两个地方都声明为同一个编码，则此编码的可信度就非常高了，所以可以强制按此编码进行解码，打算在很快发布的下个版本中修改。

**Comment by miaowm5** [comment]
嗯嗯期待下一版（因为 KindleEar 我现在开始用 Kindle 学 Python 了 :joy:

**Comment by miaowm5** [comment]
测试了一下新版，已经可以正常识别正确编码了
