### ISSUE TITLE
尝试将几本书籍合并成一本时，图片获取出错

### ISSUE THREAD

**Issue by miaowm5** [cdhigh/KindleEar#278]
因为推送的内容包含的图片较多，全部推送到同一本的话总的书籍大小太大，分开推送的话的一次多出个十几本也不舒服，所以尝试新建了一个杂志类，代码如下：
```python
class BaseMagazine(BaseFeedBook):
    book_list = []
    def Items(self, opts=None, user=None):
        for book in self.book_list:
            for data in book().Items(opts,user):
                yield data
```
之后子类各种不同设置的书籍只要分别在各自的类里正常的定义完书籍之后，加入到杂志类的列表中就好了
```python
class PixivMagazine(BaseMagazine):
    title         = u'Pixiv每日图志'
    description   = u'Pixiv每日排行 + Pixiv Spotlight 每日推送'
    mastheadfile  = "mh_pixiv.gif"
    coverfile     = "cv_pixiv.jpg"
    book_list = [
                  PixivDaily,                  
                  PixivSpotlight,
                ]
def getBook():
    return PixivMagazine
```

但是，测试的时候却发现了问题，文字内容能够正常的合并，但是图片内容的话后面几本图书使用的却是列表第一位的图书的图片，请问我是哪一步做错了呢？

**Comment by cdhigh** [comment]
每本书里面都将内部图片进行重命名，序号都是从1开始，比如img1.jpg;img2.jpg等，结果书籍之间的图片文件名就重叠了。
如果你要这样用，可以将：
<code>class BaseMagazine(BaseFeedBook):
    book_list = []
    def Items(self, opts=None, user=None):
        for book in self.book_list:
            for data in book().Items(opts,user):
                yield data</code>
改为：
<code>class BaseMagazine(BaseFeedBook):
    book_list = []
    def Items(self, opts=None, user=None):
        for idx, book in enumerate(self.book_list):
            for data in book(imgindex=idx*1000).Items(opts,user):
                yield data</code>

设置了每本书籍的起始图片文件序号后就不会出现序号重叠了。

PS：你这种需求除了自己写py文件，还可以有另一个方法可以实现：
创建多个账号，然后每个账号输入不同的订阅源合并为一本书，管理也比较简单，修改订阅源不需要重新上传，登录对应账号即可。

**Comment by miaowm5** [comment]
好的，谢谢：）
