### ISSUE TITLE
appid不能有-字符？

### ISSUE THREAD

**Issue by kangjianbin** [cdhigh/KindleEar#279]
我用的appid是类似   xxxkindle-ear。结果uploader.bat识别出来的字符是xxxkindle

**Comment by miaowm5** [comment]
在 uploader.bat 里设置 appid 有效吗？我自己的 appid 都是 “kindle-随机的数字” 的形式，在 uploader.bat 里手动设置时都是正常的

**Comment by cdhigh** [comment]
等我升级uploader吧

**Comment by cdhigh** [comment]
已升级，你可以下载新的uploader看看
