### ISSUE TITLE
自订订阅 － status 出 nonews 或 無回應

### ISSUE THREAD

**Issue by qoolala** [cdhigh/KindleEar#282]
default订阅無問題，自己改動後（如只改Title), 就不行了。

**Comment by cdhigh** [comment]
你需要附上后台的logs

**Comment by qoolala** [comment]
14:24:26.736
GET
200
102 B
93 ms
AppEngine-Google; (+http://code.google.com/appengine)
/worker?u=admin&id=5710239819104256
 0.1.0.2 - - [30/Mar/2016:14:24:26 +0800] "GET /worker?u=admin&id=5710239819104256 HTTP/1.1" 200 102 https://kindlerssv2.appspot.com/deliver?u=admin "AppEngine-Google; (+http://code.google.com/appengine)" "worker.kindlerssv2.appspot.com" ms=93 cpu_ms=36 cpm_usd=1.1399e-8 instance=00c61b117c30f3c8f90264e02b78bfc92335b65d app_engine_release=1.9.35 trace_id=eccb60b2167feb1e241c15112c37115c

**Comment by cdhigh** [comment]
DEFAULT模块的logs是正常的，请附上worker模块的logs

**Comment by qoolala** [comment]
[untitled text.txt](https://github.com/cdhigh/KindleEar/files/195135/untitled.text.txt)

發現delete default 订阅(*.py), 再upload多次去Google(python /usr/local/bin/appcfg.py update .), 有一此default 订阅不見了。

**Comment by cdhigh** [comment]
可能文件编码格式不对吧，要求utf8格式

**Comment by qoolala** [comment]
已經設定utf8  
 feed_encoding         = "utf-8"
page_encoding         = "utf-8"

**Comment by qoolala** [comment]
請指教！
按完[现在投递]後，沒有在LOG出現，好像沒有執行。
[dailynews.txt](https://github.com/cdhigh/KindleEar/files/197210/dailynews.txt)


附上后台的logs：
16:24:46.752
GET
200
116 B
1.54 s
AppEngine-Google; (+http://code.google.com/appengine)
/worker?u=admin&id=6205504040730624
 0.1.0.2 - - [31/Mar/2016:16:24:46 +0800] "GET /worker?u=admin&id=6205504040730624 HTTP/1.1" 200 116 https://kindlerssv2.appspot.com/deliver?u=admin "AppEngine-Google; (+http://code.google.com/appengine)" "worker.kindlerssv2.appspot.com" ms=1544 cpu_ms=21 cpm_usd=1.2964e-8 instance=00c61b117cc147eb8edcaff13fed4f8f984dc61c app_engine_release=1.9.35 trace_id=dfb0bfeff289b005edcd426704513647
{
metadata:
{…}
protoPayload:
{…}
insertId:
"2016-03-31|01:24:48.624953-07|10.106.36.195|-267520024"
log:
"appengine.googleapis.com/request_log"
httpRequest:
{…}
operation:
{…}
}

**Comment by cdhigh** [comment]
不是你设定的，而是保存的py文件编码

**Comment by qoolala** [comment]
我是保存的py文件编码，但上載這裡只可txt文件.

**Comment by cdhigh** [comment]
我们俩说的不是同一个东西，这里变成python培训班了。
要不你将文件内的所有中文字符全部删掉或变成英文字符再试，英文字符的utf8编码和ascii编码是一致的。

**Comment by qoolala** [comment]
謝謝！ 我再看看吧⋯⋯。
