### ISSUE TITLE
从未接收到推送

### ISSUE THREAD

**Issue by walkerwzy** [cdhigh/KindleEar#283]
1, 网站部署成功 [地址](https://kindleearwalker.appspot.com/)
2, 在设置页面里面把所有的复选框都勾上了, 推送时间选每天8:00
3, 在设置页面里面点直接推送, 提示已添加到队列
4, 我的 gmail 账号在推送邮箱白名单里
5, 我的接收邮箱地址反复确认过没错
6, 无论是定时推送, 还是直接推送, 都没有接到推送
7, 推送日志永远是空

基于以上情况, 我应该到控制台的什么页面查看日志给您提供判断依据为何没有推送?

**Comment by walkerwzy** [comment]
/worker?u=admin&id=5091364022779904%2C5096363633147904%2C5634472569470976%2C5682617542246400 404 10ms 0kb AppEngine-Google; (+http://code.google.com/appengine) module=default version=1
0.1.0.2 - - [03/Apr/2016:11:28:04 -0700] "GET /worker?u=admin&id=5091364022779904%2C5096363633147904%2C5634472569470976%2C5682617542246400 HTTP/1.1" 404 123 "https://kindleearwalker.appspot.com/deliver?u=admin" "AppEngine-Google; (+http://code.google.com/appengine)" "worker.kindleearwalker.appspot.com" ms=11 cpu_ms=8 cpm_usd=0.000014 queue_name=deliverqueue1 task_name=368551471065788328 app_engine_release=1.9.35 trace_id=bab308cfa6a62660e78e2379205250b0 instance=00c61b117cffe4be880eafbc084579eae3c3a090

会是这个原因么? 404

**Comment by cdhigh** [comment]
如果/worker为404，说明worker模块没有部署成功，可以重新部署，或者单独执行命令部署。

`python appcfg.py update module-worker.yaml`

**Comment by walkerwzy** [comment]
是的, 可是家里 vpn 连不上, 干脆部署到 vps 上, 一切从头来就好了.
另外, 碰到发送邮箱失效的问题, 要到 settings 里面设置 gmail 账号, 这个最好也在文档里一并说一下
