### ISSUE TITLE
wrong SRC_EMAIL

### ISSUE THREAD

**Issue by hrmthw** [cdhigh/KindleEar#285]
开发者你好，
现在的新版gae console的Email（Gmail）管理界面：
https://console.cloud.google.com/apis/api/gmail/overview?project=xxx
启用并创建默认凭据后，**仍然不能正常投递**。
因为不了解GAE的邮件API，请问有什么好办法解决？

**Comment by cdhigh** [comment]
https://console.cloud.google.com/appengine/settings?project=kindleear&src=ac&versionId=1&moduleId=default
那你看看这个入口，将Kindleear替换为你的id

**Comment by hrmthw** [comment]
好的，问题已解决，是入口找错了，谢谢！

**Comment by imhzr** [comment]
@cdhigh  感谢已解决~~
