### ISSUE TITLE
重写一个新的 BaseFeedBook 书籍类，需要对外提供的接口有哪些？

### ISSUE THREAD

**Issue by miaowm5** [cdhigh/KindleEar#286]
打算自己重新写一个新的 BaseFeedBook ，但是却发现除了 Items 以外，像是 mastheadfile 或者 coverfile 这些内容也都是会被外部获取的，所以我希望了解一下，重写一个 BaseFeedBook 类需要对外提供的接口都有哪些？

**Comment by cdhigh** [comment]
类属性大部分都做为外部接口，只有实例属性是私有的。

**Comment by miaowm5** [comment]
好的，谢谢
