### ISSUE TITLE
问：关于意林杂志——一个新浪博客rss的book怎么自定义

### ISSUE THREAD

**Issue by yubikong** [cdhigh/KindleEar#287]
我想自己写一个关于意林杂志的book，地址是网易博客的rss，但是开启readability后每篇文章的图片都不会显示，除了文章末尾的广告图片。
1.我是python小白，从零学起研究了好几天都不知道怎么才能把图片显示出来，并且把广告图片去掉
请大神指点O(∩_∩)O~
2.还有怎么把抓取到的网页发送到自己的邮箱？我试了下简单的把base.py里的函数工具复制到自己的book.py里是不行的。。。。
3.大神的Economist杂志的book怎么调节css，因为标题有点大
我加上css却没有效果
```
    extra_css      = ''' 
        h2 { font-size: 1em; font-weight: bold;  }
        h1 { font-size: 1.2em; font-weight: bold;  }
        h3 { font-size: 1em; font-weight: bold;  }
    '''     
```
4.我按照大神的模版写了几个微信的rss，但是在日志里显示的是nonews，这是怎么回事？
`
feeds = [
  			(u'连岳', 'http://weixin.sogou.com/gzh?openid=oIWsFt0e_MEZmRrjEbLsh99_H13E'),
            ]
`
意林的book

```
from base import BaseFeedBook

def getBook():
    return Yilin

class Yilin(BaseFeedBook):
    title                 = u'意林美文'
    description           = u'意林杂志提供的每日美文'
    language              = 'zh-cn'
    feed_encoding         = "utf-8"
    page_encoding         = "utf-8"
    mastheadfile          = "mh_yilin.gif"
    coverfile             = "cv_yilin.jpg"
    oldest_article        = 7
    keep_image = True
    fulltext_by_readability = True
    feeds = [(u'意林美文', 'http://blog.sina.com.cn/rss/yilinzazhi.xml', True),]
    def soupbeforeimage(self, soup):
        for img in soup.find_all('img'):
            imgurl = img['SRC'] if 'SRC' in img.attrs else ''
            img['src'] = imgurl  
```        
该怎么修改才能把图片显示出来，并且把广告图片去掉
广告图片地址
`http://s15.sinaimg.cn/mw690/001o8i9Fzy6WzVBTZdY8e&amp;690`
谢谢大神们了。。。唉，爱折腾就是作si啊！！！！

**Comment by cdhigh** [comment]
东西太多了，我没有细看，简单回一下：
发送网页有一个base里面的函数 debug_mail，自己调用即可。

如果extra_css不起作用，要先自己解压对应的书籍，然后确定选择器是否正确，或者对应的tag是否已经内嵌css，如果有内嵌CSS，则要用代码将其去掉，extra_css才起作用。

微信的推送现在已经需要登录搜狗才能查看了，如果你想折腾，可以通过FAQ有关网站登录的条目自己尝试一下，我就不再提供微信推送的技术支持了。

一旦设置了fulltext_by_readability为true，则其已经将网页精简了，有可能已经将图片误认为是广告去掉了，所以不显示，如果确实如此，你可以尝试一下设置一下 positive_classes 属性将你需要的图片标签保留（假如网页图片有class属性的话）。
或可能需要将fulltext_by_readability设置为false，然后自己分析网页结构，提取正文内容。

至于屏蔽广告图片，高级设置中的URL过滤就是干这个事的，需要正则表达式。
或者你在py文件中用正则表达式自己过滤即可，认出广告图片后， img.decompose()就将图片删除了。

**Comment by yubikong** [comment]
谢谢大神O(∩_∩)O哈哈~感谢你利用你的宝贵时间回答我的问题，对我有所启发。
我再尝试着学习和研究看看吧。
