### ISSUE TITLE
部署时可以输入email但无法输入密码

### ISSUE THREAD

**Issue by waaidaiwan** [cdhigh/KindleEar#288]
您好。。。我今天下载最新版的Loader与KindleEar， 在执行时， 输入完Gmail邮箱后， 无法输入密码， 我看画面上的光标是持续闪烁的， 但键盘的文字/数字键都没有功能， 只能enter。  我在Win 10自带的US键盘与Google拼音输入法下都碰到一样问题， 开机重启/重新执行也一样， 请问我该怎么调整相关设置呢？ 谢谢您！

**Comment by miaowm5** [comment]
输入密码时，密码虽然输入了，但是不会显示在屏幕上
因此正常输入密码后直接敲回车即可

**Comment by waaidaiwan** [comment]
谢谢您抽空回复！

Monkey Juice <notifications@github.com> 於 2016年4月11日 週一 下午5:31寫道：
