### ISSUE TITLE
新版本的文件名没有带日期

### ISSUE THREAD

**Issue by jxmlingyun** [cdhigh/KindleEar#289]
你好，新版本投递文件不再带日期了，请问这是基于什么原因？我觉得老版本更容易保存区分

**Comment by cdhigh** [comment]
这是对issue #114 的测试，测试不带日期是否可以自动归档，结果发现带不带日期都无法实现自动归档。
在发布时忘了改回来了，下个版本还是修改为带日期的为好。

**Comment by cdhigh** [comment]
1.23.1已经修改回来了。
