### ISSUE TITLE
使用 uploader 上传时出现 Error 404: https://developers.google.com/accounts/docs/AuthForInstalledApps

### ISSUE THREAD

**Issue by miaowm5** [cdhigh/KindleEar#291]
RT，以下是具体的上传情况：
```
10:10 AM Getting current resource limits.
Email: xxxxxxx@gmail.com
Password for xxxxxxx@gmail.com:
10:10 AM Scanning files on local disk.
Email: xxxxxxx@gmail.com
Password for xxxxxxx@gmail.com:
Error 404: --- begin server output ---
https://developers.google.com/accounts/docs/AuthForInstalledApps
--- end server output ---
```

**Comment by hccz95** [comment]
我也遇到了这个问题，搞了一天还没解决

**Comment by cdhigh** [comment]
严格按照readme了吗？
特别是 "关闭不够安全的应用访问"，要知道，程序员都比较懒，写出来的大多都是要有用的，都值得注意。

**Comment by miaowm5** [comment]
我之前是可以正常上传的，从昨天开始无法上传了，所以还特意去检查了一遍整个设置，都是正常的

**Comment by cdhigh** [comment]
从这个错误看，是GOOGLE的账号认证体系的错误，所以应该是GOOGLE修改了什么隐私方案之类的吧，如果确定你打开了不够安全的应用访问，关闭了二步验证，还是不行的话，可以试一下安装GAE SDK，使用Launcher上传试一下，其Launcher使用OAuth2验证的。

**Comment by miaowm5** [comment]
Launcher 我翻不出去 :joy: 
等 @hccz95 的回报吧……

**Comment by hccz95** [comment]
请问二次验证是？另外如果用shadowsocksfq会有问题吗?

**Comment by miaowm5** [comment]
二次验证就是是否开启了：登陆需要额外接收短信验证码

**Comment by hccz95** [comment]
感谢各位的指点！
查了很多资料，解决了这个问题
首先我是用shadowsocks上网，使用的是标准部署步骤（launcher）
然后参考了http://it.zhaozhao.info/archives/32829
总算成功了

**Comment by miaowm5** [comment]
所以用 lantern 的我只能哭泣了吗……

**Comment by onlyistranger** [comment]
@hccz95 请问具体怎么操作的，被这个搞疯了。

**Comment by onlyistranger** [comment]
解决了。参见https://github.com/jixiuf/hellogae/blob/master/readme.md

**Comment by onlyistranger** [comment]
@miaowm5 lantern亦可。

**Comment by miaowm5** [comment]
@onlyistranger SOCKS 代理的地址如何配置呢？

**Comment by miaowm5** [comment]
改用赛风翻了……终于成功上传……
附带自己的解决方法：
1.下载 GAE python 和 SocksiPy
2. 将 GAE 的 appcfg.py 稍加修改
```python
 import socks
 import socket
 socket.socket = socks.socksocket
 socks.setdefaultproxy(socks.PROXY_TYPE_SOCKS5, "127.0.0.1", 7070)
```
3.
修改 uploader 的 appcfg 路径
```
:kindle
python.exe "D:\Program Files (x86)\Google\google_appengine\appcfg.py" update KindleEar\app.yaml KindleEar\module-worker.yaml
python.exe "D:\Program Files (x86)\Google\google_appengine\appcfg.py" update KindleEar
goto end
```
4. 由于赛风的 sock 端口次次不同，所以每次上传前额外修改一下 appcfg.py 对应的端口……


所以我想知道 lantern 应该怎么配置……

**Comment by miaowm5** [comment]
好吧，重启了一下之后现在再用相同的步骤时提示：
raise GeneralProxyError((5,_generalerrors[5])) socks.GeneralProxyError: (5, 'bad input')

我的内心是崩溃的……

**Comment by onlyistranger** [comment]
我上传成功后也遇到这个情况，目前还木有搞定。(¯―¯٥)

Monkey Juice <notifications@github.com>于2016年4月15日 周五 12:02写道：

**Comment by miaowm5** [comment]
尝试把 Administrator 下的 .appcfg_oauth2_tokens 删掉，网页上取消对 appcfg 的授权，然后重新进行了授权，发现成功了

**Comment by miaowm5** [comment]
结果回到了最开始的问题 @onlyistranger 用 lantern 的话， SOCKS 代理的地址如何配置呢？

**Comment by onlyistranger** [comment]
@miaowm5 这样的话lantern估计不行。

**Comment by miaowm5** [comment]
:joy:

**Comment by lixingcong** [comment]
Email & password authentication was deprecated by Google on April 20th. You need to use oAuth2 to access your spreadsheets.

**Comment by lixingcong** [comment]
Hey, Everyone, Here is my solution:

1. got to https://cloud.google.com/appengine/downloads and download Python SDK for windows
2. Install SDK
3. go to the root dir of KindleEar
4. execute in CMD:
		appcfg.py --application=<PROJECT_ID> --email=<GOOGLE_ACCT> --oauth2 update PROJECT_DIR
5. In browser you need to Auth your application.
6. Finish

参考链接：https://groups.google.com/forum/#!topic/google-appengine/eRF3ZodRWhE

**Comment by runbing** [comment]
@miaowm5 @onlyistranger Lantern 的 Socks 是：localhost:8788。[via](https://github.com/getlantern/lantern/issues/2075)

**Comment by miaowm5** [comment]
用 lantern 的 sock5 结果出现 EOF occurred in violation of protocol ………… :joy:

**Comment by zhurui25** [comment]
如何解决uploader上传不了的问题啊，小白一个不懂代码命令，老司机带路啊！

**Comment by runbing** [comment]
@zhurui25 代码命令就两行，很简单的。给你一个详细的教程：http://kindlefere.com/post/19.html

**Comment by zhurui25** [comment]
@runbing 感谢，慢慢看看学习！

**Comment by zhanghegh** [comment]
raise url_error
urllib2.URLError: <urlopen error [Errno 10060] >
关闭了两步验证，启用了不够安全应用的访问权限，也还是不行，各位帮忙指点下，哥们实在是外行。

**Comment by miaowm5** [comment]
@zhanghegh 你这个单纯是翻墙失败没翻出去……

**Comment by zhanghegh** [comment]
@miaowm5 这个问题我也考虑了，昨天用了翻墙软件，今天我再试一遍

**Comment by miaowm5** [comment]
是的，只有成功部署了才会存在，因为你部署的就是这个 你的appid.appspot.com 啊……成功部署的话一般就是可用的了，想要测试的话，直接填一个可用的 RSS 生成杂志然后检查一下邮箱有没有收到相应邮件即可

**Comment by m2mkey** [comment]
是不是 lantern出现的这个问题
《Error 404: --- begin server output ---
https://developers.google.com/accounts/docs/AuthForInstalledApps
--- end server output ---》还是没解决办法啊？求大神指点，不然没法翻墙了

**Comment by miaowm5** [comment]
@m2mkey 
改用这种方式上传 https://github.com/cdhigh/KindleEar/issues/313
