### ISSUE TITLE
关于extra_css无效的问题

### ISSUE THREAD

**Issue by yubikong** [cdhigh/KindleEar#292]
cdhigh大神你好，我曾问过在The economic中加入extra_css无效的问题。
我在extra_css中加入
`extra_css = 'p.xhead {font-weight:bold;}'` 
kindle上显示的效果是正常的段落文字，并没有加粗效果。

我检查了debug_mail发的正文邮件，我设置的css对应的内容为
`<p class="xhead">A warning for Latin America</p>`
我尝试把邮件发到126邮箱并且解压epub文件，对应的内容为
`<p class="xhead">A warning for Latin America</p>`
没有内置css
但是在epub文件的head标签中发现了如下css
`<style type="text/css">.pagebreak{page-break-before:always;}h1{font-size:2.0em;}h2{font-size:1.5em;}h3{font-size:1.4em;} h4{font-size:1.2em;}h5{font-size:1.1em;}h6{font-size:1.0em;} </style>`

我的理解是只要在extra_css中设置了内容，相应的epub文件中就会包含相应的rss
因为base.py中有如下语句
```
        if self.extra_css:
            sty = soup.new_tag('style', type="text/css")
            sty.string = self.extra_css
            soup.html.head.append(sty)
```

但是解压的文件中却没有我设置的extra_css。
（我是小白一个，最近在开始接触这个，可能有理解不对的地方。)

问一下大神，这是怎么回事，我该如何实现想要的css效果，或者是kindleear出现了bug？

**Comment by cdhigh** [comment]
好像是kindleear的bug，过几天我看看。

**Comment by cdhigh** [comment]
1.23.1解决了此问题，此Bug是中间某个版本引入的。
