### ISSUE TITLE
isfulltext

### ISSUE THREAD

**Issue by hccz95** [cdhigh/KindleEar#294]
请问isfulltext选项起什么作用？

**Comment by miaowm5** [comment]
判断是否是全文 RSS
如果是全文 RSS，则直接用 RSS 里的内容生成杂志
否则打开 RSS 地址，抓取网页的内容

**Comment by hccz95** [comment]
还有一个问题，kindleear能区分已推送和未推送吗？因为今天早上发现有几篇文章昨天推送过

**Comment by miaowm5** [comment]
不能，对 RSS 所能做唯一判断就是判断 RSS 提供的文章发布（更新）时间
