### ISSUE TITLE
Getting current resource limits.

### ISSUE THREAD

**Issue by diggerdu** [cdhigh/KindleEar#295]
08:25 PM Host: appengine.google.com
08:25 PM Application: diggerdukindle; version: 1
08:25 PM
Starting update of app: diggerdukindle, version: 1
08:25 PM Getting current resource limits.
google到的办法都解决不了

**Comment by diggerdu** [comment]
使用的是简化的方法

**Comment by cdhigh** [comment]
还是得自己搜索解决，这个是墙的问题，不是kindleear的问题。

**Comment by diggerdu** [comment]
Error 404: --- begin server output ---
https://developers.google.com/accounts/docs/AuthForInstalledApps
--- end server output ---
查看了这个网页上的说明，要用Oauth2.0才能提交

**Comment by cdhigh** [comment]
看部署步骤，打开不够安全的应用访问

**Comment by miaowm5** [comment]
@diggerdu 
AuthForInstalled 的问题参考这个 issue：https://github.com/cdhigh/KindleEar/issues/291

**Comment by diggerdu** [comment]
@miaowm5 谢谢，这是正解。终于弄好了

**Comment by 1703011** [comment]
同样有这个问题。在墙外和墙无关，开启了两步验证不过生成了应用专属密码，以前这样上传成功过。现在是只能用标准部署方案来部署了吗？

**Comment by miaowm5** [comment]
@1703011 
在墙外的话，下载 GAE SDK，然后用记事本打开 uploader.bat ，把里面的 appcfg.py 改成你下载的 GAE SDK 里同名文件所在的位置即可

**Comment by 1703011** [comment]
没太弄明白你说的过程，不过已经用标准流程解决问题了。谢谢

**Comment by miaowm5** [comment]
@1703011 
我的意思是，标准流程第六步的那些步骤还是可以用 uploader 完成的
> 6.在以下三个文件中修改一些参数：
> 文件	待修改内容	说明
> app.yaml	application	你的ApplicationId
> module-worker.yaml	application	你的ApplicationId
> config.py	SRC_EMAIL	创建GAE工程的GMAIL邮箱
> config.py	DOMAIN	你申请的应用的域名
