### ISSUE TITLE
怎么无法上传了？使用uploader

### ISSUE THREAD

**Issue by shmily1866** [cdhigh/KindleEar#296]
分别出现了
Error 404: https://developers.google.com/accounts/docs/AuthForInstalledApps
还出现了
ssl.c:504: EOF occurred in violation of protocol

改了host后又出现
raise url_error
urllib2.URLError: <urlopen error [Errno 10060] >

求大神帮忙

**Comment by miaowm5** [comment]
https://github.com/cdhigh/KindleEar/issues/291

**Comment by shmily1866** [comment]
@miaowm5 额。。。。实在看不懂啊。。。我用的作者提供的uploader上传的

**Comment by sampsons** [comment]
我一门外汉，也遇到楼主同样的问题。似乎不是梯子的问题，我在墙内翻墙做和让朋友在墙外直接做，都是返回和楼主同样的Error404错误信息。

**Comment by miaowm5** [comment]
似乎是谷歌修改了安全政策，所以目前使用作者提供的uploader已经无法上传了，解决方法见 #291 ，暂时没有傻瓜式的解决方案……

**Comment by sampsons** [comment]
THX @miaowm5

**Comment by jxmlingyun** [comment]
@miaowm5 你好，现在上传kindleear有傻瓜式方案吗？#291的方法实在搞不定。。。

**Comment by miaowm5** [comment]
所有的方案都必须基于下载 GAE 的前提下
直到修改邮箱、填写 APPID 那一步为止 uploader 都可以正常使用，但是之后的上传请手动去做……
