### ISSUE TITLE
所有订阅书籍只有The Economist可以正常推送

### ISSUE THREAD

**Issue by 1703011** [cdhigh/KindleEar#298]
cdhigh你好：

尝试了几个kindle推送服务之后都有各种问题，在别的地方看到说kindleear手动编辑py文件可以解决推送不稳定问题，因此想用回kindleear一次解决所有问题。可是现在推送设置过程中遇到一些问题，还麻烦你能够帮我看一下。
这是投递日志：
尝试分别或者合并投送，内置的“喷嚏图卦”，和我自己编辑的“微信公众号”与“RSS订阅合集”，三个均无法投送。独立投送The Economist一直是成功的。
![default](https://cloud.githubusercontent.com/assets/4069144/14939900/830e071e-0f2a-11e6-9f43-1534b1308b2e.png)
这是我订阅的项目：
![default](https://cloud.githubusercontent.com/assets/4069144/14939913/d5b6d716-0f2a-11e6-80b0-a6afce92e472.png)
这是worker日志：
日志中有大量The Economist 403错误我就没有截取了，如果需要我再放上来。其中夹杂着一句“Book 'Weixin' import failed : unindent does not match any outer indentation level (Weixin.py, line 15)”，没有找到有关“rss订阅合集”的报错。
![fireshot screen capture 054 - logs - kindle rss - appengine_google_com_logs_ app_id s kindle-rss-1239 version_id worker_1_392469947383299143 offset](https://cloud.githubusercontent.com/assets/4069144/14939925/58aeead2-0f2b-11e6-83f9-325cb9a0b3f6.png)
这是我的weixin.py文件：
![weixin](https://cloud.githubusercontent.com/assets/4069144/14939898/7efb22f6-0f2a-11e6-8b62-5f896097d6fb.PNG)

请问我现在应该如何处理呢？非常感谢！

**Comment by miaowm5** [comment]
内置的喷嚏图卦貌似是订阅源的问题，RSS 的时间会差了一天，所以改成这样应该就能正常推送了
```
max_articles_per_feed = 1
oldest_article        = 0
```

微信公众号那个，我也不知道原因，看说明是缩进问题，试试把所有缩进重新输入一遍？另外因为搜狗改了相关设置，所以自带的微信公众号书籍的类已经不能用了

**Comment by 1703011** [comment]
非常感谢你的回复。

之前上传的时候提示错误同样错误，但是那时检查了一下，已经把所有的缩进改成空格了。之后上传就没有报错。不知道为何现在又报同样的错误。而且并不是每次推送都提示错误。我考完试换成自己的rss源再给你反馈。

还有那为何我的“rss合集”这个订阅也无法推送呢？
Monkey Juice <notifications@github.com>于2016年5月1日 周日上午1:09写道：

**Comment by miaowm5** [comment]
单独推送 rss合集 的时候后台有错误日志吗？
不过既然网页端的投递日志中都没有的话可能代码本身就有错误了……
要不你把你那个 rss 合集的代码附上来我看一下？

**Comment by 1703011** [comment]
你好：
我尝试separate单独投递rss合集，投递日志里没有，log里也没有报错。
我取消了其余所有订阅，取消separate勾选，选中"多本书籍合并投递为一本"终于看到rss合计的错误提示：not exist book <RSS订阅>

这是截图：
![logs](https://cloud.githubusercontent.com/assets/4069144/14942133/d257225e-0f81-11e6-8926-4c63cc1b0883.PNG)
截图中的weixin我没有使用。

这是我rss合计的截图：
![rss](https://cloud.githubusercontent.com/assets/4069144/14942142/1337406a-0f82-11e6-8fc2-1e56223d9e4f.PNG)

还有一个问题就是即使我已经退订经济学人，每次投递都会在发一遍经济学人。不知道是为啥。

这是投递日志：
![default](https://cloud.githubusercontent.com/assets/4069144/14942158/6cf3970c-0f82-11e6-9951-f60e39c2d182.png)

谢谢！

**Comment by miaowm5** [comment]
你这状况越看越玄乎啊，感觉是部署的问题，我自己测试这几个 feed 的时候是能够正常推送的
要不你去后台的 Datastore Viewer 看看书籍数据是不是都导入了？
或者就只能等等作者来解答了

**Comment by 1703011** [comment]
听你说可能是部署的问题我再部署了一遍竟然可以推送了。也不知道为啥，之前已经部署无数遍了。
不过话说如果rss源只显示最近一天的文章，是不是kindle设置推送7天内的文章也只能推送当天的？
比如：http://onehd.herokuapp.com/

如果rss内容推送不完整的话我有什么办法能处理吗？
rss源：http://rss.iwgc.cn/rss/5114-f5823a80ed52208ce0c474c6cce801602072
应该推送7日内的两篇文章，我却只收到从"压力对食欲的影响是因人而异的"开始的第一篇后半截。
谢谢！

**Comment by miaowm5** [comment]
RSS订阅源只提供最近文章的话推送是没法抓取更早之前的文章的，有这需求的话可以尝试自己打开网页去分析和抓取，不过需要有 python 基础和 html 基础

rss 推送不完整这个，如果你是全文 rss 的话，在 feed 的设置末尾加上 True，然后试着设置 
fulltext_by_readability = False
试试看

**Comment by cdhigh** [comment]
谢谢 @miaowm5 这几天对这个问题和其他问题的耐心解答，我最近工作很忙，接下来一两个月也会很忙，没有时间仔细看，基本上 @miaowm5 所解答的都正确，思路也清晰，谢谢。

**Comment by 1703011** [comment]
@miaowm5 
非常感谢。不过要自己弄的话确实是一个麻烦事，因为“one 一个”本身不提供rss，这个rss还是别人抓取的。
你说的全文rss的办法我到时候再试试，如果不行可能还要再来询问你呢。

**Comment by miaowm5** [comment]
试试这样设置书籍

先把这本书籍放到你的 book 目录下 https://github.com/miaowm5/KindleEar/blob/master/books/m5_base.py

然后新建一本以下内容的书籍：
```python
#!/usr/bin/env python
# -*- coding:utf-8 -*-

from m5_base import *

class Feed(BaseWebBook):

    title = u'测试杂志'
    description = u'20160504'
    language = 'zh-cn'
    mastheadfile = "mh_default.gif"
    coverfile = "cv_default.jpg"
    setting = {}
    setting["retry_time"] = 2
    setting["timeout"] = 60
    setting["css_mode"] = True
    setting["catch"] = ['.one-articulo']
    setting["remove"] = ['.articulo-compartir']
    feeds = [(u'一个-韩寒', r'http://wufazhuce.com/'),]

    def spider_refresh_capture(self, url, html):
        if html is None: return None, set()
        capture = set()
        soup = BeautifulSoup(html, "lxml")
        dom = soup.select('.one-articulo-titulo a')[0]
        if dom: capture.add(dom['href'])
        for dom in soup.select('.fp-one-articulo li a'): capture.add(dom['href'])
        return None, capture

    def spider_generate_html(self, result):
        for html, url in result:
            if not html: continue
            soup = self.process_article(html)
            tdom = soup.select('.articulo-titulo')[0]
            title = tdom.get_text() if tdom else 'no-title'
            yield title, url, soup

    def get_items(self):
        for feed in self.feeds:
            section, url = feed[0], feed[1]
            result = self.spider_main(detect = url)
            for title, url, soup in self.spider_generate_html(result):
                yield(section, title, url, soup, None)

def getBook():
    return Feed
```

另外要说明的是，这个书籍是我对原版的一个 fork 版本，所以书籍的设置方式以及书籍拥有的功能和原版是有不同的（比如可以添加的分享链接或者裁剪长图之类的）

**Comment by 1703011** [comment]
好的！我这几天考试，考完来研究一下
