### ISSUE TITLE
上传墙的问题搞定了又出现新的问题，奔溃！

### ISSUE THREAD

**Issue by zhurui25** [cdhigh/KindleEar#299]
大家帮忙看看，弄了好多天了，用osx上传一直出现Getting current resource limits.结果发现是墙的问题，墙没问题用的ss买的vps，估计OS X ss代理端口设置不了，用windows设置就不会出现墙的问题，但是windows又出现新的问题，出现：1:### **_ appcfg.py: error:Error parsing c:\kindleear\app.yaml:mapping values are not allowed here_**    2:# **_appcfg.py: error: not a directort: ~/applications/kindleear
_**搜索了一下，命令输入有误，直接复制的啊，还会错。小白还是玩不转！

> 先感谢大家了！`

**Comment by zhurui25** [comment]
不会上传图片！程序员的社区果然不好懂！

**Comment by miaowm5** [comment]
检查一下你 kindleear 的目录有没有输入对了，别复制的时候把别人的目录地址也复制了……

P.S. 图片的话，直接拖到文本框就能上传了

**Comment by zhurui25** [comment]
@miaowm5 感谢，下午在试试！

**Comment by zhurui25** [comment]
@miaowm5 你好帮我看看，我一点输入的怎么还有这个问题啊
![qq 20160503175508](https://cloud.githubusercontent.com/assets/18722509/14979969/5a545f46-1158-11e6-82e8-b9493f4882da.png)
![q25](https://cloud.githubusercontent.com/assets/18722509/14979981/5ebf7e9e-1158-11e6-9369-91d45d7bfe65.png)
![24](https://cloud.githubusercontent.com/assets/18722509/14979983/6410c29a-1158-11e6-9fdb-4c606d6b8325.png)
![qq 25](https://cloud.githubusercontent.com/assets/18722509/14979988/6826fa34-1158-11e6-83fb-e44559749cd1.jpg)

**Comment by zhurui25** [comment]
@miaowm5 
![qq 20160503175911](https://cloud.githubusercontent.com/assets/18722509/14980079/07293a8e-1159-11e6-86df-835966a8eaa4.jpg)
![qq 20160503175837](https://cloud.githubusercontent.com/assets/18722509/14980081/08246954-1159-11e6-976f-f900a1075b2a.jpg)

**Comment by zhurui25** [comment]
@miaowm5 用的是lantern.
ss也用过端口设置的是1080.上传教程用的是kindle伴侣最新发布的教程。 折腾累丝了，弄了几天了，还没成功上传过一次。

**Comment by miaowm5** [comment]
module-worker.yaml 和 app.yaml 中的内容要换行……

**Comment by zhurui25** [comment]
@miaowm5 弱弱的问下，如何换行？ Google了一下还是不懂~
![qq 20160503200002](https://cloud.githubusercontent.com/assets/18722509/14982558/c0d823f4-1169-11e6-901b-6588eb2199d5.png)
是这样换行吗？

**Comment by miaowm5** [comment]
是这样：
https://github.com/cdhigh/KindleEar/blob/master/app.yaml

**Comment by zhurui25** [comment]
@miaowm5 感谢你耐心的解答！

**Comment by zhurui25** [comment]
@miaowm5 这个解决好了，又出现getting current resource limits  无语了，不弄了，弄了几天心力憔悴~
还是谢谢你！

**Comment by 1703011** [comment]
用标准上传方案可以结局getting current resource limits的问题

**Comment by miaowm5** [comment]
@zhurui25 
卡在 getting current resource limits 说明你翻墙失败了，反正用 lantern 时我就没成功传过

**Comment by zhurui25** [comment]
@miaowm5 赛风我也用过，ss我也用了，都不会成功啊！1

**Comment by zhurui25** [comment]
@1703011 我用的是kindle伴侣发的教程上传的，基本步骤和标准差不多。

**Comment by cdhigh** [comment]
已经升级 3.0.0b，支持Python3
软件架构变化，可以多平台部署，不再受限于墙的限制，愿意的话就部署在墙内就好
