### ISSUE TITLE
希望可以提供浏览器Send to Kindle功能，抓取当前网页内容生成文章发送至Kindle

### ISSUE THREAD

**Issue by zfbp** [cdhigh/KindleEar#300]
我虽然不懂web开发，也可进我绵薄之力。

**Comment by miaowm5** [comment]
已经做了……
![qq 20160503192943](https://cloud.githubusercontent.com/assets/7985604/14981970/6aae4cc8-1165-11e6-8f43-95628d8ebf56.png)

**Comment by cdhigh** [comment]
我想 @zfbp 说的是类似chrome或firefox的插件，不过项目启动需要考虑要解决什么问题，有没有同类竞品，同类竞品还有什么问题没有解决好，要启动的项目最大的卖点是什么等一系列问题。
KindleEar项目启动的原因是其他同类服务不支持自定义RSS或需要收费，开始我只是想做一个简单的GAE程序，没想到做着做着就做成现在这样了，很多功能都加入了。
但是暂时没有想到如果再做一个基于KindleEar的send to kindle，能比其他同类服务好在哪里？

**Comment by zfbp** [comment]
@cdhigh 
对我而言最希望KindleEar有此功能的原因是它是自己的服务器：
1、不怕受到第三方服务关停的影响
2、有些抓取失败的可以自己检查原因
3、可以自定义样式
4、可以抓墙外的内容

**Comment by zfbp** [comment]
我用过的同类竞品有readability和clippings.io，这两个服务的最大问题是不稳定及容易抓取失败（比如无图）或者爬下来很多非相关内容（比如评论）。

本地抓取做的比较好的：
1、有道笔记不支持https（这太奇怪了）。
2、为知只上传文本不上传图片（时间久笔记中经常没有图）。
并且专业的笔记软件都不支持推送到Kindle。

**Comment by zfbp** [comment]
不需要做chrome插件，只需要写Bookmark栏JavaScript，将当前网址发送至KindleEar，KindleEar在后台抓取网页内容发送至Kindle。
参考https://www.readability.com/bookmarklets

**Comment by miaowm5** [comment]
把 Url2Book 这个文件改成这样

https://github.com/miaowm5/KindleEar/blob/d5bd615e8e7cd1c5e0750c9e74f92767e0e55fa7/apps/Work/Url2Book.py

上传到 GAE

然后修改下面这个 Bookmark 中的数据
```
var appid = 'kindle';
```
改成你的 appid
```
var email = 'email@qq.com';
```
改成你的 email

```javascript
javascript:(function(){
  var appid = 'kindle';
  var email = 'email@qq.com';
  var encode=function(str){function base64encode(str){var base64EncodeChars="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";var out,i,len;var c1,c2,c3;len=str.length;i=0;out="";while(i<len){c1=str.charCodeAt(i++)&255;if(i==len){out+=base64EncodeChars.charAt(c1>>2);out+=base64EncodeChars.charAt((c1&3)<<4);out+="==";break}c2=str.charCodeAt(i++);if(i==len){out+=base64EncodeChars.charAt(c1>>2);out+=base64EncodeChars.charAt(((c1&3)<<4)|((c2&240)>>4));out+=base64EncodeChars.charAt((c2&15)<<2);out+="=";break}c3=str.charCodeAt(i++);out+=base64EncodeChars.charAt(c1>>2);out+=base64EncodeChars.charAt(((c1&3)<<4)|((c2&240)>>4));out+=base64EncodeChars.charAt(((c2&15)<<2)|((c3&192)>>6));out+=base64EncodeChars.charAt(c3&63)}return out}function utf16to8(str){var out,i,len,c;out="";len=str.length;for(i=0;i<len;i++){c=str.charCodeAt(i);if((c>=1)&&(c<=127)){out+=str.charAt(i)}else{if(c>2047){out+=String.fromCharCode(224|((c>>12)&15));out+=String.fromCharCode(128|((c>>6)&63));out+=String.fromCharCode(128|((c>>0)&63))}else{out+=String.fromCharCode(192|((c>>6)&31));out+=String.fromCharCode(128|((c>>0)&63))}}}return out}return base64encode(utf16to8(str))};
  var link = [
    'https://', appid, '.appspot.com/url2book?nozlib=1&urls=', encode(window.location.href),
    '&u=admin&subject=title&to=', email ,'&lng=zh-cn'
  ];
  window.open(link.join(''));
})();
```

最后添加到书签栏

**Comment by luckykong** [comment]
为什么我尝试之后，提示我 ”internal server error“？
修改了appid，也将email改成了GAE 的账户邮箱。

**Comment by miaowm5** [comment]
@luckykong 
请重新复制我的代码，你把我不需要修改的地方也改掉了（我的代码里是nozlib=1，你的代码里是 nozlib=0，）

**Comment by luckykong** [comment]
不好意思，我后期改为1，是我自己瞎弄的时候尝试的。
即使是1的时候， 也是同样的错误

**Comment by miaowm5** [comment]
请看我的第一句话：

> 把 Url2Book 这个文件改成这样
> 
> https://github.com/miaowm5/KindleEar/blob/d5bd615e8e7cd1c5e0750c9e74f92767e0e55fa7/apps/Work/Url2Book.py
> 
> 上传到 GAE
> 

是否上传了修改后的Url2Book？

**Comment by luckykong** [comment]
已经修改并上传过了

**Comment by luckykong** [comment]
![image](https://cloud.githubusercontent.com/assets/7273053/15044695/de001554-1308-11e6-91e8-62f5f6ed175a.png)
再控制台里， 显示这样的错误

**Comment by miaowm5** [comment]
同样的网址我这边是能正常开始工作的（虽然煎蛋干掉了 GAE 的爬虫），控制台报错内容说的是 nozlib=1 这个设置并没有生效
要不你把你的 Url2Book.py 的第 40 行前后的代码发上来看看？

**Comment by luckykong** [comment]
![image](https://cloud.githubusercontent.com/assets/7273053/15044910/2b942b2e-130a-11e6-81d7-b5af2507ba0a.png)

**Comment by miaowm5** [comment]
嗯？代码好像也没什么问题？
要不然你把代码中的这段
```python
        if bool(web.input().get("nozlib") == '1'):
            urls = base64.urlsafe_b64decode(urls)
        else:
            urls = zlib.decompress(base64.urlsafe_b64decode(urls))
```
直接改成
```python        
        urls = base64.urlsafe_b64decode(urls)
```
试试看能不能工作？

**Comment by luckykong** [comment]
咦，好奇怪，我明明已经修改过代码了，也上传了。但是为什么依然是这个错误。
![image](https://cloud.githubusercontent.com/assets/7273053/15045113/72361cf8-130b-11e6-92cf-a8f6df826a92.png)
虽然我是代码白痴，但是我感觉上面修改过之后，应该不会再有这个出现才对呀
zlib.decompress(base64.urlsafe_b64decode(urls))

**Comment by miaowm5** [comment]
是啊，我也觉得很奇怪，按道理来说折代码都已经被删掉了为什么还会出这个错误……
出于保险，问一句，你的 Url2Book 是放在 KindleEar/apps/Work/Url2Book.py 这里还是放到 books 目录下了？

**Comment by luckykong** [comment]
额，我看这个文件路径是再work下，就放在 KindleEar/apps/Work/Url2Book.py  里了。。
难道需要放在 books里？

**Comment by miaowm5** [comment]
不不不，就是放在你说的那里没错，
那我就真的不知道是怎么回事了……明明修改了代码却没用也太神奇了……难道是部署失败了？
app.yaml  和 module-worker.yaml 都部署了吗？

**Comment by luckykong** [comment]
好像是我部署的方法错了。。
之前一直用 uploader 快捷上传的，今天发现不行，便安装了python和sdk。
可能是我没有上传 module-worker.yaml的原因吧。。
我再试试看

**Comment by luckykong** [comment]
是我上传方法错了。
应该是这样做
`python.exe "D:\Program Files (x86)\Google\google_appengine\appcfg.py" update KindleEar\app.yaml KindleEar\module-worker.yaml
python.exe "D:\Program Files (x86)\Google\google_appengine\appcfg.py" update KindleEar`
但是我上传的时候，只做了第二个命令，没有输入第一个命令，导致部署失败。。

另外，我再问一下，我换了个其他页面，能够顺利发送到kindle。但是刚刚jandan的新闻，我点击书签后，显示“[Url2Book]Fetch url failed.”，是因为你所说的煎蛋屏蔽了gae么？有没有简单的方法能突破这类网站的封锁？

**Comment by miaowm5** [comment]
https://github.com/cdhigh/Forwarder

**Comment by luckykong** [comment]
thanks~~~ 我去研究一下

**Comment by luckykong** [comment]
1，在heroku上搭建好了服务器，也再config.yaml里修改了SHARE_FUCK_GFW_SRV 变量，也再网站上选择了 我要翻墙。然后重新上传的app.yaml和module-worker.yaml。
但是推送jandan的时候，依然显示 “Fetch url failed.”
2，通过这个方法推送书籍，是不是无法显示图片？

**Comment by miaowm5** [comment]
支持图片，具体请参考 Url2Book.py 的源代码

**Comment by zfbp** [comment]
非常感谢，可以一键抓取了，抓取出的文章也很漂亮。
有两个小问题：
1、没有图片，我试了这两个网址都没有图
https://www.ibm.com/developerworks/cn/rational/rationaledge/content/apr06/widney/
http://learnyousomeerlang.com/finite-state-machines
2、title是传给url的，查了资料似乎可以直接从document.title中取到，我试了改成这样
`  '&u=admin&subject=', encode(document.title), '&to=', email ,'&lng=zh-cn'`
再点书签没反应了。

**Comment by miaowm5** [comment]
@zfbp @luckykong 
在网址中传递参数即可
```python
&keepimage=1
```
具体的实现细节全都可以参考 Url2Book.py 的源代码
@zfbp
document.title 不需要 encode

**Comment by zfbp** [comment]
增加了 &keepimage=1，ibm的网站可以抓到图片，

**Comment by zfbp** [comment]
最终的代码是这样，可以取到title，但是还有有些网页抓不到图

``` javascript
javascript: (function() {
    var appid = 'kindle-ear';
    var email = 'email@kindle.cn';
    var encode = function(str) {
        function base64encode(str) {
            var base64EncodeChars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
            var out, i, len;
            var c1, c2, c3;
            len = str.length;
            i = 0;
            out = "";
            while (i < len) { c1 = str.charCodeAt(i++) & 255;
                if (i == len) { out += base64EncodeChars.charAt(c1 >> 2);
                    out += base64EncodeChars.charAt((c1 & 3) << 4);
                    out += "==";
                    break }
                c2 = str.charCodeAt(i++);
                if (i == len) { out += base64EncodeChars.charAt(c1 >> 2);
                    out += base64EncodeChars.charAt(((c1 & 3) << 4) | ((c2 & 240) >> 4));
                    out += base64EncodeChars.charAt((c2 & 15) << 2);
                    out += "=";
                    break }
                c3 = str.charCodeAt(i++);
                out += base64EncodeChars.charAt(c1 >> 2);
                out += base64EncodeChars.charAt(((c1 & 3) << 4) | ((c2 & 240) >> 4));
                out += base64EncodeChars.charAt(((c2 & 15) << 2) | ((c3 & 192) >> 6));
                out += base64EncodeChars.charAt(c3 & 63) }
            return out }

        function utf16to8(str) {
            var out, i, len, c;
            out = "";
            len = str.length;
            for (i = 0; i < len; i++) { c = str.charCodeAt(i);
                if ((c >= 1) && (c <= 127)) { out += str.charAt(i) } else {
                    if (c > 2047) { out += String.fromCharCode(224 | ((c >> 12) & 15));
                        out += String.fromCharCode(128 | ((c >> 6) & 63));
                        out += String.fromCharCode(128 | ((c >> 0) & 63)) } else { out += String.fromCharCode(192 | ((c >> 6) & 31));
                        out += String.fromCharCode(128 | ((c >> 0) & 63)) } } }
            return out }
        return base64encode(utf16to8(str)) };
    var link = ['https://', appid, '.appspot.com/url2book?nozlib=1&urls=', encode(window.location.href), '&u=admin&subject=', document.title, '&to=', email, '&lng=zh-cn&keepimage=1'];
    window.open(link.join('')); })();
```

**Comment by miaowm5** [comment]
还是不行那就是网站本身的问题，很多网站本来就反感机器人的抓取，所以对于疑似是机器人抓取的请求会禁掉

**Comment by zfbp** [comment]
非常感谢！

**Comment by zfbp** [comment]
http://www.infoq.com/cn/articles/yhd-11-11-queuing-system-design

**Comment by zfbp** [comment]
有什么方法可以在本地调试么？

**Comment by miaowm5** [comment]
1. 未必准确的说明：
readability 的代码的意思：把网址发送到readability，让readability的服务器抓取
KindleEar 的做法：把网址发给 GAE，让 GAE 的服务器抓取
网站：哦，这个是 readability ，我把图片给他，哦，那个 GAE 老是有各种各样的爬虫乱来，不爽，不给图片

2.https://github.com/cdhigh/KindleEar/issues/301
Github 的 Issue 本身提供了搜索功能你有用过吗？

**Comment by zfbp** [comment]
也就是说很多网站都能够判断出这是gae的ip发过来的抓取么？这种判断很容易失效吧。
还是说抓取的时候调用了gae的sdk，里面有些特殊的标记？
我先看看源码了解下吧。

#301 看了一遍，也就是说本地调试的意义不大，最终还是要依赖gae平台。

**Comment by miaowm5** [comment]
不一定通过 IP 分析，这就涉及到爬虫和反爬虫的内容了，比如，GAE 发过去的抓取，只会下载图片和文章，而人类正常浏览网页的时候还会下载 js 下载 css 等等，那么有一类用户都只是下载图片的那我禁掉影响就不大，大不了发现误伤了就解禁……这些都是一套分析规则，你了解了规则并针对该规则改变之后那个规则确实就失效了，但是没什么大不了，发现失效的话再加一个新规则来对抗就好了呗

**Comment by Edenharder** [comment]
[Send to kindle](https://chrome.google.com/webstore/detail/send-to-kindle-by-klipme/ipkfnchcgalnafehpglfbommidgmalan/related?hl=zh-CN), a Chrome plugin.

**Comment by zfbp** [comment]
@Edenharder 
对我而言最希望KindleEar有此功能的原因是它是自己的服务器：
1、不怕受到第三方服务关停的影响
2、有些抓取失败的可以自己检查原因
3、可以自定义样式
4、可以抓墙外的内容
