### ISSUE TITLE
Rss源，Calibre能正常生成书籍，KindleEar不能

### ISSUE THREAD

**Issue by Edenharder** [cdhigh/KindleEar#301]
自己设置了几个Rss源，除了Rss源：https://rss.lilydjwg.me/zhihuzhuanlan/zhishifenzi 都能正常接收并生成书籍。

但rss源：https://rss.lilydjwg.me/zhihuzhuanlan/zhishifenzi 生成的书籍却是一片空白。

而用Calibre或其他Rss阅读器是能正常接收生成的。

1. KindleEar接收并生成书籍的模块不是从Calibre中提取出的么？为什么会这样呢？
2. 如何在本地测试KindleEar接收并生成书籍的模块，调试好之后再上传会方便些。

**Comment by miaowm5** [comment]
1.生成书籍的模块从Calibre中提取不代表抓取网页、解析网页也从 Calibre 提取啊，其中一种情况是，网站屏蔽了谷歌爬虫的抓取，你电脑去抓取的时候没屏蔽，GAE 去抓取的时候屏蔽了，于是就空白了

顺便，这个 RSS 已经是全文 RSS 了，你有直接将对应的 RSS 源设置为全文 RSS 而不是让 GAE 尝试去访问原网页抓取吗？

2.https://github.com/cdhigh/KindleEar/issues/274

**Comment by Edenharder** [comment]
谢谢！

1. 的确是没有设置为全文rss的问题。怎么判别是不是全文rss呢？
2. [#274](https://github.com/cdhigh/KindleEar/issues/274)里的方法太复杂了。只是抓取rss然后生成书籍，为什么必须开GAE SDK呢？我以为在KindleEar内就能完成，GAE只是用来在线托管的呢。

**Comment by miaowm5** [comment]
1.打开 RSS ，看看 RSS 是否包含了文章正文的内容，如果包含就是全文 RSS，这些内容就能直接当成文章来用，否则 KindleEAR 就会尝试去访问文章的原网站，然后分析网站的内容 balabalabala，这时候如果知乎屏蔽了 GAE 那访问原网站时 GAE 拿到的就只有一个空白页面了于是内容也变成空白了

2.这你得问作者了，或者尝试自己去理解他的源代码，反正我暂时没理解透，所以最后放弃了本地测试书籍

**Comment by cdhigh** [comment]
本地测试书籍是可以的，在开发之初我就是在本地测试书籍的，两种方法我都用过：
1.将dev_appserver.py的参数 smtp_host/smtp_port设置为GMAIL服务器地址 将书籍发送出来（GAE sdk有bug，需要修改其本地的mailstub，具体修改方法我忘了，可以自己搜索）
2. 本地搭建SMTP服务器，保存书籍在本地。（推荐方法，python的标准库中有相关模块，很简单的几十行代码既可以实现一个本地SMTP服务器，其代码我现在一下子找不到）

至于说，如果只是本地生成书籍，当然可以不依赖GAE SDK，修改修改代码即可，但是本地生成书籍的最终目的还是要测试KindleEar，上线后后台就是GAE，所以依赖GAE SDK才可以完整的测试KindleEar。

如果只是本地使用，Calibre是更好的选择。

时间过去太久，一些细节我忘了。

**Comment by Edenharder** [comment]
@cdhigh 整个流程应该是

1. 抓取内容
2. 生成书籍
3. 然后用gmail发送至kindle的邮箱

第3步的话应该不会和抓取的内容有关系，至多会因为书籍太大而发送失败。而我们关心的主要是第1，2步，比如添加的一些rss源能不能成功抓取所需要的内容，或自己定制的书籍格式能不能成功生成书籍。这两步在本地调试会更加方便，对应你说的“至于说，如果只是本地生成书籍，当然可以不依赖GAE SDK，修改修改代码即可”。

而调试第1，2步还是为了整个流程，而并不是为了本地使用。

如果将步骤1，2，3都很清楚地模块化，第1，2步本地就能执行，这对调试和维护升级代码都更方便吧。

**Comment by cdhigh** [comment]
安装一个GAE SDK又不难，意义不大。
