### ISSUE TITLE
自动推送好像不太好使 都是我手动推送的？

### ISSUE THREAD

**Issue by asonwrei** [cdhigh/KindleEar#303]
请问是我设置的问题还是？

**Comment by miaowm5** [comment]
勾选使能自动推送了吗？

**Comment by asonwrei** [comment]
[](url)

**Comment by asonwrei** [comment]
勾选了

-

**Comment by asonwrei** [comment]
![qq 20160510212850](https://cloud.githubusercontent.com/assets/19283352/15148082/3f09917c-16f6-11e6-84ef-35fd9adac92a.jpg)这是logs 麻烦帮忙看看

**Comment by miaowm5** [comment]
log 要切换到 worker 模块再截图（左上角下拉框选择 worker）

无法自动投递的是默认书籍还是自定义的 RSS？建议你的设置界面也截图一下

**Comment by asonwrei** [comment]
![1111](https://cloud.githubusercontent.com/assets/19283352/15169125/829e8b4e-176a-11e6-9a93-c76252431ffa.jpg)
![222](https://cloud.githubusercontent.com/assets/19283352/15169127/8c219db4-176a-11e6-8a10-4a0514680812.jpg)
![333](https://cloud.githubusercontent.com/assets/19283352/15169129/907d2f9a-176a-11e6-86d2-8f86e996c504.jpg)
辛苦了

**Comment by miaowm5** [comment]
上传过程是按照什么步骤上传的？
GAE 后台左边有一个 Cron Jobs ，点击进去看一看是不是图中这样？

![qq 20160511120854](https://cloud.githubusercontent.com/assets/7985604/15169747/2c3a47b4-1771-11e6-9a69-c0d2b5e1e1b6.png)

**Comment by asonwrei** [comment]
![111111](https://cloud.githubusercontent.com/assets/19283352/15169920/3fee6414-1773-11e6-8138-0b07e469e86e.jpg)
图和你的一样，今天推送了，不过在kindle显示日期为昨天的的。是不是延迟的问题？

**Comment by miaowm5** [comment]
我觉得是时差问题……能正常推送了那还有什么问题吗……

**Comment by asonwrei** [comment]
谢谢啊
