### ISSUE TITLE
请增加“期刊自动归档功能”，谢谢！

### ISSUE THREAD

**Issue by HanGeGe** [cdhigh/KindleEar#305]
个人建议增加了此功能能为使用者带来更多便利，请开发者考虑，谢谢！

**Comment by miaowm5** [comment]
手动将生成的文件复制到 Kindle 中的话能够自动归档，你可以考虑把杂志发到自己邮箱，然后数据线手动拷贝到 Kindle 中…… 通过邮件推送的话，文件名末尾会被强制加上一堆乱码导致无法归档，暂时没找到解决方法，相关的讨论见这个 issue：https://github.com/cdhigh/KindleEar/issues/114 也就发表新 issues 那个按钮往下大概 5 厘米左右的那个 issue
