### ISSUE TITLE
微信订阅新思路，但是遇到点问题，求助大神

### ISSUE THREAD

**Issue by jiey2016** [cdhigh/KindleEar#307]
国内有个网站叫**微广场**，注册登录后可以获取几个自己喜欢的公众号的rss源，这些rss源都是个性化的，但是得到的是全文RSS，所以非常好用！我这里放一个出来
eg：http://rss.iwgc.cn/rss/161-924a1e200abc8e1cbcbea0749ecf24a63291
**不同用户即使订阅同一个微信公众号，得到的rss地址也是不同的** 
尝试在kindleear中订阅此源却发现得不到内容，而是显示“跳转链接”，这个rss源在软件里是好用的，我在网页端尝试也发现有一个跳转过程，不知道大神能不能让kindleear支持这个跳转功能呢？

**Comment by cdhigh** [comment]
KindleEar支持HTML标准的300,301,302,303等跳转（重定向）指令，如果网站按照标准去做，KindleEar直接会跟踪跳转指令，默认支持5层跳转。

这个网站的网页跳转没有使用标准的300,301,302,303等跳转指令，而是自己写一个HTML，在HTML中使用JAVASCRIPT设一个定时器，再设置DOM的window.location.href属性为需要跳转的目标地址，而KindleEar没有Javascript引擎，无法解释Javascript指令，所以不能直接支持。

如果要支持也容易，自己写一个py文件，分析网页内容，BeautifulSoup都可以不用，直接使用正则表达式提取出 window.location.href 后面的值，然后再去抓取即可，要不 @jiey2016 你自己试一下？

**Comment by jiey2016** [comment]
不会编程。。。欲哭无泪。。。但是还是多谢大神的耐心回复

在 2016-06-01 08:28:15，cdhigh <notifications@github.com> 写道：


KindleEar支持HTML标准的300,301,302,303等跳转（重定向）指令，如果网站按照标准去做，KindleEar直接会跟踪跳转指令，默认支持5层跳转。

这个网站的网页跳转没有使用标准的300,301,302,303等跳转指令，而是自己写一个HTML，在HTML中使用JAVASCRIPT设一个定时器，再设置DOM的window.location.href属性为需要跳转的目标地址，而KindleEar没有Javascript引擎，无法解释Javascript指令，所以不能直接支持。

如果要支持也容易，自己写一个py文件，分析网页内容，BeautifulSoup都可以不用，直接使用正则表达式提取出 window.location.href 后面的值，然后再去抓取即可，要不 @jiey2016 你自己试一下？

**Comment by lostpsyche** [comment]
才搭了一个kindleear，使用微广场生成rss，我来回复下楼主的问题吧
因为微广场生成的rss是全文rss，因此，在kindleear添加自定义rss时，**勾选上isfulltext**的框就好了，这样就能抓取到微信内容。

**Comment by jiey2016** [comment]
@lostpsyche 请问你这样能正常抓到图片吗
