### ISSUE TITLE
rss订阅能否支持每个源的图片单独开关？

### ISSUE THREAD

**Issue by jiey2016** [cdhigh/KindleEar#308]
kindle邮件投递的附件大小上限是50M而gmail是25M。。。对于每周投递一次的我，如果订阅源的图片一多就容易使书籍大小超标而导致发送失败，不是每个rss源的图片都值得一看的，还容易用完app的免费配额，请问能不能支持一下rss每个订阅源的单独开关呢？

**Comment by miaowm5** [comment]
作者提供的方案：
你可以给自己的网站注册多个账号，有的账号设置为投递图片，有的账号设置为不投递图片，然后投递不同的 RSS

我自己的方案：
自定义书籍，重写一个新的书籍类（https://github.com/miaowm5/KindleEar/blob/master/books/m5_base.py）
