### ISSUE TITLE
通过传送门抓取的TED渤海湾实效

### ISSUE THREAD

**Issue by jiey2016** [cdhigh/KindleEar#309]
之前我提到过使用微广场来订阅的方法，因为是rss，大神这个方法也不错就是不知道为什么实效了，书直接不显示。
是什么原因呢？

**Comment by miaowm5** [comment]
同一个话题为什么要连续开 3 个 issue ……
要问为什么失效你必须提供后台的错误纪录

另外想要专门针对某个网站抓取内容的话请参考默认的书籍，如果无法看懂的话请去学习 python 的爬虫相关的基础知识
