### ISSUE TITLE
微信公众号订阅思路2，请大神指教

### ISSUE THREAD

**Issue by jiey2016** [cdhigh/KindleEar#310]
前面提到过国内网站  微广场  是支持定制版rss输出的

但是天知道这种服务能用多久

于是产生了思路2：

还是国内的网站：**爱微帮**

eg：http://www.aiweibang.com/yuedu/117808049.html

网站本身不提供订阅，但是如果能抓取下公众号的内容应该是不错的，这是一个自媒体营销网站，主打营销和多账户发送自媒体内容，跟微广场有本质区别，应该更为坚挺吧，可能内容更新没有rss及时，但也差不了太多，不知道大神能不能做一个抓取爱微帮内容的教程呢？

**Comment by cdhigh** [comment]
因精力有限，理论上不再新增预置书籍，如果网友有感兴趣的，其内容也还值得一看的，不妨自己写一个，并且发给我，或推一个pull request，我觉得值得内置，我就将其加入。
