### ISSUE TITLE
删除账户重新登录时出现  internal server error

### ISSUE THREAD

**Issue by jiey2016** [cdhigh/KindleEar#312]
错误日志：

2016-05-25 06:39:43.340 /login 500 322ms 0kb Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Maxthon/4.4.8.1000 Chrome/30.0.1599.101 Safari/537.36 module=default version=1
E 2016-05-25 06:39:43.334 Traceback (most recent call last):
E 2016-05-25 06:39:43.334 File "lib/web/application.py", line 239, in process
E 2016-05-25 06:39:43.334 return self.handle()
E 2016-05-25 06:39:43.334 File "lib/web/application.py", line 230, in handle
E 2016-05-25 06:39:43.334 return self._delegate(fn, self.fvars, args)
E 2016-05-25 06:39:43.334 File "lib/web/application.py", line 420, in _delegate
E 2016-05-25 06:39:43.334 return handle_class(cls)
E 2016-05-25 06:39:43.334 File "lib/web/application.py", line 396, in handle_class
E 2016-05-25 06:39:43.334 return tocall(*args)
E 2016-05-25 06:39:43.334 File "/base/data/home/apps/s~j******/1.393037217897189156/apps/View/Login.py", line 96, in POST
E 2016-05-25 06:39:43.334 if not wl.user:
E 2016-05-25 06:39:43.334 File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/db/__init__.py", line 3734, in __get__
E 2016-05-25 06:39:43.334 reference_id.to_path())
E 2016-05-25 06:39:43.334 ReferencePropertyResolveError: ReferenceProperty failed to be resolved: [u'KeUser', 5452580167614464L]

**Comment by jiey2016** [comment]
我在其他app上部署的kindleear没有出现此问题，不知道是否需要重新部署，但是gae的应用貌似无法彻底删除吧

**Comment by cdhigh** [comment]
确认有这个问题，是因为删除账号时没有删除干净邮件白名单导致，尽管我测试过删除账号，但是没有设置白名单，所以测试不充分。
做为补救，你可以在后台将邮件白名单whitelist数据库条目全部删除。

**Comment by jiey2016** [comment]
是的，必须进入后台删除whitelist数据才行，我以为这部分数据也是存在keuser里面呢，删掉以后就可以了。

**Comment by legendslov** [comment]
谢谢作者的辛苦劳作，删除Keuser可以解决问题。
