### ISSUE TITLE
现在可以通过google cloud shell直接上传了

### ISSUE THREAD

**Issue by nmly** [cdhigh/KindleEar#313]
昨天刚刚弄了自己的kindle ear，多谢开发者。
发现新的google cloud console有个cloud terminal功能，已经不需要自己安装python和GAE SDK去上传了，可以直接在terminal里git clone过去。也许国内上传翻墙等问题，也可以通过这个解决？

**Comment by miaowm5** [comment]
新版 GAE 我老是找不到想要的功能……请问下楼主你说的那个 cloud terminal 入口在哪？

**Comment by nmly** [comment]
https://console.cloud.google.com/home/dashboard?project=xxxxxxxxx   (your app id)
在gae dashboard里，右上角project name右边第一个小图标，鼠标放上去显示activate google cloud shell

**Comment by shenxiu** [comment]
@nmly 

为什么我git clone后，打开是404……
说一下我的步骤：
1.fork项目，再按FAQ：https://htmlpreview.github.io/?https://github.com/cdhigh/KindleEar/blob/master/static/faq.html#ownserver 修改了那三个文件。
2.在shell里执行：git clone https://github.com/shenxiu/KindleEar.git
3.打开xxxxx.appspot.com，显示Error: Not Found，The requested URL / was not found on this server.

**Comment by nmly** [comment]
@shenxiu 

我的做法是
1. cloud shell里直接git clone
2. cloud里用emacs(或者其他你熟悉的编辑器)，改那三个文件
3. 在kindleear目录里输入 appcfg.py update ./

**Comment by shenxiu** [comment]
@nmly 
谢谢回复，已安装成功

**Comment by miaowm5** [comment]
我试了试，确实可以直接上传，于是写了一个 repo ，这样就能直接用简易方式上传了
https://github.com/miaowm5/KeUploader

**Comment by jiey2016** [comment]
好东西啊

**Comment by shmily1866** [comment]
请问如果我想上传自己写的py文件怎么办啊 @miaowm5 @nmly

**Comment by miaowm5** [comment]
先fork那个repo，把 upload.sh中第二行的git地址改成你自己写的py文件的git地址，然后，上传时，步骤的第二步 git clone https://github.com/miaowm5/KeUploader.git 改成你fork 后的地址

**Comment by shmily1866** [comment]
遇到点问题求帮助
首先使用您的方法 @miaowm5 网页打开后500
所以大概采用 @nmly 的方法
我先fork了kindleear，然后加上了自己的py文件和所需的封面图片，修改了FAQ里说的那三个文件
然后1.git clone https://github.com/shmily1866/KindleEar.git
2.cd kindleear
3.appcfg.py update ./
最后页面可以打开登陆，但是不推送，手动推送后等了好久推送日志也没有内容
自己写的文件应该没问题是之前一直用的，而且自带的也无法推送
gae日志里也没有什么报错内容
小白一个求帮助万分感谢 @miaowm5 @nmly

**Comment by shmily1866** [comment]
莫名其妙又好了。。。不知道问题出在哪反正能推送就好
@miaowm5 话说之所以用您的方法失败是因为我在输完账号之后顺手就输的密码==
于是把时区改成我密码了。。。。。。。。。。。

**Comment by Gemring** [comment]
@miaowm5 使用了你的简易上传，成功部署好了！非常感谢。

**Comment by lqzh1987** [comment]
@miaowm5 helper.py 中“Do you want to remove Chinese books?”是什么鬼？会不会影响我上传自己的book？

**Comment by miaowm5** [comment]
@lqzh1987 移除书籍名称包含中文的书籍，除非你输入了 'Y', 'YES', 'y', 'yes' 中的某一个，否则的话什么都不会发生

**Comment by lqzh1987** [comment]
噢噢噢 谢谢


2016-06-25 20:04 GMT+08:00 Monkey Juice <notifications@github.com>:

**Comment by JiangXL** [comment]
亲测可用

**Comment by seamaner** [comment]
@nmly 
执行完报这个错是怎么回事呢？

Validation error: Invalid dispatch configuration - module 'worker' does not exist. Upload a version of this module and try again.

**Comment by seamaner** [comment]
1st. 
appcfg.py update app.yaml module-worker.yaml
2nd.
appcfg.py update .

**Comment by javenfeng** [comment]
感谢提醒，已经成功部署。
之前用简易上传和标准上传均未能成功，耗费了很多时间。这个方法很有用。

**Comment by nmly** [comment]
@seamaner 

我猜是因为update指定的目录不对吧，你掉了个斜线
appcfg.py update ./

**Comment by mlyksuu** [comment]
@miaowm5 非常感谢 程序小白之前总是部署失败,用这个方法一下成功了
比较杯具的是,一开始绑全球付的虚拟信用卡,股沟扣了1刀后,才说不能用这个卡_(:з」∠)_ 白扣了1刀和手续费_(:з」∠)_
更悲伤的是 原来装个新版本的python就部署成功இωஇ 啊 总之终于能用了 感谢作者

**Comment by miaowm5** [comment]
@mlyksuu 
嗯会扣钱吗？我自己没绑卡没扣钱但是可以正常使用……

**Comment by mlyksuu** [comment]
@miaowm5 可能是我当时智商下线了இωஇ

**Comment by cassano0409** [comment]
@miaowm5 请问那三个文件一定要提前修改吗，如果不需要的话，是不是直接clone 原kindleear作者的地址栏然后到了c'loud shell里面修改，因为我修改完上传1万多次没成功🤣，打不开。。。。

**Comment by miaowm5** [comment]
@cassano0409 
可以在 cloud shell 里修改，不过既然你能clone成功了……你直接fork一份，然后在fork的那份里修改，最后clone你fork的那份不就好了……

**Comment by cassano0409** [comment]
@miaowm5 thx~

**Comment by ylhaven** [comment]
感谢@miaown5 亲测成功！

**Comment by Demired** [comment]
@nmly 咋会出现这个问题呢？奇怪
-----------
Please visit https://developers.google.com/appengine/downloads
for the latest SDK
****************************************************************
05:52 PM Starting update of app: kindleear-163107, version: 1
05:52 PM Getting current resource limits.
05:52 PM Scanning files on local disk.
Error 404: --- begin server output ---
This application does not exist (project_id=u'kindleear-163107'). To create an App Engine application in this project, run "gcloud app create" in your console.
--- end server output ---

**Comment by miaowm5** [comment]
@Demired 
项目不存在

**Comment by ZJJane** [comment]
请问各位大佬部署后的版本是多少，我一些自定义的rss需要翻墙才能获取，FAQ中说要升级到1.5及以上版本，并且将被qiang的RSS的链接协议改为https。
我用此方法部署后是1.25，但我fork并git clone的应该是最新的才对啊，求解。

**Comment by cdmask** [comment]
I uploaded the application with the method menioned here https://github.com/miaowm5/KeUploader, but i can not login with the default username and password: admin...
@miaowm5

**Comment by miaowm5** [comment]
Default admin account is created by kindleEar with this code:
https://github.com/cdhigh/KindleEar/blob/master/apps/View/Login.py#L39
KeUploader doesn't edit it, so if you can't login, try to check your kindleEar version or check your spell
@cdmask

**Comment by cdhigh** [comment]
FAQ can help you, in backend of GAE, find the sector datastore, delete the data item which name is 'admin', then the KindleEar will create a new 'admin' with password 'admin'

**Comment by cdmask** [comment]
Yeah, i deleted KeUser entry in datastore admin, and now its working fine. Thank you!

**Comment by cdmask** [comment]
@Demired Just follow the instruction, run the "gcloud app create" in the console, and then upload the application. You need to create an application in the project that you already created.

**Comment by cruiser** [comment]
> @nmly
> 执行完报这个错是怎么回事呢？
> 
> Validation error: Invalid dispatch configuration - module 'worker' does not exist. Upload a version of this module and try again.

Try this command again.
appcfg.py update ./app.yaml ./module-worker.yaml

**Comment by cdhigh** [comment]
已经升级 3.0.0b，支持Python3
部署方法参考文档
https://cdhigh.github.io/KindleEar/

**Comment by ylhaven** [comment]
已经收到您的来信，我会尽快回复。Your email has been received ,and it will be handled with as soon as possible. Thanks.
