### ISSUE TITLE
用feed43生成的rss，推送时只推送第一个

### ISSUE THREAD

**Issue by shenxiu** [cdhigh/KindleEar#314]
比较爱看小说，就用feed43做了几个rss，用KindleEar推送。
目前遇到了这两个问题：
1.添加了13个rss，只推送第一个rss。

- 这个问题从昨天下午刚搭建好KindleEar就有了。添加了rss后，手动推送，只推送了第一个rss的内容。

- 于是试着把这十几个rss链接都点击了一次，再手动推送，发现13个rss都是正常推过来了。

- 本以为就此大吉，没想到，今天早上的定时推送，又出现了“只推送了第一个rss的内容”，这种现象。

- 试着再点击了2个rss，再手动推送，发现刚好是这3个的rss正常推送过来了，其余的不见动静。

感觉像是feed43生成的xml有问题…… 有大大遇到过这种情况吗？不知道有没有解决的方法。

2.推送过的文章，下一次继续推送。

- 小说A第一次推送，从200章到181章，全部阅读；第二次推送，是201到182章。

请问，是否可以设置为只推送更新的章节，发送过的章节不必再推送呢？

谢谢~

**Comment by miaowm5** [comment]
这是 feed43 的问题啊……
KR 只会根据 rss 的时间来判断是否推送，不会去纪录哪些内容推送过哪些内容没推送过，rss 里时间变了是否推送的判断自然也就混乱了……

**Comment by shenxiu** [comment]
@miaowm5 

谢谢回复。
果然是feed43的锅呀。

今天解决第一个问题了。
这样的feed：http://www.feed43.com/xxxxx.xml，放在KindleEar里可以正常使用。
而这样的feed：http://feed43.com/xxxxx.xml，放在KindleEar里，必须每次在推送前手动点击一下，才能正常使用。

……

不懂其中有何玄机。

第二个问题。
“KR 只会根据 rss 的时间来判断是否推送”，观察了一下feed43生成的xml链接，feed内的链接好像并无时间记录，只有feed有最后更新时间的记录。
大概是因为这样，其会推送所以文章。
不知道有没有什么解决办法。

**Comment by miaowm5** [comment]
我自己的解决方法是，针对需要的网站，专门写一个抓取网页更新生成带时间的 RSS 的工具……
https://github.com/miaowm5/RSSGen

**Comment by shenxiu** [comment]
@miaowm5 

厉害，这个东西我得好好琢磨一下。
