### ISSUE TITLE
Error code 204 无法投递

### ISSUE THREAD

**Issue by miaowm5** [cdhigh/KindleEar#319]
今天某一本杂志忽然无法投递，于是登陆后台查看纪录时发现出现了一个特殊的错误

> A problem was encountered with the process that handled this request, causing it to exit. This is likely to cause a new process to be used for the next request to your application. (Error code 204)

这个是后台 log 的附图，其中 Warn 级别及以下的 log 是正常的（都是我自己加上方便调试的警告），同样的书籍配置，昨天是可以正常推送的

![qq 20160603091954](https://cloud.githubusercontent.com/assets/7985604/15765909/818356b8-296c-11e6-8307-84c60269c1b5.png)

另外，从早晨六点正常推送时出现这个错误后 GAE 就一直在尝试重新执行推送，在该应用的部分书籍没有出现该错误，部分书籍出现错误后反复尝试最后成功推送，还有的书籍……至今还在尝试，看情况估计要把今天的免费配额消耗完强行停止了……

因为触发条件不明，我不知道如何在其他账号重现这个错误……

**Comment by miaowm5** [comment]
将相同的书籍转移到了另外一个应用，结果该报错仍然发生，投递该应用的其他书籍时正常，初步怀疑是某个 RSS 源的问题，现在开始排查各个 RSS 源……

**Comment by cdhigh** [comment]
这个可能是很多年前的GAE的bug，曾经的GAE SDK里面写到，任务队列触发后不保证运行，同时不保证只运行一次，后来说修复了，结果还有用户报此bug，后来好像又说修复了，但估计还是没有彻底解决，我在前期也偶尔遇到此bug，一次触发后一旦出错，Gae就一直尝试，尽管在queue.yaml里面已经限制了重试次数。
这个问题很难重现。

**Comment by miaowm5** [comment]
不知道为什么，下午测试的时候发现抓取这个rss的时候必定重现，不过也可能和应用以及rss内容有关，之后我再试试
