### ISSUE TITLE
突然今天收不到推送了会是啥原因？

### ISSUE THREAD

**Issue by nmly** [cdhigh/KindleEar#324]
过去差不多一个月都正常，就是今天突然没收到推送了。kindleear显示deliver status没问题，但是kindle没收到，进了amazon.cn去看我的内容，电子文挡里就是没有今天的。在KE手动推送一次，还是没收到。这是可能啥原因？

**Comment by nmly** [comment]
很奇怪今天收到了昨天应该收到的投递，但是今天的又没收到了。。

**Comment by nmly** [comment]
最近投递获取持续的不正常，KE后台全部显示投递正常，但是最近13,14号没收到，16号的也没收到。。。奇怪啊，有人出现过类似问题吗？

**Comment by miaowm5** [comment]
会不会也和亚马逊有关？杂志拆成多本分开投递试试？

**Comment by nmly** [comment]
也有可能，不知道是不是GMAIL往国内AMAZON.CN发信会有丢失的情况？最近几天又正常了。。不太想拆分，看起来太乱了。

**Comment by nmly** [comment]
突然想到也许是订阅的quora出现了啥关键字被墙了。。
