### ISSUE TITLE
能否设置所有推送的电子书到一个文件夹中

### ISSUE THREAD

**Issue by waitandsoon** [cdhigh/KindleEar#325]
现在推送的东西都是到达最外面，多了看着难受。
是否能够设置推送到一个文件夹内。

**Comment by nmly** [comment]
setting有merge books into one

**Comment by waitandsoon** [comment]
@nmly 这个选项的意思，是把多个RSS源放进一本书里。
但我的意思是，把多本书，放进一个kindle的文件夹里。毕竟有点乱。

**Comment by miaowm5** [comment]
没法办到，因为 Kindle 本身连文件夹功能都没有，收藏夹功能也不好用
