### ISSUE TITLE
Mobi有大小限制吗？

### ISSUE THREAD

**Issue by waitandsoon** [cdhigh/KindleEar#326]
今天一直出现send failed。
怀疑是昨天增加的几个rss会导致出现mobi体积增大到30Mb左右。
想问一下亚马逊对这个有要求吗？

**Comment by miaowm5** [comment]
GAE 对附件大小有要求，不能超过 30M
亚马逊的话印象中中亚是不能超过 50M

不过这次 Sedn failed 是 GAE 的锅

**Comment by waitandsoon** [comment]
有办法突破吗
毕竟30M真的不太够用

**Comment by miaowm5** [comment]
也许花钱买 GAE 高级账户的话可以突破

另外 30M 是单个附件的大小限制，你可以把 Feed 拆成多本杂志，一般图片没有太多的话 30M 还是够用的（我十几个feed加起来每天推送大小也才30M左右）

**Comment by cdhigh** [comment]
如果不是需要太清晰的图，还可以考虑将图片压缩一下尺寸，在config.py里面有选项。
