### ISSUE TITLE
KE是基于GAE，按说已经是翻墙状态呀。为什么有些RSS获取不到呢？

### ISSUE THREAD

**Issue by waitandsoon** [cdhigh/KindleEar#327]
如题，既然是墙外状态，为什么还需要使用cdhigh/Forwarder之类的
请大神解惑。

**Comment by miaowm5** [comment]
某些网站反感爬虫，看到通过 GAE 来访问的机器人就会拒绝提供内容，因此需要再用一层 Forwarder

**Comment by cdhigh** [comment]
除了部分网站反爬虫，墙外的GAE（GOOGLE是防火墙重点提防的）有时候访问墙内的部分敏感网站也出错，我发现有几个网站有这个问题，用了中转就可以了。
