### ISSUE TITLE
Feedly support

### ISSUE THREAD

**Issue by mgarciate** [cdhigh/KindleEar#330]
Hi, have you thought about adding as an option synchronize with Feedly? I mean, being able to connect your Feedly account (through the API) and select some sources and/or folders you'd like to send to your book. Mark as read the entry after it was sent. Graphical interface not required. Thx

**Comment by cdhigh** [comment]
I'm very busy for many things recently, so I will not think about it in this year.

**Comment by mgarciate** [comment]
Alright, thx
