### ISSUE TITLE
附件的文件名如何不带日期？

### ISSUE THREAD

**Issue by Spaiol** [cdhigh/KindleEar#333]
是否可以加入选项，使邮件附件的文件命名不带日期和时间，从而实现设备上自动替换为最新一期？

**Comment by cdhigh** [comment]
名字一样都无法自动归档，之前测试过了，Amazon会在文件名后添加一堆数字，除非你自己从电脑上直接拷贝到kindle才可以。

**Comment by Spaiol** [comment]
嗯，收到，谢谢您的回复
