### ISSUE TITLE
设置里的 设备类型是干嘛的

### ISSUE THREAD

**Issue by waitandsoon** [cdhigh/KindleEar#334]
里面有 kindle，kindle DX， kindle pw， kindle fire，其他
分别代表什么？
如果说分辨率不同我能理解，但是“其他”是什么。。。
另外我是kindle ko，应该选择哪个

**Comment by miaowm5** [comment]
决定分辨率、DPI、字体大小等参数的
其他表示使用默认分辨率

功能看这里：
https://github.com/cdhigh/KindleEar/blob/master/lib/makeoeb.py#L77

各个选项对应的屏幕大小等设置看这里
https://github.com/cdhigh/KindleEar/blob/master/lib/calibre/customize/profiles.py

**Comment by waitandsoon** [comment]
@miaowm5 反馈好快！
那kindle oasis应该选择哪个

**Comment by waitandsoon** [comment]
@miaowm5 
还有，选择不同的选项，是否会影响最终生成mobi文件的大小。
毕竟最终的清晰度改变了。

**Comment by miaowm5** [comment]
这我就不确定了，不过反正服务是免费的，你可以自己把每个设置一遍试试看

**Comment by cdhigh** [comment]
最终文件的大小只和图片压缩率和是否转成黑白图有关，在config.py里面有设置。
