### ISSUE TITLE
isfulltext选项是不是任何时候选上都没错？

### ISSUE THREAD

**Issue by waitandsoon** [cdhigh/KindleEar#335]
对于普通用户来说其实挺难界定一个rss是否是全文输出的
所以我是都勾上，不知道合适不合适

**Comment by miaowm5** [comment]
不合适，
对于普通用户啊，你直接打开 rss 地址就能看到是否是全文的了……

勾上之后，即使是全文 RSS ，KE 也会尝试访问原网页去抓取，最终抓取到的网站质量不如直接用全文 RSS 自带的内容来的要好……如果你不介意这重问题的话也可以全部选上，选上至少不会报错就是了

**Comment by cdhigh** [comment]
基本上如此，不过选上了全文后，除非RSS里面没有内容，否则不会再次联网抓取，一是提高效率，而是减小了网络超时导致部分文章抓取不到的可能，内置的“智能”正文提取模块也不是那么智能，可能抓到广告或分享链接等无关内容，网站自己提供的全文信息一般排版较好。
