### ISSUE TITLE
为什么最近打开不了管理页面了？

### ISSUE THREAD

**Issue by zhoujiealex** [cdhigh/KindleEar#336]
RT
我7.3号用最新的版本上传成功后，当时又更新添加了几个RSS源，最近登陆都打不开
<domain>.appspot.com的地址。

但是我的kindle还是能按时收到推送，说明后台没问题，是google哪边出问题了么？

包括作者你自己的站点[http://kindleear.appspot.com/]( http://kindleear.appspot.com/)
我的地址是： [https://think-diff.appspot.com/](https://think-diff.appspot.com/)

请帮忙确认下是不是我自己个人的原因？

**Comment by zhoujiealex** [comment]
然后我今天又重新上传了一遍，还是打不开管理页面~~~

**Comment by WangShanpeng** [comment]
我可以上，应该是被墙了，你尝试一下翻墙

**Comment by zhoujiealex** [comment]
用手机翻墙可以访问了 感谢

**Comment by cdhigh** [comment]
在FAQ里面提到一个tip.
将appspot里面的o(字母)改成0(数字)即可不用翻墙访问
