### ISSUE TITLE
手动推送后一直没反应

### ISSUE THREAD

**Issue by waitandsoon** [cdhigh/KindleEar#337]
以前，即使推送失败，也会在“投递日志”页面有显示。
但是今天手动推送尝试了一晚上了，投递日志页面没有任何信息。
也没有推送成功。
需要怎么排错？

**Comment by waitandsoon** [comment]
@miaowm5 跪求方法
比如怎么看日志，怎么重启

**Comment by miaowm5** [comment]
进入 GAE 后台
另外 GAE 每日有限制，你可能用完了每天的服务器配额，建议24小时之后重新再试试

**Comment by waitandsoon** [comment]
@miaowm5 怎么进入呀。。。。。

**Comment by miaowm5** [comment]
你KE首页最下方就有进入的网址啊……
