### ISSUE TITLE
支持生成azw格式吗 

### ISSUE THREAD

**Issue by LiuR** [cdhigh/KindleEar#339]
如果可以的话在哪里可以设置呢

**Comment by LiuR** [comment]
发现azw不能推送 close吧 不过依然期待解答

**Comment by LiuR** [comment]
azw应该是支持的 azw3不行

**Comment by LiuR** [comment]
有个想法是生成epub，通过kindlegen转换为mobi，设置转发至自己的kindle邮箱，主题为convert 将会实现azw格式的转换。不过我记得以前在哪个issue中看到开发者说自己避免使用kindlegen这是出于哪方面的考虑吗。

**Comment by cdhigh** [comment]
GAE托管环境是纯python环境，无法使用kindlegen，kindlegen是二进制执行文件。
