### ISSUE TITLE
SAVE TO WIZ选择“需要翻墙”后出错

### ISSUE THREAD

**Issue by mlyksuu** [cdhigh/KindleEar#341]
不使用heroku中转的话使用正常，然而我kindle并不能翻墙
使用中转的话，save to wiz的url会变成这个样子，中转url会出现两次：
http://xxx.herokuapp.com/?k=xzSlE&t=30&u=http://XXXX.appspot.com/share?act=wiz&u=admin&url=http://xxx.herokuapp.com/?k=xzSlE&t=30&u=http://daily.zhihu.com/story/8696011
结果是加载出错。
因为wiz提供了url2wiz功能（http://note.wiz.cn/url2wiz ）所以其实只要直接打开特定的url就可以发送到wiz，不需要发邮件给wiz邮箱
<s>然而代码盲的我并不知道可以在哪里修改_(:з」∠)_ 球赐教</s>找到惹_(:з」∠)_

**Comment by miaowm5** [comment]
试试改这里：
https://github.com/cdhigh/KindleEar/blob/ceb0f8a97f094f6ff538fe5d4796388bd16a3acc/books/base.py#L1051
```python
        if sharetype in ('evernote','wiz'):
            href = "%s/share?act=%s&u=%s&url=" % (DOMAIN, sharetype, user.name)
```
改成
………………
啊，你已经找到了啊（:joy:
