### ISSUE TITLE
自定义的RSS内容并不会被投递

### ISSUE THREAD

**Issue by crabwq** [cdhigh/KindleEar#342]
每次只会把默认提供的RSS投递出去。
这个问题该怎么解决？

**Comment by LiuR** [comment]
可能没有打开自定义投送的开关

**Comment by mpb159753** [comment]
同样问题，手动推送也失败了，
没有其他订阅，只投递自定义 RSS 的话会提示：没有需要推送的书籍！
有其他订阅，也有自定义 RSS 的话手动推送只会推送默认提供的。

**Comment by Demired** [comment]
> 设置 - 自定义RSS设置

* [ ] 保留文章图片

* [x] 自动定时投递自定义RSS

钩上就行了
