### ISSUE TITLE
关于微信公众号的推送

### ISSUE THREAD

**Issue by gjy3035** [cdhigh/KindleEar#343]
我采用的是http://www.iwgc.cn/这个网站，他先会将特定的公众号转成XML。然后我将生成的地址加入到自定义后，推送并不能成功抓取信息。可能有重定向的问题，而PC版本的calibre 没有这个你问题，希望能解决一下

**Comment by fwl2000613** [comment]
我也有同样的问题，求解！

**Comment by mlyksuu** [comment]
他家生成的RSS带全文，所以选isfulltest就好啦
