### ISSUE TITLE
Unable to assign value 的问题。

### ISSUE THREAD

**Issue by DamonOre** [cdhigh/KindleEar#344]
操作Log如下。

C:\Program Files (x86)\Google\google_appengine>c:\python27\python.exe appcfg.py update c:\kindleear\app.yaml c:\kindleear\module-worker.yaml 10:03 AM Host: appengine.google.com Usage: appcfg.py [options] update <directory> | [file, ...]  appcfg.py: error: Error parsing c:\kindleear\app.yaml: Unable to assign value 'DaDaDaDaDamonOreKindleEar' to attribute 'application': Value 'DaDaDaDaDamonOreKindleEar' for application does not match expression '^(?:(?:[a-z\d-]{1,100}~)?(?:(?!-)[a-z\d-.]{1,100}:)?(?!-)[a-z\d-]{0,99}[a-z\d])$'   in "c:\kindleear\app.yaml", line 1, column 14.

**Comment by cdhigh** [comment]
是因为你的文本编辑器将app.yaml保存为不知什么格式的文件了，请使用代码编辑器比如notepad++ sublime等来修改。
