### ISSUE TITLE
fetch rss failed(405 Method Not Allowed):http://www.freebuf.com/feed

### ISSUE THREAD

**Issue by waitandsoon** [cdhigh/KindleEar#346]
之前用的好好的，突然这几天出现这个错误。
fetch rss failed(405 Method Not Allowed):http://www.freebuf.com/feed
请教怎么解决。。。。。

**Comment by cdhigh** [comment]
可能封锁了GAE的IP段访问吧，可以考虑试试使用转发是否可以
