### ISSUE TITLE
请问谁有KindleEar在Google中的运行环境搭建详细教程

### ISSUE THREAD

**Issue by liaomars** [cdhigh/KindleEar#347]
请问有谁能说明下 KindldeEar 在Google 运行环境的搭建的详细教程，我自已试了下操作跟说明文档中的操作步骤有出入。

**Comment by kindlefere** [comment]
@liaomars 这里有个教程：https://kindlefere.com/post/19.html

**Comment by runbing** [comment]
@liaomars 那看看这个教程呢 https://kindlefere.com/post/19.html
