### ISSUE TITLE
投递日志显示结果，推送不成功

### ISSUE THREAD

**Issue by hqwxyz** [cdhigh/KindleEar#353]
时间                           书籍标题          附件大小      收件人                 状态
2016-11-16 15:06   KindleEar                0         *****55@kindle.cn     nonews
2016-11-16 15:06   The Economist    4.8 MB   *****55@kindle.cn     wrong SRC_EMAIL

投递日志显示如上。gmail地址已放到允许投递的地址列表内并且直接用电邮投递已成功。不知道这是什么问题。

**Comment by hqwxyz** [comment]
如果投递日志状态显示为 wrong SRC_EMAIL，请左上角的菜单，在弹出的菜单中点击“APP 引擎（App yin qin）”，然后点击 APP 引擎页面左侧的“设置 (settings)”，看看“Email API 已获授权发件人（Email API authorized senders）”账号里面有无添加发送邮箱地址，如果没有就点击上方的“编辑（Edit）”添加一下并保存，此问题即可解决。

//已根据以上进行了设置，依然wrong SRC_EMAIL错误。

**Comment by hqwxyz** [comment]
换了一个gmail帐号，按照教程一步步搭建，成功了。
现在是稀里糊涂，不知道为何失败，也不知道为何成功。

**Comment by xiaosefengyun** [comment]
@hqwxyz 是因为你没有把邮箱添加进白名单
