### ISSUE TITLE
推送结果显示ok但是收不到

### ISSUE THREAD

**Issue by CabbSir** [cdhigh/KindleEar#354]
就是显示成功，kindle上就是收不到推送

**Comment by knightpanda** [comment]
同样的问题....怎么解决....

**Comment by CabbSir** [comment]
有木有人列

**Comment by CabbSir** [comment]
感觉可能是google被墙的原因吧，过几天自己搭个服务器试试吧

**Comment by nmly** [comment]
我也有过类似问题，怀疑是有啥gfw弄的问题，不过大部分出问题的也就是晚几个小时或1,2天收到，所以也无所谓了

**Comment by cdhigh** [comment]
墙的问题还是得自己搜索解决，这里不答复
