### ISSUE TITLE
我写了个book的py文件，怎么让它生效呢

### ISSUE THREAD

**Issue by duhai973** [cdhigh/KindleEar#355]

**Comment by miaowm5** [comment]
扔到books文件夹下，然后部署到GAE，之后在首页就能添加这个 book 了
如果首页没找到的话，去后台看错误纪录，一般是你的代码有错导致book导入失败

**Comment by chengshuyi** [comment]
@miaowm5 我也遇到了这样的问题。我是用gcloud shell直接上传的文件。我觉得需要重启kindleEar它才会生效吧！但是，现在我不知道怎么重启，请问你有什么好方法让book.py生效吗？
