### ISSUE TITLE
每一篇文章，能否在结尾处附上网址和二维码

### ISSUE THREAD

**Issue by sakuraOnlin** [cdhigh/KindleEar#356]
每一篇文章，能否在结尾处附上网址和二维码？？这样的话，看到好的文章，就可以在手机上扫码后在手机上做进一步处理了。

**Comment by miaowm5** [comment]
可以在结尾加上分享到印象笔记啥的，之后手机上登陆印象笔记啊

**Comment by cdhigh** [comment]
附上网址功能已经有了，就是“Open in brower”功能，在归档和分享菜单里面打开即可。
附加二维码这个想法不错，有时候我也需要，最近考虑加入此功能。

**Comment by cdhigh** [comment]
已在1.23.3中加入此功能
