### ISSUE TITLE
能不能加上用163邮箱发送推送？？

### ISSUE THREAD

**Issue by DzInorganic** [cdhigh/KindleEar#359]
能不能加上用163邮箱发送？？Gmail发送延迟太大。
先发送到Outlook邮箱，outlook再转发到kindle也有延迟。
用163转发倒是挺快，但Gmail发送到163邮箱有很大延迟。
能不能自己设置163SMTP，用163直接发送？？

**Comment by cdhigh** [comment]
GAE应用当然是用GAE的邮件服务，推送至美亚基本上没有延迟，如果不能接受延迟，可以将kindle的中亚账号改成美亚账号。
