### ISSUE TITLE
能不能加上用163邮箱发送？？

### ISSUE THREAD

**Issue by DzInorganic** [cdhigh/KindleEar#360]
能不能加上用163邮箱发送？？Gmail发送延迟太大。
先发送到Outlook邮箱，outlook再转发到kindle也有延迟。
用163转发倒是挺快，但Gmail发送到163邮箱有很大延迟。
能不能自己设置163SMTP，用163直接发送？？

**Comment by liuyanxi975** [comment]
我有了一个解决方案，就是有些麻烦，但是好用，亲测自kindleear发出后5分钟内设备可接收推送。
原理就是我发现给自己的gmail发邮件几乎是没有延迟的，而发到outlook则需要50分钟时间，而outlook到kindle则很快，主要就是从gmail到outlook耽误的时间。但奇怪的是手动用gmai给outlook发邮件则很快，所以才有下面的方案。
------------------------------------------------
1.将kindleear推送地址设置为自己的gmail地址，是的，就是往自己的邮箱发。
2.设置过滤器或转发，将kindleear邮件转发到outlook等不需要验证的邮箱，当然，gmail得验证outlook邮箱，到outlook里接收下就好，很简单。
3.再在outlook邮箱设置转发，直接到设备地址。
--------------------------------------
值得注意的是，outlook有时会把邮件视为垃圾邮件而拦截，建议将gmail的邮箱地址添加进入outlook的安全邮件列表可解决这个问题。
