### ISSUE TITLE
上传出现502 bad gateway错误,怎么解决？

### ISSUE THREAD

**Issue by aodi2004** [cdhigh/KindleEar#361]
运行：
C:\python27\python.exe appcfg.py update D:\zjy\KindleEar-master\KindleEar\app.yaml D:\zjy\KindleEar-master\KindleEar\module-worker.yaml
总出现 502 badgateway 错误提示。
运行
C:\python27\python.exe appcfg.py update D:\zjy\KindleEar-master\KindleEar
则正常，没有出错提示，这是什么问题？
谢谢

**Comment by aodi2004** [comment]
又出现下面问题：

aodi2004@aodi2004:~/KeUploader$ sh update.sh

KindleEar uploader v1.3.1 (2015-08-20) by cdhigh

Your custom info :
          app id : aodi2004
           email : aodi2004@gmail.com
        timezone : 8
Correct? (y/n) : y
08:27 PM Host: appengine.google.com
08:27 PM Application: aodi2004; version: 2
08:27 PM Starting update of app: aodi2004, version: 2
08:27 PM Getting current resource limits.
08:27 PM Scanning files on local disk.
08:27 PM Cloning 15 static files.
08:27 PM Cloning 390 application files.
08:27 PM Compilation starting.
08:27 PM Compilation completed.
08:27 PM Starting deployment.
08:27 PM Checking if deployment succeeded.
08:27 PM Deployment successful.
08:27 PM Checking if updated app version is serving.
08:27 PM Completed update of app: aodi2004, version: 2
08:27 PM Application: aodi2004; module: worker; version: 1
08:27 PM Starting update of app: aodi2004, module: worker, version: 1
08:27 PM Getting current resource limits.
08:27 PM Scanning files on local disk.
Error 409: --- begin server output ---
Another transaction by user aodi2004 is already in progress for app: s~aodi2004, version: 1. That user can undo the transaction with "appcfg rollback".
--- end server output ---
08:28 PM Application: aodi2004; version: 2
08:28 PM Host: appengine.google.com
08:29 PM Starting update of app: aodi2004, version: 2
08:29 PM Getting current resource limits.
08:29 PM Scanning files on local disk.
08:27 PM Application: aodi2004; version: 2
08:29 PM Cloning 15 static files.
08:29 PM Cloning 390 application files.
08:29 PM Compilation starting.
08:29 PM Compilation completed.
08:29 PM Starting deployment.
08:29 PM Checking if deployment succeeded.
08:29 PM Deployment successful.
08:29 PM Checking if updated app version is serving.
08:29 PM Completed update of app: aodi2004, version: 2
08:29 PM Uploading index definitions.
08:29 PM Uploading cron entries.
08:29 PM Uploading task queue entries.
08:29 PM Uploading dispatch entries.


用：appcfg.py rollback KindleEar/  也没有效果

**Comment by cdhigh** [comment]
翻墙的问题这里不答复，自己搜索网络
