### ISSUE TITLE
您好！google中添加邮箱后仍然出现wrong SRC_EMAIL

### ISSUE THREAD

**Issue by lqsxianxu** [cdhigh/KindleEar#362]
您好！
部署好了之后出现wrong SRC_EMAIL。
按照FAQ中所说的 `投递日志状态wrong SRC_EMAIL的解决方案`
完成操作后依旧出现wrong SRC_EMAIL。

恩，我是设置了两个账户，一个推送到kindle，一个推送到多看。两个都是提示wrong SRC_EMAIL。
忘得到您的帮助。

另我是大陆用户，用的Shadowsocks软件。

实在不行的话，您看我把设置中接受邮箱改成我的gmail或者163邮箱，然后用IFTTT之类的功能让他再自动转发到我的推送邮箱。您看可以吗，实在不行的办法，作为Plan B

感激不尽
需要提供我部署的KindleEar的地址及登陆账户密码吗？
顺祝健康、吉祥
2016年12月7日

**Comment by lqsxianxu** [comment]
附上 GAE后台 的Logs信息，以便定位问题，也可以得到更快的答复。

不知道在哪里？
小白，望谅解

**Comment by lqsxianxu** [comment]
不知道是不是这个：


2016-12-05 香港時間
 查看选项
在过去 30 天内找不到与当前过滤条件相符的更旧的条目。
09:50:22.821
GET
404
123 B
1.3 s
Unknown
/_ah/start
 0.1.0.3 - - [05/Dec/2016:09:50:22 +0800] "GET /_ah/start HTTP/1.1" 404 123 - "-" "0.1.worker.kindle677677.appspot.com" ms=1300 cpu_ms=1363 cpm_usd=1.3746e-8 loading_request=1 instance=00c61b117c9136e5f17d4788baf493948007a4f6dc378503db89d2bfea56 app_engine_release=1.9.48 trace_id=-
{
 metadata: {…}   
 protoPayload: {…}   
 insertId: "2016-12-04|17:50:29.122793-08|10.106.194.155|-1224457767"   
 log: "appengine.googleapis.com/request_log"   
 httpRequest: {…}   
 operation: {…}   
}
09:50:24.121
This request caused a new process to be started for your application, and thus caused your application code to be loaded for the first time. This request may thus take longer and use more CPU than a typical request for your application.
12:21:05.101
GET
404
123 B
1.6 s
Unknown
/_ah/start
 0.1.0.3 - - [05/Dec/2016:12:21:05 +0800] "GET /_ah/start HTTP/1.1" 404 123 - "-" "0.1.worker.kindle677677.appspot.com" ms=1571 cpu_ms=1390 cpm_usd=1.3746e-8 loading_request=1 instance=00c61b117cdcf1f76205be080f0df5ac3a6a58aba252f3ae8d936c900698 app_engine_release=1.9.48 trace_id=-
{
 metadata: {…}   
 protoPayload: {…}   
 insertId: "2016-12-04|20:21:11.674548-08|10.106.158.214|1661620207"   
 log: "appengine.googleapis.com/request_log"   
 httpRequest: {…}   
 operation: {…}   
}
12:21:06.673
This request caused a new process to be started for your application, and thus caused your application code to be loaded for the first time. This request may thus take longer and use more CPU than a typical request for your application.
21:05:12.748
GET
404
123 B
1.6 s
Unknown
/_ah/start
 0.1.0.3 - - [05/Dec/2016:21:05:12 +0800] "GET /_ah/start HTTP/1.1" 404 123 - "-" "0.1.worker.kindle677677.appspot.com" ms=1576 cpu_ms=1439 cpm_usd=1.3746e-8 loading_request=1 instance=00c61b117ccf18b43e73add27a3fc1dc6e51d6ec111159ef05c36144d958 app_engine_release=1.9.48 trace_id=-
{
 metadata: {…}   
 protoPayload: {…}   
 insertId: "2016-12-05|05:05:19.326467-08|10.106.18.19|-586363452"   
 log: "appengine.googleapis.com/request_log"   
 httpRequest: {…}   
 operation: {…}   
}
21:05:14.324
This request caused a new process to be started for your application, and thus caused your application code to be loaded for the first time. This request may thus take longer and use more CPU than a typical request for your application.
22:43:02.401
GET
404
123 B
1.4 s
Unknown
/_ah/start
 0.1.0.3 - - [05/Dec/2016:22:43:02 +0800] "GET /_ah/start HTTP/1.1" 404 123 - "-" "0.1.worker.kindle677677.appspot.com" ms=1373 cpu_ms=1288 cpm_usd=1.3746e-8 loading_request=1 instance=00c61b117cc46603e2bbb9767a2f703740a9cb3e639d6f9c4fecd84ba206 app_engine_release=1.9.48 trace_id=-
{
 metadata: {…}   
 protoPayload: {…}   
 insertId: "2016-12-05|06:43:08.775730-08|10.106.51.79|101566887"   
 log: "appengine.googleapis.com/request_log"   
 httpRequest: {…}   
 operation: {…}   
}
22:43:03.774
This request caused a new process to be started for your application, and thus caused your application code to be loaded for the first time. This request may thus take longer and use more CPU than a typical request for your application.
2016-12-06
07:43:01.284
GET
404
123 B
1.2 s
Unknown
/_ah/start
 0.1.0.3 - - [06/Dec/2016:07:43:01 +0800] "GET /_ah/start HTTP/1.1" 404 123 - "-" "0.1.worker.kindle677677.appspot.com" ms=1219 cpu_ms=1254 cpm_usd=1.3746e-8 loading_request=1 instance=00c61b117cfe20b9e5635369025cc2343202decb8b30c023195b785c90fb09 app_engine_release=1.9.48 trace_id=-
{
 metadata: {…}   
 protoPayload: {…}   
 insertId: "2016-12-05|15:43:07.505426-08|10.106.89.72|-418783030"   
 log: "appengine.googleapis.com/request_log"   
 httpRequest: {…}   
 operation: {…}   
}
07:43:02.503
This request caused a new process to be started for your application, and thus caused your application code to be loaded for the first time. This request may thus take longer and use more CPU than a typical request for your application.
22:43:01.875
GET
404
123 B
1.5 s
Unknown
/_ah/start
 0.1.0.3 - - [06/Dec/2016:22:43:01 +0800] "GET /_ah/start HTTP/1.1" 404 123 - "-" "0.1.worker.kindle677677.appspot.com" ms=1462 cpu_ms=1348 cpm_usd=1.3746e-8 loading_request=1 instance=00c61b117c9a4521f94f5d7276256e041ee9d5f90e80c3e3eedbd3c790392b app_engine_release=1.9.48 trace_id=-
{
 metadata: {…}   
 protoPayload: {…}   
 insertId: "2016-12-06|06:43:08.338892-08|10.106.129.21|285535302"   
 log: "appengine.googleapis.com/request_log"   
 httpRequest: {…}   
 operation: {…}   
}
22:43:03.337
This request caused a new process to be started for your application, and thus caused your application code to be loaded for the first time. This request may thus take longer and use more CPU than a typical request for your application.
2016-12-07
07:43:01.239
GET
404
123 B
1.2 s
Unknown
/_ah/start
 0.1.0.3 - - [07/Dec/2016:07:43:01 +0800] "GET /_ah/start HTTP/1.1" 404 123 - "-" "0.1.worker.kindle677677.appspot.com" ms=1168 cpu_ms=1221 cpm_usd=1.3746e-8 loading_request=1 instance=00c61b117cc8394c9d46de932456312ba1755105f23603ee96270a93c386f6 app_engine_release=1.9.48 trace_id=-
{
 metadata: {…}   
 protoPayload: {…}   
 insertId: "2016-12-06|15:43:07.408418-08|10.106.122.195|-150878793"   
 log: "appengine.googleapis.com/request_log"   
 httpRequest: {…}   
 operation: {…}   
}
07:43:02.406
This request caused a new process to be started for your application, and thus caused your application code to be loaded for the first time. This request may thus take longer and use more CPU than a typical request for your application.

**Comment by nmly** [comment]
https://github.com/cdhigh/KindleEar/issues/285

根据这个issue里的连接你确定下gae后台的发送邮件设置正确么？

**Comment by lqsxianxu** [comment]
恩，是這個地方，之前就是設置的這裡。
Email API 获得授权的发件人  lqsxianxu677@gmail.com

**Comment by lqsxianxu** [comment]
您好，从新创建了项目，重新部署之后，上午测试了一下ok了，设置什么的都没改。。。不清楚是什么原因呢。
希望不再出什么问题。

另， kindle伴侣中，有位作者在介绍您的kindleear部署方法的时候，提供了一种更便捷的方式
`复制下面的代码，粘贴到 Google 云端 Shell（如下图所示），回车执行。

wget https://raw.githubusercontent.com/kindlefere/KindleEar-Uploader/master/uploader.sh && \
chmod +x uploader.sh && \
./uploader.sh
google-cloud-shell-code

4、按照脚本的提示，输入你的 Gmail 地址和准备好的 APPID，回车，等待上传成功即可。
`

原链接见`https://kindlefere.com/post/19.html`

谢谢您开发的kindleear平台，很方便，很好用！
顺祝平安快乐！
