### ISSUE TITLE
xxx@appid.appspotmail.com邮箱使用疑问

### ISSUE THREAD

**Issue by woshishen0902** [cdhigh/KindleEar#364]
您好！我已经成功使用了kindleear，自己的订阅也可以收到了。但是我有个疑问：
我在高级设置中，将邮箱白名单设置成了*，然后向邮箱123@kindle-ear-1000.appspotmail.com发了邮件，但是kindle上并没有收到相关文档。我还需要在亚马逊或者谷歌平台上做什么设置吗？请指教，谢谢！

**Comment by cdhigh** [comment]
这个功能是我用的最多的，时不时就在手机上分享网页发送至kindleear，然后稍候就可以在kindle上仔细阅读文章了。

1.  在后台LOGS看看，是否有接收到邮件的提示，是否有邮件被拦截的提示。
2. kindleear界面上的投递历史上是否有显示？
3. 邮件白名单里面的*不能包括引号比如这样'*' (因为我在FAQ中是用的单引号括起来的，可能误会)

**Comment by woshishen0902** [comment]
又尝试了一次，成功推送了。状态为OK了，感谢您抽时间回答！
