### ISSUE TITLE
Error 409: --- begin server output --- Another transaction by user aodi2004 is already in progress for app: s~aodi2004, version: 1. That user can undo the transaction with "appcfg rollback". --- end server output ---

### ISSUE THREAD

**Issue by aodi2004** [cdhigh/KindleEar#365]
aodi2004@aodi2004:~/KeUploader$ sh update.sh

KindleEar uploader v1.3.1 (2015-08-20) by cdhigh

Your custom info :
app id : aodi2004
email : aodi2004@gmail.com
timezone : 8
Correct? (y/n) : y
08:27 PM Host: appengine.google.com
08:27 PM Application: aodi2004; version: 2
08:27 PM Starting update of app: aodi2004, version: 2
08:27 PM Getting current resource limits.
08:27 PM Scanning files on local disk.
08:27 PM Cloning 15 static files.
08:27 PM Cloning 390 application files.
08:27 PM Compilation starting.
08:27 PM Compilation completed.
08:27 PM Starting deployment.
08:27 PM Checking if deployment succeeded.
08:27 PM Deployment successful.
08:27 PM Checking if updated app version is serving.
08:27 PM Completed update of app: aodi2004, version: 2
08:27 PM Application: aodi2004; module: worker; version: 1
08:27 PM Starting update of app: aodi2004, module: worker, version: 1
08:27 PM Getting current resource limits.
08:27 PM Scanning files on local disk.
Error 409: --- begin server output ---
Another transaction by user aodi2004 is already in progress for app: s~aodi2004, version: 1. That user can undo the transaction with "appcfg rollback".
--- end server output ---

这是什么问题啊？

**Comment by cdhigh** [comment]
执行python appcfg.py rollback kindleear/
等回滚后即可正常重新部署。
