### ISSUE TITLE
知乎、喷嚏图卦等不推送

### ISSUE THREAD

**Issue by lqsxianxu** [cdhigh/KindleEar#366]
如题
知乎、喷嚏图卦等不推送
还有我自己添加的：科学松鼠会  http://songshuhui.net/feed?format=xml

**Comment by mingde816** [comment]
我也遇到了同样的情况，nonews持续好几天了。

**Comment by miaowm5** [comment]
喷嚏图卦不推送貌似是因为rss源挂了……

**Comment by lqsxianxu** [comment]
恩，不是nowes
是有的可以推送，有的不行。

**Comment by mingde816** [comment]
![image](https://cloud.githubusercontent.com/assets/7845927/21173909/1d93a292-c215-11e6-86a5-4e2a5b3818a6.png)
如图，知乎不管转发与不转发，喷嚏换了个源也没有，不过另一个用户自定义的书却倒是可以。

**Comment by cdhigh** [comment]
界面上有两个知乎日报，换另外一个即可

**Comment by lqsxianxu** [comment]
知乎转发的，怎么弄呢？那个https://github.com/ohdarling/ZhihuDailyForwarder中的看不大懂的。
另@mingde816 上面说，貌似转发的也不行。

**Comment by lqsxianxu** [comment]
![default](https://cloud.githubusercontent.com/assets/24423089/21178530/e6175ef6-c22a-11e6-8638-f78347f2f407.png)

**Comment by lqsxianxu** [comment]
收到的只有BBC 、爱思想

**Comment by cdhigh** [comment]
直接搭建转发器吧，我搭建的免费的转发器不够用了，经常down。
