### ISSUE TITLE
部分RSS推送失败

### ISSUE THREAD

**Issue by CaesarW** [cdhigh/KindleEar#368]
部分RSS推送失败，想问一下如何查询详细的logs。。。
失败的RSS订阅地址：http://rakuen.thec.me/PixivRss/daily-20
有没有可能是GAE的服务器内存不够排版转换失败？

**Comment by cdhigh** [comment]
在你搭建的网站下方不是有App Engine的链接吗？点击进入后再点左上角的菜单键，再选择“日志”即可。
