### ISSUE TITLE
使用xxx@appid.appspotmail.com推送不成功日志显示Spam mail from :

### ISSUE THREAD

**Issue by grayseagull** [cdhigh/KindleEar#370]
![image](https://cloud.githubusercontent.com/assets/16035182/21668028/f6e19926-d338-11e6-8d31-b6982cc7ba73.png)
显示垃圾邮件应该怎么解决，谢谢

**Comment by cdhigh** [comment]
先添加白名单，FAQ有介绍

**Comment by grayseagull** [comment]
那是已经添加白名单之后显示的，如下图，不知道是哪里错误？

![image](https://cloud.githubusercontent.com/assets/16035182/21674286/f2ffbe58-d367-11e6-9217-64ece84b31f6.png)

然后如果添加“*”到白名单的话就变成显示：
![image](https://cloud.githubusercontent.com/assets/16035182/21674316/197376c4-d368-11e6-89e7-09af619207ec.png)

**Comment by cdhigh** [comment]
这是我的错，在1.23.3（前一个版本）中修改不完备引入了一个错误。
已升级1.23.4，解决此错误。
