### ISSUE TITLE
增加行距 increase line spacing

### ISSUE THREAD

**Issue by Steven630** [cdhigh/KindleEar#372]
您好。现在推送到Kindle上的文件，默认行间距都很小（比亚马逊微信官方send to kindle服务小一些，比大部分亚马逊电子书的行距也小。）能否考虑**增加行间距**，或**让用户自定义**？谢谢。

（Calibre抓取新闻推送的文件行距也太小。）

Hello. The default line spacing for documents sent to Kindle is too small. It is smaller than that of files sent with Amazon's official Wechat "Send to Kindle" service and than that of most Kindle books bought on Amazon. Would you please consider **increasing the line spacing**, or perhaps **allowing users to personalize it**? Thank you. 

(Documents fetched by Calibre have the same problem.)

**Comment by cdhigh** [comment]
我一直没有觉得行间距小，一直都很满意KindleEar的排版，看来你的要求比较高。

如果只是部分书籍的行间距小，可以自己添加一个py文件，然后修改属性 extra_css即可，在里面写标准的CSS代码即可（不要包括style标签）。

如果所有的书籍你都觉得行间距小，可以考虑修改base基类中的extra_css属性，在books/base.py里面，搜索extra_css就可以找到。

你能提出这个问题，估计怎么写CSS的事情应该难不倒你。

**Comment by Steven630** [comment]
谢谢。所有的行间距都小，用亚马逊官方微信推送一篇订阅里也有的文章，对比一下，还是很明显的。以前Calibre就有这个问题，而且很奇怪似乎只有新闻新闻抓取行距小（英语新闻抓取的行距好像没有问题，如Economist就可以）。现在看推送的中文RSS，都把Kindle的行距调成最大，才勉强觉得合适。而平时在亚马逊上买的正版书，一般Kindle行距用最小的，就觉得很合适了。还有能不能让用户设定某些订阅保留图片，有些删除呢？多谢啦。

**Comment by cdhigh** [comment]
可以设定那些订阅保留图片，那些不保留图片，添加一个py文件，设定keep_image属性即可
或使用两个账户，一个订阅需要图片的书籍，一个订阅不需要图片的书籍。

**Comment by Steven630** [comment]
原来如此，谢谢。再问个问题吧。假设订阅了十个RSS，五个中文，五个英文。能否把中文的五个放一本书里，英文的五个放另一本书呢？这样可以分别设置书籍语言。

**Comment by cdhigh** [comment]
两个账户自己分类不就得了

**Comment by Steven630** [comment]
所以一个账户暂时做不到？

**Comment by cdhigh** [comment]
自己写py书籍吧，你要什么都可以

**Comment by Steven630** [comment]
谢谢！
