### ISSUE TITLE
让用户上传单个py文件 Allow Users to Upload Individual py files

### ISSUE THREAD

**Issue by Steven630** [cdhigh/KindleEar#373]
目前自定义订阅只能添加RSS链接，能不能增加个选项，让用户上传py文件呢？这样就不用更新整个KindleEar文件夹了。谢谢！

Personalized subscription only accepts RSS links. Is it possible to add an option which allows users to upload py files so that there would be no need to update the whole KindleEar document again? Thank you!

**Comment by cdhigh** [comment]
你提的这个功能我在实现KindleEar的初期就考虑过了，但是经过一些思考和权衡，最终还是予以否决了，仅提供网页管理简单RSS订阅源的功能，复杂的一律通过py文件的方式实现（重新上传整个应用以更新py文件订阅）。
因时间过久，有些考虑的细节忘了，不过还记得大体的一些纲目：
1. 此应用的目标定位是喜欢折腾的同学，喜欢自己掌控一切的同学。
2. 如果要实现网页管理界面直接上传py文件，则还需要再同时提供封面图/题图上上传功能。
3. 上传后的py文件需要编辑或调试，则可能还需要提供一个网页版的py文件查看器或编辑器。
4. 即使上传py文件正常运行了，但若干时间后可能抓取条件变化了（比如网站改版之类的）导致抓取失败，又面临着一个如何调试和定位的问题。
5. 在网页上上传可直接执行代码（实际上如此）会引入一些可能意料不到的安全性问题。
还有一些其他细节上的考虑，反正这个功能没有想象的那么好，还带来了较大的代码复杂性，
产品的实现过程就是不停的妥协过程，不会什么功能都添加的，主要看产品定位。
能写py文件的，上传一下应用应该也不费多少事，不能写py文件的，则不需要这个功能。

**Comment by Steven630** [comment]
好的，谢谢。有几个以前为Calibre写的代码，想加进去，但开头import什么得修改。改完了又不知道对不对，所以想最好有简单上传的功能，那样马上就能测试，更新起来也方便。毕竟翻墙上传整个应用还是不太稳定。唉。

**Comment by Steven630** [comment]
虽然自学过一点Python，但只是三脚猫。以前写Calibre recipe，也是依样画葫芦。因此很不自信，怕上传了一遍，又有错误。顺便请教一下，除了开头的import from要改，Calibre recipe还要怎么改，才能保证KindleEar也能用？

**Comment by cdhigh** [comment]
如果不是专业python程序员，第一次写出的代码有错基本上是肯定的，如果要自己写py文件，建议下载GAE SDK，在本地运行无错之后再上传为好。

**Comment by cdhigh** [comment]
因为资源限制和精力有限，KindleEar实现的是calibre recipe的一个子集，属性名如果有对应关系的则名字也一样，如果recipe里面的属性你在base.py里面找不到也不支持或需要用其他类似的base.py里面的属性或方法实现。
稍稍阅读base.py文件前面部分即可，其他的地方不需要了解。
内置的书籍不是因为其内容好，而是用于展示py书籍文件的写法的，可以参考
