### ISSUE TITLE
有几个个问题哈，一个是限定文件大小，一个是订阅小说章节更新的…………

### ISSUE THREAD

**Issue by sakuraOnlin** [cdhigh/KindleEar#374]
第一个呢，，文件大小，，比如，坑爹多看貌似就最大20M的推送来着，所以如果订阅列表比较长，每个订阅里又更新了一大堆文章，还加上图片，，最后可能总的文件是大于20M的，所以能不能增加一个指定文件大小，达到文件大小就自动分割成多本书籍？？？

第二个呢，就是可不可分输家？？比如娱乐类的订阅，技术性的订阅，小说类的订阅，这样每本书都是相关书架上的。

第三个呢，，我不知道现在这个系统支不支持文章里出现下一页或下一章节的时候，会不会自动跳转过去接着采集，如果可以的话，那是不是应该也能适用于小说之类的章节性比较强的网站？？这样的话，也能在推送的时候顺便把小说也推送了，毕竟手机上看小说，，看多了眼睛也累啊，，，，酸酸的，，

另外，在问个蛋疼的问题哈，就是这个App能不能在VPS上搭建好一个仿GAE环境后，实现在VPS上跑这个项目？？？这样的话，就不会有辣么多蛋疼的Google配额限制了

**Comment by cdhigh** [comment]
1.  文件大小的事情还是自己把握吧，不要订阅太多。
2. 分书架的事情也是可以自己搞定，分几个账号即可。
3. “自动”获取下一章节理论上是不能做成针对所有网站自动的，即使浏览器的自动翻页插件，也不是自动的，要等你滚动到有分页符的地方才自动加载下一页。如果是抓取网页时一直自动抓取下一页，如何知道什么时候该结束呢（有一百章则自动抓一百章）？
所以还只能针对特定的网站实现“自动”抓下一页，books/Aisixiang.py里面就演示了这种用法。
4. VPS部署的问题，好像有部分容器实现可以在VPS模拟GAE环境，可尝试。或者之前还有人提取了KindleEar核心模块而实现了一个能部署到标准Linux环境的应用（https://github.com/ynhacler/RedKindle），你也可以尝试是否是你需要的。

**Comment by sakuraOnlin** [comment]
1和2可以，4的话我去看了下，好久好久没更新了的说，
3的话，我已经搭建好了一个本地的GAE的环境了，但是不管神马订阅，只要一点点击 现在投递，马上报Bug，不知道神马问题的说，而且我还不是Py的人，，妈蛋，，

`<class 'google.appengine.api.modules.modules.InvalidModuleError'> at /deliver
Python	D:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\api\modules\modules.py in _CheckAsyncResult, line 146
Web	GET http://127.0.0.1:8080/deliver
Traceback (innermost first)

D:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\api\modules\modules.py in _CheckAsyncResult
        raise mapped_error() ...
▶ Local vars
D:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\api\modules\modules.py in _ResultHook
    _CheckAsyncResult(rpc, mapped_errors, []) ...
▶ Local vars
D:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\api\apiproxy_stub_map.py in get_result
      return self.__get_result_hook(self) ...
▶ Local vars
D:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\api\modules\modules.py in get_hostname
                        _ResultHook).get_result() ...
▶ Local vars
D:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\api\taskqueue\taskqueue.py in __host_from_target
                                  instance=instance) ...
▶ Local vars
D:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\api\taskqueue\taskqueue.py in __resolve_hostname_and_target
      host = self.__host_from_target(self.__target) ...
▶ Local vars
D:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\api\taskqueue\taskqueue.py in __init__
    self.__resolve_hostname_and_target() ...
▶ Local vars
D:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\api\taskqueue\taskqueue.py in add
  return Task(*args, **kwargs).add( ...
▶ Local vars
D:\Git\KindleEar\apps\View\Deliver.py in queueit
                params=param,target="worker") ...
▶ Local vars
D:\Git\KindleEar\apps\View\Deliver.py in GET
                    self.queueit(user, book.key().id(), book.separate) ...
▶ Local vars
lib\web\application.py in handle_class
            return tocall(*args) ...
▶ Local vars
lib\web\application.py in _delegate
            return handle_class(cls) ...
▶ Local vars
lib\web\application.py in handle
        return self._delegate(fn, self.fvars, args) ...
▶ Local vars
lib\web\application.py in process
                    return self.handle() ...
▶ Local vars
Request information

INPUT
Variable	Value
u	
'admin'
COOKIES
Variable	Value
webpy_session_id	
'9567dd45e01fdfec5b12d4ddb4d8509f5f08651d'
META
Variable	Value
app_stack	
[<web.application.application instance at 0x0000000006EB5C48>]
fullpath	
u'/deliver?u=admin'
headers	
[]
home	
u'http://127.0.0.1:8080'
homedomain	
u'http://127.0.0.1:8080'
homepath	
u''
host	
u'127.0.0.1:8080'
ip	
u'127.0.0.1'
method	
u'GET'
output	
u''
path	
u'/deliver'
protocol	
u'http'
query	
u'?u=admin'
realhome	
u'http://127.0.0.1:8080'
status	
'200 OK'
ENVIRONMENT
Variable	Value
APPENGINE_RUNTIME	
'python27'
APPLICATION_ID	
'dev~getmykindle'
AUTH_DOMAIN	
'gmail.com'
CURRENT_MODULE_ID	
'default'
CURRENT_VERSION_ID	
'1.537601067982212778'
DATACENTER	
'us1'
DEFAULT_VERSION_HOSTNAME	
'127.0.0.1:8080'
HTTPS	
'off'
HTTP_ACCEPT	
'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
HTTP_ACCEPT_LANGUAGE	
'zh-CN,zh;q=0.8'
HTTP_COOKIE	
'webpy_session_id=9567dd45e01fdfec5b12d4ddb4d8509f5f08651d'
HTTP_DNT	
'1'
HTTP_HOST	
'127.0.0.1:8080'
HTTP_REFERER	
'http://127.0.0.1:8080/setting'
HTTP_UPGRADE_INSECURE_REQUESTS	
'1'
HTTP_USER_AGENT	
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36'
HTTP_X_APPENGINE_COUNTRY	
'ZZ'
INSTANCE_ID	
'712171ddb20343388a81160a20c840ccafc8'
PATH_INFO	
'/deliver'
PATH_TRANSLATED	
'D:\\Git\\KindleEar\\apps\\module_front.pyc'
QUERY_STRING	
'u=admin'
REMOTE_ADDR	
'127.0.0.1'
REQUEST_ID_HASH	
'81CC036E'
REQUEST_LOG_ID	
'6cc2f4eec570cd2d7f2c2f9af8fe85c923fc5dd1ddf186ad'
REQUEST_METHOD	
'GET'
SCRIPT_NAME	
''
SERVER_NAME	
'127.0.0.1'
SERVER_PORT	
'8080'
SERVER_PROTOCOL	
'HTTP/1.1'
SERVER_SOFTWARE	
'Development/2.0'
TZ	
'UTC'
USER_EMAIL	
''
USER_ID	
''
USER_IS_ADMIN	
'0'
USER_NICKNAME	
''
USER_ORGANIZATION	
''
wsgi.errors	
<google.appengine.api.logservice.logservice._LogsStreamBuffer object at 0x0000000006FA1A90>
wsgi.input	
<cStringIO.StringI object at 0x00000000072128B0>
wsgi.multiprocess	
True
wsgi.multithread	
True
wsgi.run_once	
False
wsgi.url_scheme	
'http'
wsgi.version	
(1, 0)
You're seeing this error because you have web.config.debug set to True. Set that to False if you don't want to see this.`


上面的就是报Bug的地方

**Comment by sakuraOnlin** [comment]
自定义书籍的话，面对章节类小说，我可以想到的办法就是读取小说主页里的章节目录，从那立获取到所有章节的URL后，交给上层来处理，我这里需要处理的就是从章节目录那里提取出URL成一个集合就可以，面对小说实际内容页面里的那种分页小说网站，，换一个小说网站不就可以了吗？？尽量找一个不分页的小说网站就行。。


下面这个是我自己写得一个例子

到后面那里就不会弄了，


#!/usr/bin/env python
# -*- coding:utf-8 -*-
""" 处理章节类小说的一个测试示例 """

import re
from bs4 import BeautifulSoup, NavigableString
from base import BaseFeedBook

def getBook():
    return BaBaDuShuHLBTZCJFS

class BaBaDuShuHLBTZCJFS(BaseFeedBook):
    title                 = u'哈利波特之超级法神 -- 88读书网'
    description           = u'哈利波特之超级法神 -- 起点小说'
    language = 'zh-cn'
    feed_encoding = "gbk"
    page_encoding = "gbk"
    deliver_days = []
    fulltext_by_readability = True
    fulltext_by_instapaper = False
    
    feeds = [
            (u'哈利波特之超级法神 章节列表', 'http://www.8dushu.com/xiaoshuo/79/79918'),
           ]
    
    def processtitle(self, title):
		title = title[title.find(',') + 1:]
		title = title[:-6]
                return title
        
    def postprocess(self, content):
        return content.replace('()', '')

	def ParseFeedUrls(self):
		mainurl = 'http://www.economist.com/printedition'
		urls = [] #保存返回的文章列表
		urladded = set()  #用于防止文章重复，不用也可以
		opener = URLOpener(self.host)
		result = opener.open(mainurl)  #下载页面
		if result.status_code != 200:
			self.log.warn('fetch rss failed:%s'%mainurl)
			return []
		content = result.content.decode(self.feed_encoding)	
		print content
			''' 这里开始处理网页里正文网页链接，并放到urls里，处理完毕后返回该urls就行 ，然后就是这里不会弄了，上面的也是我按照那些books里的例子弄出来的'''

        return urls
	      



写得很菜，没办法了，见谅哈

**Comment by sakuraOnlin** [comment]
这个是新写得，但好像推送的时候说没有新消息，，，貌似推送不了
这个本地调试是能获取到完整的网页链接的，而且拼接的网址也正确。
求帮忙瞅瞅是什么问题



#!/usr/bin/env python
# -*- coding:utf-8 -*-
""" 处理章节类小说的一个测试示例 """

import chardet
from lxml import etree
from base import BaseFeedBook
from lib.urlopener import URLOpener

def getBook():
    return BaBaDuShuHLBTZCJFS

def decode_html(html):
    # 解码
    encoding = charset.search(str(html))
    if encoding is not None:
        encoding = encoding.group(1)
    if encoding is None:
        encoding = 'utf-8'
    try:
        html=html.decode(encoding)
    except UnicodeDecodeError:
        encoding= chardet.detect(html)
        if 'GB2312' == encoding.get('encoding').upper():
            try:
                html=html.decode(encoding.get('encoding'))
            except UnicodeDecodeError:  # 有些编码即使是GB2312也要使用gbk来解码
                html=html.decode('gbk')
        else:
            html=html.decode(encoding.get('encoding'))
    return html
	
class BaBaDuShuHLBTZCJFS(BaseFeedBook):
    title                 = u'哈利波特之超级法神 -- 88读书网'
    description           = u'哈利波特之超级法神 -- 起点小说'
    language = 'zh-cn'
    feed_encoding = "gbk"
    page_encoding = "gbk"
    deliver_days = []
    fulltext_by_readability = True
    fulltext_by_instapaper = False
    
    feeds = [
            (u'哈利波特之超级法神最新章节列表', 'http://www.8dushu.com/xiaoshuo/79/79918/'),
           ]
    
    def ParseFeedUrls(self):
	urls = []
	root_url = feeds[0][1]
	opener = URLOpener(self.host, timeout=self.timeout)
        response = opener.open(root_url)
	body = decode_html(response.content)
	root = etree.HTML(body)
	tree = etree.ElementTree(root)
    	i = 1
        while True:
            result = tree.xpath('/html/body/div[8]/ul/li[%d]/a/@href' % i)
            if not result:
                break
	    urls.append(os.path.join(root_url, result[0]))
            i += 1
        return urls

**Comment by cdhigh** [comment]
我现在没有精力去研究你的代码，
不过类似你提供的这个网页，不一定的用书籍来推送嘛，完全可以使用KindleEar的邮件中转服务来替代。
就是发一个邮件到xxx@appid.appspotmail.com
邮件标题就是你希望的书籍标题 
（ 建议在标题后添加一个后缀 !links，让KindleEar忽略文字，只提取链接，比如标题为："哈利波特之超级法神 !links" ）
邮件内容就是你在这个网页 <http://www.8dushu.com/xiaoshuo/79/79918> 上直接用鼠标选择你要推送的章节然后拷贝粘贴到邮件里面即可。

**Comment by sakuraOnlin** [comment]
好吧，，，搞到今天，还是没怎么搞出来，，，，蛋疼的一逼…………
