### ISSUE TITLE
避免重复抓取

### ISSUE THREAD

**Issue by Steven630** [cdhigh/KindleEar#376]
您好，又来请教了。有的RSS**没有日期**，又是**不定期更新**（比如有时候一天更新两三篇，有时候两天才更新一篇）。因为没有日期，KindleEar会抓取RSS列表上所有的文章，有时连续几天的文章都会重复。

有没有办法让KindleEar记住抓取过什么文章，第二天不再抓取？

**举个例子：**
某RSS列表显示最近10篇文章，而无日期信息，因此KindleEar每天都会将表上的十篇全部抓取、投递。

> 昨天投递了1 2 3 4 5 6 7 8 9 10 （1是最新的文章）
> 今天RSS更新了ABC三篇文章，于是列表上有 A B C 1 2 3 4 5 6 7 共十篇文章
> 
> 因此，今天投递时，1-7的文章和昨天重复了。

但是这个RSS又是不定期更新，每次更新有多有少，所以如果设定每隔两三天抓取一次可能会漏掉。

有什么方法解决这个问题吗（即每天都检查，如有文章更新，则抓取更新的，无更新则不抓取）？望不吝赐教。谢谢！

**Comment by sakuraOnlin** [comment]
自定义RSS设置那里不是有个最旧文章设置咩………………你看看设置成一天还会不会有重复的……

**Comment by cdhigh** [comment]
这个很久之前就答复过了，不考虑保存已推送文章列表

**Comment by mangococo** [comment]
你好，请问楼主是怎么解决这个问题的
