### ISSUE TITLE
发现一个抢作者生意的

### ISSUE THREAD

**Issue by corkine** [cdhigh/KindleEar#378]
https://kindlefere.com/post/19.html

五、付费安装

如果你懒得折腾，可以支付一点儿费用，让 Kindle 伴侣帮你安装，你支付的费用将用于 Kindle 伴侣网站的运营。具体方法为：进入“捐助页面”选用页面中提供的任意方式支付 ¥50（你支付的费用不会列在捐助列表中），然后写一封邮件发送到 i@kindlefere.com，邮件必须包含以下内容：

你支付时所用昵称以及付款时间（或截图）
你的 Google (Gmail) 账号和登录密码
在收到你的邮件后，Kindle 伴侣会在 1 天之内为你配置好 KindleEar，并回复一封邮件给你。

注意！你支付的费用仅包含成功安装 KindleEar，并能正常推送 RSS。不包括升级等后期维护，以及在使用过程中如遇到功能性问题，如遇到由于不标准的 RSS 内容导致的推送错误、无法抓取全文等问题。

**Comment by cdhigh** [comment]
呵呵，谢谢提醒，这个是开源软件，采用AGPL授权协议，其他人可以用这个项目来赚钱，只是不能将其本身源码和衍生代码转为闭源，并且需要保留我的版权声明即可。

**Comment by cdhigh** [comment]
说到版权，RedKindle直接使用了KindleEar的核心架构代码和网页抓取代码，但是删掉了原本的版权声明，尽管其项目也是开源的，但是其实也违反了AGPL授权协议。
这个其实还是细心的网友发现并指出的，尽管其作者被发现后承认了，但是没有恢复版权声明，所以...
