### ISSUE TITLE
能否支持短链接？

### ISSUE THREAD

**Issue by liangzhdp** [cdhigh/KindleEar#383]
象推特的短链接，如果可以，会方便很多。

**Comment by cdhigh** [comment]
现在不支持吗？
我不知道短链接的实现机理，不知道是否所有的短链接提供商的实现都是一样的？
如果是HTTP跳转的话，KindleEar应该已经支持。

**Comment by liangzhdp** [comment]
现在不支持啊，比如我以这个为邮件正文：
https://t.co/ap9ITlRc3N
再发到我的kindleEar服务器，然后不会推到kindle的。

**Comment by liangzhdp** [comment]
谢谢。
