### ISSUE TITLE
请教发送邮件为什么要发送到`xx@appid.appspotmail.com`

### ISSUE THREAD

**Issue by chengshuyi** [cdhigh/KindleEar#384]
> 将发到`string@appid.appspotmail.com`的邮件正文转成附件发往kindle邮箱。   --这个过程看不懂

＃＃＃ 第一种想法
1. 先发到`xx@appid.appspotmail.com`
2. `xx@appid.appspotmail.com`接收，转成附件，然后发送到kindle邮箱。

＃＃＃ 第二种想法
为什么不直接转成附件发送到kindle邮箱呢？

期待任何人的解答！！！

**Comment by cdhigh** [comment]
看FAQ有解答

**Comment by chengshuyi** [comment]
@cdhigh 感谢作者的解答！

不过还有几点不太明白：

1.  > Important: Please activate your kindle firstly, and goto Personal Document Settings Page and add c152****3451@gmail.com to 'Approved Personal Document E-mail List'.  - 来自搭建好的rss网站设置

* 这个 Personal Document Settings Page有一个超链接到Amazon,我觉得这个白名单不是应该添加到rss网站的white list里面吗？（因为你没有我这个gmail.com的密码，你不可能用这个邮箱给我的kindle邮箱发送邮件）

* `我觉得这个白名单不是应该添加到rss网站的white list里面` 因为我要用我自己的gmail邮箱给xxx@appid.appspotmail.com这个邮箱发送文件，然后按FAQ所说的处理邮件!link和!article之类的，然后转发到我的kindle邮箱

2. > 默认推送至管理员注册的邮箱，如果要推送至其他用户的邮箱，则使用格式：username__xxx@appid.appspotmail.com。（注意是双下划线） - 来自FAQ

* 这句看不太明白。如果是推送到管理员注册的邮箱，那就是我的gmail吗？但是我的gmail并没有开启转发啊！怎么推送到我的kindle呢？

* 然后其他用户的邮箱，则使用格式：username__xxx@appid.appspotmail.com，为什么格式要是这样的，不应该是用户的kindle邮箱吗？

**Comment by chengshuyi** [comment]
@cdhigh 还有一个问题就是over quota.我看了app engine使用量，发现电子邮件收件人数量 	
11（上限为 10） ，这个email已经超了，这个是怎么回事？

**Comment by cdhigh** [comment]
估计你没有用过Kindle的邮件推送功能，否则不会问那么多这种问题。
1. Kindle推送设置的邮件地址填哪个随你，都可以
2. 先忽略Advance里面的功能吧
3. GAE后台的授权发件人就是你用来搭建这个系统的gmail地址
