### ISSUE TITLE
自己写了book.py文件，通过gcloud shell上传，但是并没有生效

### ISSUE THREAD

**Issue by chengshuyi** [cdhigh/KindleEar#385]
我觉得是不是没有在gae上面没有更新，所以才导致book.py没有生效！

* 下面这个是我本地的gae,可以看出可以正确显示我新加的几本书籍：
![fireshot capture 8 - my subscription - kindle s ear - http___localhost_8080_my](https://cloud.githubusercontent.com/assets/10515655/22721589/a142a3ba-edec-11e6-8286-a7aaae729e32.png)

* 下面这个是我云端的gae,可以看出没有显示我新加的几本书籍：
![fireshot capture 9 - my subscription - kindle s ear - http___kindle-157810 appspot com_my](https://cloud.githubusercontent.com/assets/10515655/22721634/ea328716-edec-11e6-8686-1d3c18b08caa.png)

**Comment by cdhigh** [comment]
增加书籍后重新正常上传即可，不需要重启什么的。
如果上传后看不到，请到后台去看是什么错误导致书籍加载失败，可能本地有一些依赖在网上没有或其他原因。
