### ISSUE TITLE
昨天突然提示no news

### ISSUE THREAD

**Issue by Steven630** [cdhigh/KindleEar#389]
我有两个账号（一个默认的admin，另一个是半年要登陆一次的），都是每天同一时刻推送，一直很正常。昨天却只收到admin的推送，另一个没收到。于是看日志，说no news。但是这个推送有好几个rss源（即好几本书合并一起推送），我也检查过了，昨天rss源都正常更新，不可能无新闻可读取。设置是不显示图片，每次推送平均也就两三百KB，所以也不可能是文件太大。昨天、今天还手动推送了几次，也都提示no news。看了谷歌后台的记录，也无异常，不知道是为什么。我甚至删了几个rss源再推送，还是不行。admin账号昨天、今天都正常。总之百思不得其解，还烦请解惑。多谢！

**Comment by cdhigh** [comment]
1. 看后台记录要看default模块和worker模块的记录。
2. 如果要确定是源的问题还是KindleEar的问题，可以将另一个帐号的订阅源加到admin里面看看结果。
3. no news的原因不单是源没有更新，如果抓取失败也会no news。

**Comment by Steven630** [comment]
谢谢大侠。找到一些错误，是不是NYT RSS的问题？

12:39:55.803
Decoded by buffered encoding(ascii): [http://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/topic/destination/china/rss.xml] (/base/data/home/apps/s~kindle-154912/worker:1.399092238798359665/lib/autodecoder.py:119)

12:39:56.815
Decoded by buffered encoding(ascii): [http://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/topic/destination/south-korea/rss.xml] (/base/data/home/apps/s~kindle-154912/worker:1.399092238798359665/lib/autodecoder.py:119)

12:39:56.934
Decoded by buffered encoding(ascii): [http://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/topic/destination/north-korea/rss.xml] (/base/data/home/apps/s~kindle-154912/worker:1.399092238798359665/lib/autodecoder.py:119)

12:39:57.124
Failure in pushing book 'My Country' : object has no attribute 'title' (/base/data/home/apps/s~kindle-154912/worker:1.399092238798359665/apps/Work/Worker.py:152)

**Comment by cdhigh** [comment]
有一个源的文章格式错误。
用的是哪个版本？
升到最新版本看看？

**Comment by Steven630** [comment]
用的就是最新版。前天突然有问题，以前都正常，也都是那几个源。

**Comment by Steven630** [comment]
解决了，找到了那个源。多谢！

不过一个源出了问题，不能跳过继续推送吗？

**Comment by cdhigh** [comment]
是哪个源？

**Comment by Steven630** [comment]
是用feed43做的源，可能是网页结构改了，发现突然只有链接，没有标题。

对了，发现NYT的文章经常只抓取一半，可能是NYT网站比较奇葩吧，总把文章分成好几段。

**Comment by cdhigh** [comment]
我用feed43做了一个源测试，发现没有问题啊

**Comment by Steven630** [comment]
是源网站的问题，feed43的确没问题。

如果有一个RSS无标题，其他RSS都正常，可否让KindleEar跳过该RSS，继续抓取其他的，并在日志上记录... has no titles, download failed.

**Comment by cdhigh** [comment]
在1.23.5中解决此问题

**Comment by Steven630** [comment]
谢谢，辛苦啦！
