### ISSUE TITLE
可以本地安装Python执行么？

### ISSUE THREAD

**Issue by appleftg** [cdhigh/KindleEar#390]
可以本地安装Python执行么，如win\linux？

**Comment by cdhigh** [comment]
安装GAE SDK即可

**Comment by appleftg** [comment]
谢谢，再请教下，我想把它放在路由器上运行，梅林或者openwrt应该怎么做？如果不行，放在Linux下应怎么做，麻烦指个方向

**Comment by cdhigh** [comment]
估计不行

**Comment by appleftg** [comment]
哦，看到有些gae项目可以，比如xx-net，kindleear离开gae需要哪些环境支持？

**Comment by cdhigh** [comment]
如果其他GAE项目可以，应该KindleEar也可以，除GAE外，没有更多的外部依赖

**Comment by appleftg** [comment]
哦，谢谢
