### ISSUE TITLE
Book 'XXX' import failed : invalid syntax (XXX.py, line 27) 

### ISSUE THREAD

**Issue by Steven630** [cdhigh/KindleEar#391]
Book 'XXX' import failed : invalid syntax (XXX.py, line 27) 
不知道代码什么地方写错了，第27行是remove_classes，27行开始的几行如下：
```
    remove_classes = [
            'articleFooter',
            'articleTools',
            'rfd', 'story-footer-links', 'page-footer',
            'columnGroup singleRule',
            'columnGroup last',
            'columnGroup  last',
            'doubleRule',
            'dottedLine',
            'entry-meta',
            'entry-response module',
            'leftNavTabs',
            'metaFootnote',
            'messages',
            ]
```

其实一开始用的是remove tags，大概如下： 
```
   remove_tags = [
        dict(attrs={'class': [
            'articleFooter',
            'articleTools',
            ]})]
```

可发现推送的文件依然没有移除这些class，于是就添加了remove classes，想不到提示no news，日志显示标题的错误。请教是什么地方写错了。

**Comment by cdhigh** [comment]
可以贴全一点的代码吗

**Comment by Steven630** [comment]
谢谢，1楼的问题已经解决了（后来都不知道怎么好的……）。现在又有个问题：

Failure in pushing book 'XXX' : find() argument after ** must be a mapping, not str

估计是这句代码的问题吧：
`remove_tags_before = ['h1']`

请教一下，想把 **<h1 itemprop="headline" id="headline" class="headline">这里是标题</h1>** 之前的tag都清楚掉，应该怎么写呢，上面那句错在哪里？

还有，这两天为了测试代码，多次上传。后台提示免费资源快用完了，看了一下，主要是“Backend Instance Hours”达到了8多一点，而免费上限是9，请问这个是每天刷新的吗？谢谢。

**Comment by cdhigh** [comment]
代码中不是有注释吗？remove_tags_before/remove_tags_after的格式和keep_only_tags一致。
要写成：
remove_tags_before = [dict(name='h1'),]
或：
remove_tags_before = [{'name':'h1'}]

Instance Hours是每24小时清零的，所以今天用完了，明天又可以继续用。

**Comment by Steven630** [comment]
多谢！明白了，原来本质上是dictionary。

再请教一下，如果在子类里写了fetch_cover的函数抓取图片，能将抓取后的结果设为该书的封面吗`coverfile = fetch_cover (self.link)`？

**Comment by cdhigh** [comment]
在1.23.5添加此需求，可以将coverfile设置为回调函数，此回调函数直接返回图像二进制数据即可。
因为一本书籍只有一个封面，所以回调函数无参数。
也因为这个应用在实例化书籍前就提取了书籍元信息，所以此回调函数需要定义为类函数。
比如：
```

class MyBook(BaseFeedBook):
    ......
    coverfile=MyBook.fetch_cover
    ......
    @classmethod
    def fetch_cover(cls):
        ......
          return img_data

```

**Comment by Steven630** [comment]
十分感谢！初学编程，还有很多不懂的，能否给个读取封面图片实例好让我学习琢磨？麻烦了。

**Comment by cdhigh** [comment]
那等过几天有空再试试

**Comment by Steven630** [comment]
多谢！

**Comment by Steven630** [comment]
再来请教。自己试着写了一个获取封面的，不知道对不对。“返回图像二进制数据”指的是这个吗？还望赐教。
   
```
    @classmethod
    def get_cover_url(cls):
        mainurl = 'http://www.economist.com/printedition'
        opener = URLOpener(self.host, timeout=30)
        result = opener.open(mainurl)
        content = result.content.decode(self.feed_encoding)
        soup = BeautifulSoup(content, "lxml")
        div=soup.find('div', attrs={'class':'print-edition__cover-widget'})
        img = div.find('img', src=True)
        cover = img.get('src')
        if cover.startswith('/'):
            cover = 'http://www.economist.com' + cover
        return cover
```

**Comment by cdhigh** [comment]
不能返回图片网址，要下载图片，然后返回content

**Comment by Steven630** [comment]
百度了好多，不知道对不对。最后两行改成：content = requests.get(cover).content

再return content。是吗？

**Comment by Steven630** [comment]
又写了一个，用urllib。上传后却提示

> name 'Economist' is not defined

```
class Economist(BaseFeedBook):
    ......
    coverfile = Economist.fetch_cover
    ......
    @classmethod
    def fetch_cover(cls):
        mainurl = 'http://www.economist.com/printedition'
        opener = URLOpener(self.host, timeout=90)
        result = opener.open(mainurl)
        content = result.content.decode(self.feed_encoding)
        soup = BeautifulSoup(content, "lxml")
        div=soup.find('div', attrs={'class':'print-edition__cover-widget'})
        img = div.find('img', src=True)
        cover = img.get('src')
        if cover.startswith('/'):
            cover = 'http://www.economist.com' + cover
        data = urllib.urlopen(cover).read()
        return data
```

**Comment by cdhigh** [comment]
把 fetch_cover提到类外面去吧。
然后
coverfile = fetch_cover

**Comment by cdhigh** [comment]
Kindle是有bug，到你写的函数也太那个了。
要去掉classmethod和cls

**Comment by Steven630** [comment]
哎呀，贻笑大方了。谢谢，回去再试试。

**Comment by Steven630** [comment]
刚才试了两次。

第一次是直接去掉classmethod和cls，未改其他地方。结果和昨天一样，没有收到推送，提示错误。

又觉得既然已经把fetch_cover放到类外面了，self.feed_encoding、self.host是不是也不能用了。就改成了：

```
def fetch_cover():
    mainurl = 'http://www.economist.com/printedition'
    opener = URLOpener(None, timeout=90)
#    opener = URLOpener(self.host, timeout=90)
    result = opener.open(mainurl)
    content = result.content.decode('utf-8')
#    content = result.content.decode(self.feed_encoding)
    soup = BeautifulSoup(content, "lxml")
    div=soup.find('div', attrs={'class':'print-edition__cover-widget'})
    img = div.find('img', src=True)
    cover = img.get('src')
    if cover.startswith('/'):
        cover = 'http://www.economist.com' + cover
    data = urllib.urlopen(cover).read()
    return data
```

结果还是不行，错误提示和昨天的**一模一样**。

py在此：https://github.com/Steven630/KindleEar/blob/master/books/EconomistBeta.py

还请指教。多谢！

**Comment by cdhigh** [comment]
我之前的答复说了，KindleEar在这里有bug：一旦获取封面的函数出现异常，则无法准确记录错误原因（导致崩溃），所以首要原因是你的函数还是错的。
明天我升级先修正这个问题。

**Comment by Steven630** [comment]
谢谢。现在很疑惑，不知道是前面解析的问题，还是最后返回的问题。是不是还是最后两步不对呢？

如果图片网址是url，那么:

data = urllib.urlopen(url).read()
        return data

这样对吗？

这些天总来打扰，十分抱歉。

**Comment by cdhigh** [comment]
你用新版本就知道是什么错了

**Comment by Steven630** [comment]
谢谢。用了新版本，获取封面失败，成功推送。可没有找到错误记录，在worker、default的log里都找过了，也搜索关键词“cover”，但是都没发现。

**Comment by cdhigh** [comment]
因为这个功能是未测试的，所以有问题是当然的，我看一下吧。

**Comment by cdhigh** [comment]
升级1.24.2看看吧，
还有你写的文件可以修改一下
1. 类名最好不要和文件名完全一致。
2.图片内容直接返回，不要使用StringIO封装。
3.fetch_cover()加一个参数self，这样：fetch_cover(self)

还有，调试时如果没有看到错误信息，要展开LOGS来看，我直接测试就一堆异常，怎么会看不到异常？

**Comment by Steven630** [comment]
非常感谢！周末再试试。

**Comment by Steven630** [comment]
这次可以了，感激不尽，祝周末愉快。
