### ISSUE TITLE
someting is wrong when i'm using the EarKindle

### ISSUE THREAD

**Issue by DevinHalward** [cdhigh/KindleEar#392]
The content of the Deliver Logs are always shown with "send failed", So, what's happening to this?

**Comment by DevinHalward** [comment]
The content of the Deliver Logs are always shown with "send failed", So, what's happening to this?

**Comment by cdhigh** [comment]
In page "Logs" of [GAE BackEnd](https://console.cloud.google.com/appengine), you can find out what happened actually.

**Comment by DevinHalward** [comment]
09:23:15.802
GET
200
127 B
92.5 s
AppEngine-Google; (+http://code.google.com/appengine)
/worker?u=admin&id=5066549580791808%2C5113123132407808%2C5634472569470976%2C5659313586569216
 0.1.0.2 - - [21/Mar/2017:09:23:15 +0800] "GET /worker?u=admin&id=5066549580791808%2C5113123132407808%2C5634472569470976%2C5659313586569216 HTTP/1.1" 200 127 http://devin-halward.appspot.com/deliver?u=admin "AppEngine-Google; (+http://code.google.com/appengine)" "worker.devin-halward.appspot.com" ms=92541 cpu_ms=62210 cpm_usd=0.000022601466 loading_request=0 instance=00c61b117c4237aba1ccd725c2ba2db7f0175b3b266a101c209b236b204652fe7a948bed87 app_engine_release=1.9.48 trace_id=fbeb4e0fd64bfbc6bf3a85671a66263c
{
 protoPayload: {…}   
 insertId: "58d080e0000542765c5efa26"   
 httpRequest: {…}   
 resource: {…}   
 timestamp: "2017-03-21T01:23:15.802866Z"   
 severity: "WARNING"   
 labels: {…}   
 logName: "projects/devin-halward/logs/appengine.googleapis.com%2Frequest_log"   
 operation: {…}   
}
09:24:32.707
fetch article failed(503):http://www.aisixiang.com/data/103576.html.
09:24:32.708
url [javascript:void();] failed [Invalid request URL: javascript:void();].
09:24:32.708
fetch article failed(535):http://www.aisixiang.com/data/103576.html.
09:24:32.931
fetch article failed(503):http://www.aisixiang.com/data/103617.html.
09:24:33.021
fetch article failed(503):http://www.aisixiang.com/data/103569.html.
09:24:33.112
fetch article failed(503):http://www.aisixiang.com/data/103570.html.
09:24:33.487
fetch article failed(503):http://www.aisixiang.com/data/103634.html.
09:24:33.578
fetch article failed(503):http://www.aisixiang.com/data/103634.html.
09:24:33.668
fetch article failed(503):http://www.aisixiang.com/data/103634.html.
09:24:33.757
fetch article failed(503):http://www.aisixiang.com/data/103634.html.
09:24:33.845
fetch article failed(503):http://www.aisixiang.com/data/103634.html.
09:24:34.005
fetch article failed(503):http://www.aisixiang.com/data/103634.html.
09:24:34.095
fetch article failed(503):http://www.aisixiang.com/data/103634.html.
09:24:34.244
url [javascript:void();] failed [Invalid request URL: javascript:void();].
09:24:34.245
fetch article failed(535):http://www.aisixiang.com/data/103634.html.
09:24:34.560
fetch article failed(503):http://www.aisixiang.com/data/103598.html.
09:24:34.650
fetch article failed(503):http://www.aisixiang.com/data/103568.html.
09:24:35.893
fetch article failed(503):http://www.aisixiang.com/data/103582.html.
09:24:35.975
fetch article failed(503):http://www.aisixiang.com/data/103582.html.
09:24:36.058
fetch article failed(503):http://www.aisixiang.com/data/103582.html.
展开  收起  全部显示  


These are logs about "send failed ",Can anyone could explain what wrong with it? and there exist someting i have to say that all of the logs belong to "wanring" other than "error"

**Comment by cdhigh** [comment]
You need to expand the logs and paste it again.

**Comment by DevinHalward** [comment]
I don't know what exactly logs should i send to show you.can you operate my computer with a telecontrol tool,such as TEAMVIEWER ,in order to figure out what exactly wrong@cdhigh

**Comment by DevinHalward** [comment]
I don't know what exactly logs should i send to show you.can you operate my computer with a telecontrol tool,such as TEAMVIEWER ,in order to figure out what exactly wrong @cdhigh

**Comment by insert0003** [comment]
@DevinHalward If you can give me your google account and password, may be I can update it for you。
After done that， you can modify your password. If you needed just mail me. <zheng00032003@gmail.com>
