### ISSUE TITLE
Remove tags有时不起作用？

### ISSUE THREAD

**Issue by Steven630** [cdhigh/KindleEar#393]
又来讨教了。下面是网页部分源代码

```
<aside class="一串内容" data-component="rich-link" data-link-name="rich-link-1 | 1">
<div class="rich-link tone-news--item ">
    <div class="rich-link__container">
        中间省略
    </div>
</div>
</aside>
```

aside之间显示的是“相关文章”。**为了删除aside，在remove tags里加上了aside。**
```
    remove_tags = [
                   dict(name=[ 'footer', 'aside', 'blockquote'])]
```

可由投递的结果看，还是没有删除。

以前也发现过，同样用`remove_tags = [dict(attrs={'class':[‘名称’]})]`，**Calibre可以去除这些class，但KindleEar不行**，要用`remove_classes = [‘名称’]`才能去除。

keep_only_tags也有这个问题，**而且好像都是涉及class的时候**（即用`keep_only_tags = [dict(attrs={'class':[‘名称’]})]`）才有这个问题。

想请教是哪里出了问题，谢谢。

**Comment by cdhigh** [comment]
写成
    remove_tags = [
                   {'name':'footer'}, {'name';'aside'}, {'name':'blockquote'}]

**Comment by Steven630** [comment]
谢谢~ 试试去
