### ISSUE TITLE
有的图片未抓取

### ISSUE THREAD

**Issue by Steven630** [cdhigh/KindleEar#395]
又来请教高手，是抓取Economist时遇到的问题，**几乎所有图表都没有抓取到**，无论是readability自动抓取还是自己写py都有这个问题。

比如这篇文章：http://www.economist.com/news/china/21719508-can-money-buy-sort-thing-china-spending-billions-make-world-love-it

**同样是正文的图片，也都是figure的标签**，这张保留了（文章中间的合照）：

```
<figure class="blog-post__inline-image blog-post__inline-image--generic">
<img src="http://cdn.static-economist.com/sites/default/files/images/print-edition/20170325_CNP002_0.jpg" alt="" title="" height="335" width="595" class=" blog-post-article-image"><figcaption>Let there be no confusion about Confucius</figcaption>
</figure>
```

<figure class="blog-post__inline-image blog-post__inline-image--generic">
<img src="http://cdn.static-economist.com/sites/default/files/images/print-edition/20170325_CNP002_0.jpg" alt="" title="" height="335" width="595" class=" blog-post-article-image"><figcaption>Let there be no confusion about Confucius</figcaption>
</figure>

**但是这张却没有**（文章中间偏后的图表）：

```
<figure class="blog-post__inline-image blog-post__inline-image--generic blog-post__inline-image--slim">
<img src="http://cdn.static-economist.com/sites/default/files/images/print-edition/20170325_CNC236.png" alt="" title="" height="598" width="580" class=" blog-post-article-image blog-post-article-image__slim">
</figure>
```

<figure class="blog-post__inline-image blog-post__inline-image--generic blog-post__inline-image--slim">
<img src="http://cdn.static-economist.com/sites/default/files/images/print-edition/20170325_CNC236.png" alt="" title="" height="598" width="580" class=" blog-post-article-image blog-post-article-image__slim">
</figure>

百思不得其解，还望指教。谢谢！

**Comment by cdhigh** [comment]
你要看后台有什么错

**Comment by Steven630** [comment]
后台也没有提示出错……太奇怪了，只要是chart（数据图表）就一定不会抓取，但要是一般的照片就没问题。

http://www.economist.com/news/briefing/21719772-worlds-most-important-bilateral-economic-relationship-flourishingand-deep
比如上面这个链接，只有最后一张马云和川普握手的照片，其他中美贸易数据的图表都未抓取。

感觉是不是TE的网站比较特殊？不知道Calibre是怎么都抓取到的。

升级到了1.24，依然没有解决这个问题。

**Comment by cdhigh** [comment]
是不是你写的py文件有问题，我直接将其RSS订阅源地址加到 自定义RSS 里面，是有图表的。

**Comment by Steven630** [comment]
自定义也没有图表啊。

刚才试了，只把http://www.economist.com/rss/briefings_rss.xml 加入自定义RSS。

这样的话，（下周更新前）抓取的文章正好就是3楼的文章（http://www.economist.com/news/briefing/21719772-worlds-most-important-bilateral-economic-relationship-flourishingand-deep）

投递结果依然没有图表，只有最后一张川普和马云握手的照片。 抓取结果和官网网页截图如下：

**官网图表一：**
![default](https://cloud.githubusercontent.com/assets/24987637/24640973/05812ca4-192e-11e7-8e99-5421fe13a128.jpg)

**抓取结果没有图表**
![default](https://cloud.githubusercontent.com/assets/24987637/24640980/14aab38a-192e-11e7-9798-6bda847034d5.jpg)

**官网握手照片：**
![default](https://cloud.githubusercontent.com/assets/24987637/24640997/2ab3501a-192e-11e7-83e3-995254a761c0.jpg)

**照片正常抓取**
![default](https://cloud.githubusercontent.com/assets/24987637/24641001/311d44a6-192e-11e7-8b86-2355c0b79c75.jpg)

**Comment by cdhigh** [comment]
有的没有是因为readability将其认为是广告删除了，抓取图表是没问题的

**Comment by Steven630** [comment]
好像并非如此，这篇文章图表很多，不仅是截图的chart，剩下的几张也都没有，仅有一张两人握手的照片，应该不是当成广告了。

而且我自己写的py也无法获取图表。（TE文章的正文都在article标签中，我在keep only tags里加上了article，remove classes则只去除了社交分享、发表时间、最新文章等内容，不会删掉图片。py去除的标签，也比Calibre的recipe去除的还少。）

况且由1楼也可以看出，无论是照片还是图表，都是在figure的标签里的，穿插在正文中，本质上没有区别。再巧合也不可能一张图表也不剩吧。

下了最新一期TE，也没见一张图表，只有照片。Calibre抓取的文件，至少有六七M，但是KindleEar抓取的只有二点几兆。

这个问题困扰多时，才来讨教。

**Comment by cdhigh** [comment]
你先自己调试，等我有时间再看看。

**Comment by Steven630** [comment]
来汇报一下进展，依然毫无头绪。这周抓取的结果：照片正常，图表或地图一律没有。

比如这篇文章：http://www.economist.com/news/china/21720318-will-xi-jinpings-dream-come-true-plan-build-city-scratch-will-dwarf-new-york

雄安的地图没有。

还是猜测所有png格式的图片都抓取不到。

**Comment by cdhigh** [comment]
既然怀疑是png的原因，但后台又没错，则有可能是其生成的png格式不标准导致格式转换失败。
可以尝试将lib/makeoeb.py中的image_png_to_jpg属性修改为False。
setattr(opts, "image_png_to_jpg", False)

**Comment by Steven630** [comment]
刚才去看了，这个属性原来就是False，唉。

**Comment by cdhigh** [comment]
改成投递epub，投递到你的常用邮箱，然后下载到电脑，后缀改成zip，解压，看文件中是否有png图表

**Comment by Steven630** [comment]
竟然有图表：
[KindleEar(2017-04-09_17-23).zip](https://github.com/cdhigh/KindleEar/files/908094/KindleEar.2017-04-09_17-23.zip)

而且epub文件用Calibre打开也是能看见png图表的。

**Comment by cdhigh** [comment]
calibre默认将png转换为jpg，因为Kindle的阅读器有读取png的bug，可以考虑将KindleEar的image_png_to_jpg设置为Ture

**Comment by Steven630** [comment]
谢谢，下周再看看是否能显示。

**Comment by Steven630** [comment]
可以显示了，非常感谢@cdhigh 帮忙。
