### ISSUE TITLE
如果要移植到其他PYTHON环境，复杂度有多高呢

### ISSUE THREAD

**Issue by skytt** [cdhigh/KindleEar#397]
现在Kindleear很多功能基于gae的模块  如果要脱离gae运行，移植复杂度大吗
谢谢

**Comment by cdhigh** [comment]
移植难度高不高看你的水平、耐心和喜不喜欢折腾，GAE不就是那么回事嘛，对运行于其上的应用来说，它就是一堆各种库的总和。
比如任务队列，数据存储，邮件发送等，你自己找对应的解决方案替换即可，网上都有相应的资源。
