### ISSUE TITLE
object soup invalid

### ISSUE THREAD

**Issue by Steven630** [cdhigh/KindleEar#398]
今天写了个py，投递显示no news，查看日志，说**object soup invalid!** 
HTTP://www.yonhapnews.co.kr/nk/2017/04/08/4807080000AKR20170408050300007.HTML 这个网页可以正常打开。

错误提示：

> object soup invalid!(HTTP://www.yonhapnews.co.kr/nk/2017/04/08/4807080000AKR20170408050300007.HTML) (/base/data/home/apps/s~kindle-154912/worker:1.400407102225353775/books/base.py:724)

其他的链接也都是object soup invalid，**上面只是其中一条。**

**Comment by cdhigh** [comment]
是不是你自己写的preprocess()没有写对？
要判断是不是KindleEar的问题，要先使用内置的“自定义RSS”功能检查，确定是网页问题还是程序问题。

**Comment by Steven630** [comment]
自定义RSS是可以正常抓取的。

py里只加上了keep only、remove、language、extra css等。按道理不应该啊。难道是因为language设成了“ko”？

这是py地址：https://github.com/Steven630/KindleEar/blob/master/books/yonhap.py

麻烦高手看一眼，实在不知道为何出错。

**Comment by cdhigh** [comment]
language不参与任何处理，只影响到在Kindle上查字典时默认调用的字典语种。

这个网站输出的网页真实编码不是其内部声明的utf-8，而是utf-8-sig，在你的py文件中修改编码。

**Comment by Steven630** [comment]
非常感谢，可以正常投递了。自定义RSS是不是默认都自动检测编码，所以没有出错？

发现虽然我语言写的是ko，但推送文件的语言是中文，可能是因为两个韩文的RSS合并成一本书的时候，语言取决于KindleEar“投递语言”的设置。

顺便再请教一下，这次为了增加行距，加入了extra css：
```
    extra_css      = '''
        body { font-size: 1em;  text-align: justify;  line-height: 1.618em}
        .img-info {font-style: italic}
        h1 { font-size: large  }
        '''
```

因为亚马逊的书，很多css行距都是1.618em，所以也这样设置。但发现投递结果和自定义RSS的无区别，行距还是很小。

**Comment by cdhigh** [comment]
那就不知道了，CSS写入html如果无效说明Kindle不认你写的CSS，换其他属性或标签吧

**Comment by Steven630** [comment]
多谢解答！
