### ISSUE TITLE
如直接替换readability，会有副作用吗？

### ISSUE THREAD

**Issue by Steven630** [cdhigh/KindleEar#399]
发现KindleEar用的readability是0.3.0.5版本。

最新版是0.6.2：https://pypi.python.org/pypi/readability-lxml

最新版除了__init__、browser、cleaners、debug、encoding、htmls、readability这几个py，还多了compat的文件夹。

如果直接将lib/readability的文件替换为最新版本，会有副作用吗？

**Comment by cdhigh** [comment]
原readbility对中文的标题抽取实现有些问题，我修改过的，直接替换当然不影响功能，但是抓取到的文章标题可能会很长。

**Comment by Steven630** [comment]
谢谢！
