### ISSUE TITLE
投递日志显示over quota

### ISSUE THREAD

**Issue by hjf9259** [cdhigh/KindleEar#402]
投递日志显示over quota，翻查后台的配额发现电子邮件收件人数量已经超出了每天10个的限额，可是投递的地址只有我自己一个，请问这个要怎么解决呢？
![screenclip](https://cloud.githubusercontent.com/assets/12413215/25211874/0b8ec866-25ba-11e7-920f-d133c8a8eeea.png)
![screenclip2](https://cloud.githubusercontent.com/assets/12413215/25211875/0b97fe4a-25ba-11e7-9c01-09b2637e1f18.png)

**Comment by cdhigh** [comment]
合并推送

**Comment by hjf9259** [comment]
所以就是说每天推送的数量最多是10次啰

**Comment by cdhigh** [comment]
那你就在后台绑定信用卡，然后设置消费限额为0，就可以每天发100个了。

**Comment by hjf9259** [comment]
这样啊…明白了，谢谢
