### ISSUE TITLE
去除正文最后一段

### ISSUE THREAD

**Issue by Steven630** [cdhigh/KindleEar#404]
有的文章会在正文最后一段加上额外信息。

比如：

> (Additional reporting by Michael Martina in Beijing; Linda Sieg in Toyko; Kanupriya Kapoor and Karen Lema in Manila; Sanjeev Miglani in New Delhi; Greg Torode in Hong Kong; Matt Spetalnick and David Brunnstrom in Washington; Editing by Alex Richardson and Frances Kerry)

因为是正文的一部分，并未用特殊的标签，所以无法用remove tags去除。

请教怎么做才能去掉最后一段。觉得应该用postprocess，但不知道何从下手。谢谢！

**Comment by miaowm5** [comment]
Beautiful Soup 的 last-child

**Comment by cdhigh** [comment]
miaowm5的提示是正确的方向，最好用soupprocessex回调，这个回调已经提供BeautifulSoup实例做为输入参数了。
还有如果最后的文字直接嵌入文章内容，没有使用任何标签包装，也需要使用正则表达式或类似的方式去掉之。

**Comment by Steven630** [comment]
@miaowm5 @cdhigh 谢谢二位指明方向！

以我现在的三脚猫功夫，估计还写不出来。会继续学习的，以后再来讨教。
