### ISSUE TITLE
投递日志报wrong SRC_EMAIL

### ISSUE THREAD

**Issue by BG2BKK** [cdhigh/KindleEar#405]
根据FAQ检查了config.py，应该是我的邮件，注册应该没问题，在美亚、中亚也都已经添加。

> 到Gae后台的Settings页面，看看 已经授权的Email列表里面有没有你的发送邮箱地址，如果没有就添加即可。

这个不知道怎么看Setting，就看见我的gmail是owner角色了，请问怎么办呢？

**Comment by cdhigh** [comment]
到

**Comment by cdhigh** [comment]
到http://appengine.google.com/，应用的设置页面的settings页面，你会找到授权发送邮件的email域，将你的email添加进去即可。
