### ISSUE TITLE
一个源为什么最多只有20来条信息？

### ISSUE THREAD

**Issue by Biercenter** [cdhigh/KindleEar#406]
为什么在Feedly订阅cnbeta一天有100来条，在KindleEar上每天只有20来条？哪里需要修改吗？谢谢！

**Comment by cdhigh** [comment]
base.py 
    max_articles_per_feed = 30

限制一个源最多30个。

**Comment by Biercenter** [comment]
@cdhigh 
谢谢！原来是改这里！
