### ISSUE TITLE
利用KindleEar-Uploader无法部署啦

### ISSUE THREAD

**Issue by nietulong** [cdhigh/KindleEar#409]
Error 404: --- begin server output ---
https://developers.google.com/accounts/docs/AuthForInstalledApps
--- end server output ---

**Comment by sirius-fan** [comment]
https://kindlefere.com/post/19.html
你可以参考这个云端部署

**Comment by cdhigh** [comment]
是墙的问题，如果自己搞不定墙的问题确实可以考虑云端部署

**Comment by nietulong** [comment]
应该不是墙的问题，而是认证的问题。要修改一下安装说明啦，云端部署非常好用啊 @cdhigh
