### ISSUE TITLE
关于抓取公众号的问题

### ISSUE THREAD

**Issue by sirius-fan** [cdhigh/KindleEar#410]
我想抓传送门的两个公众号，然后改那个ted渤海湾，不工作；
我又搭建了一个huginn，从搜狗搜索和传送门分别抓取了公众号做成rss，用inoreader订阅没问题，不过用kindleear, 搜狗的rss 就是nonews,  传送们的rss,推送到kindle上显示"我们怀疑你不是真实用户,已对你的访问做了限制“  ||-_-
我然后又在heroku上部署了那个流量转发，改了config.py, 用ZhihuDaily.py做模板改了一个，然后还是不能用，为什么啊

**Comment by cdhigh** [comment]
这是对方反爬虫，可以破解，但我不用公众号，不对此进行技术支持。
推荐用微广场。

**Comment by sirius-fan** [comment]
微广场应该是挂了，有同样问题的同学可以用这个http://www.jintiankansha.me

还有个问题是调试时候 一堆warning，这个pil是第三方模块吗  用pip找不到, 
WARNING  2017-05-22 11:36:46,404 __init__.py:30] Book 'Aisixiang' import failed : No module named PIL
WARNING  2017-05-22 11:36:46,423 __init__.py:30] Book 'Anbang' import failed : No module named PIL
WARNING  2017-05-22 11:36:46,444 __init__.py:30] Book 'D5yuansu' import failed : No module named PIL
WARNING  2017-05-22 11:36:46,467 __init__.py:30] Book 'Dapenti' import failed : No module named PIL
WARNING  2017-05-22 11:36:46,496 __init__.py:30] Book 'Economist' import failed : No module named PIL
WARNING  2017-05-22 11:36:46,516 __init__.py:30] Book 'FolhaDeSaopaulo' import failed : No module named PIL
还有一个error
ERROR    2017-05-22 11:36:46,877 wsgi.py:263]

**Comment by sirius-fan** [comment]
微广场应该是挂了，有同样问题的同学可以用这个http://www.jintiankansha.me

**Comment by mlyksuu** [comment]
传送门那个应该是屏蔽了特定网站，我用FEED43抓传送门失败，用heroku转发就可以成功。然而我并不知道应该如何修改ted渤海湾使用heroku转发_(:з」∠)_ 球赐教

**Comment by mlyksuu** [comment]
有个折衷的办法，我现在在用_(:з」∠)_
LZ不是有huginn嘛，用huginn抓这个网站：https://www.wxwenku.com/，然后得到的RSS给kindleear。
搜狗抓得太多会被ban，只抓一两个的话，应该是能正常推送的？
传送门屏蔽了GAE但没屏蔽heroku，所以制作成全文RSS应该可以但我没试过。
