### ISSUE TITLE
请问这是要开始收费了吗

### ISSUE THREAD

**Issue by blankspace1989** [cdhigh/KindleEar#411]
Dear Google Cloud Source Repositories Customer, 
The General Availability of Cloud Source Repositories (CSR) comes with a new pricing model effective from May 22, 2017.
The following is a list of all of your CSR projects that may be affected by this change: 
•	
From August 21st, 2017, all CSR projects, including projects in the free tier, must have an associated billing account for continued access to CSR repositories. Failure to associate a billing account for the projects containing your CSR repositories will cause you to lose access to them. If you do lose access to your repo due to the lack of a billing account, you’ll have until September 21st, 2017, to add a billing account and regain access. 
More details about the CSR pricing model can be found in the CSR product documentation. 
If you have any questions or concerns, please do not hesitate to contact Google Cloud Support.

这个意思是需要添加一个付款账户吗？

**Comment by blankspace1989** [comment]
今天刚刚收到的邮件

**Comment by cdhigh** [comment]
CSR是另一个项目，不是GAE
