### ISSUE TITLE
设置extra_css无法生效

### ISSUE THREAD

**Issue by richars** [cdhigh/KindleEar#412]
在books下的书里增加
extra_css      = '''
        body { font-size: 1em; text-align: justify;  line-height: 1.618em; margin: 0; }
        p { font-size: 1em; text-align: justify;  line-height: 1.618em; }
        h1 { font-size: large; }
        '''
无论怎么都无法生效，请帮助看看到底是怎么回事呢，是不是有bug啊

**Comment by cdhigh** [comment]
Kindle的阅读器对css的支持并不是很好，有很多属性不支持。
你可以将文件（epub）推送到普通邮箱，然后在电脑上用WinRAR解压。就可以看文件中有没有你写的css了。

**Comment by Steven630** [comment]
这是Calibre的问题，生成old mobi不支持css，生成new mobi却又无法邮箱推送（亚马逊会说格式不对。）我向Calibre作者指出过这个问题，暂时未解决。但KindleGen生成的mobi既包含kf8属性，又能正常推送，在Kindle上生效。希望以后Calibre也能做到。

**Comment by cdhigh** [comment]
@Steven630 估计你说的是不支持独立的CSS文件吧？
我是将CSS写到每个html的head标签里面的，所以如果有部分CSS不生效，则是Kindle阅读器的问题

**Comment by Steven630** [comment]
Kindle大概也有问题，但Calibre应该能解决，Kindlegen做得到，Calibre应该也能做到吧？

https://www.mobileread.com/forums/showthread.php?t=286385

这是我不久前在mobileread论坛发的帖。感觉他们并未完全理解我的意思。

即便用Kindle最小行距，英文行距也不嫌小，也难怪他们不在意，而是提倡用azw3了。

**Comment by richars** [comment]
中文这样看着很难受啊，@cdhigh  你的意思应用生成的是epub，不是mobi
@Steven630 应该不是calibre的问题，使用calibre手工转mobi的时候，可以选择行距，格式选both，amazon也支持推送

**Comment by richars** [comment]
要是能解决行距的问题，这个就完美了

**Comment by richars** [comment]
我们这个应用中生成并推送出去的mobi文件是old还是both啊

**Comment by richars** [comment]
生成的epub用calibre看了，加上去的extra_css在html中都有，格式没问题，效果很好。
那么问题因该是出在生成mobi上了。

**Comment by richars** [comment]
生成的mobi用caibre看了，加上去的extra_css都没发挥作用。
我们应用中生成的mobi用的是啥格式啊，old or both？

**Comment by Steven630** [comment]
both虽然可以推送，但行距还是不生效的，我试过（也许是经过亚马逊云推送，属性就改变了？），而且both比old大一倍（因为both其实就是同时包含old和new，至于识别与否，还得看机器，要是只认old，和直接推送old就无区别了）。KindleEar应该默认的是old。

就是不明白，为什么Kindlegen生成的mobi能完美支持高级格式，而且也能推送。现在我实验的结果，Calibre生成的mobi，能推送的必然格式不生效，格式生效的又推送不了。

**Comment by richars** [comment]
恩，刚才完整地测试了一下：
用calibre手工转换成mobi，在calibre里指定行高（140%），结果如下：
1、用生成的epub用calibre手工转换成mobi，无论是选both还是old，css都没有起作用；
2、把epub里的html提取出来，用calibre手工转换成mobi，无论是选both还是old，css都没有起作用；
3、用一个普通的html文件，例如以下这个文件，用calibre手工转换成mobi，无论是选both还是old，calibre中指定的设置都生效了。

有点奇怪。

**Comment by richars** [comment]
@cdhigh @Steven630   “就是不明白，为什么Kindlegen生成的mobi能完美支持高级格式，而且也能推送。现在我实验的结果，Calibre生成的mobi，能推送的必然格式不生效，格式生效的又推送不了。”

不是这样的，普通的html文件，使用calibre转换，选择 最小行高140%，both，可以推送，也可以实现预期的行间距效果，效果很不错。

**Comment by richars** [comment]
比较了下epub里提取出来的html和普通的html，差别在epub里的内容是  <p class="paragraph"> 内容 </p>
普通html里的内容是<p>   内容  </p>
猜想是calibre把extra_css里定义的p  和 p class处理成两个东西了，所以格式无法生效。

**Comment by richars** [comment]
对css不熟悉，这两个的区别在哪里啊

**Comment by richars** [comment]
在extra_css 中增加了一个  p.paragraph { font-size: 1em; text-align: justify;  line-height: 1.618em; }  
1、生成的epub中的html文件会生效； 但应用生成的mobi还是无效；
2、将生成的epub，用calibre手工转换成mobi，在calibre里指定行高（140%，both），转换后extra_css无效；
3、将epub中的html文件提取出来， 用calibre手工转换成mobi，在calibre里指定行高（140%，both）， 转换后extra_css生效；  如果用old，转换后格式无效；

现在的问题：
1、应用生成的过程中，calibre是直接将html转成mobi，还是先生成epub，再生成mobi？
2、calibre在生成mobi时，选择的是old？还是both？

**Comment by cdhigh** [comment]
KindleEar直接将HTML转换成old的mobi，无法使用both格式，因为在GAE上无法压缩文件，所以文件太大会导致推送失败，
就如Steven630所说，要等Calibre修正此问题

**Comment by richars** [comment]
可以直接使用both模式转换不，看了下，我们用的calibre应该是老版本吧，好像old确实无法生效

**Comment by cdhigh** [comment]
不可以，只有old才可以生成期刊格式，
除非大修改Calibre

**Comment by richars** [comment]
能不能换种思路，不要通过css来控制，直接修改mobi生成的参数，把格式加上去呢

**Comment by Steven630** [comment]
> 另外，单独拿出推送的英文书来比较，实际上和中文书是一样的格式，只是由于字体不一样，所以显示效果不一样而已。

对啊。正是这个缘故，所以这个问题少有人重视。Calibre的作者（还有其他贡献者）大都母语是英语，看的英文，也不会觉得行距小。

**Comment by Steven630** [comment]
我该怎么向Calibre作者描述这个问题，才能既让他明白我的意思，又能对症下药，加以修改？

**Comment by richars** [comment]
@Steven630 
就问在生成mobi的时候，可以不可直接定义不同部分的line_height
我昨天试着改了下lib里的html.css，貌似也没作用。

**Comment by richars** [comment]
@cdhigh 为什么说both不支持期刊格式呢。

**Comment by cdhigh** [comment]
这是Amazon的限制

**Comment by richars** [comment]
@cdhigh 能不能换种思路，不要通过css来控制，直接修改mobi生成的参数，把格式加上去呢

**Comment by Steven630** [comment]
不知道是不是Calibre更新了，這兩天測試了兩本書，推送到Kindle，行距都生效了。

將一般的mobi用Calibre仍然轉換為mobi，參數里minimum line height設置為150（默認為120），輸出格式選both，生成的文件投遞成功，行距生效。

用的是最新版本的Calibre，是不是KindleEAR更新一下Calibre的組件，然後選擇both，也能達到效果呢？

**Comment by Steven630** [comment]
不是150，是150％（默認120％）。

**Comment by richars** [comment]
赞成，请@cdhigh看看有没有可能进行更新。
