### ISSUE TITLE
不知道啥时候才可以支持国内的SAE、BAE呀？GAE必须翻墙！

### ISSUE THREAD

**Issue by mingyue2017** [cdhigh/KindleEar#413]
说实话，现在用GAE部署倒是很方便，就是GAE被“墙”用起来真的是太有局限性了！

**Comment by richars** [comment]
^_^，估计作者不会去折腾修改这个了。
上gae是基本技能。

**Comment by cdhigh** [comment]
从来就没有移植到SAE等的想法，所以不用等了

**Comment by linhua55** [comment]
可以用 xxnet 扫描到的 IP 来访问GAE。 或直接使用xxnet代理

2017-06-11 15:47 GMT+08:00 cdhigh <notifications@github.com>:
