### ISSUE TITLE
无法获取feed43产生的rss全文

### ISSUE THREAD

**Issue by nbcc** [cdhigh/KindleEar#414]
例子：http://feed43.com/bitcoin-daily.xml

是通过feed43 抓取生成的 rss, 希望可以支持全文

**Comment by cdhigh** [comment]
本来就支持全文，你的这个订阅源无效。

**Comment by nbcc** [comment]
你好，能解释一下吗？是 feed43 生成的 rss 格式不标准，所以无法用接口获取全文吗？

2017-06-13 7:26 GMT+08:00 cdhigh <notifications@github.com>:

**Comment by cdhigh** [comment]
在浏览器里面输入订阅源url不就知道了吗？

**Comment by nbcc** [comment]
这个url现在无法访问了；可以用其他的url做测试：http://feed43.com/damingyaonie.xml

2017-06-15 17:24 GMT+08:00 cdhigh <notifications@github.com>:

**Comment by nbcc** [comment]
访问全文这个功能在 feed43 生成的  rss 上不生效~

在 2017年6月16日 下午1:18，Yu-kun Li <nbcc.zz@gmail.com>写道：

**Comment by Biercenter** [comment]
在添加的 RSS 地址后面添加一个参数 ?format=xml 或 ?fmt=xml 就可以了

**Comment by cdhigh** [comment]
楼上正解，除feed43外，Feedburner生成的订阅源也要如此处理，Feedburner在FAQ里面有描述。

**Comment by Steven630** [comment]
记得后面不加也可以，关键是前面加上www.

**Comment by nbcc** [comment]
为了减少大家的麻烦。我另开了一个 新 kindleaer 服务，使用链接
http://www.feed43.com/damingyaonie.xml?format=xml 仍然无法获取全文

ps，uploader 的脚本只要更新了最新版的 google_appengine appcfg 就可以使用了。windows的 shell 真是难用

2017-06-17 9:12 GMT+08:00 Steven630 <notifications@github.com>:

**Comment by nbcc** [comment]
各位抱歉，周末有时间看了一下代码；原来 isfulltext 是为了节省资源，如果rss已经是全文则***的一个判断；
我理解成如果需要获取全文，则选择这个选项（被狗耳朵误导了）；@cdhigh

在 2017年6月17日 下午10:53，Yu-kun Li <nbcc.zz@gmail.com>写道：
