### ISSUE TITLE
使用gcloud部署

### ISSUE THREAD

**Issue by btyh17mxy** [cdhigh/KindleEar#415]
我尝试使用gcloud部署了一下, 发现需要把app.yaml中的application和version删掉, 然后执行下面命令
gcloud app deploy app.yaml index.yaml cron.yaml queue.yaml --project <PROJECTID>

**Comment by cdhigh** [comment]
可能吧，不同平台有差异是很正常的。
不过gcloud不是免费的，只提供免费试用，用他部署KindleEar的少，用KindleEar大多数是因为GAE的免费（限额）策略。
