### ISSUE TITLE
漫画模式

### ISSUE THREAD

**Issue by insert0003** [cdhigh/KindleEar#416]
我添加了几个漫画书籍，比如下面的海贼王的漫画
https://github.com/insert0003/zkindlerss/blob/master/books/onepiece.py
增加了一个漫画更新话的页面，用于设置最新话数。
https://github.com/insert0003/zkindlerss/blob/master/templates/updatelogs.html
目前利用我的github的代码可以正常推送，但是有几个问题我一直在调查无法解决，如果您有时间可以帮忙看看吗？

1 图片无法显示全屏。
  我想添加如下css，利用这个css可以显示全屏。但是不知道怎么加。
   singlePage {
   position: absolute;
   width:  auto;
   height: 100%;
   margin: auto;
   text-align:center;
   }

2 中间有空白页
   找不到具体的原因，生成出来的文件，每隔一个图片有个空白页。
   为了解决这个问题，不得不把所有的图片放到同一页，虽然解决了空白问题，但是问题1就永远无法解决了。
lib/calibre/ebooks/mobi/writer2/serializer.py
```
  @@ -305,10 +305,10 @@
          tag = prefixname(elem.tag, nsrmap)
          # Previous layers take care of @name
          id_ = elem.attrib.pop('id', None)
+        self.logger.warn(tag)
+        if tag == "mbp:pagebreak":
+            return

```

**Comment by cdhigh** [comment]
这个话题有点意思，漫画是我从来没有考虑过的，除了识字前看过连环画，从记忆开始我就没记得我有看过其他什么漫画类的。
曾经我有一个最好的哥们很喜欢火影忍者，想让我也喜欢，但我根本看不下去连续5页。
发发随想，
不过我觉得解决这个问题应该不难，下载一部你觉得制作比较好的漫画书，然后使用kindleunpack之类的软件将其反编译为html，再分析其文档结构即可。
如果有结论，不妨将修改提交一个pull request，让其他喜欢漫画的朋友也能在Kindle上享受漫画的乐趣。

**Comment by insert0003** [comment]
其实我已经对比过了，如下面的附件，发现网站下载的是KF8 标准的，而我自己的默认mobi模式。
另外我把我的修改做了pull request了，你看看。其中针对lib/calibre/ebooks/mobi/writer2/serializer.py的修改是为了不显示空白页的暂时对策，有可能会影响其他的书籍。可以暂时不合并，但是会有空白页。

我自己导出的 全职猎人(2017-07-20_10-41).mobi 
[全职猎人(2017-07-20_10-41).mobi.zip](https://github.com/cdhigh/KindleEar/files/1161117/2017-07-20_10-41.mobi.zip)
某网站下载的 [Vol.moe][獵人HUNTERxHUNTER]第361-362話.mobi
[[Vol.moe][獵人HUNTERxHUNTER]第361-362話.mobi.zip](https://github.com/cdhigh/KindleEar/files/1161119/Vol.moe.HUNTERxHUNTER.361-362.mobi.zip)

**Comment by cdhigh** [comment]
kf8不能推送，再找找有没有老mobi格式的漫画书，Google搜索年份用的是两个点号，因为kf8是2011年推出的，比如可以这样搜索：
你要的漫画书籍 kindle 2009.. 2011
你要的漫画书籍 mobi 2009.. 2011
你要的漫画书籍 filetype:mobi 2009.. 2011

**Comment by insert0003** [comment]
你看一下这个网站<http://vol.moe/>向kindle推送的文件，推送到kindle生成的文件是azw3, 里面的结构是HDImages，mobi7，mobi8三个文件夹。
而我自己制作出来的mobi文件，推送到kindle里生成的文件是pobi，结构是HDImages，mobi7。
从网上查到的，HDImages，mobi7，mobi8结构的应该是kf8的，应该是可以推送的。我的kindle一直可以收到。

**Comment by cdhigh** [comment]
不知道他是怎么做到的，你可以试一下用Calibre生成一个混合模式的azw3，然后推送，可以发现，无法推送成功

**Comment by insert0003** [comment]
今天试了一天，使用calibre的软件生成的全屏漫画对比了。最后生成相同的html，推送也无法全屏。
后来不得不怀疑是旧格式的问题，所以尝试用混合推送，推送失败。
发现混合格式推送不是亚马逊的问题，是代码有些错误。
我的能力有限，不知道如何完美修改，所以暂时改了一版临时版本，推送以后发现全屏了。
稍后把临时版本的代码给你pull一下，抛砖引玉吧，你看看怎么改比较合适。

**Comment by insert0003** [comment]
这个问题可以关闭，或者合并到425上吧，作为遗留的问题。
