### ISSUE TITLE
rss订阅的新闻有重复的

### ISSUE THREAD

**Issue by CDF5B9FAC9AD** [cdhigh/KindleEar#418]
rss订阅的新闻有重复的，已经设置为最旧文章为一天。请问怎么解决呀？

**Comment by CDF5B9FAC9AD** [comment]
顺便请问在网页中添加的rss订阅是哪个文件呀？

**Comment by cdhigh** [comment]
新闻有重复可能是RSS源不规范，没有时间信息或时间信息错误。
自定义RSS直接保存到数据库的，可以看apps/work/worker.py

**Comment by CDF5B9FAC9AD** [comment]
thx  重复是指，今天的新闻与昨天的新闻有重复……

**Comment by cdhigh** [comment]
不打算修复
