### ISSUE TITLE
维基百科历史上的今天RSS无法抓取

### ISSUE THREAD

**Issue by frankline-DPRC** [cdhigh/KindleEar#420]
http://zh.wikipedia.org/w/api.php?action=featuredfeed&feed=onthisday&feedformat=atom

改成https也没用  发到设备上就一个标题下面是no data available 和链接的二维码 但是用rss阅读器却可以收到推送

**Comment by frankline-DPRC** [comment]
I tried to change it into https ,but it does not work. The article in my kindle is just with a title and "no data available" and an QR code. Yet, I can see the whole article in a rss reader(The Old Reader)

**Comment by cdhigh** [comment]
一般出现这种情况是因为网站使用ajax更新内容，现在没有精力去调试和适配，不过我看这个订阅源里面已经有全文信息了，所以勾选isfulltext即可。
