### ISSUE TITLE
怎样修改设置并生效？

### ISSUE THREAD

**Issue by LastFlydragon** [cdhigh/KindleEar#423]
Readme 里面说修改config.py之后要运行命令：
c:\python27\python.exe appcfg.py update ...
是不是旧版本啊？
我只找到了config.py, 用find也没有找到appcfg.py呀。
想确认一下，已经部署好并运行两天了，今天改了COLOR_TO_GRAY到False，然后是不是要运行以下命令就好了：
python config.py update ~/KindleEar/app.yaml ~/KindleEar/module-worker.yaml
python config.py update ~/KindleEar
没有运行这两步，现在好像还是黑白图片。

**Comment by LastFlydragon** [comment]
另外，以后每次运行过uploader.sh是不是都要重新修改config.py并运行命令？就是说会不会覆盖已有设置？
一堆小白问题，先谢过了！  ：）

**Comment by LastFlydragon** [comment]
我找到了，似乎只要运行upload.sh就可以了？
不过我运行之后先报了个错：
KindleEar uploader v1.3 (2015-08-20) by cdhigh
Cant found folder 'KindleEar'! Please download it from github firstly.
后面好像就更新index啥的了，这个没问题吧？

**Comment by cdhigh** [comment]
下载下来的KindleEar要放到uploader目录下才行

**Comment by LastFlydragon** [comment]
我是用uploader自动部署的，似乎所有子目录包括uploader.sh全都自动放进home目录也就是“~/”里面了，没有uploader目录哇。不过虽然报了这个错，运行过upload.sh后修改的参数倒是生效了。
现在一切运行正常，哦耶！
