### ISSUE TITLE
那个漫画模式看到的漫画四周有空白

### ISSUE THREAD

**Issue by suoba** [cdhigh/KindleEar#425]
应该是没有全屏，四边有空白，导致正文里的有些文字太小，无法阅读。
如图：
[http://picgur.org/images/2017/08/19/2017-08-19_19-30-47.png](url)

**Comment by cdhigh** [comment]
漫画模式是 @insert0003 的代码贡献，才第一版，能用，但还是不完美版，
而我没有精力去调试，有待 @insert0003 或其他贡献者继续优化完善。

**Comment by insert0003** [comment]
不好意思，我也很想解决这个问题。研究了很长时间也没有解决。
现在的状态是，在meta数据里添加下面的内容就可以实现全屏。
但是问题是，如果这个书籍只有一张图片，显示没有问题。
如果有多张图片，会把多张图片垂直合并成一张，显示在一个屏幕里，变成一个细长条。
我认为应该是书籍的html构成的问题，但是不知道该如何修改。
<meta name="RegionMagnification" content="false" />
<meta name="book-type" content="comic" />
<meta name="zero-gutter" content="true" />
<meta name="zero-margin" content="true" />
<meta name="primary-writing-mode" content="horizontal-lr" />
<meta name="fixed-layout" content="true" />
<meta name="orientation-lock" content="portrait" />
<meta name="original-resolution" content="1072x1448" />

**Comment by insert0003** [comment]
@suoba 全屏做出来了，需要在calibre的库里修改，这么做的话，同时订阅的其他的书籍也会变成全屏。由于影响较大，所以我不打算合并到KindleEar里了。如果你需要的话，看我的Github里有代码可以用。
https://github.com/insert0003/KindleEar
这个master的代码是全屏修改完的。
@cdhigh 为了达到全屏，在lib/calibre/ebooks/mobi/writer8/exth.py里，添加了全屏用的metadata。针对漫画来说，最好的效果是下面的组合。
1 setattr(opts, "mobi_file_type", 'both')
2 pubtype='book:book:KindleEar'):
3 全屏的meta数据
4 TOC关闭
这几项的更改以后，同时订阅的其他书籍都会有变化，
而且，最近看到很多问题，都是both下的排版问题，我认为很难整合杂志和漫画的代码。

**Comment by insert0003** [comment]
![webwxgetmsgimg](https://user-images.githubusercontent.com/11204704/29876622-4ce1f474-8dd8-11e7-8c79-f43572b7d0ba.jpg)
效果如图，我认为是比较完美的显示了。

**Comment by suoba** [comment]
@insert0003
其它书籍全屏后是什么情况，有预览图没？毕竟还是看书为主，如果不能接受，我就不折腾漫画了。

**Comment by insert0003** [comment]
我觉得可以，当然你自己也看看吧。
我是单独推送的，没有合并。
![Image](http://i.imgur.com/WyixM5S.jpg)

**Comment by insert0003** [comment]
我自己没有看书，刚刚为了截图订阅了爱思想，貌似文字没有全屏，只有漫画全屏了。

**Comment by cdhigh** [comment]
如果实在不能兼顾，可以考虑在web界面上添加一个“漫画模式”的选项。

**Comment by insert0003** [comment]
你的意思是，有个漫画模式选项，允许用户选择。当漫画模式选中时，更改为如下选项。
从上面的截图看，漫画模式下书籍也可以看。所以我觉得可以，但是你的代码我还没有完全看明白，不知道怎么加。
1 setattr(opts, "mobi_file_type", 'both')
2 pubtype='book:book:KindleEar'):
3 全屏的meta数据
4 TOC关闭

**Comment by cdhigh** [comment]
好的，我来改一下

**Comment by insert0003** [comment]
@cdhigh 辛苦你了。
我还有个想法，跟你稍微讨论一下。
漫画使用的书籍，结构都是一样的。可不可以像自定义RSS那样，加个自定义漫画。
只要在自定义漫画加上对应的漫画网址，就可以推送那个网址的漫画。
当然漫画页面的结构应该是目前我一直使用的那个网站的。
这样的好处就是，新加漫画不需要重新上传书籍文件。如何实现，稍微指点指点我，该去参照哪块的代码。

**Comment by cdhigh** [comment]
总体来说，因为没有标准，直接抓取网站很难实现长期有效，我以前写的一些内置书籍都陆续失效了，因为网站（特别是运营有效的网站）会不停进化，不停改版。

所以直接抓取网站的需求是必须要在python文件中写明抓取逻辑的，这样才能应付对应网站的未来修改。

**Comment by insert0003** [comment]
我明白你的意思，其实我是想用在我自己的GAE上，比较方便，如果网站变了我可以改。所以想问问你，看其中的哪段代码可以报销自定义Rss做一个自定义漫画。

**Comment by cdhigh** [comment]
实现这个其实很简单，还是正常添加自定义RSS，然后推送时在worker里面判断URL，如果是那个漫画网站就创建一个你写的漫画基类实例（而不是默认基类），就行了。
或者等我完成了修改这个版本后给你一段示范代码。

**Comment by insert0003** [comment]
OK，多谢啦

**Comment by cdhigh** [comment]
@insert0003 我用你已经pullrequest的代码推送漫画没有全屏，但是正常观看，用你的github仓库里面的代码推送则所有图片都挤在一页内，你可以将你的推送成功的（漫画全屏）代码发我一份吗？<cdhigh@sohu.com>

**Comment by insert0003** [comment]
https://github.com/insert0003/KindleEar
我的这个的master是全屏的，因为我觉得没法直接merge，所以没有做pullrequest

**Comment by insert0003** [comment]
base.py里面，comic的类修改了。
`-	if len(imgs)> 0:
 -            tmphtml = '<html><head><title>Picture</title></head><body><img src="'+ '"/><img src="'.join(imgs) + '"/></body></html>'
 -            yield (self.title, url, ftitle, tmphtml, '', None)
 +            tmphtml = '<html><head><title>Picture</title></head><body><img src="%s" /></body></html>' % fnimg
 +            yield (fnimg.split(".")[0], url, ftitle, tmphtml, '', None)
  
      def updatelog(self, name, count):
          try:
 @@ -1431,7 +1430,7 @@ def GetComicUrls(self, href):
                      body = pageresult.content.decode(self.feed_encoding, 'ignore')
                      sp = BeautifulSoup(body, "lxml")
                      mhpic = sp.find("img", {"oncontextmenu": 'return false'}).get("src")
 -                    urls.append( (self.title, mh.text, mhpic, None))
 +                    urls.append( (self.title, mh.text.replace(' ', ''), mhpic, None))`

**Comment by insert0003** [comment]
这个改动是把单张图片，作为一个section，这样就不会挤在一页了。
![default](https://user-images.githubusercontent.com/11204704/30116003-44dead2e-9357-11e7-9da1-b818778a3c18.PNG)

**Comment by cdhigh** [comment]
现在明白了，相当取巧的方法，相当于每篇文章就一个图片。
但是这样的话，如果一本书里面有几个漫画的话，能选择看哪个吗？就是说目录情况如何？

**Comment by insert0003** [comment]
我看了用kindle gen做的漫画，结构就是这样的，书的目录就是单页了，没办法区分不同的书籍。

**Comment by cdhigh** [comment]
或者如果这本漫画书和其他比如新闻类的书籍合并推送到话，还有正常的目录吗（不是期刊目录，只要能选目录即可）

**Comment by insert0003** [comment]
我测试的结果，合并推送有目录页，但是漫画的目录跟漫画页数一样。选择book类型的时候，目录点击没有跳转效果。如果我测试的是正确的话，选择book后，应该不要添加toc和目录。

**Comment by insert0003** [comment]
还有选择book类型，最好不好合并推送。

**Comment by cdhigh** [comment]
有点不完美，不过将就了，我改改看

**Comment by insert0003** [comment]
我尽力了，哈哈

**Comment by cdhigh** [comment]
已升级1.25。
所有继承自BaseComicBook的书籍都将自动应用漫画模式，并且会自动单独推送。
还有你写的UpdateLog已经重命名为LastDelivered，因为UpdateLog感觉有点歧义，此数据项将来不单用在漫画上，还可以用在其他期刊的推送上。
“漫画日志”移到了“投递日志”内，如果存在，则在下部显示。

**Comment by insert0003** [comment]
这样的结构感觉比较好，不用考虑漫画和杂志的设置了。
关于漫画的改动我看完了，其他部分有点多，没看完，辛苦了。

**Comment by cdhigh** [comment]
库模块我更新了几个，只是更新，和本次修改无关

**Comment by insert0003** [comment]
上回跟你提过的通过自定义RSS的形式支持漫画，我做出来了。做了一个pullrequest，你看看要不要合并。
这个issue应该没问题，可以关闭了吧。
