### ISSUE TITLE
Kindle paperwrite无法正常显示期刊排版

### ISSUE THREAD

**Issue by CnTteng** [cdhigh/KindleEar#426]
无法显示期刊排版是怎么回事呢？

**Comment by CnTteng** [comment]
不仅是paper white 所有的kindle都是

**Comment by cdhigh** [comment]
以前可以吗？
如果是刚创建的，有可能 @insert0003 的这次pull request修改导致，因为我也没有测试此版本，精力有限，直接合入的。
如果你会用git（或者直接使用github 客户端），不妨获取前一个版本来创建。

**Comment by insert0003** [comment]
sorry，原谅我的无知。这个问题的现象是什么呢，我不太懂“无法显示期刊排版”的具体含义，能发一个图片吗？

**Comment by insert0003** [comment]
@cdhigh 默认改成期刊比较好吧？

**Comment by cdhigh** [comment]
我已经合并了 @insert0003 的pullrequest，可以测试一下是否已经修正

**Comment by CnTteng** [comment]
已正常谢谢
