### ISSUE TITLE
Want to recieve only part of rss feeds

### ISSUE THREAD

**Issue by local-boy** [cdhigh/KindleEar#427]
I want to receive only '[CDATA[National]] category'  feeds from http://www.thehindu.com/news/national/?service=rss . Is it possible by making my own book? I assume keep_only_tags in base file could be used for the same but have no idea of HTML. Can anybody pls guide for this please. Thanx in advance!

**Comment by cdhigh** [comment]
Yes, you can.
Create a subclass of BaseFeedBook, then copy and modify the function ParseFeedUrls(), add some statements for example:
```
if hasattr(e, 'category') and e.category != 'National':
     continue
```

**Comment by local-boy** [comment]
Thanks @cdhigh for the wonderfull program and quick guidance. I added following in the basefile and it's working fine.

`if url == 'http://www.thehindu.com/news/national/?service=rss':
          if hasattr(e, 'category') and e.category != 'National':
                            continue`
