### ISSUE TITLE
目录字体问题？

### ISSUE THREAD

**Issue by bh3nvn** [cdhigh/KindleEar#428]
目录有些字体不美观，在哪里修改？尤其“门”字，显示成“冂”字在上边加一竖

**Comment by bh3nvn** [comment]
https://github.com/bh3nvn/KindleEar/blob/master/%E6%97%A0%E6%A0%87%E9%A2%98.jpg

**Comment by bh3nvn** [comment]
像这样：https://github.com/bh3nvn/KindleEar/blob/master/%E6%97%A0%E6%A0%87%E9%A2%98.jpg

**Comment by cdhigh** [comment]
KindleEar没有修改和内嵌字体，是网页本身的设定，或者你的Kindle没有特定的字体，而使用的某个特定字体

**Comment by cdhigh** [comment]
这个问题已经定位，正在修改，是新的kf8格式问题

**Comment by bh3nvn** [comment]
好像就是最近更新了才这样，之前没事。

**Comment by cdhigh** [comment]
已在1.25中修正

**Comment by bh3nvn** [comment]
升级到1.25已经恢复正常，谢谢~
