### ISSUE TITLE
最新版推送的文件排版和字体显示有问题

### ISSUE THREAD

**Issue by dubu45** [cdhigh/KindleEar#431]
之前一直用的是老版，17年6月份部署的，一切正常；
最近8月27号，在老版的GAE上上传了最新版本，成功部署。
然后28号收到的推送排版和字体都有一些问题，今天再次尝试，问题依旧。
如图所示，以“门”字为例，老版和新版的显示明显不同，排版就不用说了。
kindle环境同为KP3，最新版固件。

旧版排版：
![default](https://user-images.githubusercontent.com/9401856/29821264-de7d5278-8cf9-11e7-822d-d7808673c2f8.jpg)
新版排版：
![default](https://user-images.githubusercontent.com/9401856/29821273-e4782004-8cf9-11e7-97f4-b8775da88257.jpg)
旧版字体：
![default](https://user-images.githubusercontent.com/9401856/29821279-e89b8a40-8cf9-11e7-8977-d6dcbc26e9c3.jpg)
新版字体：
![default](https://user-images.githubusercontent.com/9401856/29821282-ed7d391e-8cf9-11e7-8ada-30545246e727.jpg)

**Comment by cdhigh** [comment]
估计是最新版的kf8修改代码引入的bug，你可以尝试一下将
lib/makeoeb.py里面的
setattr(opts, "mobi_file_type", 'both')
改成
setattr(opts, "mobi_file_type", 'old')

@insert0003 你觉得问题可能在哪？

**Comment by insert0003** [comment]
有可能是both和old的区别。毕竟calibre的代码没有完全确认过，混合模式（both）会有什么差异还真不知道。我在本地试试看both和old，然后再回复。

**Comment by dubu45** [comment]
@insert0003 您好，cnbeta是通过RSS订阅的，订阅地址 http://rssdiy.com/u/2/cnbeta.xml

**Comment by dubu45** [comment]
@cdhigh 经测试，改为old后，排版和字体都正常了。改为new的话则会被亚马逊拒绝推送，说是不支持的格式。old的参数是旧格式，new参数是新格式，both到底是什么意思呢？

**Comment by insert0003** [comment]
我的理解，都是亚马逊的kindle格式。
old采用的mobi7格式，解压完可以看到HDImages，mobi7两个文件夹，mobi7有html和图片。
new采用的Kindle Format8，解压完有HDImages，mobi7和mobi8文件夹，mobi7下只有图片没有html，mobi8有html和图片。
both指的是混合模式，解压完有HDImages，mobi7和mobi8文件夹，mobi7，mobi8的都有html和图片。
目前的亚马逊不支持KF8格式的推送，只支持both和old。
both模式貌似支持一些css，style，但是还没有完全理解，如果想采用原来的排版和字体，还是使用old吧，我添加both是为了看漫画用的。

**Comment by dubu45** [comment]
@cdhigh @insert0003 感谢耐心解答！
