### ISSUE TITLE
搜狗微信公众号的接口失效，替代方案

### ISSUE THREAD

**Issue by Stonesjtu** [cdhigh/KindleEar#432]
最近在弄微信公众号推送kindle的事，wiki里面关于公众号的已经不可用了，希望能更新一下文档。
另外我找到一个项目是利用新api爬取公众号文章的，准备用这个写一份。请问大家有什么comment吗？
https://github.com/Chyroc/WechatSogou

**Comment by cdhigh** [comment]
就是不知这个API能用多久，微信是独立王国，而RSS有国际标准。
爬取微信注定要和腾讯一直玩猫和老鼠游戏。
如果你能提供一个pullrequest，倒是可以合入。

**Comment by yefoenix** [comment]
@Stonesjtu 求pullrequest~~
