### ISSUE TITLE
Initium Media RSS 如何设置登录阅读全文？

### ISSUE THREAD

**Issue by cmmei** [cdhigh/KindleEar#435]
Initium Media 端传媒会员登录阅读完整文章，尝试自己写了 `theinitium.py` ，代码如下。

试了一下可以填写登录信息，但推送的不是完整文章，只是未登录状态时的部分文字。

不知是哪里写的不对？

```
#!user/bin/env python
# -*- coding:utf-8 -*-

from base import BaseFeedBook

def getBook():
    return Theinitium

class Theinitium(BaseFeedBook):
    title = 'initium media'
    description = 'global news'
    language = 'zh-cn'
    feed_encoding = 'utf-8'
    page_encoding = 'utf-8'
    mastheadfile = 'mh_theinitium.gif'
    coverfile = 'cv_theinitium.jpg'
    needs_subscription = True
    login_url = "https://theinitium.com/auth/login"
    form_4_login = None
    email = ''
    password = ''
    feeds = [('initium media', 'https://theinitium.com/newsfeed')]
```
推送显示如下图：
![img1](https://i.loli.net/2017/09/12/59b76abde03fe.jpg)

**Comment by cdhigh** [comment]
需要登录的网站大部分都用不了， KindleEar内置的登录功能仅适用于小部分网站，这是因为现在的网站大部分都会使用到Javascript处理登录过程，而囿于GAE环境下无法解析Javascript，所以除非某些网站仅使用传统的form/submit技术登录，或者分析Javascript的处理过程，在KindleEar上模拟，否则都用不了。

我看这个RSS订阅内已经有全文信息了，不妨勾上"isfulltext"再订阅试试？

**Comment by cmmei** [comment]
这个网站订阅，部分文章是开放全文阅读，部分是付费会员登录阅读全文。于是尝试了一下登录后推送。看来还是得用它的 App 看了。

谢谢! @cdhigh
