### ISSUE TITLE
一天推送多次好像没有成功

### ISSUE THREAD

**Issue by mrsoshining** [cdhigh/KindleEar#437]
如何一天推送多次？

需要及时跟踪网站最新消息的同学可能有一天推送多次的需求，以下步骤告诉你如何实现：

在books目录下添加一个py文件。
deliver_times设置为你需要推送的整点时间列表。 
比如：
deliver_times=[6,14,22] #6:00,14:00,22:00三次推送
如果需要，oldest_article设置为多次推送的间隔秒数，这样就不推送重复文章了。 
比如：
oldest_article=28800 #8*60*60

按照大神的指导这么做，不过好像还只是一天推送一次。这个意思是我只要新建一个py文件，然后写上这两句上传就行了吗？谢谢！

**Comment by cdhigh** [comment]
是这样就行，至于能否推送多次，还要看订阅源能否每天更新多次，每次的"发布时间"或"修改时间"是否准确。

**Comment by mrsoshining** [comment]
我在base.py中相应字段加上了时间设置，不过好像也没有推送，不知这样行不行，请大神再指导。

**Comment by cdhigh** [comment]
最简单判断的方法就是oldest_article=0，看是不是一天推了三次。

**Comment by mrsoshining** [comment]
好的，我再试试，谢谢

**Comment by mrsoshining** [comment]
从这两天测试的结果看，推送的时间还是按照设置页面里设定的时间推送的，麻烦再给些指导

**Comment by cdhigh** [comment]
把你写的py文件贴上来

**Comment by mrsoshining** [comment]
#!/usr/bin/env python
# -*- coding:utf-8 -*-
deliver_times = [8,12,16,20] 
oldest_article        = 0   


就是贴过来这么两句，另外base.py里相应的两行也改成上面这样了

**Comment by cdhigh** [comment]
还是不清楚你怎么做的，
你要仿照books目录下的文件，新增一个py文件，添加你要的信息，然后在web界面订阅，就会每天推送多次了。

**Comment by mrsoshining** [comment]
哦，好像有点明白了，就是我想订阅哪个刊物或RSS，就建一个类似的py文件，然后这个订阅就会按照文件里设定的时间推送了，是吧！多谢了！

**Comment by cdhigh** [comment]
这样理解才对

**Comment by mrsoshining** [comment]
明白明白、多谢多谢！

**Comment by mrsoshining** [comment]
新增的py文件，是应该出现在我的订阅-未订阅里吗，然后再选择订阅？不过我新建的并没有出现在web界面，可能是我的py文件有问题？

**Comment by mrsoshining** [comment]
web设置这个站点一般多久更新一次，一天吗？谢谢不厌其烦解答！

**Comment by cdhigh** [comment]
修改可代码，上传后马上就可以看到新的书，如果没有，说明你的新文件有错误，可以到gae后台的log界面看是什么错。

**Comment by mrsoshining** [comment]
日志中看不出有什么问题，以下是我仿照修改的，帮忙看看吧，谢谢

文件名：Pepolitics.py

#!/usr/bin/env python
# -*- coding:utf-8 -*-
from base import BaseFeedBook

def getBook():
    return Pepolitics

class Pepolitics(BaseFeedBook):
    title                 = u'国内新闻-人民网'
    description           = u'国内新闻-人民网。'
    language              = 'zh-cn'
    feed_encoding         = "utf-8"
    page_encoding         = "utf-8"
    mastheadfile          = " "
    coverfile             = " "
    oldest_article        = 14400    #下载多长时间之内的文章，小于等于365则单位为天，大于365则单位为秒，0为不限制,4*60*60
    deliver_times         = [8,12,16,20]
    
    feeds = [
            (u'国内新闻', 'http://www.people.com.cn/rss/politics.xml'),
            ]
    
    def fetcharticle(self, url, opener, decoder):
        #每个URL都增加一个后缀full=y，如果有分页则自动获取全部分页
        url += '?full=y'
        return BaseFeedBook.fetcharticle(self,url,opener,decoder)

**Comment by cdhigh** [comment]
我下载了你的代码仓库中的对应文件，测试是正常的，你再试试？

**Comment by mrsoshining** [comment]
是否需要整体都重新部署一遍，还是我只需要上传单个py文件即可

**Comment by mrsoshining** [comment]
我把books下的所有py文件，除了__init__.py和base.py，都删除掉了，可是web设置里还有这些书籍，我需要怎么做，网站上才能更新？谢谢

**Comment by mrsoshining** [comment]
重新部署了一遍，web订阅列表里有了，就看能不能成功推送了

**Comment by mrsoshining** [comment]
这次好像可以了，不懂程序真可怕，感谢耐心帮助指导

**Comment by cdhigh** [comment]
添加书籍是马上生效的，删除书籍则最长24小时更新，这个也是为了效率考虑，不是什么技术方面的障碍。
