### ISSUE TITLE
gcloud app deploy错误

### ISSUE THREAD

**Issue by insert0003** [cdhigh/KindleEar#439]
重新deploy一个新的工程的时候，被提示app.yaml和module-work.yaml里的application和version是无效的，需要删除。删除以后就可以正常deploy了。
`
ERROR: (gcloud.app.deploy) The [application] field is specified in file [/home/tte/study/zkindlee/app.yaml]. This field is not used by gcloud and must be removed. Project name should instead be specified either by `gcloud config set project MY_PROJECT` or by setting the `--project` flag on individual command executions.
`
`
ERROR: (gcloud.app.deploy) The [version] field is specified in file [/home/tte/study/zkindlee/app.yaml]. This field is not used by gcloud and must be removed. Versions are generated automatically by default but can also be manually specified by setting the `--version` flag on individual command executions.
`
`
ERROR: (gcloud.app.deploy) The [application] field is specified in file [/home/tte/study/zkindlee/module-worker.yaml]. This field is not used by gcloud and must be removed. Project name should instead be specified either by `gcloud config set project MY_PROJECT` or by setting the `--project` flag on individual command executions.
`
`
ERROR: (gcloud.app.deploy) The [version] field is specified in file [/home/tte/study/zkindlee/module-worker.yaml]. This field is not used by gcloud and must be removed. Versions are generated automatically by default but can also be manually specified by setting the `--version` flag on individual command executions.
`
有个警告
`
WARNING: The "module" parameter in application .yaml files is deprecated. Please use the "service" parameter instead.
`

**Comment by cdhigh** [comment]
readme不是有这个信息吗？
安装了新sdk ，可以使用gcloud部署，也可以使用appcfg.py部署。

**Comment by insert0003** [comment]
不好意思，没有注意到那个。。。

**Comment by cdhigh** [comment]
随着GAE的不停升级，其实部署步骤有一些过时的内容了，因为懒，而且考虑大部分折腾KindleEar的都有很强的动手能力和意愿，都能自己寻找答案解决问题，所以就一直没有更新部署步骤。
