### ISSUE TITLE
通过配置反向代理方式访问某些页面依然会跳转回xxx.appspot.com

### ISSUE THREAD

**Issue by tcvictor** [cdhigh/KindleEar#440]
通过设置个人的域名指向一台境外vps，并在vps上配置反向代理访问xxx.appspot.com, 大部分页面可以通过个人的域名访问，但是登录、登出以及高级设置的页面会重新跳转到xxx.appspot.com。个人不太懂python，简单看了一下源码，可能是因为raise web.seeother()重定向导致的跳转回xxx.appspot.com。尝试将config.py中的DOMAIN配置为个人的域名并删除了当前运行的实例，新的实例依然存在以上问题，请作者帮忙看一下，十分感谢！

**Comment by cdhigh** [comment]
这个问题很奇怪呢，代码中所有使用到的链接都是相对路径，没有写死appspot.com的，会不会是反向代理的某些设置？
对于我来说，没有反向代理，也无法调试

**Comment by cdhigh** [comment]
可能是反向代理对303状态码（See other）的处理有问题？

**Comment by tcvictor** [comment]
返回的303应答携带的跳转地址已经是xxx.appspot.com了

**Comment by cdhigh** [comment]
可能是框架对303的处理问题了。
帮忙调试一下，修改lib/web/webapi.py(line 88): 
`'Location': newloc`
改成：
`'Location': url`

**Comment by tcvictor** [comment]
it works!

**Comment by cdhigh** [comment]
好的，这个问题记下了，下个版本修改

**Comment by cdhigh** [comment]
1.25.1已经修正
