### ISSUE TITLE
在授权google cloud SDK访问账户权限时出错

### ISSUE THREAD

**Issue by houjuehouzhi** [cdhigh/KindleEar#441]
安装SDK后，需要授权google cloud SDK访问账户的权限，按提示输入密码登陆账户，点击授权后页面显示无法访问（http://localhost:8085/?code=4/oSGnuOhI8ZAAk0mQG8KVcJQwbFudkptnPNY2wfGpK5g#），命令页面提示如下错误：
ERROR: There was a problem with web authentication. Try running again with --no-launch-browser.
ERROR: (gcloud.auth.login) Failed to find "code" in the query parameters of the redirect.
ERROR: (gcloud.init) Failed command: [auth login --force --brief] with exit code [1]

请教大神应该如何解决？多谢！

**Comment by xiaods** [comment]
加上VPN在尝试。
