### ISSUE TITLE
推送内置漫画，图片大小没有被rescale

### ISSUE THREAD

**Issue by cover-me** [cdhigh/KindleEar#442]
Hi! 这个应用非常不错，但是我遇到了一个问题：推送内置漫画（比如一拳超人），得到的mobi文件里的图片还是原始大小。即使在config.py里面将REDUCE_IMAGE_TO设成(300,300)，图也不会被缩。
我看了半天代码也找不出原因，只能找到这个小错误（第338行第二个方括号里应该是1不是0）：
apps/Work/Worker.py
336	        #新生成的图片再整体缩小到设定大小
337	        rw,rh = opts.reduce_image_to
338	        ratio = min(float(rw)/float(new_size[0]), float(rh)/float(new_size[0]))
339	        imgnew = imgnew.resize((int(new_size[0]*ratio), int(new_size[1]*ratio)))

**Comment by cdhigh** [comment]
这段代码是拆分长图才用到的，不是这段代码。
过两天我看看代码。
普通书籍推送的图片压缩了吗？

**Comment by cover-me** [comment]
我加了几行代码（见我的Pull Request），现在可以缩放自带漫画类中的图片了。虽然不是很完美。

**Comment by cover-me** [comment]
我还有一个问题，自定义RSS推送的书籍是带有二级目录的，在老旧的Kindle 4上第二级目录有一部分在屏幕外面，不知道该调哪个变量把它整体左移一点？

**Comment by cover-me** [comment]
类似于下面这种情况，一部分字跑到屏幕外，无法显示了
https://user-images.githubusercontent.com/9401856/29821282-ed7d391e-8cf9-11e7-8ada-30545246e727.jpg

**Comment by cover-me** [comment]
我还有一个问题，自定义RSS推送的书籍是带有二级目录的，在老旧的Kindle 4上第二级目录有一部分在屏幕外面，不知道该调哪个变量把它整体左移一点？
类似于下面这种情况，不同的是有一部分字跑到屏幕外看不到了：
https://user-images.githubusercontent.com/9401856/29821282-ed7d391e-8cf9-11e7-8ada-30545246e727.jpg

**Comment by cover-me** [comment]
可能跟设备有关。英文能正确换行，所以不会超出去。中文有时候换行不成功，有时候换行成功。

**Comment by cover-me** [comment]
普通书籍里的是压缩的。
