### ISSUE TITLE
在此非常感谢作者，要是增加「自定义RSS订阅列表的排序功能」就完美了。

### ISSUE THREAD

**Issue by yeehomlee** [cdhigh/KindleEar#444]
希望自定义RSS订阅列表，可以按照自己的阅读习惯进行先后排序。

这样在Kindle上看到的会更加舒服，更易于阅读。

一个小建议。

再次感谢作者。

**Comment by cdhigh** [comment]
以前已经有过讨论了，现在是根据添加时间排序的，一般已经足够，没有必要非得添加“拖拉”等方式排序。
