### ISSUE TITLE
The Economist经济学人RSS订阅地址失效

### ISSUE THREAD

**Issue by LiuR** [cdhigh/KindleEar#445]
使用程式兩年多來，經濟學人訂閱一直在穩定地運行，一直到今年11月份，而現在除了The world this week，其他訂閱源幾乎全部失效。

**Comment by Steven630** [comment]
http://www.economist.com/rss
这里是最新的

**Comment by LiuR** [comment]
有朋友提到 www.economist.com/rss，網站中Sections中的feed源還是可以使用的，不過就個人看來，作者使用的rss地址應該是對應着Print edition。

**Comment by hccz95** [comment]
遇到了跟你同样的问题

**Comment by putiyeb** [comment]
Sections的有些RSS貌似与print edition不匹配
可以看看下面链接里面的RSS，有全文也有对应的摘要RSS
https://shui.azurewebsites.net/2017/12/18/share-rss/

**Comment by cdhigh** [comment]
有些RSS订阅源的地址改变了，我记下了。

**Comment by cdhigh** [comment]
已在1.25.2更新
