### ISSUE TITLE
一些rss不能推送，不知道怎么解决。

### ISSUE THREAD

**Issue by ZJJane** [cdhigh/KindleEar#451]
1.Solidot    https://feeds2.feedburner.com/solidot?fmt=xml
fetch page failed(530 Timeout):https://www.solidot.org/story?sid=55042. (/base/data/home/apps/s~my-kindlepush/worker:1.406442596030949763/books/base.py:494)

2.战隼的学习探索  全文RSS  https://www.read.org.cn/feed
这个在日志中貌似找不到，所以不知道那里有问题。

3.另外还有一个
fetch img failed(404 Not Found):data:image/svg+xml;utf8,<svg%20xmlns='http://www.w3.org/2000/svg'%20width='640'%20height='438'></svg> (/base/data/home/apps/s~my-kindlepush/worker:1.406442596030949763/books/base.py:678)
这个我看不出是哪个订阅。
![image](https://user-images.githubusercontent.com/27692584/34440039-6fde6d26-eced-11e7-89ad-809642100875.png)

**Comment by cdhigh** [comment]
1. RSS源里面的URL地址错误，比如成这样了 //www.solidot.org/story?sid=55180，少了HTTP:或多了//
2. 战隼的学习探索订阅RSS源里面的时间错误，都写成了2015年的时间了，如果要推送，则需要设置
"最旧文章 :" "不限制"
3. 暂不支持SVG格式的图片
