### ISSUE TITLE
send failed是什么原因？

### ISSUE THREAD

**Issue by cyang812** [cdhigh/KindleEar#453]
是推送的附件太大吗？
28.3M推送失败，前一天的25.3M可以。
另外，推送支持的最大文件大小是多少？

**Comment by cdhigh** [comment]
大约25M，是GAE发送邮件的限制。

**Comment by cyang812** [comment]
能不能从程序里判断，大于25M就删减部分内容，不至于推送失败。

**Comment by cdhigh** [comment]
这种处理是不适当的，订阅源小一点就可以

**Comment by yangguodongbeijing** [comment]
GAE发送邮件的限制。从哪里可以查看 、 修改 、 去掉？

**Comment by cdhigh** [comment]
你google一下吧，在GAE文档，找找限额部分或邮件功能部分就能找到。
