### ISSUE TITLE
自带知乎日报rss没有内容

### ISSUE THREAD

**Issue by frankline-DPRC** [cdhigh/KindleEar#454]
1月份以来知乎日报rss好像一直没有更新无法获取 显示nonew

**Comment by cdhigh** [comment]
知乎日报有两个订阅源，一个需要转发器，一个是纯RSS。

纯RSS的那个本来就是其他热心网友提供的先抓取再转成RSS的免费服务，非“知乎”官方，所以不做保证，随时会倒掉。

需要转发器的那个是直接从知乎服务器上抓取的，所以不容易倒掉，问题就是我搭建的转发器负荷比较重【Heroku经常发邮件提示我此转发器应用较受欢迎，建议我付费】，所以可能也会时不时收不到订阅，如果你自己搭建转发器 <https://github.com/cdhigh/Forwarder> ，就不用担心这个问题了。
