### ISSUE TITLE
部署成功了，在设置界面点击“现在投递”，遇到 internal server error

### ISSUE THREAD

**Issue by sparksunflower** [cdhigh/KindleEar#455]
日志如下：
![snipaste_20180116_165925](https://user-images.githubusercontent.com/5681656/34980185-a567d1ae-fade-11e7-9949-f7bf8cef9553.png)

**Comment by sparksunflower** [comment]
求作者给点反馈啊

**Comment by cdhigh** [comment]
这种不用想，搭建错误，如果不懂编程，就严格一个步骤一个步骤的做，不要想当然的变通。
要不就网络搜索搭建教程。

**Comment by sparksunflower** [comment]
解决了，谢谢！
不过投递日志出现状态wrong SRC_EMAIL
我看了faq，说要到到Gae后台的Settings页面，看已经授权的Email列表
不过我在GAE后台没有看到那个settings页面有 Email列表。能不能指点下哦

**Comment by sparksunflower** [comment]
找到了，已经解决，成功用上了，谢谢作者
