### ISSUE TITLE
最新Kindle固件不显示推送文件的日期了

### ISSUE THREAD

**Issue by Steven630** [cdhigh/KindleEar#457]
原来periodical封面下方默认显示的是推送日期，如果用Kindle最新固件，现在会显示KindleEar。这样一来，日常推送就分不清时间了。

https://www.mobileread.com/forums/showthread.php?t=292776
这里也有讨论，Calibre作者和其他网友说了解决办法，不知道能否用在KindleEar上。

麻烦看看，谢谢。

**Comment by cdhigh** [comment]
试试设置里面的选项：
标题样式？

**Comment by cdhigh** [comment]
修改了封面样式后，封面下显示的什么内容？

**Comment by Steven630** [comment]
@cdhigh 顯示“KindleEar”。有時候剛下載完的一瞬間會顯示日期，然後馬上又變成KindleEar

**Comment by cdhigh** [comment]
Amazon的这个版本升级存在不合理之处，书本下面显示的应该是书籍标题或日期，现在变成了显示作者。
说不准过不了多久，Amazon会修正这个“Bug”。
你可以试一下修改apps/Work/Worker.py(line92)
`setMetaData(oeb, bookTitle, book4meta.language, local_time("%Y-%m-%d",tz), pubtype=pubtype)`
修改为：
`setMetaData(oeb, bookTitle, book4meta.language, local_time("%Y-%m-%d",tz), pubtype=pubtype, creator=local_time("%Y-%m-%d",tz))`

**Comment by Steven630** [comment]
这样修改了以后，确实能暂时解决这个问题。虽然日期的字体阿拉伯数字用的是中文字体，看着有点别扭，但毕竟比显示作者好。

**Comment by Sciroccogti** [comment]
好像至今都没有修复，是否考虑直接将此修改写到代码中？或者作为一个可选项？

**Comment by cdhigh** [comment]
可以，添加一个选项修正此问题

**Comment by cdhigh** [comment]
升级了1.26.7，添加了一个选项。
