### ISSUE TITLE
internal server error（非索引问题，详情见正文TraceBack）

### ISSUE THREAD

**Issue by sword2ya** [cdhigh/KindleEar#461]
line: [
   0: {
    logMessage:  "Traceback (most recent call last):"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.706260Z"     
   }
   1: {
    logMessage:  "  File "lib/web/application.py", line 239, in process"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.706320Z"     
   }
   2: {
    logMessage:  "    return self.handle()"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.706340Z"     
   }
   3: {
    logMessage:  "  File "lib/web/application.py", line 230, in handle"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.706360Z"     
   }
   4: {
    logMessage:  "    return self._delegate(fn, self.fvars, args)"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.706380Z"     
   }
   5: {
    logMessage:  "  File "lib/web/application.py", line 420, in _delegate"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.706390Z"     
   }
   6: {
    logMessage:  "    return handle_class(cls)"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.706420Z"     
   }
   7: {
    logMessage:  "  File "lib/web/application.py", line 396, in handle_class"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.706440Z"     
   }
   8: {
    logMessage:  "    return tocall(*args)"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.706450Z"     
   }
   9: {
    logMessage:  "  File "/base/data/home/apps/j~kindleajw/20180201t155431.407343221886657806/apps/utils.py", line 83, in wrapper"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.706470Z"     
   }
   10: {
    logMessage:  "    rsp_data = func(*args, **kwds)"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.706490Z"     
   }
   11: {
    logMessage:  "  File "/base/data/home/apps/j~kindleajw/20180201t155431.407343221886657806/apps/View/Subscribe.py", line 35, in GET"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.706500Z"     
   }
   12: {
    logMessage:  "    books=books, myfeeds=myfeeds, tips=tips)"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.706520Z"     
   }
   13: {
    logMessage:  "  File "/base/data/home/apps/j~kindleajw/20180201t155431.407343221886657806/apps/BaseHandler.py", line 190, in render"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.706540Z"     
   }
   14: {
    logMessage:  "    html = main.jjenv.get_template(templatefile).render(title=title, **kwargs)"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.706550Z"     
   }
   15: {
    logMessage:  "  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/third_party/jinja2-2.6/jinja2/environment.py", line 894, in render"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.706570Z"     
   }
   16: {
    logMessage:  "    return self.environment.handle_exception(exc_info, True)"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.706590Z"     
   }
   17: {
    logMessage:  "  File "templates/my.html", line 1, in top-level template code"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.706610Z"     
   }
   18: {
    logMessage:  "    {% extends "base.html" %}"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.706620Z"     
   }
   19: {
    logMessage:  "  File "templates/base.html", line 142, in top-level template code"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.706640Z"     
   }
   20: {
    logMessage:  "    {% block content -%}"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.706660Z"     
   }
   21: {
    logMessage:  "  File "templates/my.html", line 6, in block "content""     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.706670Z"     
   }
   22: {
    logMessage:  "    {% for feed in myfeeds -%}"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.706690Z"     
   }
   23: {
    logMessage:  "  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/1/google/appengine/ext/db/__init__.py", line 2330, in next"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.706710Z"     
   }
   24: {
    logMessage:  "    return self.__model_class.from_entity(self.__iterator.next())"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.706720Z"     
   }
   25: {
    logMessage:  "  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/1/google/appengine/datastore/datastore_query.py", line 3321, in next"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.706740Z"     
   }
   26: {
    logMessage:  "    next_batch = self.__batcher.next_batch(Batcher.AT_LEAST_OFFSET)"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.706760Z"     
   }
   27: {
    logMessage:  "  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/1/google/appengine/datastore/datastore_query.py", line 3207, in next_batch"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.706770Z"     
   }
   28: {
    logMessage:  "    batch = self.__next_batch.get_result()"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.706790Z"     
   }
   29: {
    logMessage:  "  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 613, in get_result"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.706810Z"     
   }
   30: {
    logMessage:  "    return self.__get_result_hook(self)"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.706820Z"     
   }
   31: {
    logMessage:  "  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/1/google/appengine/datastore/datastore_query.py", line 2921, in __query_result_hook"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.706840Z"     
   }
   32: {
    logMessage:  "    yaml_index=yaml, xml_index=xml)"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.706860Z"     
   }
   33: {
    logMessage:  "NeedIndexError: no matching index found. recommended index is:"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.706880Z"     
   }
   34: {
    logMessage:  "- kind: Feed"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.706900Z"     
   }
   35: {
    logMessage:  "  properties:"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.706920Z"     
   }
   36: {
    logMessage:  "  - name: book"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.706940Z"     
   }
   37: {
    logMessage:  "  - name: time"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.706960Z"     
   }
   38: {
    logMessage:  "The suggested index for this query is:"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.707Z"     
   }
   39: {
    logMessage:  "- kind: Feed"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.707010Z"     
   }
   40: {
    logMessage:  "  properties:"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.707030Z"     
   }
   41: {
    logMessage:  "  - name: book"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.707050Z"     
   }
   42: {
    logMessage:  "  - name: time"     
    severity:  "ERROR"     
    time:  "2018-02-01T08:09:17.707070Z"     
   }
  ]

**Comment by sword2ya** [comment]
我看错了，是Index错误，但是我按照FAQ执行命令，GAB报错。请问如何解决，报错如下：
jiaweiangg@kindleajw:~/src_2/KindleEar$ ls
apps  app.yaml  books  changelog_en.md  changelog.md  config.py  config.pyc  cron.yaml  dispatch.yaml  helper.py  i18n  images  index.yaml  lib  module-worker.yaml  queue.yaml  readme_EN.md  readme.md  static  templates  upload.sh
jiaweiangg@kindleajw:~/src_2/KindleEar$ appcfg.py update_indexes ./
05:18 PM Host: appengine.google.com
05:18 PM Uploading index definitions.
Error 400: --- begin server output ---
<h3>Client Error</h3><p>The request is invalid for an unspecified reason.</p>
--- end server output ---

**Comment by cdhigh** [comment]
还是索引问题，重建索引吧

**Comment by sword2ya** [comment]
是Index错误，但是我按照FAQ执行命令，GAB报错。请问如何解决，报错如下：
jiaweiangg@kindleajw:/src_2/KindleEar$ ls
apps app.yaml books changelog_en.md changelog.md config.py config.pyc cron.yaml dispatch.yaml helper.py i18n images index.yaml lib module-worker.yaml queue.yaml readme_EN.md readme.md static templates upload.sh
jiaweiangg@kindleajw:/src_2/KindleEar$ appcfg.py update_indexes ./
05:18 PM Host: appengine.google.com
05:18 PM Uploading index definitions.
Error 400: --- begin server output ---

Client Error
The request is invalid for an unspecified reason.

--- end server output ---

**Comment by cdhigh** [comment]
梯子的问题
