### ISSUE TITLE
手动投递 自定义RSS 未投递

### ISSUE THREAD

**Issue by brady2037** [cdhigh/KindleEar#462]
添加了一个自带的rss，三个自定义的，点击 现在投递后 ,日志中只显示自带的，自定义的rss没有投递

![订阅](http://oph0392na.bkt.clouddn.com/kin1.png)
![设置](http://oph0392na.bkt.clouddn.com/kin2.png)
![结果](http://oph0392na.bkt.clouddn.com/kin3.png)

**Comment by cdhigh** [comment]
你没有选择“自动定时投递自定义RSS”

**Comment by brady2037** [comment]
@cdhigh 还以为只是定时的开关，万分感谢～
