### ISSUE TITLE
自定义RSS如何订阅早期的文章

### ISSUE THREAD

**Issue by HOUpu** [cdhigh/KindleEar#466]
您好，我订阅新浪博客只能订阅最新的10篇文章，不加载图片的话我看配额应该还够，我想问程序改哪里能订阅早期的文章，我试着改了一下没找到

**Comment by cdhigh** [comment]
KindleEar最多一次允许30篇文章，如果是10篇的话，说明订阅源输出只有10个，怨有头债有主，这个锅要订阅源背。

**Comment by HOUpu** [comment]
好的谢谢了，我看了一下新浪的rss地址里确实只有10个输出

在 2018-02-11 18:41:34，"cdhigh" <notifications@github.com> 写道：


KindleEar最多一次允许30篇文章，如果是10篇的话，说明订阅源输出只有10个，怨有头债有主，这个锅要订阅源背。
