### ISSUE TITLE
代码耦合度太高

### ISSUE THREAD

**Issue by xujun05** [cdhigh/KindleEar#469]
有些地方代码的耦合度，真的是太高了。好多东西都黏糊在一起。

**Comment by cdhigh** [comment]
这种issue无太大意义，提这种问题太容易了，难得是解决，建议贡献代码

**Comment by cdhigh** [comment]
我想起我刚开源时，还收到评价说我英语太烂了，呵呵，但是我还大胆的继续做不是吗？
talk is cheap, show me the code

**Comment by cdhigh** [comment]
一直没有代码贡献，喷子而已。关闭
