### ISSUE TITLE
更换不了封面

### ISSUE THREAD

**Issue by babopo** [cdhigh/KindleEar#473]
上传图片后显示上传成功，刷新之后又变成了默认封面，推送收到的也是默认封面
log信息没有报错

**Comment by cdhigh** [comment]
是什么格式的图片？

**Comment by cdhigh** [comment]
用的是什么浏览器？
或者你将图片发给我确认也行
chsqyuan@hotmail.com

**Comment by babopo** [comment]
已发

**Comment by cdhigh** [comment]
你没看到提示吗？
在选择封面文件后，KindleEar提示：封面图片必须小于500KB
你这个封面图片太大了

**Comment by babopo** [comment]
抱歉，本地的图片确实是显示小于500k的，上传也只有上传成功的提示，不知道为什么转发后再保存就大于500k了，
[cid:image002.png@01D3C6DC.5BC41C00]

找其他的图片尝试成功了，可能是图片的问题

感谢

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
