### ISSUE TITLE
推送错误！

### ISSUE THREAD

**Issue by L1cardo** [cdhigh/KindleEar#475]
推送错误，推送失败显示over quota
![1](https://user-images.githubusercontent.com/33802186/38744656-f3ca7894-3f74-11e8-87a4-f64b9b3f0911.png)

**Comment by cdhigh** [comment]
不单是没必要的问题，而且还加叹号
免费服务总有限额的嘛，这不很正常吗？
解决方法是搭建几个应用，分别推送。
或交钱给google

**Comment by L1cardo** [comment]
sorry啦，我不知道呢，打扰了。
