### ISSUE TITLE
投递日志状态显示 over quota

### ISSUE THREAD

**Issue by YingtongDou** [cdhigh/KindleEar#476]
好像是说收件人邮箱已满。不知道如何解决这个问题？

**Comment by cdhigh** [comment]
GAE不停修改配额政策，现在一个应用最多只能使用最多10个邮件收件人了。
如果要突破，有两个方法：
1. 推送至一个其他邮箱比如outlook，然后设置邮箱自动转发即可，这样可以添加任意你希望的收件人数量。
2. 部署多个应用，每个应用都有单独的10个收件人配额。
