### ISSUE TITLE
喷嚏图卦已经无法推送

### ISSUE THREAD

**Issue by glucee** [cdhigh/KindleEar#477]
好多天了，推送都是0，请帮忙检查下问题。

**Comment by cdhigh** [comment]
因为源没有更新，最近的一期是4月8号的。
等图卦有更新后，KindleEar会自动推送给你。

**Comment by WangShanpeng** [comment]
> 好多天了，推送都是0，请帮忙检查下问题。

我更换了一个rss源，请检查一下有没有正常推送。
