### ISSUE TITLE
how to disable hyperlinks in books?

### ISSUE THREAD

**Issue by fw-tamu** [cdhigh/KindleEar#478]
kindle reader is not that suitable for webpage browsing, the processor and memory is too slow.
Some generated books contain a lot of hyperlinks and it is very easy to trigger the built-in browser which is very laggy and irresponsive. 
Is there a way we can disable the generation of hyperlinks in the book?

Thanks

**Comment by cdhigh** [comment]
even thought with limit of capability of browser, some links are useful during reading, I can follow some links for much information occasionally.
If this feature is important to you, I can add it to next version.

**Comment by fw-tamu** [comment]
yes please, thanks in advance!
another feature i'd like to see is to allow user select the feeds for manual push.
Currently, the manual push will deliver all subscribed feeds.

**Comment by cdhigh** [comment]
the "manual push" was developed for test or debug.
did you use it many times?

**Comment by fw-tamu** [comment]
i used it when some feeds cannot deliver automatically, e.g, ending up with "nonews" status.

**Comment by cdhigh** [comment]
if manual push can select which feed will been pushed, I have to put this feature to a seperate page, for example, a page in menu "Advanced".

**Comment by fw-tamu** [comment]
also could you allow one account to deliver to multiple kindle account? this is useful for users with multiple kindle reader devices like me and also sharing between friends/family.
Thanks

**Comment by cdhigh** [comment]
multiple email address is supported.
emails are separated by semicolon in field "Kindle email".

**Comment by cdhigh** [comment]
Added in 1.25.3, please try it

**Comment by cdhigh** [comment]
Improved in 1.25.4
