### ISSUE TITLE
都设置好了，只要点击现在投递就显示“Internal Server Error"

### ISSUE THREAD

**Issue by Chyowing** [cdhigh/KindleEar#480]
GAE后台检查都没有问题，显示是serving，amazon信任邮箱也添加了，自己的邮箱白名单也添加了，不知道问题出在哪里，到现在还没有推送成功过，一直显示Internal server error,求大神帮帮忙！！！！

**Comment by cdhigh** [comment]
一定有错误记录，再找找

**Comment by Chyowing** [comment]
不好意思，我是电脑白痴，我完全是按照[https://bookfere.com/post/19.html](url)这个网站上的操作进行的，很顺利，但是到现在推送就不好使了，请问有什么方法检测错误记录呢？

**Comment by cdhigh** [comment]
打开GAE后台后，在左边选择“日志”，然后就可以进去看报错的项了。

**Comment by Chyowing** [comment]
![image](https://user-images.githubusercontent.com/33175600/39970677-36f58b80-5722-11e8-855c-657174679a97.png)
您好，这是我的报错项，我不太懂要怎么看，请问可以帮忙看看吗？拜托了

**Comment by Chyowing** [comment]
这些是展开后的信息
![image](https://user-images.githubusercontent.com/33175600/39970844-1f6050e2-5725-11e8-967e-c7ae7b14f016.png)
![image](https://user-images.githubusercontent.com/33175600/39970853-2f966c4e-5725-11e8-8552-3188b9b3e1a6.png)
![image](https://user-images.githubusercontent.com/33175600/39970856-3c77e8ca-5725-11e8-888f-ed1162c70693.png)
![image](https://user-images.githubusercontent.com/33175600/39970862-47e1aade-5725-11e8-9ccb-d8bca1d496f0.png)

**Comment by cdhigh** [comment]
最后一个图还要点击 show more 或 show all才能看到有效错误信息

**Comment by Chyowing** [comment]
![image](https://user-images.githubusercontent.com/33175600/39973268-6f9efeca-5750-11e8-9c3f-b494add8183c.png)

**Comment by cdhigh** [comment]
没部署好，要执行appcfg.py update KindleEar目录

**Comment by Chyowing** [comment]
请问这个appcfg.py update KindleEar要怎样执行呢？是直接把才段文字输入到Cloud Shell里面 吗？

**Comment by cdhigh** [comment]
readme和FAQ都写的很清楚了
