### ISSUE TITLE
推送RSS到kindle的原理是什么？

### ISSUE THREAD

**Issue by nidegexing** [cdhigh/KindleEar#481]
打算自制本地运行的推送服务。不明白RSS推送的原理。
比如说推送txt或者mobi文件，是把文件作为附件发送kindle邮箱即可。
那RSS文件要如何推送呢，也是附件？
比如说我有一个RSS订阅源，http://zhihurss.miantiao.me/dailyrss，
我从这个源取到RSS.xml文件，作为附件发送？

**Comment by cdhigh** [comment]
制作成mobi文件做为附件发送至kindle邮箱即可。
