### ISSUE TITLE
When I add a new custom rss it is not being sent to Kindle 'Book'

### ISSUE THREAD

**Issue by will76** [cdhigh/KindleEar#482]
After I deployed the app I added a custom rss and hit the Delivery button. So far so good, looks awesome on Kindle.

Then I added another custom feed and hit the Delivery again, but this time nothing changed in the book.

Then I changed the name of the book in 'Settings' and hit Delivery. This time the (new) book include both rss I added.

Why is this happening? How is this supposed to work when I want to add feeds to my current book?

Thanks a lot!

**Comment by will76** [comment]
Hi @cdhigh , thanks for answering!

I don't think that happened. 
First because the size of the book increased, even though nothing changed in the Kindle. See log:
_2018-05-16 06:20 | KindleEar | 622.8 kB | xxxx@Kindle.com | ok
2018-05-15 21:35 | KindleEar | 344.9 kB | xxxx@Kindle.com | ok_

Second because when I changed the name of the book, the new one came with both feeds successfully crawled.

**Comment by cdhigh** [comment]
or you can send me the book of 622.8KB for debug
chsqyuan@hotmail.com

**Comment by will76** [comment]
Hi @cdhigh ,

I found that the newer versions were added to a 'collection' called "Periodicals: Back Issues".

Is this a bug? I don't remember changing my Time Zone.

**Comment by cdhigh** [comment]
it is a feature of Kindle
