### ISSUE TITLE
漫画大小超过邮箱附件限制怎么办？

### ISSUE THREAD

**Issue by micnp** [cdhigh/KindleEar#487]
gmail 仅支持 25MB 大小 很多一卷的漫画都接近50MB 甚至超过 50MB 想请教一下 有没有办法将邮箱换成其他附件大的邮箱 

或者 

有办法把提取漫画打包成mobi 的 py 文件应用到 calibre 上面吗？ 让自己来下载漫画 然后USB传输到kindle

我是一个代码都看不懂的萌新，如有表达不足之处还望海涵。

**Comment by cdhigh** [comment]
漫画模式是 @insert0003 的贡献，看 @insert0003 是否有兴趣做一个单机版的工具？

**Comment by micnp** [comment]
谢谢，我去询问了这位作者，等待回复。
