### ISSUE TITLE
推送的文章不全

### ISSUE THREAD

**Issue by Howard-guo** [cdhigh/KindleEar#490]
通过INOREADER看，一天会更新好多文章，但是通过kindleear推送的就那么几篇，没看到哪里有限制参数，这个是跟什么有关系呢？

**Comment by Biercenter** [comment]
这听说是要改源码哪个地方，但是忘记了。

Howard-guo <notifications@github.com> 于2018年6月24日周日 下午5:44写道：

**Comment by cdhigh** [comment]
碍于资源限制和其他原因，KindleEar没有默认一天多次抓取，也不暂存抓取到的文章，所以推送的文章就是抓取时刻的订阅源的文章列表，目前默认最近30篇。
有的订阅源可能每次只提供少量文章（比如10篇），但每天多次更新，如果是这种订阅源，KindleEar每次抓取推送的文章可能较少（比如10篇），但inoreader就可以更新很多文章，因为其在一天内会多次抓取并暂存历史文章。
这是机制和架构限制，KindleEar暂时不会解决。
如果确实需要，
KindleEar目前提供一个变通的方法：创建一个自定义书籍py文件，设置deliver_times属性，可以实现一天多次推送，具体参见books/base.py文件开始部分代码和注释。

**Comment by Howard-guo** [comment]
呃，其实我是抓的微信公众号文章转RSS，没准什么时候抓到。。

**Comment by cdhigh** [comment]
这样可以使用之前说的多次推送的方案，反正没有新文章不会推送的
