### ISSUE TITLE
抱歉 请问南方周末一直nonews正常吗

### ISSUE THREAD

**Issue by chanw9** [cdhigh/KindleEar#491]
Failed to push <南方周末> : list index out of range, in file 'nfzm.py', ParseFeedUrls (line 49)

**Comment by chanw9** [comment]
0.1.0.2 - - [06/Jul/2018:22:42:08 +0800] "GET /worker?u=chan&id=5643172898144256 HTTP/1.1" 200 102 http://kindlepush-chan.appspot.com/deliver?u=chan&id=5643172898144256 "AppEngine-Google; (+http://code.google.com/appengine)" "worker.kindlepush-chan.appspot.com" ms=NaN cpu_ms=551 cpm_usd=3.06989e-7 loading_request=0 instance=00c61b117c316a055863fa2469b4aaae0ce6033df7f725872b9662c311a7b359527496 app_engine_release=1.9.54 trace_id=2b3900fca5f5ee08cbd5b0b2a36ee636
全部展开 | 全部收起 {
 httpRequest: {
  status:  200   
 }
 insertId:  "5b3f7fc400012df5b16c00cc"  
 labels: {
  clone_id:  "00c61b117c316a055863fa2469b4aaae0ce6033df7f725872b9662c311a7b359527496"   
 }
 logName:  "projects/kindlepush-chan/logs/appengine.googleapis.com%2Frequest_log"  
 operation: {
  first:  true   
  id:  "5b3f7fc000ff0873f6683b6da80001627e6b696e646c65707573682d6368616e0001776f726b65723a31000100"   
  last:  true   
  producer:  "appengine.googleapis.com/request_id"   
 }
 protoPayload: {
  @type:  "type.googleapis.com/google.appengine.logging.v1.RequestLog"   
  appEngineRelease:  "1.9.54"   
  appId:  "b~kindlepush-chan"   
  cost:  3.06989e-7   
  endTime:  "2018-07-06T14:42:11.916605Z"   
  finished:  true   
  first:  true   
  host:  "worker.kindlepush-chan.appspot.com"   
  httpVersion:  "HTTP/1.1"   
  instanceId:  "00c61b117c316a055863fa2469b4aaae0ce6033df7f725872b9662c311a7b359527496"   
  ip:  "0.1.0.2"   
  latency:  "3.362631s"   
  line: [
   0: {
    logMessage:  "Failed to push <南方周末> : list index out of range, in file 'nfzm.py', ParseFeedUrls (line 49)"     
    severity:  "WARNING"     
    sourceLocation: {
     file:  "/base/data/home/apps/b~kindlepush-chan/worker:1.410892978254123702/apps/Work/Worker.py"      
     functionName:  "GET"      
     line:  "208"      
    }
    time:  "2018-07-06T14:42:11.882450Z"     
   }
  ]
  megaCycles:  "551"   
  method:  "GET"   
  moduleId:  "worker"   
  pendingTime:  "1.968963623s"   
  referrer:  "http://kindlepush-chan.appspot.com/deliver?u=chan&id=5643172898144256"   
  requestId:  "5b3f7fc000ff0873f6683b6da80001627e6b696e646c65707573682d6368616e0001776f726b65723a31000100"   
  resource:  "/worker?u=chan&id=5643172898144256"   
  responseSize:  "102"   
  startTime:  "2018-07-06T14:42:08.553974Z"   
  status:  200   
  taskName:  "71823091905099033011"   
  taskQueueName:  "deliverqueue1"   
  traceId:  "2b3900fca5f5ee08cbd5b0b2a36ee636"   
  urlMapEntry:  "apps.module_backend.app"   
  userAgent:  "AppEngine-Google; (+http://code.google.com/appengine)"   
  versionId:  "1"   
 }
 receiveTimestamp:  "2018-07-06T14:42:12.095453382Z"  
 resource: {
  labels: {
   module_id:  "worker"    
   project_id:  "kindlepush-chan"    
   version_id:  "1"    
   zone:  "asia-northeast1-2"    
  }
  type:  "gae_app"   
 }
 severity:  "WARNING"  
 timestamp:  "2018-07-06T14:42:08.553974Z"  
 trace:  "projects/kindlepush-chan/traces/2b3900fca5f5ee08cbd5b0b2a36ee636"  
}

**Comment by cdhigh** [comment]
不正常。
因为南方周末不提供RSS，内置的这个“源”是直接分析网页抓取的文章，出现这个异常说明南方周末网页改版了，等过段时间重新分析网页，更新代码才能继续抓取。
如果你有这方面的经验，也欢迎贡献代码。

**Comment by TTTPOB** [comment]
https://docs.rsshub.app/traditional-media.html#nan-fang-zhou-mo

**Comment by cdhigh** [comment]
谢谢提供的信息，可以将内置的 南方周末 删除了。

**Comment by skyalien** [comment]
> 谢谢提供的信息，可以将内置的 南方周末 删除了。

请问下我订阅的纽约时报双语版只有图片和摘要没有正文正常吗？浏览器里打开rss链接的话是有正文的。

**Comment by cdhigh** [comment]
重新订阅，订阅的时候选择isfulltext
