### ISSUE TITLE
批量导入订阅源时，如何设定全文/摘要的属性？

### ISSUE THREAD

**Issue by yefoenix** [cdhigh/KindleEar#493]
默认全是摘要源？

**Comment by cdhigh** [comment]
opml标准里面没有定义 ‘全文/摘要' 的域，所以我只能在里面添加了一个’isfulltext‘自定义域，如果是从KindleEar导入的xml文件修改后再导入是会保留’全文/摘要'属性的，如果是其他软件生成的xml，则没有这个自定义域，则KindleEar全部按摘要订阅源处理，因为这样处理对于全文订阅源或摘要订阅源都能正常抓取信息（一般来说）。
看来可以考虑在导入时添加一个选项，设定导入时的默认处理方式。

**Comment by yefoenix** [comment]
嗯对于全文的源，再进行抓取全文有点浪费资源。我之前不知道已经有了 isfulltext 这个自定义域，建议写到faq里，这样导入之前大家可以手动处理一下，倒是也不复杂。

**Comment by cdhigh** [comment]
这其实是我在导入界面放一个“保存”按钮的原因，保存下来后就知道文件结构了，不过还是添加一个选项好了。

**Comment by cdhigh** [comment]
1.25.5已经添加此选项
