### ISSUE TITLE
网站不翻墙访问

### ISSUE THREAD

**Issue by YHSM** [cdhigh/KindleEar#496]
步骤：1'申请一个域名，可以申请免费的顶级域名.tk。网址： kindleear.tk    体验账号和密码:YHSM
              域名申请网址：http://www.freenom.com
           2'寻找域名解析服务商，然后在freenom的域名管理中添加 nameserver。这里选择的是dnspod， 
           nameserver为A.DNSPOD.COM 、B.DNSPOD.COM、C.DNSPOD.COM三个,别忘记保存
           3‘在GAE自定义网域中添加域名并绑定域名解析服务商，并在域名解析服务商处添加解析记录

**Comment by wangzan200808** [comment]
绑定之后，需要多久才能访问呢？

**Comment by YHSM** [comment]
不到一炷香时间。

**Comment by wangzan200808** [comment]
已经可以访问了
