### ISSUE TITLE
建议添加RSShub的友情链接or别的类似内容

### ISSUE THREAD

**Issue by Sciroccogti** [cdhigh/KindleEar#497]
因为发现[RSS hub](rsshub.app)确实是不可多得的RSS平台，而本respo**似乎**还没有相关内容，建议考虑添加一下？

仅是建议，并没有考虑太多因素，也没有利益相关2333如有冒犯还请见谅。 

[RSS hub GitHub](https://github.com/DIYgod/RSSHub)

**Comment by cdhigh** [comment]
没有什么冒犯之说，话说我曾经也想提供一个‘官方’的wiki页面，提供一个RSS列表的，但是碍于精力有限，而且每个人都兴趣爱好不一，很难提供到很全的列表，所以作罢，曾经狗耳朵是一个很好的RSS列表源（狗耳朵很良心，源都提供源地址），我们可以通过狗耳朵获取到我们感兴趣的地址。
至于你提到的RSS HUB，是不错的资源，我会添加一个链接到首页上。
