### ISSUE TITLE
AppSpotMail 模式无法抓取知乎专栏文章

### ISSUE THREAD

**Issue by yefoenix** [cdhigh/KindleEar#499]
日志显示
`2018-07-30 07:23:48.132 HKT
fetch page failed(404 Not Found):https://zhuanlan.zhihu.com/p/36668981. (/base/data/home/apps/b~yfkindleear/worker:1.411079096033811762/books/base.py:495)`

**Comment by cdhigh** [comment]
所以内置订阅知乎日报才需要一个转发器啊，知乎屏蔽了GAE的IP段的访问。

**Comment by Tianluo-Qi** [comment]
请问一下这个转发器要怎么用呢？这里是代码小白
