### ISSUE TITLE
send  to  my kindle Email 

### ISSUE THREAD

**Issue by DeanWanghewei** [cdhigh/KindleEar#500]
![image](https://user-images.githubusercontent.com/22656622/43466496-3c2dc7b0-9512-11e8-846f-728fcb2fe5c4.png)
log日志
`{
 httpRequest: {
  status:  503   
 }
 insertId:  "5b603328000cda699667a74c"  
 labels: {
  clone_id:  ""   
 }
 logName:  "projects/kindlepushspider/logs/appengine.googleapis.com%2Frequest_log"  
 operation: {
  first:  true   
  id:  "5b60332800ff0cccb2b1369fb20001737e6b696e646c65707573687370696465720001776f726b65723a31000100"   
  last:  true   
  producer:  "appengine.googleapis.com/request_id"   
 }
 protoPayload: {
  @type:  "type.googleapis.com/google.appengine.logging.v1.RequestLog"   
  appEngineRelease:  "1.9.54"   
  appId:  "s~kindlepushspider"   
  cost:  1.08405e-7   
  endTime:  "2018-07-31T10:00:08.841901Z"   
  finished:  true   
  first:  true   
  host:  "worker.kindlepushspider.appspot.com"   
  httpVersion:  "HTTP/1.1"   
  instanceIndex:  -1   
  ip:  "0.1.0.2"   
  latency:  "0.003067s"   
  method:  "GET"   
  moduleId:  "worker"   
  referrer:  "https://kindlepushspider.appspot.com/deliver?u=admin"   
  requestId:  "5b60332800ff0cccb2b1369fb20001737e6b696e646c65707573687370696465720001776f726b65723a31000100"   
  resource:  "/worker?u=admin&id=5712088936742912"   
  responseSize:  "970"   
  startTime:  "2018-07-31T10:00:08.838834Z"   
  status:  503   
  taskName:  "3132270889903974696"   
  taskQueueName:  "deliverqueue1"   
  traceId:  "a3a71759f3d1ff3501de12f58836177d"   
  userAgent:  "AppEngine-Google; (+http://code.google.com/appengine)"   
  versionId:  "1"   
 }
 receiveTimestamp:  "2018-07-31T10:00:08.843123376Z"  
 resource: {
  labels: {
   module_id:  "worker"    
   project_id:  "kindlepushspider"    
   version_id:  "1"    
   zone:  "us10"    
  }
  type:  "gae_app"   
 }
 timestamp:  "2018-07-31T10:00:08.838834Z"  
 trace:  "projects/kindlepushspider/traces/a3a71759f3d1ff3501de12f58836177d"  
}`

**Comment by DeanWanghewei** [comment]
中亚的账号不能send  么？

**Comment by cdhigh** [comment]
可以发中亚，理论上什么邮箱都可以，出错是其他原因，你给出的log没有包含错误信息，你要再找找后台的log，每次出错都会有记录的。
