### ISSUE TITLE
KindleEar-Uploader 内没有修改 config.py 中 Domain 参数

### ISSUE THREAD

**Issue by Sciroccogti** [cdhigh/KindleEar#502]
建议也顺便加一个自动改version 的小功能吧😊

**Comment by cdhigh** [comment]
有修改DOMAIN参数功能啊，你是不是用的是很旧的版本？
修改version的功能就不能添加了，version是我在发布版本时修改，你在部署时version不应随便修改，这是功能集的标识，如果你要修改，version在apps/__init__.py里面，你要怎么修改就这么修改。

**Comment by Sciroccogti** [comment]
@cdhigh 欸？我用的是readme链接里给的啊（Google drive）
然后那个version因为我看都是1，emmmmm可能确实是我下的版本有鬼吧😅

**Comment by cdhigh** [comment]
有的，google drive里面是有DOMAIN参数的。
至于version=1，这个version不是kindleear的version，是部署version，不是应用version。
如果不了解，就忽略它就可以了，默认version=1
