### ISSUE TITLE
GAE中出现这个日志错误

### ISSUE THREAD

**Issue by SleepyHeadyxx** [cdhigh/KindleEar#504]
![image](https://user-images.githubusercontent.com/40975841/43997362-5319d250-9e0b-11e8-8a1b-7d096f0750a1.png)
0.1.0.3 - - [11/Aug/2018:21:56:47 +0800] "GET /_ah/start HTTP/1.1" 404 123 - "-" "0.1.worker.kindle2491330857.appspot.com" ms=NaN cpu_ms=3176 cpm_usd=1.3746e-8 loading_request=1 instance=00c61b117cc813f9ed0d018f3e197b8f79087920e8d74576453647e30529ee7e6e09819749 app_engine_release=1.9.54 trace_id=7366842a05949f06406a6b6171d7ad99
全部展开 | 全部收起 {
 httpRequest: {…}  
 insertId:  "5b6eeb220007e8531a2e4ac1"  
 labels: {…}  
 logName:  "projects/kindle2491330857/logs/appengine.googleapis.com%2Frequest_log"  
 operation: {…}  
 protoPayload: {…}  
 receiveTimestamp:  "2018-08-11T13:56:50.518775284Z"  
 resource: {…}  
 severity:  "INFO"  
 timestamp:  "2018-08-11T13:56:47.796838Z"  
 trace:  "projects/kindle2491330857/traces/7366842a05949f06406a6b6171d7ad99"  
}
请问这是为什么，在kindleear中推送显示ok

**Comment by cdhigh** [comment]
INFO不是错误，无影响
