### ISSUE TITLE
KindleEar 显示发送状态OK，但Kindle接收不到推送

### ISSUE THREAD

**Issue by DemaroXion** [cdhigh/KindleEar#506]
推送状态显示OK，但推送成功后收到亚马逊退信邮件，提示推送不成功是什么问题，烦劳各位多多指教！

**Comment by Sciroccogti** [comment]
@DemaroXion 退信邮件上写的啥

**Comment by DemaroXion** [comment]
尊敬的客户，

您从2018年8月15日18:08 发出的如下文档无法发送到您指定的Kindle上：
* KindleEar_NVJTWM5X3SXGRCOBPAI7SDG5QWPTBIHO.pobi


Kindle个人文档服务目前只能转换并发送以下类型的文档：
Microsoft Word (.doc, .docx)
RTF文件(.rtf)
HTML(.htm, .html)
TXT文件(.txt)
Zip, x-zip压缩文件
Mobi格式电子书

JPEG (.jpg), GIF (.gif), Bitmap (.bmp) 和 PNG (.png) 格式的图片。
Adobe PDF (.pdf)文档可维持原文件格式，发送至您的Kindle。

Adobe PDF (.pdf)文档可转换为Kindle格式发送，目前处于试用阶段。

如上述格式的文档未成功发送，请确认文档是否受到密码保护或被加密。特别说明，目前最新的Kindle支持读取受密码保护的PDF文档。

以附件形式发送个人文档时的使用提示：

  *   每个附件文档大小应在50MB以下（压缩到ZIP文件中之前）
  *   邮件的附件数不能超过25个

要了解发送个人文档至Kindle的更多信息，请访问帮助页面：
http://www.amazon.cn/Kindledocuments/<https://www.amazon.com/gp/f.html?C=2ZN90T15N5CVX&M=urn:rtn:msg:20180815180820111fb012e5924a75acc7d026d980p0na&R=16FMM7L2IYONB&T=C&U=http%3A%2F%2Fwww.amazon.cn%2FKindledocuments%2F%3Fref_%3Dpe_1825130_138612630&H=GBP0BMAOIOSJWV4NHPZ3QXFZSKWA&ref_=pe_1825130_138612630>

如您需要人工协助，欢迎拨打客服电话 4008170100(国内客户) 或 +86-22-59677408(国际客户)

真诚地，
亚马逊Kindle客服

该邮件仅用于自动发送相关说明及通知，请勿回复。

进入Kindle商店选购<https://www.amazon.com/gp/f.html?C=2ZN90T15N5CVX&M=urn:rtn:msg:20180815180820111fb012e5924a75acc7d026d980p0na&R=16FMM7L2IYONB&T=C&U=http%3A%2F%2Fwww.amazon.cn%2Fkindlestore%2F%3Fref_%3Dpe_1825130_138612630&H=7ZILYMEQCIJ7OFOQUHLEU9RTTRYA&ref_=pe_1825130_138612630>

如果您有更多有关Kindle的问题，请访问亚马逊Kindle帮助中心<https://www.amazon.com/gp/f.html?C=2ZN90T15N5CVX&M=urn:rtn:msg:20180815180820111fb012e5924a75acc7d026d980p0na&R=16FMM7L2IYONB&T=C&U=http%3A%2F%2Fwww.amazon.cn%2Fkindlesupport%2F%3Fref_%3Dpe_1825130_138612630&H=ROOPAWD0HHMDYOVXMFVZFXDJ5ESA&ref_=pe_1825130_138612630>
Kindle帮助中心提供常见问题解答，以及亚马逊Kindle客服专员的联系方式。
如需联系亚马逊Kindle客服，请点击帮助页面【联系我们】按钮，客服人员将通过电话或电子邮件与您取得联系。
________________________________
发件人: 无风引漩 <notifications@github.com>
发送时间: 2018年8月16日 3:45
收件人: cdhigh/KindleEar
抄送: DemaroXion; Mention
主题: Re: [cdhigh/KindleEar] KindleEar 显示发送状态OK，但Kindle接收不到推送 (#506)


@DemaroXion<https://github.com/DemaroXion> 退信邮件上写的啥

―

**Comment by Sciroccogti** [comment]
@DemaroXion 文件格式不对，应该是mobi的2333，你看一下是不是写错了

**Comment by cdhigh** [comment]
可能是Calibre生成的mobi格式有些和“官方”标准有些不一致，或文件内有非法字符等原因，偶尔导致会被退回来，但是极少，我用的这几年总共被退回不超过10个推送。

**Comment by Sciroccogti** [comment]
@cdhigh 注意，他发送的格式是`pobi`而非`mobi`，应该是在自行修改代码时操作失误所致

**Comment by DemaroXion** [comment]
感谢各位的分享，与Amazon客服沟通后得到的答复是格式之前推送成功过就不会存在问题，之所以被退回是系统判定内容违规。经多次试验，发现直接通过KindleEar的Gmail邮箱推送容易产生退回或接收不到而没有任何提示的情况。
目前我采用了一种迂回解决办法：在KindleEar中只设置推送给自己的Outlook邮箱，在Outlook邮箱中设置自动转发规则。即可成功接受每一条推送。（当然需要在亚马逊个人文档设置增添自己的Outlook邮箱至可信任名单）
以上。
