### ISSUE TITLE
请教怎么将抓取到的网页发至邮箱

### ISSUE THREAD

**Issue by Steven630** [cdhigh/KindleEar#508]
请教一下，看到base里面有两个函数，是用来将抓取到的网页发到自己邮箱的。但是不知道具体怎么写到py里。
比如有一个源，用的是网页抓取，目录是 www.test.com/test 怎样才能让KindleEar将这个目录抓取后发送到我的邮箱呢？

新建一个py，然后写成下面这样可以吗。
```
def debug_mail(content, name='page.html'):
    from google.appengine.api import mail
    mail.send_mail(SRC_EMAIL, SRC_EMAIL, "KindleEar Debug", "KindlerEar",
    attachments=[(name, content),])

def debug_fetch(url, name='page.html'):
    if not name:
        name = 'page.html'
    opener = URLOpener()
    result = opener.open(url)
    if result.status_code == 200 and result.content:
        debug_mail(result.content, name)

testresult = debug_fetch(http;//www.test.com/test, name='page.html')
debug_mail(testresult, name='page.html')

```

谢谢。
---------------------------------------------------

> #将抓取的网页发到自己邮箱进行调试
> ```
> def debug_mail(content, name='page.html'):
>     from google.appengine.api import mail
>     mail.send_mail(SRC_EMAIL, SRC_EMAIL, "KindleEar Debug", "KindlerEar",
>     attachments=[(name, content),])
> ```
> 
> #抓取网页，发送到自己邮箱，用于调试目的
> ```
> def debug_fetch(url, name='page.html'):
>     if not name:
>         name = 'page.html'
>     opener = URLOpener()
>     result = opener.open(url)
>     if result.status_code == 200 and result.content:
>         debug_mail(result.content, name)
> ```

**Comment by cdhigh** [comment]
是正确的

**Comment by Steven630** [comment]
谢谢，还有一个小问题，这个并不是RSS，在订阅列表里看不见。那么怎么才能启动这个py呢？谢谢。

**Comment by cdhigh** [comment]
可以使用邮件触发，比如接收到特定的地址page@youid.appspotmail.com的邮件则启动抓取。
在handlemail.py里面添加一个判断即可。

**Comment by cdhigh** [comment]
说起邮件触发，我才想起，其实KindleEar已经有这个功能了。
发送到debug@youid.appspotmail.com 并在邮件正文里面写上要抓取的链接即可，如果多个链接则每行一个。
不需要你再实现了

**Comment by Steven630** [comment]
非常感谢，确实是很实用的功能。debug邮件附件的网页除了发送到管理员的gmail邮箱，有没有办法发送到指定邮箱呢？毕竟国内上gmail还是不太方便。

**Comment by cdhigh** [comment]
自己改一下就好了嘛，想发那个邮箱还不是随意。
毕竟这个是调试功能，发送至管理员邮箱是理所当然的做法。

**Comment by Steven630** [comment]
谢谢
