### ISSUE TITLE
网站将GAE地址封了？

### ISSUE THREAD

**Issue by Steven630** [cdhigh/KindleEar#509]
Economist网站debug抓取的网页是空白页，源代码如下：

```
<html>
<head>
<META NAME="robots" CONTENT="noindex,nofollow">
<script src="/_Incapsula_Resource?SWJIYLWA=5074a744e2e3d891814e9a2dace20bd4,719d34d31c8e3a6e6fffd425f7e032f3">
</script>
<body>
</body></html>
```

是不是将GAE地址封了？有什么办法解决吗。谢谢。

搜索了一下，可能是Incapsula的反爬虫机制，不知道该怎么办

**Comment by cdhigh** [comment]
针对“反爬虫”机制的突破，需要综合性的措施，在GAE这种严格限制的平台上不是那么容易实现，比如无法javascript等。
一旦一个网站开始启用反爬虫，最好的方法就是本地模拟真实浏览器登录，其他的办法都不一定能持久使用，因为反爬虫会不停升级。
在一个逐步封闭的网络上，以后获取“免费”信息的渠道会越来越难。
RSS也在逐步消亡。。。

**Comment by Steven630** [comment]
看来没办法了，谢谢
