### ISSUE TITLE
cartoonmad打开图片失败

### ISSUE THREAD

**Issue by insert0003** [cdhigh/KindleEar#511]
http://web4.cartoonmad.com/c8n3o733a62/1152/001/001.jpg
利用URLOpen打开cartoonmad的图片网址的时候，无法打开页面。提示如下的信息。
`<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>403 - Forbidden: Access is denied.</title>
<style type="text/css">

</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>403 - Forbidden: Access is denied.</h2>
  <h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>
 </fieldset></div>
</div>
</body>
</html>
`

如果使用urlopen(url).read()，则可以正常获得图片数据，这个可以通过修改URLOpen来完成吗？
或者针对cartoonmad直接使用urlopen(url).read().

**Comment by insert0003** [comment]
我自己的git里，直接使用urllib2.urlopen改了下，可以正常推送cartoonmad。
https://github.com/insert0003/zkindlerss/commit/c8bd9af41936b6064bfa01266c5017979d6b177e

**Comment by cdhigh** [comment]
因为之前是可以的，而现在出现Forbidden，说明网站已经开始防盗链或反爬虫，直接使用urllib2.urlopen能下载，我更愿意相信是caroonmad程序员的疏忽或程序的BUG，所以说不定什么时候urllib2.urlopen()也用不了了。
urllib2.urlopen和urlopener的相同点是后台都使用同样的API接口：urlfetch.fetch();
区别是urlopener带cookie和Referer，而cookie和Referer是用来反“反盗链”和登录使用。
urlopener()里面有一个参数：addreferer，设置为False则不添加Referer。
而cookie我暂时没有提供参数取消，如果后面证实是cookie的问题，可以添加一个参数。

**Comment by cdhigh** [comment]
问题是urllib2没有失败重试。
我抽时间看看是什么原因。

**Comment by insert0003** [comment]
OK, 3Q. 顺便咨询个别的问题，你有什么建议吗。
我尝试去爬另一个网站，manhuagui，本地的gae模拟可以实现，上传到gae上以后出现了问题。
https://github.com/insert0003/zkindlerss/blob/master/books/comic/kanmanhuabase.py
1 需要使用lzstring解压缩一段代码，在kindleear里面加入第三方库可以实现，但是感觉加了很多的东西。kindleear里面有没有可以用的库呢？
    def getImgList(self, url):
2 有一段js，需要用nodejs来运行，我找了个在线nodejs的网站，用接口实现了。
    def get_node_online(self, input_str):
3 manhuagui保存的图片为webp的格式的，想使用PIL转换成jpeg保存。在img.py里加了一个def convert_image(data):的函数，本地的环境ubuntu16.04是好使的，ubuntu14.04和上传到gae以后，都出现了同一个错误。https://github.com/insert0003/zkindlerss/blob/master/lib/calibre/utils/img.py
   错误log: cannot identify image file, in file 'Image.py', open (line 1980)
   比较发现ubuntu14和16的PIL的版本一样，但是代码有些不同。

**Comment by cdhigh** [comment]
1. 如果实在需要lzstring库，就引入吧
2. 这个在线nodejs是不错的资源，但是应用范围其实也不大，因为很多js都有很多依赖，不过用于具体的算法模块之类的倒是一个好主意。
3. 在PIL的官方文档中没有webp支持，如果ubuntu16.4支持的，说明其修改了PIL代码，但是又没有修改版本号，又没有提交pullrequest到PIL，实在不是合格的开源精神。
