### ISSUE TITLE
kindleear推送有大小限制吗？

### ISSUE THREAD

**Issue by yondor** [cdhigh/KindleEar#512]
多订阅了几个订阅发现无法推送，查看日志有31MB，
之前订阅发送大小只有23MB，一直可以成功推送的。
请问这个推送大小限制是哪个导致：
1、Gmail邮箱发送限制？
2、kindle邮箱接收限制？
3、kindleear程序限制？

**Comment by cdhigh** [comment]
GAE限制的，25M
