### ISSUE TITLE
求教如何手动推送自定义的rss源，是自定义的！

### ISSUE THREAD

**Issue by Aaron-Rong** [cdhigh/KindleEar#516]
在“高级设置“里的“现在投递”只能投递在kindle ear里自带的rss源，并没有见到自定义的rss源，在”设置"里也没有见到有“现在投递”，我看了别人的图都有这个的，是因为现在的已经改版了吗

**Comment by cdhigh** [comment]
1. 先在“设置”页面选择“自动定时投递自定义RSS”
2. “高级设置”里面的“现在投递”将会出现自定义RSS的书籍名字（就是“设置”页面的区段“自定义RSS设置”里面的属性“书籍标题”）
3. 如果你只订阅自定义RSS，没有订阅任何内置书籍，则“现在投递”会将每个自定义RSS都单列出来。

**Comment by Aaron-Rong** [comment]
万分感谢！还有一个问题想问一下，就是自定义的那些rss打开网址出现This XML have no style information...是什么问题？是表示这个rss已经不能用了吗？

**Comment by cdhigh** [comment]
这个无所谓，要看是否是合法的Xml，可以右键查看网页源文件

**Comment by Aaron-Rong** [comment]
好的，今天已经正常推送，谢谢！
