### ISSUE TITLE
本次更新后的bug： 漫画投递后期号不会自动更新

### ISSUE THREAD

**Issue by mlyksuu** [cdhigh/KindleEar#518]
![mw073 2018-09-18](https://user-images.githubusercontent.com/7322734/45688720-b580e280-bb84-11e8-87cc-2c52e3cf545d.png)
如图所示，推送了37话，但期号没有相应更新，依然显示36，于是反复推送37话。

**Comment by cdhigh** [comment]
@insert0003 帮忙看看？
还有，如果要修正此问题的话，顺便也帮我修正issue #514
删除apps/handlemail.py(line 236)行即可。
`from main import local_time`
劳烦了。

**Comment by insert0003** [comment]
OK，明天看看。

**Comment by insert0003** [comment]
我这面测试了没有问题呢。log发一下看看？

![kindleear](https://user-images.githubusercontent.com/11204704/45726050-97ed6080-bbf8-11e8-82b5-ab269c97c0c6.png)

**Comment by mlyksuu** [comment]
log...是指这个吗
![mw073 2018-09-19](https://user-images.githubusercontent.com/7322734/45729754-8740e880-bc00-11e8-943b-6c414ebdfd1d.png)
我点了手工推送
------
之前cartoonmad抓取出了问题的时候，每次推送过后期号都会增加，但没有东西推送到kindle。那时我到zkindlerss里下了个cartoonmadbase.py覆盖过去，就变成了能推送但期号不会自动增加的状况。后来这边KindleEar更新了，我又把整个项目重新拖了一遍重传，结果问题依旧。不知道问题出在哪里

**Comment by insert0003** [comment]
KindleEar和zkindlerss有点小差别。
KindleEar发送失败也会继续增加期号，所以有可能出现发送失败期号也增加。
zkindlerss修改了一点数据库，如果发送失败就不增加期号。
两个不能混用，直接覆盖cartoonmadbase.py会有问题，出现期号永远不增加的现象。
只用最新的KindleEar的话，应该可以正常增加期号，但是发送失败的时候也会增加期号。
所以我推荐，要么就完全用KindleEar，或者完全用zkindlerss。我自己一直的zkindlerss，你用那个也行。

**Comment by mlyksuu** [comment]
谢谢
不过我这次有把原来的文件全删掉，重新下了KindleEar，改了再部署的，应该没有混搭……
等有时间我再试试砍掉重练_(´ཀ`」 ∠)_

**Comment by insert0003** [comment]
log指的是gcloud里面的日志，可以查看运行过程中输出的错误，警告等。
![gae01](https://user-images.githubusercontent.com/11204704/45734998-5f15b180-bc21-11e8-9f71-d18e751a4115.png)
![gae02](https://user-images.githubusercontent.com/11204704/45735005-676dec80-bc21-11e8-9b36-e0a876263704.png)

**Comment by mlyksuu** [comment]
新建了个app传了没有修改过的zkindlerss，自定义RSS和现成book各订一个漫画，手动推送几次，也出现了奇怪的bug
![mw073 2018-09-19](https://user-images.githubusercontent.com/7322734/45750429-a449db80-bc41-11e8-9732-da122c9774fd.jpg)
我的英雄学院跳跃推送（2、5、9话
Planet with第一次推送成功后一直no news

真是很迷இωஇ

**Comment by insert0003** [comment]
> 我的英雄学院跳跃推送（2、5、9话)
这是我故意的，不是跳跃推送，是一次性推送了多话，正确的显示应该1-2话，3-5话，6-9话。意图是当有很多话更新的时候，可以一次性推送，但是为了防止页数太多文件太大，所以设置页数超过60的话，就换到下次推送。

**Comment by insert0003** [comment]
> Planet with第一次推送成功后一直no news

不好意思，这是zkindlerss的bug，标题中间不能有空格。内部逻辑的问题，需要修改。
你先把标题改成PlanetWith试试？

**Comment by mlyksuu** [comment]
原来乳齿！这下算是基本没有问题了谢谢！
