### ISSUE TITLE
考虑兼容python3？

### ISSUE THREAD

**Issue by specter119** [cdhigh/KindleEar#522]
我发现GAE建立的python环境中已经包含python3.5了，虽然版本有点低，但是可以考虑支持？

**Comment by cdhigh** [comment]
短期内没有可能，最重要的是Calibre不支持，我自己写的代码基本上都是兼容2.x和3.x的，因为我平时使用的都是Python3。

**Comment by specter119** [comment]
@cdhigh 感谢，那这个issue先留着把。

**Comment by cdhigh** [comment]
既然无法解决，所以留着干嘛，而且非得花大代价兼容3.x意义不大
