### ISSUE TITLE
怎样发送中文的html

### ISSUE THREAD

**Issue by anson2416** [cdhigh/KindleEar#530]
使用肥皂下载好的html，怎样使用python发送出去？测试了很久都是接收到的文件内容是乱码。谢谢。

**Comment by cdhigh** [comment]
肥皂 是什么？
说明也没头没尾，
最好看看 "提问的艺术"

**Comment by anson2416** [comment]
我使用python requests库下载了一个html的文本。
使用python email模块把该html作为附件发送到kindle的时候会乱码。
请问你知道怎与解决吗？
注意：mobi没有问题。

**Comment by cdhigh** [comment]
是不是html文件头的编码声明不正确？
如果一直搞不定，又嫌mobi麻烦，可以考虑发epub，如果不用calibre，生成epub更简单，就一个zip文件

**Comment by anson2416** [comment]
请问你有邮箱马吗？我想把附件发给你看一下。
对于epub，我暂时不清楚怎样生成。

**Comment by cdhigh** [comment]
epub格式虽然很简单，但也不是一两句话能讲清楚的，要善于搜索，而且也有很多库可以直接生成epub。
