### ISSUE TITLE
求教怎么自定义书籍上传到Books目录

### ISSUE THREAD

**Issue by 99junlin99** [cdhigh/KindleEar#540]
我是采用的简洁搭建方式（使用uploader），不知道怎么把自定义的书籍py上传到gcp，我使用这种方式上传，似乎不行，图片如下
![qq 20190123205800](https://user-images.githubusercontent.com/35255028/51608288-ff723e80-1f51-11e9-9d75-1088bc1c85d2.png)

**Comment by cdhigh** [comment]
暂不支持书籍放到存储分区，现在都放在代码分区，将书籍添加到你的github代码仓库，再部署一次即可。

**Comment by 99junlin99** [comment]
这么简单的道理我竟然忘了。。。🙃🙃多谢多谢，我去fork之后更改一下updownloader应该就可以了吧。不过我有点好奇为啥我用我的gae直接用rm -f ./KindleEar竟然不能删除

**Comment by 99junlin99** [comment]
我昨天fork之后，修改了NiuLiu.py，然后修改了一个updownloder。。。但似乎并没起到作用。。。updownloader图片在下面，fork的修改在books里的biquge中
![gew ublidp sajmb2pm](https://user-images.githubusercontent.com/35255028/51648531-d8e8ed80-1fbb-11e9-9170-2328c7c3156c.png)

**Comment by cdhigh** [comment]
你确认有NiuLiu.py？

**Comment by 99junlin99** [comment]
那肯定有啊。。。。
![qq 20190124222940](https://user-images.githubusercontent.com/35255028/51684702-a1178f80-2027-11e9-9696-1a00cb1efc0a.png)

**Comment by cdhigh** [comment]
我指的是你的代码仓库

**Comment by 99junlin99** [comment]
我把NiLiu.py直接改为了ShaShen.py然而逆流修真时代还是有
![qq 20190125084705](https://user-images.githubusercontent.com/35255028/51717932-db138080-207d-11e9-910d-37afd2d8328a.png)

**Comment by anything-everything** [comment]
安装完成后，一直无法访问私人链接；https://cx1724.appspot.com/

**Comment by 99junlin99** [comment]
没挂vpn，这很简单
