### ISSUE TITLE
订阅reddit一直不成功

### ISSUE THREAD

**Issue by Tianluo-Qi** [cdhigh/KindleEar#544]
我尝试了以下两种reddit订阅方法：
1.用reddit自带的在网页后面添加‘.rss’字符串生成订阅链接，并且试了https://www.reddit.com/r/pathogendavid/comments/tv8m9/pathogendavids_guide_to_rss_and_reddit/
这里面的大多数方法
2.生成链接后再用feedburner烧一下（后面已添加fqa中所说字符串）
这两种方法在feedly上都可以正常显示内容，但是推送到kindle上面后，显示的不会是一楼，或者我想要的没一楼的东西，而似乎每个帖子都是各自subreddit的介绍什么的：比如r/Fantasy就会显示“please be ware that the sidebar in 'old' Reddit is no longer……about mission /r/Fantasy is the internet's largest discussion……”；r/lotr则会显示"all that is gold does not glitter……don't put movie spoilers in post titles!……"
请问一下这个要怎么解决？

**Comment by cdhigh** [comment]
怎么我尝试了
https://www.reddit.com/r/pathogendavid/comments/tv8m9/pathogendavids_guide_to_rss_and_reddit/
上面给出的几个例子链接，好像是可以的？
