### ISSUE TITLE
How do you generate the mobi/epub books?

### ISSUE THREAD

**Issue by starkshaw** [cdhigh/KindleEar#548]
Hi all,

I have found this project from [here](https://bookfere.com/post/19.html). However, I am currently using a similar product (Reabble). But I am not very pleased with the font it is using. Like this image:

![kindleear-rss](https://user-images.githubusercontent.com/9618357/53842968-e5883a80-3f98-11e9-840b-ed3b0a384a04.png)

So, considering the fact that now Kindle supports custom font, I want to generate my own RSS magazine in order to customize the font in it. I wonder how do you generate books in your implementation? I see you have Calibre included, did you use that to generate the book? What is the template like?

Thanks.

**Comment by cdhigh** [comment]
Yes, The Calibre module can embed a font in book, but I didn't implement the feature yet.
You can try it youself and contribute to KindleEar project.

The relevant parts are 'apps/Work/Worker.py' and 'lib/calibre/ebooks/mobi'
1. lib/makeoeb.py -> getOpts() -> set mobi_file_type to 'both'
2. add a manifest of font to OEB instance
3. modify a css to use the font you added. (maybe not need to do it)

**Comment by starkshaw** [comment]
Hi,

I think you may misunderstood me.

I meant not embedding the font to the book, but to use the fonts stored in `/fonts/`. I think a simple CSS can do.

What I am curious is how to generate this “magazine” type of book and what format is it natively in, and what structure of the files are in the package.

Thanks.

**Comment by cdhigh** [comment]
You can browser code in worker.py.
mobi = htmls + images + css.

magazine type is a feature of kindle reader, it shows the contents of book as magazine type when a bit in head of book is set to 'magazine'.
