### ISSUE TITLE
kindleear怎样才能使用https？

### ISSUE THREAD

**Issue by luckyfatpig** [cdhigh/KindleEar#551]
kindleear怎样才能使用https？另外能增加像send to kindle那样推送网址到kindle的功能吗？

**Comment by cdhigh** [comment]
1. 直接使用https://appid.appspot.com就支持https
2. <https://kindleear.appspot.com/static/faq.html#mailservice> 不知这个功能是否是你所说的？

**Comment by luckyfatpig** [comment]
第2个功能看了说明弄不明白，添加白名单指的是哪里添加白名单？试了kindleear里添加了发送网址的邮箱地址，kindle的白名单添加了kindleear的appspot邮箱，发送没有反应

**Comment by cdhigh** [comment]
可能是FAQ太啰嗦了：）
这里的白名单就是你要使用哪些地址向KindleEar发邮件。
如果添加了合适的白名单，并且发送没有反应，可以打开GAE后台，看是否有收到，是否已经拒收？

2. 要抓取图片只能全部抓取，如果想按每个区别定制，则需要写一个py文件，放到books目录下。
py文件里面就有属性可设置是否抓取图片:keep_image
