### ISSUE TITLE
错误提示 wrong SRC_EMAIL

### ISSUE THREAD

**Issue by AlessandroChen** [cdhigh/KindleEar#552]
根据之前的Issue我尝试添加Email

然而我的添加选项是灰色的。Doc也没有相应问题，请问有什么办法吗

**Comment by cdhigh** [comment]
是不是你使用了不同的gmail部署的？
可以尝试部署前清除auth缓存，忘了命令了，不过好像其缓存文件名为appcfg_oauth2_tokens，搜索删除即可。
