### ISSUE TITLE
伪多接收邮件地址的正则判断修正建议

### ISSUE THREAD

**Issue by duxingmoyu** [cdhigh/KindleEar#557]
您好！
感谢开发出了这么好的Rss订阅开源工具，经过一下午的折腾，收益良多。
在部署及设置过程中，遇到了这样的问题：

发送状态日志列表：
![image](https://user-images.githubusercontent.com/5433616/56428773-2e9b1080-62f3-11e9-8b23-29b6cb0ac7ac.png)

其中多次出现了邮件返回值为：
[u'duxxx@kindle.com',u'']的send failed 状态，

经过多方比对，发现是由于只有1个收件人，但是收件人后加了“;”造成的，系统误以为需要解析多个收件人，但是第二个为空，因此出现错误。

能否修正为自动判断‘;’之后的字符，如果不构成xxx@kindle.xxx 的格式，则自动截去该字符与之前的”；“，防止出现解析值为空因此发送失败的情况？

**Comment by cdhigh** [comment]
这是一个小BUG，记录下来了，之后修正

**Comment by cdhigh** [comment]
针对强迫症，已在1.26添加，1.26还加了一个 “共享库” 功能，可以看到其他网友的推荐订阅源。
