### ISSUE TITLE
可以将calibre的recipe导入到kindleear使用吗？

### ISSUE THREAD

**Issue by pundits** [cdhigh/KindleEar#558]
可以将calibre的recipe导入到kindleear使用吗？Calibre 的recipe可是个宝库啊

**Comment by cdhigh** [comment]
一般来说不行，因为KindleEar只是实现了Calibre的一个有限子集。
有部分recipe能直接用，改成py后缀即可，但是大部分应该不行。
用之前核对一下里面的属性设置，如果KindleEar都有对应的实现，就可以直接用。
