### ISSUE TITLE
有必要添加kindle paperwhite4的支持?

### ISSUE THREAD

**Issue by wy-luke** [cdhigh/KindleEar#559]
现在我的是最新版的kindle pw4,但是选项里面没有,会有妨碍吗?
其实就是强迫症不能选有点难受

**Comment by Au3C2** [comment]
pw3和pw4没有区别吧，在calibre里也找不到区别

**Comment by cdhigh** [comment]
针对强迫症，已在1.26添加，1.26还加了一个 “共享库” 功能，可以看到其他网友的推荐订阅源。
