### ISSUE TITLE
能否在处理图像时加入图像压缩？

### ISSUE THREAD

**Issue by Au3C2** [cdhigh/KindleEar#560]
这样能够减小邮件附件的大小，可以将图像压缩成灰度图

**Comment by cdhigh** [comment]
已经转换成灰度图了

**Comment by cdhigh** [comment]
还有，如果想压缩的更小，可以选择推送到设备类型为Kindle（最老的型号）即可，选定型号越新，生成的图片越大。
因为KindleEar会将图片缩小为对应设备类型的分辨率。
如果Kindle类型还不够小，则自己修改config.py里面 REDUCE_IMAGE_TO 即可，比如
REDUCE_IMAGE_TO = (400, 600)

**Comment by Au3C2** [comment]
> 还有，如果想压缩的更小，可以选择推送到设备类型为Kindle（最老的型号）即可，选定型号越新，生成的图片越大。
> 因为KindleEar会将图片缩小为对应设备类型的分辨率。
> 如果Kindle类型还不够小，则自己修改config.py里面 REDUCE_IMAGE_TO 即可，比如
> REDUCE_IMAGE_TO = (400, 600)

请问，如果修改为“REDUCE_IMAGE_TO = (400, 600)”，漫画的分辨率也会更改吗？

**Comment by cdhigh** [comment]
是的，压缩是全局的，如果部分书籍不想压缩，定制内置书籍py文件即可

**Comment by Au3C2** [comment]
> 是的，压缩是全局的，如果部分书籍不想压缩，定制内置书籍py文件即可

好的，非常感谢你的回复！
