### ISSUE TITLE
推送排序

### ISSUE THREAD

**Issue by 269774331** [cdhigh/KindleEar#562]
请问，我有订阅自带的内容并添加自定义的源，在推送的时候，那些自定义添加的源会合成一本书排在自带的订阅源前。请问怎么才能让自定义的源排在自带的订阅源后面（推送的时候选的是合成一本书）。

**Comment by cdhigh** [comment]
现在没有排序，采用默认顺序，应该就是创建数据表时的顺序。
如果你想要排序，尝试修改 apps/view/deliver.py (line  50)
现在是 `books = Book.all()`
可以尝试修改为：
`books = Book.all().order('builtin')`
或：
`books = sorted(Book.all(), key=attrgetter('builtin'))`

**Comment by 269774331** [comment]
两种方法试过了，没用，有没有其它方法或者顶置或底置（自定义源的合集）

**Comment by cdhigh** [comment]
没用就反向排序，在builtin前加一个减号，
Book.all().order('-builtin')

**Comment by 269774331** [comment]
试过了，自定义源还是穿插在自带的订阅中

**Comment by cdhigh** [comment]
这有点没道理啊。
重新部署时有没有default和worker模块都部署了？
default对应app.yaml
worker对应module-worker.yaml

**Comment by 269774331** [comment]
感谢大佬，手动推送和自动推送都已经成功了，之前一直看的是手动推送
