### ISSUE TITLE
save to wiz / pocket 失败

### ISSUE THREAD

**Issue by alonewoo** [cdhigh/KindleEar#563]
save to wiz， 显示 No have wiz mail yet. 但是确认 高级设置/归档和分享 的页面加了wiz 邮箱 XXX@mywiz.cn,; 参考了issue #341 改了base.py: 
def makesharelink(  )
 .........
elif sharetype = 'wiz' : href='
http://note.wiz.cn/url2wiz?url=http%3A%2F%2Fwww.wiz.cn%2F&folder=%2F%E4%B8%AA%E4%BA%BA%E7%AC%94%E8%AE%B0%E6%9C%AC%2FMy%20Notes%2F&user=alonewoo@mywiz.cn&content-only=false'
还是提示没有wiz mail； 没改对地方吗？

save to pocket:
点击网站上的"高级设置" | "归档与分享"页面中的 'Save to Pocket' 区段的[申请授权]，设置了pocket 账号，返回： hash not match! kindlear refuse to execute your command.
按faq里改了config.py 里的POCKET_CONSUMER_KEY，填了自己的key，还是返回同样的提示。

**Comment by jinzaizhichi** [comment]
save to pocket:
我的设置成功了，key是web  那项。

**Comment by alonewoo** [comment]
重新运行uploader，pocket能用了.....
有一种方式能将kindle里的文字共享出来就可以了，关闭问题。
