### ISSUE TITLE
能否同步分享Rss阅读源？

### ISSUE THREAD

**Issue by suoba** [cdhigh/KindleEar#567]
背景：RSS源时不时就没了，又要去寻找更新，麻烦而且效率低。

1.假设甲的RSS阅读源很好，他也愿意乐意推荐给其它人。那他就可以一键分享出去。我就可以在我自己部署的KindleEar上看到他的推荐，当然了其它人也可以看到。依次类推。那么我们就有一个巨大量的优质的RSS源随时可以食用了。如果再考虑到订阅数和推荐数量，那么就更完美了。

2.考虑到有部分超级优质的RSS阅读源可能是甲自己手动写代码搞定的，如果大家能一键复制他的这部分代码（前提依然是甲先分享了），无缝的将他写的这个代码复制到自己部署的KindleEar上来使用，如果再考虑到能手动或自动更新这个RSS阅读源的代码，那就牛逼了！

    人人为我，我为人人。——大概就这意思。可惜我的水平只能提供idea，提供不了代码。

**Comment by cdhigh** [comment]
这个需求其实几年前就有人提了，那时候我就建议去 狗耳朵 “偷” RSS链接，因为 狗耳朵 很慷慨的将所有RSS订阅链接都公开了。几年过去了，不知道 狗耳朵 是否还活着，是否还公开 RSS链接，现在其实可以考虑此需求了。

不过因为GAE的资源限制，KindleEar使用了很多很多省资源的方式实现，“内测”的时候，我还使用ZIP打包订阅源文件，后来将其分开为几个文件（这样就不用在推送到时候再解压占用宝贵的内存和CPU时间），还去掉了jQuery库等。KindleEar处处透着“省吃俭用”的优良作风：）

所以现在的架构无法很简单在网页上分享网友自己写的订阅代码，对于分享网友的RSS订阅链接倒是可以实现，所以可以考虑先实现一个简单的版本，不过因为我已经维护了几年的KindleEar了，兴趣也消退了，精力也有限，不知什么时候能实现了。

**Comment by dianjiweiling** [comment]
这个可以配合rsshub一起用，能解决大部分问题

**Comment by cdhigh** [comment]
最近打算升一次级，把一些遗留问题处理一下，这个需求我也想想怎么实现

**Comment by cdhigh** [comment]
周末加了一个班，实现了一个我自己认为的 “共享库” 功能，所有KindleEar的用户都可以分享自己的订阅，不知好不好用，有感兴趣的试用一下呗，有问题可以反馈。
在1.26中已经实现。

**Comment by dianjiweiling** [comment]
请问下怎么升级？是重新pull安装吗？

**Comment by cdhigh** [comment]
当然，每次都需要pull安装。

**Comment by dianjiweiling** [comment]
好的，谢谢~

**Comment by suoba** [comment]
重新上传了一个新的app，试用了几天。感觉挺好！
有3个问题反馈一下：
1.当订阅的数量过多，合为一本书时候，书大于29M，推送失败，kindle默认是50M内，不知到是哪里的问题。如下图：
[推送失败](https://i.vgy.me/q3tlO2.png)
2.一开始是能正常看到“网友分享”的页面，也能订阅和分享。现在其它页面正常，唯独”网友分享“页面不正常，如下图显示：
[网友分享](https://i.vgy.me/JvpAOi.png)
3.我特地等了几天，发现”网友分享“这个rss数量没有变化过，除我自己分享的会有变化。换句话说，我没有接收到任何其它人分享的RSS链接信息。——除非这几天都没有人分享过，或者接收不了。

      我理解你的目前的构思是： 以自己的服务站作为中转RSS链接的，不知道理解得对不对。我在想去中心化的是不是更好，比如区块链/电驴kad节点的方式。当然了这个工作量我就不知道了，估计很大。我也只是随便说说，大家随便看看好了。不商业化运作的话，无需浪费太多时间。
     以上。谢谢！

**Comment by cdhigh** [comment]
1. 能推送到最大邮件小于30M，这个好像是Amazon限制的（我忘了具体细节），几年前就有过讨论和确认。
2. 这个是我的疏忽导致的，之前我已经向一个网友道歉了，是我在升级1.26.1中修改了API导致，所以请升级为1.26.1，以后不会再修改API了，不会再出现类似的问题。
