### ISSUE TITLE
保存到印象笔记报错。

### ISSUE THREAD

**Issue by Tsiung** [cdhigh/KindleEar#568]
我订阅了FT中文，https://feedx.net/rss/ftweekly.xml，选择保存到印象笔记，然后就报错，说链接不到服务器，经排查发现是制作期刊时，保存到印象笔记那个地址中的原url中的http被强制改成了https，生成的二维码也是https的，而FT中文又没有HTTPS访问，删除地址中的S，就可以保存到印象笔记了。希望能修正一下。

**Comment by cdhigh** [comment]
好的，后续修改

**Comment by cdhigh** [comment]
我现在着手修改，能简单说一下是哪个地址http被改成https吗？

**Comment by Tsiung** [comment]
> 我现在着手修改，能简单说一下是哪个地址http被改成https吗？
我用的这个rss 订阅地址https://feedx.net/rss/ftweekly.xml。   例如《中国各地面临基础设施支出下降 》这篇文章。原地址应该是http://www.ftchinese.com/story/001084158?full=y，但是生成的电子文档里保存到印象笔记生成的地址 是http://*.appspot.com//share?act=evernote&u=*&url=https%3A//www.ftchinese.com/story/001084158%3Ffull%3Dy （星号是我自己隐藏的），文章后生成的二维码也是https的https://www.ftchinese.com/story/001084158?full=y。

**Comment by cdhigh** [comment]
好的，明白

**Comment by cdhigh** [comment]
已在1.26修正。
