### ISSUE TITLE
新加账户不同订阅和其他账户相同的rss，显示重复订阅。

### ISSUE THREAD

**Issue by dianjiweiling** [cdhigh/KindleEar#570]
先用一个账户订阅并分享了每日一文rss。
之后添加个新账户，在网友分享里订阅每日一文就会显示“无法添加此订阅源，错误描述：重复的订阅！”，但此账户实际上并没有订阅。

**Comment by cdhigh** [comment]
对的，找到一个bug了，判断url时没有加上账户名

**Comment by cdhigh** [comment]
已在1.26.1修正

**Comment by dianjiweiling** [comment]
辛苦大佬啦
