### ISSUE TITLE
请问下能否在保留之前用户相关配置情况下进行升级？

### ISSUE THREAD

**Issue by dianjiweiling** [cdhigh/KindleEar#571]
给好友添加了账号，请问在升级时怎么才能保留之前的相关账号配置呢？

**Comment by cdhigh** [comment]
升级不影响账号和相关的订阅配置。

**Comment by dianjiweiling** [comment]
执行
`appcfg.py update KindleEar/app.yaml KindleEar/module-worker.yaml`
`appcfg.py update KindleEar/`
完成升级后，网友分享页面无法正常显示，全部为空
![tianruo_2019-9-3-637031006140415678](https://user-images.githubusercontent.com/16662089/64138396-7dbf8900-ce2f-11e9-900b-5687c081f24d.png)

**Comment by cdhigh** [comment]
你用的浏览器是什么版本？
因为我将部分计算从服务器移到浏览器了，估计有不兼容的情况，

**Comment by dianjiweiling** [comment]
> Google Chrome 已是最新版本
版本 76.0.3809.132（正式版本） （64 位）

我新建了一个应用从零安装，网友分享可以正常显示；但是从1.26升级过来的还是不能用（刚刚又确认了一遍）。

**Comment by cdhigh** [comment]
我自己的应用就是从1.26升级来的，没问题。
帮忙打开chrome的开发者工具，看看下部有没有红色的错误信息。

**Comment by cdhigh** [comment]
开发者工具在 菜单 更多工具 子菜单里

**Comment by cdhigh** [comment]
一般来说，这个是浏览器缓冲的问题，清除浏览器缓冲应该就好了，
但是我想知道究竟是那个错误

**Comment by dianjiweiling** [comment]
嗯，我也想知道啥问题，现在在吃饭，一会回去把日志提交上来

**Comment by dianjiweiling** [comment]
我刚试了下，并没有错误信息，而且我打开隐身浏览器也是这样，换了edge浏览器也是。
这是[网址](http://kindle-dianjiweiling.appspot.com/),用户test密码为test，会出现相同的问题。
另外，我用的是这个repo里的代码进行更新的https://github.com/miaowm5/KeUploader 
 ，但是我看代码好像并没有什么问题。

**Comment by cdhigh** [comment]
你没有升级成功，没注意到屏幕下部的版本号吗？还是1.26

**Comment by dianjiweiling** [comment]
确实执行
`appcfg.py update KindleEar/app.yaml KindleEar/module-worker.yaml`
`appcfg.py update KindleEar/`
并且有输出，为啥没有升级成功。请问下具体的升级步骤该如何做？

**Comment by cdhigh** [comment]
那就再执行一次部署步骤。

这是我的锅，此BUG也体现了个人项目的随意和不严谨，是因为我修改了API导致，以后我不会再修改已有API了，只会新增了。

**Comment by dianjiweiling** [comment]
嗯嗯，好的，多谢多谢
