### ISSUE TITLE
提个需求——能够自定义css——看大神是否接受

### ISSUE THREAD

**Issue by jxmlingyun** [cdhigh/KindleEar#572]
生成的epub文件内部其实并么有css文件来控制显示格式，希望可以增加一个上传自己css的功能，这样显示更加美观，感谢！
图中样式一栏是空的
![image](https://user-images.githubusercontent.com/3866004/64388540-f9107d00-d071-11e9-8470-894d2f05a747.png)

**Comment by cdhigh** [comment]
在books目录下添加一个py文件，在属性extra_css里可以添加css

**Comment by jxmlingyun** [comment]
感谢

**Comment by cdhigh** [comment]
1.26.2中添加 自定义上传样式表 功能

**Comment by jxmlingyun** [comment]
感谢。试用后有个bug，底栏显示异常。
![image](https://user-images.githubusercontent.com/3866004/64917735-0cd08780-d7c6-11e9-8f55-df00b15a756c.png)

**Comment by cdhigh** [comment]
这个是calibre自动处理以便在电子书上使用的，电子书只支持有限的css特性。

**Comment by cdhigh** [comment]
我搜索了一下，|是命名空间选择器，calibre给css自动添加了一个命名空间h，然后所有新导入的css都归入此命名空间，我不知道为何要这样，不过只要能用就好。

**Comment by cdhigh** [comment]
好吧，升级1.26.3，去掉样式表里面自动添加的命名空间。

**Comment by jxmlingyun** [comment]
已经升级了1.26.3。问题已经解决，感谢。
在此，建议使用kindleear的朋友试用一下这个功能，会让你的推送文件更加精致！
一个简单方法：如果你在平时看到有排版很好的epub电子书，可以解压（7zip就可以）这个epub电子书，解压后在style文件夹里面又有一个.css文件，就是把这个文件上传。上传的位置在网页端“高级设置—样式表”，点击选择文件，点击上传，就全搞定了。希望大家阅读愉快。再次感谢cdhigh！

**Comment by cdhigh** [comment]
去掉css命名空间 会导致一个问题: 在手机或电脑上观看推送的书籍会导致目录跳转到不正确的位置，看来还需要这个命名空间。
