### ISSUE TITLE
豆瓣广播rss推送无图片

### ISSUE THREAD

**Issue by jack110804** [cdhigh/KindleEar#573]
kindle截图：https://s2.ax1x.com/2019/09/08/n3zah8.png
rss地址：https://rsshub.app/douban/topic/51678
排序方式为最新
脚本中有图片地址，推送到kindle上并没有图片
脚本中加入了referrerpolicy="no-referrer"属性防止跨域，是因为kindleear触发了跨域导致图片无法加载吗？

**Comment by cdhigh** [comment]
查看了网页源代码，图片格式为webp，应该是Kindle还不支持。
如果要转换为JPG，目前暂时还不支持，要等GAE上的PIL库支持，参考 #511
