### ISSUE TITLE
投递两三天了,没有一次成功

### ISSUE THREAD

**Issue by playdougher** [cdhigh/KindleEar#577]
这两天投递了五六次,每次都说发送成功,但是投递日志里面什么都没有.

**Comment by cdhigh** [comment]
打开GAE后台的日志页面，看看有什么异常？

**Comment by cdhigh** [comment]
是不是漫画书？我发现了一个BUG，在1.26.2版本上引入的，会导致漫画书推送失败。

**Comment by playdougher** [comment]
我没有看漫画,看的是纽约时报之类的杂志 
日志是这里的吗.我对这控制台不太熟悉

![pic](https://user-images.githubusercontent.com/26463515/65257381-b485e680-db33-11e9-8a09-0b8f58676c49.png)

[gae_app__logs__2019-09-19T05-57.txt](https://github.com/cdhigh/KindleEar/files/3631966/gae_app__logs__2019-09-19T05-57.txt)

**Comment by cdhigh** [comment]
这个BUG从第一个版本开始就一直存在，不知为何现在才触发，你升级一下1.26.4看看，应该解决了。

**Comment by playdougher** [comment]
怎么升级?就把项目删掉重新来一遍吗?

**Comment by cdhigh** [comment]
不需要删掉，重新部署一次即可。
步骤都一样。

**Comment by playdougher** [comment]
刚才重新用./uploader.sh部署了一次,现在我看版本是1.26.3,推送后还是没看到投递
[gae_app__logs__2019-09-19T11-40.txt](https://github.com/cdhigh/KindleEar/files/3632124/gae_app__logs__2019-09-19T11-40.txt)
日志

**Comment by cdhigh** [comment]
那就没有部署成功，要1.26.4

**Comment by playdougher** [comment]
我重新执行一遍上传程序,还是1.26.3,不会弄了

**Comment by cdhigh** [comment]
你是用什么方法上传的？
所用命令？

**Comment by playdougher** [comment]
昨天用了这个
`./uploader.sh`

今天用了这个
`rm -f uploader.sh* && \
wget https://raw.githubusercontent.com/bookfere/KindleEar-Uploader/master/uploader.sh && \
chmod +x uploader.sh && \
./uploader.sh`

**Comment by cdhigh** [comment]
还没升级好？

**Comment by playdougher** [comment]
就把命令输进去,跑了一阵子.说升级好了,但还是一直1.26.3. 搞不懂哪里出问题了

**Comment by cdhigh** [comment]
那你将本地代码库全部删掉，从github重新下载，并确认apps/__init__.py里面的版本号是1.26.4，然后再使用本地脚本上传。

**Comment by playdougher** [comment]
最近网络不太行,过几天再试试

**Comment by rhuang-astro** [comment]
用bookfere的upload不能更新到1.26.4的原因是新的config.py文件与本地的冲突。 git pull 的时候需要处理冲突。

**Comment by cdhigh** [comment]
用这个脚本的大多数同学不懂处理冲突，建议给bookfere提一个issue修改上传脚本，应该pull完之后再覆盖config.py。

**Comment by bookfere** [comment]
上传脚本已修改。原来的处理方式确实会在拉取新版本时出现冲突的情况，修改后的脚本会读取旧配置的相关参数，重新拉取源代码后再应用到新配置文件中。
