### ISSUE TITLE
想问一下，马上2020年1月python2就要到期了，不知道什么时候可以出一个python3的版本？要不各路大神，咱们一起把代码迁移一下python3？

### ISSUE THREAD

**Issue by r0103** [cdhigh/KindleEar#579]
想问一下，马上2020年1月python2就要到期了，不知道什么时候可以出一个python3的版本？要不各路大神，咱们一起把代码迁移一下pytho年？

**Comment by cdhigh** [comment]
工作就是各种依赖库的移植和切换，最麻烦的就是Calibre，因为之前我本来就是魔改Calibre的很早版本（2013版本），而这几年Calibre的代码变动很大，所以移植Calibre的工作量最大。
还有web.py框架，我看官网对于python3的支持一直都是beta版，不知稳定性如何？要不只能切换为其他框架了，我最偏向于bottle，轻巧。
我看其他库都支持Python3了。

我自己的代码都是Python2/3兼容的，理论上不需要动，不过还需要测试。

**Comment by daimiaopeng** [comment]
又不是不能用（滑稽）

**Comment by cdhigh** [comment]
已经升级 3.0.0b，支持Python3
