### ISSUE TITLE
如何让推送的rss不显示封面

### ISSUE THREAD

**Issue by wsxzyz** [cdhigh/KindleEar#581]
kindleear主要每天用来看rss新闻的，非常方便，但是不需要封面的。在高级设置里我明明没选择封面，但是推送的时候还是有这张默认的封面。
![15698881782331717635337370636240](https://user-images.githubusercontent.com/56006829/65925093-f7a64c00-e3b4-11e9-930a-f638a66bc15d.jpg)
请问能不显示封面么，打开直接就是rss内容

**Comment by cdhigh** [comment]
config.py 
DEFAULT_COVER=None

**Comment by wsxzyz** [comment]
> config.py
> DEFAULT_COVER=None

多谢指点，十分感谢，学习了
