### ISSUE TITLE
安卓手机或者电脑阅读kindleear生成的书，目录无法正常跳转

### ISSUE THREAD

**Issue by wsxzyz** [cdhigh/KindleEar#583]
使用安卓手机或者电脑打开kindleear生成的mobi和epub时，能显示正常的目录，但点目录进去后跳转有些问题，跳不到指定的文章中。

如附件，目录点进去，大部分都无法正常跳转。
[测试epub.zip](https://github.com/cdhigh/KindleEar/files/3681367/epub.zip)
[测试mobi.zip](https://github.com/cdhigh/KindleEar/files/3681368/mobi.zip)

**Comment by cdhigh** [comment]
可以考虑换一个阅读器

**Comment by wsxzyz** [comment]
安卓上有什么阅读器推荐么？
试了alredaer好像不行，mobi和epub都有跳转问题。
fbreader阅读epub正常，mobi跳转也不正常。

**Comment by jxmlingyun** [comment]
> 安卓上有什么阅读器推荐么？
> 试了alredaer好像不行，mobi和epub都有跳转问题。
> fbreader阅读epub正常，mobi跳转也不正常。
> 我之前使用的kindleear远古版本1.20.21时候，所有阅读器都正常的。
> 更新kindleear1.26.4后，就出这个问题，请问有办法恢复老版本的文件格式么？

推荐多看阅读器

**Comment by wsxzyz** [comment]
> > 安卓上有什么阅读器推荐么？
> > 试了alredaer好像不行，mobi和epub都有跳转问题。
> > fbreader阅读epub正常，mobi跳转也不正常。
> > 我之前使用的kindleear远古版本1.20.21时候，所有阅读器都正常的。
> > 更新kindleear1.26.4后，就出这个问题，请问有办法恢复老版本的文件格式么？
> 
> 推荐多看阅读器

多看阅读对epub支持不错，但不支持mobi。
有时想把kindle上的mobi书传到安卓手机上看，不想转换格式的。
以前老版本kindleear制作的mobi是没有这个问题的。

**Comment by wsxzyz** [comment]
试了下1.26.2这个版本是没有目录跳转问题的

**Comment by cdhigh** [comment]
那就是1.26.3修改的，
起因是1.26.2添加了允许用户上传CSS文件定制书籍样式的功能，然后有网友反馈最后添加到书籍里的样式表和上传的不一样，自动添加了一个CSS命名空间。
然后我就将Calibre的这一个功能(自动添加命名空间)屏蔽了，因为我看新版本的calibre是默认禁止的。
看来还需要重新打开此功能。

**Comment by bookfere** [comment]
其实这个问题不是目录跳转的问题，而是电子书的格式化问题。我把问题的测试结果放在 lib/calibre/ebooks/mobi/mobiml.py 的 407 行的 [Comment ](https://github.com/cdhigh/KindleEar/commit/3bc5a74c2634ba0b0cfd96f8af3f6f54d69098a1#r35373348)里了，看看不注释一条代码会不会影响自定义 CSS 功能。

**Comment by cdhigh** [comment]
这样修改后你上传的书籍自定义样式表是否正常？

**Comment by bookfere** [comment]
正常的，没有添加 `h|` 前缀。

![epub-custom-css](https://user-images.githubusercontent.com/29969316/66265670-e645bf80-e84c-11e9-8915-92b6ffe16636.png)

**Comment by cdhigh** [comment]
已在1.26.5修正
