### ISSUE TITLE
升级版本（1.26.4 ）推送样式有问题

### ISSUE THREAD

**Issue by lppsuixn** [cdhigh/KindleEar#584]
旧版本(很久前的了，忘了记录)
![image](https://user-images.githubusercontent.com/12748339/66265717-87347a80-e84d-11e9-926f-7213340367ac.png)

新版本（1.26.4 ）
![image](https://user-images.githubusercontent.com/12748339/66265720-9d423b00-e84d-11e9-9c54-997f9b59ac89.png)

**Comment by bookfere** [comment]
Duplicate of #583

**Comment by cdhigh** [comment]
已在1.26.5修正

**Comment by lppsuixn** [comment]
@cdhigh 另外，kindle现在已经支持自定义字体了。但是kindleear推送的是不行的，请问这个有计划支持吗？

**Comment by bookfere** [comment]
Kindle 设备的自定义字体功能只支持 KF8 标准的 MOBI8 或更新的格式，而期刊样式的电子书只能用旧的 MOBI7 格式。所以 KindleEar 对这个需求没什么可做的。
