### ISSUE TITLE
书本语言能否增加韩语？

### ISSUE THREAD

**Issue by Steven630** [cdhigh/KindleEar#588]
现在设置选项书本语言没有韩语，合并推送或简单链接定制的时候不太方便，希望大神下个版本考虑增加韩语选项。谢谢。

**Comment by cdhigh** [comment]
这个简单，只是添加一个字符串而已，又不是韩语翻译

**Comment by cdhigh** [comment]
1.26.6已经添加

**Comment by Steven630** [comment]
多谢！

**Comment by Steven630** [comment]
试了一下，语言设成韩语推送后，字体设置界面只能选择英文字体（Bookerly等），似乎没有生效？

**Comment by cdhigh** [comment]
我将韩语的代码设置为 ko-kr，
你找一本能选择韩文字体的书籍看看，其语言代码是什么？
获取直接使用Calibre生成一本韩语的书籍，看是否可以选择韩文字体？

**Comment by Steven630** [comment]
Calibre之前我试过，language设置为Korean，是可以在Kindle上选韩语字体的。

**Comment by cdhigh** [comment]
Calibre设置韩语为 ko，要不你修改一下 apps/View/Setting.py里面的 
`("ko-kr", _("Korean")` 为 `("ko", _("Korean")`
再尝试一下？

**Comment by Steven630** [comment]
修改了，可还是英文字体，好奇怪啊。Calibre自制的书明明可以。难道期刊格式还不太一样？

**Comment by cdhigh** [comment]
可能吧，这个书籍语言主要是用来查字典使用的，Kindle根据语言来调用不同的字典。
至少对于查字典，此语种属性是可用的。

**Comment by Steven630** [comment]
试了一下，日语是支持的。可能是因为亚马逊还没有进入韩国市场，Kindle也没有准备汉语词典，所以期刊格式就用不了韩语吧。如果在Kindle上读，哪怕用中文字体也是可以显示韩语的，但是如果用安卓版app，韩语就出不来。推送格式可以选择书籍吗？以前记得好像哪里有这个选项，现在看只能选期刊和漫画了。

**Comment by cdhigh** [comment]
普通书籍格式其实是支持的，但是没有测试过，估计封面/目录等元素需要优化，所以目前没有在设置界面上体现。
你可以尝试一下效果：
lib/makeoeb.py
将 setMetaData() 的参数 pubtype 改为 'book:book:KindleEar' 。

**Comment by Steven630** [comment]
谢谢，这样修改后，是否所有推送全成了书籍格式？能否仅某个推送或某个账户才用书籍格式？

**Comment by cdhigh** [comment]
这个修改是全局性的，只是让你看看书籍格式是否可以解决你的问题。
毕竟此书籍格式没有经过测试。
