### ISSUE TITLE
能否适配centos?

### ISSUE THREAD

**Issue by liuxiucheng** [cdhigh/KindleEar#589]
您好！
从2013年Hi-pad跟到Github也是一件不容易的事情。先为这个程序点赞！
因GAE在国外的关系，而自己受python的影响，同时也买了VPS学习做了简单的网站，想咨询：
有没有把这套程序移植到centos可用的网站程序？
如果没有这个计划，我想学习如何移植，从您的角度来看，我需要掌握那些知识？
谢谢啊！

**Comment by cdhigh** [comment]
其实移植并不复杂，为什么我对移植到其他系统不热心，因为Calibre本身就可以直接跑在标准Linux下，可能远程操作麻烦点，但是至少是可行的。
而且好像之前已经有人尝试使用KindleEar的核心开发过在标准Linux下跑的应用了，不知进展如何了。
在linux下生成mobi比较简单，不建议使用calibre模块，而是直接使用Amazon官方的kindlegen，兼容性更好，只要根据"亚马逊Kindle电子书发布指南"里面的要求创建几个xml和html，再调用Kindlegen即可。
生成epub就更简单了，它就是一个标准的zip文件，根据格式打包相关文件就好了。
核心的电子书生成搞定了，其他的就简单了。
开发语言: 不限，python或java或其他
定时任务: cron或python schedule模块。
发送邮件: sendgrid或其他第三方服务。
数据库: sqlite+peewee或干脆mysql
前端: 任意
邮件服务器: VPS提供的吧
至于直接提供Docker映像之类的，如果感兴趣的话，可以折腾。
自己实现的话，技术方案很随意，可以使用一些听起来很"吓人"的技术。

**Comment by liuxiucheng** [comment]
嗯嗯，感谢您前瞻性的指导，为我提供了方向与具体的可实现路径。
其实这也算我的心魔之一 :)  
谢谢啦！
