### ISSUE TITLE
cannot get rss data created by RSSHub

### ISSUE THREAD

**Issue by denny0810** [cdhigh/KindleEar#591]
I create a feed by rsshub as shown. It can be read by Feedly but not kindle ear.
https://zf-rsshub.herokuapp.com/wechat/csm/janelee1231,
tested the link by adding "?fmt=xml", not work.

![屏幕捕获_2019_12_22_10_29_52_796](https://user-images.githubusercontent.com/59128785/71316140-290b5100-24a6-11ea-9c3a-7f68f2a87fd2.png)
![屏幕捕获_2019_12_22_10_30_35_250](https://user-images.githubusercontent.com/59128785/71316141-29a3e780-24a6-11ea-81fa-46dab1d72c1a.png)

**Comment by cdhigh** [comment]
I canot even open the link in browser. please check it firstly.

**Comment by cdhigh** [comment]
Now I can access the link.
But you have to set 'Oldest article' to 'No limit'.
