### ISSUE TITLE
我这边显示ok但是收不到书籍怎么办呢

### ISSUE THREAD

**Issue by echocherish** [cdhigh/KindleEar#593]
![image](https://user-images.githubusercontent.com/40596525/71365673-acc65a00-25da-11ea-9572-9dadeb753143.png)

**Comment by cdhigh** [comment]
确定在Amazon的网页上正确启用了白名单。
如果还收不到，可能是墙的问题，可能会要花一段时间才能到达。
一直收不到就是墙完全屏蔽了。

**Comment by echocherish** [comment]
> 确定在Amazon的网页上正确启用了白名单。
> 如果还收不到，可能是墙的问题，可能会要花一段时间才能到达。
> 一直收不到就是墙完全屏蔽了。

我凌晨的时候收到了KinderEar这本，但TE还是过不来。hhh不过能收到一本就好啦。

**Comment by echocherish** [comment]
@cdhigh 
我好像不太会用这个回复抱歉呀。
