### ISSUE TITLE
[Help Wanted] 关于自定义css

### ISSUE THREAD

**Issue by TTTPOB** [cdhigh/KindleEar#595]
我留意到设置中有自定义css的选项，可是kindle只支持旧mobi格式的推送，这种情况下自定义的css可用吗(字体啥的)

**Comment by cdhigh** [comment]
基本的css是可用的，Kindle只支持一个css子集

**Comment by TTTPOB** [comment]
有没有哪里有相关的资料呀我很想让推送的杂志能使用自己的字体(不需要可以切换，我写死就行了，这个支持吗)...另外希望加一个下载本次生成书籍的功能,或者是保存到gmail的已发送邮件里，这样也好调试生成的书...

**Comment by TTTPOB** [comment]
另外经过我测试把epub文件后缀改成html是可以推送到kindle上的...不知道是否能够加上这个选项呢？(毕竟epub格式就能够支持新的排版特性了

**Comment by cdhigh** [comment]
关于CSS的支持，为什么不顺手搜索一下呢？
https://kdp.amazon.com/en_US/help/topic/G200673180

KindleEar可以发送到多个邮件地址，如果要备份，直接添加多个EMAIL即可，使用分号分隔。

即使epub推送到Kindle，固件支持的排版特性也和mobi一样吧，因为这个是Kindle固件的能力问题，而不是mobi本身的限制，不过你可以尝试一下，如果确实epub直接推送到Kindle的排版更好，我可以添加此功能。

**Comment by TTTPOB** [comment]
hhh谢谢耐心解答
我其实查过啦查到的都是kf8的资料...然后链接里是支持的html标签我似乎没看到css属性...

然后我刚试了一下把生成的epub改成html推送过去，得到的是普通的书的格式而不是期刊，但确实可以自己调字体调粗细之类的了（看上去自动使用了新的KF8格式而不是旧的mobi7格式），我很满意

**Comment by cdhigh** [comment]
《亚马逊Kindle 电子书发布指南》 内容比较全面，HTML/CSS都有
