### ISSUE TITLE
无法自动投递，手动可以投递

### ISSUE THREAD

**Issue by bluezd** [cdhigh/KindleEar#596]
通过 Uploader 方式部署，无法自动投递。

<img width="1384" alt="Screen Shot 2020-01-10 at 10 28 49" src="https://user-images.githubusercontent.com/977107/72120766-088f3200-3394-11ea-9c1c-d7df996f0173.png">
<img width="810" alt="Screen Shot 2020-01-10 at 10 28 15" src="https://user-images.githubusercontent.com/977107/72120783-15138a80-3394-11ea-84c1-2a3d12104199.png">

**Comment by cdhigh** [comment]
打开了 "使能自动定时投递" 和 "自动定时投递自定义RSS" 这两个开关了没有？

**Comment by bluezd** [comment]
打开了, 这两天又好用了，但是投递时间不准确，我设置的是11:00am

<img width="564" alt="Screen Shot 2020-01-13 at 11 34 44" src="https://user-images.githubusercontent.com/977107/72231879-bdc22400-35f8-11ea-9f5a-e00c65839188.png">

**Comment by cdhigh** [comment]
投递时间误差在一个小时内，因为用的是一个小时间隔的定时任务检查是否需要推送，如果推送时间是否准确对你很重要，可以自己修改 cron.yaml，改成你需要的时间，准确到秒都可以。

**Comment by huang5307** [comment]
我的情况差不多，有时候能够自动推送但有时候却不行，不知道逻辑在哪里？能推送的时候，时间也是差了不止1小时。哪里可以看到log吗？
