### ISSUE TITLE
时间长了某一源不推送

### ISSUE THREAD

**Issue by markpimi** [cdhigh/KindleEar#598]
我是自己用fivefilter写的源，有VOA和小说，
不同源创建有先后顺序

最近发现有些个别几个RSS本身没问题的情况下，Kindle没能推送那个RSS，同时另外几个RSS推送正常。

有人碰到类似问题吗？

**Comment by cdhigh** [comment]
推送失败原因很多，无法一一列举，想知道什么原因你可以通过GAE后台的LOG查看，出错或失败都有记录的。
