### ISSUE TITLE
科学松鼠会的feed似乎无法打包发送

### ISSUE THREAD

**Issue by wintersun** [cdhigh/KindleEar#599]
无法打包发送科学松鼠会的feed。
URL地址： https://songshuhui.net/feed
用Chrome开发者工具跟踪了一下，发现其response返回的是html（Content-Type: text/html），虽然文本是xml，猜测是这个问题。

版本：KindleEar @1.25.5

**Comment by cdhigh** [comment]
我看是科学松鼠会的feed不再更新，最新的都是2019-08-31的

**Comment by wintersun** [comment]
是的，我也注意到了，木有问题了，谢谢。
