### ISSUE TITLE
一开始可以自动推送但是后来又无法自动推送了

### ISSUE THREAD

**Issue by huang5307** [cdhigh/KindleEar#601]
一开始可以自动推送但是后来又无法自动推送了，但是试了手动推送可以。
错误的信息如下：
error_group("CIrN87DStoHJaQ")
 我把所有的错误log下载下来。
[gae_app_module_id_worker_version_id_1__logs__2020-02-25T02-37.zip](https://github.com/cdhigh/KindleEar/files/4250121/gae_app_module_id_worker_version_id_1__logs__2020-02-25T02-37.zip)

**Comment by cdhigh** [comment]
升级了1.26.7，升级了readability模块，同时跳过解析失败的文章，希望能解决此问题。
