### ISSUE TITLE
建议修改打包支持自定义字体

### ISSUE THREAD

**Issue by appleftg** [cdhigh/KindleEar#602]
系统很方便很好用，但是在阅读的时候只能选默认的四种字体，据说是因为打包格式版本的问题，建议修改打包程序支持自定义字体方便大家更优雅的阅读，谢谢

**Comment by enneaa** [comment]
支持

**Comment by cdhigh** [comment]
以前讨论过了，只有新的格式才支持自定义字体，而新格式无法通过邮件推送。

**Comment by appleftg** [comment]
> 以前讨论过了，只有新的格式才支持自定义字体，而新格式无法通过邮件推送。
不好意思，没注意到
