### ISSUE TITLE
css 可以自定义字体吗

### ISSUE THREAD

**Issue by enneaa** [cdhigh/KindleEar#603]
我把字体文件放在根目录下 font 文件夹中，再上传了如下样式，字体好像没法生效。

`@page {
    margin-bottom: 5pt;
    margin-top: 5pt
    }
@font-face {
    font-family: "FZPingXYSJW";
    src: local("FZPingXYSJW")
    }
body {
    font-family: "FZPingXYSJW", serif;
    font-size: 1em;
    font-weight: normal;
    line-height: 1.2;
    }`

**Comment by cdhigh** [comment]
支持自定义字体的新格式无法邮件推送，如果有心，不妨到amazon请愿，要求：
1. 新格式支持推送
2. 新格式支持期刊格式

**Comment by enneaa** [comment]
谢谢回复，现在已经很好用了，还是有些贪心。
https://reabble.cn/ 可以选择推送到kindle的格式是否为期刊，如果是期刊就没法自定义字体，如果是普通的电纸书格式就可以换字体。
如果 kindleear 以普通的电纸书格式推送，能不能实现自定义字体。

**Comment by cdhigh** [comment]
你可以自己尝试一下：
1. lib/makeoeb.py (line 76)
`setattr(opts, "mobi_file_type", 'both' if book_mode == 'comic' else 'old')`
修改为
`setattr(opts, "mobi_file_type", 'both')`
2. lib/makeoeb.py (line 126)
`pubtype='periodical:magazine:KindleEar'`
修改为
`pubtype='book:book:KindleEar'`

**Comment by enneaa** [comment]
> 
> 
> 你可以自己尝试一下：
> 
>     1. lib/makeoeb.py (line 76)
>        `setattr(opts, "mobi_file_type", 'both' if book_mode == 'comic' else 'old')`
>        修改为
>        `setattr(opts, "mobi_file_type", 'both')`
> 
>     2. lib/makeoeb.py (line 126)
>        `pubtype='periodical:magazine:KindleEar'`
>        修改为
>        `pubtype='book:book:KindleEar'`

试了下不行，没有变化。不知道哪的问题

**Comment by cdhigh** [comment]
那估计不行吧，或者amazon自动转换了格式，不通过邮件，直接通过USB拷贝到kindle看看？
