### ISSUE TITLE
通过发送邮件无法抓取微信公众号的文章啦，能不能改进一下

### ISSUE THREAD

**Issue by nietulong** [cdhigh/KindleEar#606]
如题

**Comment by cdhigh** [comment]
之前可以吗？
我从来没有试过，考虑微信的封闭，我认为应该不行才对。

**Comment by nietulong** [comment]
> 之前可以吗？
> 我从来没有试过，考虑微信的封闭，我认为应该不行才对。

之前是可以的。

**Comment by cdhigh** [comment]
微信的封闭导致了它会不停的封堵，就像公众号的抓取方案，换了很多种方案了，每次都用不了多久。

**Comment by huangchanghu** [comment]
我以前经常用来推送公众号文章，挺好用，从2019年某个时候开始就用不了了，有办法解决吗
