### ISSUE TITLE
知乎日报订阅有问题。

### ISSUE THREAD

**Issue by loghder** [cdhigh/KindleEar#607]
①订阅rsshub提供的知乎日报，文章数不全
②使用内置转发器订阅知乎，一直显示nonews，尝试自己修改代码。发现了几处问题（不一定对，我编程水平不太好。。）
1.ZhihuDaily.py 文件里所使用的知乎日报接口http://news.at.zhihu.com/api/1.2/news/latest已经失效。
2.我把api接口改成https://news-at.zhihu.com/api/4/news/latest 然后根据新的api返回的json修改了ZhihuDaily.py的代码后，发现博主提供的转发器虽然可以正常转发知乎日报的一级页面https://daily.zhihu.com，但是却无法转发二级页面（eg.https://daily.zhihu.com/story/9722746）。我自己尝试在haruko上搭建转发器后，也是相同情况，猜测可能是二级页面屏蔽了haruko的ip？
所以我现在想找到一个能够完美推送知乎日报的方法。。。

**Comment by cdhigh** [comment]
使用rsshub提供的订阅，文章数不全是多少篇？
Kindle Ear默认抓取删除30篇文章。
如果少于30篇，可以尝试将日期限制改成不限制看看。
如果需要多于30篇，在base.py里面可以修改

**Comment by loghder** [comment]
> 使用rsshub提供的订阅，文章数不全是多少篇？
> Kindle Ear默认抓取删除30篇文章。
> 如果少于30篇，可以尝试将日期限制改成不限制看看。
> 如果需要多于30篇，在base.py里面可以修改

我弄的是不限制+全文rss。rsshub提供的知乎日报rss包括最近两天大概10篇文章吧（直接看xml格式，并没有缺内容）。但是只能推送两篇文章（最新一天的五篇文章中的第一篇和最后一篇，中间三篇被跳过了），并且其中一篇“瞎扯 正确吐槽”实际内容是集合了四五个知乎问题和答案，结果推送内容就变成了一个知乎答案（连问题都没有）。如果不勾选全文rss的话，就推送0篇

**Comment by cdhigh** [comment]
知乎好像很多文章的格式有问题，提取文章内容出错。
应该是因为这个原因

**Comment by cdhigh** [comment]
升级了1.26.7，升级了readability模块，同时跳过解析失败的文章，希望能解决此问题。
