### ISSUE TITLE
部署问题请教。ERROR appcfg.py:2584

### ISSUE THREAD

**Issue by lovesars** [cdhigh/KindleEar#608]
********************************************************************************
Python 2 is deprecated. Upgrade to Python 3 as soon as possible.
See https://cloud.google.com/python/docs/python2-sunset
To suppress this warning, create an empty ~/.cloudshell/no-python-warning file.
The command will automatically proceed in  seconds or on any key.
********************************************************************************
05:34 PM Application: ancient-torch-260203; version: 1
05:34 PM Host: appengine.google.com
05:34 PM Starting update of app: ancient-torch-260203, version: 1
05:34 PM Getting current resource limits.
05:34 PM Scanning files on local disk.
05:34 PM Cloning 41 static files.
05:34 PM Cloning 484 application files.
05:34 PM Compilation starting.
05:34 PM Compilation completed.
05:34 PM Starting deployment.
05:34 PM Checking if deployment succeeded.
05:34 PM Will check again in 1 seconds.
05:34 PM Checking if deployment succeeded.
05:34 PM Deployment successful.
05:34 PM Checking if updated app version is serving.
05:34 PM Application deployment failed. Message: Deployments using appcfg are no longer supported. See https://cloud.google.com/appengine/docs/deprecations
2020-04-21 17:34:34,119 ERROR appcfg.py:2584 Application deployment failed. Message: Deployments using appcfg are no longer supported. See https://cloud.google.com/appengine/docs/deprecations 
05:34 PM Rolling back the update.
Could not start serving the given version.
请问大佬们。这个部署失败问题怎么解决？

**Comment by cdhigh** [comment]
提示不再支持 appcfg 部署，请使用 gcloud 部署
