### ISSUE TITLE
折腾半天还是没部署上

### ISSUE THREAD

**Issue by jeezy711** [cdhigh/KindleEar#609]
因为看到python2已经不支持了，就在本机用gcloud部署，但是总是出错。
```
Beginning deployment of service [default]...
╔════════════════════════════════════════════════════════════╗
╠═ Uploading 0 files to Google Cloud Storage                ═╣
╚════════════════════════════════════════════════════════════╝
File upload done.
WARNING: You will be unable to deploy applications after November 30, 2019 without adding a billing instrument to your project. Please add one at https://console.cloud.google.com/billing/linkedaccount?kindlerss-274914

Updating service [default]...failed.                                           
ERROR: (gcloud.app.deploy) Error Response: [7] Access Not Configured. Cloud Build has not been used in project kindlerss-274914 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudbuild.googleapis.com/overview?project=kindlerss-274914 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
```
看样子上传文件成功了，那下面这个服务无法启动是啥意思？我估计是翻墙的稳定性造成的，不知对不对。
然后看到有cloud shell的方案，试了下，倒是没有翻墙的问题了，但是提示python版本太低，还是无法顺利打开服务。
所以现在各条路都走不通，麻烦大家给看看，应该怎么办？

**Comment by jeezy711** [comment]
下面那个警告意思是要充值买空间？

**Comment by cdhigh** [comment]
在去年底后，需要添加一个付款方式才能部署，不过放心，还是免费的。
Google还是可信赖的，不会乱搞。

**Comment by JerryCui** [comment]
glcoud 是可以部署成功的，不要使用那个脚本了

**Comment by jeezy711** [comment]
> 在去年底后，需要添加一个付款方式才能部署，不过放心，还是免费的。
> Google还是可信赖的，不会乱搞。

我看写了个120天免费，之后一天多钱，是啥意思？是不是现在政策有变化？我终于部署成功了！不过进去没有引导，还没找到怎么添加rss源。

**Comment by jeezy711** [comment]
在“高级设置”里，导入OPML，结果显示：
`internal server error`
在网友分享里直接订阅，显示
<img width="442" alt="截屏2020-04-23 下午10 21 07" src="https://user-images.githubusercontent.com/22372200/80110355-2bdf9500-85b1-11ea-8b0d-074dd743e74b.png">
相当的郁闷！

**Comment by cdhigh** [comment]
可以打开gae后台看logs记录，如果需要，可以发上来。
Opml仅支持utf8格式。

**Comment by jeezy711** [comment]
> 可以打开gae后台看logs记录，如果需要，可以发上来。
> Opml仅支持utf8格式。

日志是下面这个
```
E 2020-04-24T04:20:06.791340Z POST 500 187 B 109 ms Safari 13 /feeds/add POST 500 187 B 109 ms Safari 13 5ea268f600ff0c132cf2ba2fb500016e7e6b696e646c657273732d323735323033000131000100
  162.245.239.68 - - [24/Apr/2020:12:20:06 +0800] "POST /feeds/add HTTP/1.1" 500 187 http://kindlerss-275203.appspot.com/library "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15" "kindlerss-275203.appspot.com" ms=109 cpu_ms=566 cpm_usd=2.0898e-8 loading_request=0 instance=00c61b117c92eff1269cad992295268f678f29038f98c128a0e5f4f7897c1f2cee688f8b app_engine_release=1.9.71 trace_id=fd8c93b46119e940c011f876bebf2b7f

```

**Comment by jeezy711** [comment]
这是导入opml时出错的日志记录

[日志.xlsx](https://github.com/cdhigh/KindleEar/files/4527025/default.xlsx)

**Comment by cdhigh** [comment]
部署只成功了一半，没有创建数据库索引，在faq里面有说明如何创建。

**Comment by jeezy711** [comment]
按照提示把数据库索引创建了，这个状态按理说没问题了吧。结果在“高级设置”-“现在投递”里推送后，还是“internal server error”。
<img width="1435" alt="截屏2020-04-24 下午7 36 17" src="https://user-images.githubusercontent.com/22372200/80208494-ec718100-8662-11ea-8ed2-c2277f450bb2.png">
创建索引时，提示让开启datastore API，我看已经开启了，但是有个“创建凭据“。需要吗？

**Comment by cdhigh** [comment]
出现错误就查看log, 猜没用

**Comment by jeezy711** [comment]
[日志1.xlsx](https://github.com/cdhigh/KindleEar/files/4528750/1.xlsx)
现在的日志，麻烦再帮我看看。感谢！

**Comment by cdhigh** [comment]
你没有部署完，刚才是索引，现在是任务队列没有创建。
部署有两步，看readme或FAQ都说的很详细，除非很懂，否则就一步一步去做就行，
大部分程序员都不喜欢写文档，既然程序员愿意花“宝贵”的时间写到文档里面了，就说明确实很重要！

`
gcloud app deploy --version=1 KindleEar目录\app.yaml KindleEar目录\module-worker.yaml
*** gcloud app deploy --version=1 KindleEar目录**
`

**Comment by jeezy711** [comment]
这两个命令我执行过了，而且成功了。按照readme文件，因为python2已经不被支持，我就用的gcloud部署，删掉了两个yaml文件的前两行，改了config.py文件的内容，然后执行了
>gcloud auth login
>gcloud config set project 你的ApplicationId
>gcloud app deploy --version=1 KindleEar目录\app.yaml KindleEar目录\module-worker.yaml
>gcloud app deploy --version=1 KindleEar目录
>gcloud datastore indexes create KindleEar目录\index.yaml

这些命令。最后一个命令执行时提示要打开datastore API，上浏览器打开，再重新执行这个命令，也顺利完成了。然后可以打开自己的kindleear网页，也能做各种设置。但就是推送出错！
我确确实实把readme和FAQ好好看了，可这服务器就是不配合。服务器有什么问题了？

**Comment by cdhigh** [comment]
那就用 gcloud 重新生成 任务队列、定时任务，具体参数我忘了，你搜索一下。

**Comment by jeezy711** [comment]
暂时没得到解决，回头找个Windows再试试吧。谢谢！

**Comment by hipages-guoxu** [comment]
阿，信用卡不支持。。。淦
