### ISSUE TITLE
现在部署需要开始收费了吗？

### ISSUE THREAD

**Issue by gukejing** [cdhigh/KindleEar#610]
在云端命令行操作的时候，得到这样一条信息反馈，有朋友遇到这样的问题吗？
WARNING: You will be **unable to deploy applications after November 30, 2019 without adding a billing instrument** to your project. Please add one at https://console.cloud.google.com/billing/linkedaccount?wechattorss
Updating service [default]...failed.
ERROR: (gcloud.app.deploy) Error Response: [7] Access Not Configured. Cloud Build has not been used in project wechattorss before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudbuild.googleapis.com/
overview?project=wechattorss then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

**Comment by jeezy711** [comment]
点那个链接，进去需要绑定信用卡，没关系，只是绑定，不是真的收费，部署还是免费的。

**Comment by gukejing** [comment]
绑定了信用卡，通过，观察下，避免被收费，多谢 jeezy711
