### ISSUE TITLE
请教Cloud Shell部署的问题

### ISSUE THREAD

**Issue by Steven630** [cdhigh/KindleEar#615]
出来下面截图的这个提示，以前从来没有过。不知道什么问题。烦请指教。

![Screenshot_20200917_165619](https://user-images.githubusercontent.com/24987637/93448949-bf21ba00-f906-11ea-8988-9fa97a8a4fee.jpg)

**Comment by cdhigh** [comment]
需要 OAUTH授权才能部署
如果chrome没有弹出auth的窗口，可以试试 --noauth_local_webserver

**Comment by Steven630** [comment]
noauth_local_webserver

谢谢。请问这个具体还怎么输呢？shell一激活吗？

**Comment by cdhigh** [comment]
我没有使用过shell部署，
你需要在gcloud的命令行后面添加此参数。

**Comment by Steven630** [comment]
命令是sh upload.sh
是这样加吗：
sh upload.sh --noauth_local_webserver

**Comment by cdhigh** [comment]
要加到upload.sh里面，如果脚本不是你写的，可以反馈给作者请求修改

**Comment by Steven630** [comment]
https://github.com/miaowm5/KeUploader/blob/master/update.sh

就是这个，加到第一行吗？具体该怎么写能否指教

**Comment by Sciroccogti** [comment]
好像是是加在第二行末尾，你可以把文件里的三行命令复制出来，单独运行就知道了。

不过实测 appcfg 方法已经不能用了，建议直接使用 README.md 中的 gcloud 方法：
https://github.com/cdhigh/KindleEar/blob/e1df4824d3405c621ddaad3ff9c87924f29b1f3a/readme.md#L49
1. 删除`app.yaml`和`module-worker.yaml`开头的两行：`application / version`
2. ```
   gcloud auth login
   gcloud config set project 你的ApplicationId
   gcloud app deploy --version=1 KindleEar目录\app.yaml KindleEar目录\module-worker.yaml
   gcloud app deploy --version=1 KindleEar目录
   ```
3. 如果服务器没有正常创建数据库索引，可能需要手动执行如下语句
`gcloud datastore indexes create KindleEar目录\index.yaml`

**Comment by Steven630** [comment]
> 好像是是加在第二行末尾，你可以把文件里的三行命令复制出来，单独运行就知道了。
> 
> 不过实测 appcfg 方法已经不能用了，建议直接使用 README.md 中的 gcloud 方法：
> https://github.com/cdhigh/KindleEar/blob/e1df4824d3405c621ddaad3ff9c87924f29b1f3a/readme.md#L49
> 
> 1. 删除`app.yaml`和`module-worker.yaml`开头的两行：`application / version`
> 2. ```
>    gcloud auth login
>    gcloud config set project 你的ApplicationId
>    gcloud app deploy --version=1 KindleEar目录\app.yaml KindleEar目录\module-worker.yaml
>    gcloud app deploy --version=1 KindleEar目录
>    ```
> 3. 如果服务器没有正常创建数据库索引，可能需要手动执行如下语句
>    `gcloud datastore indexes create KindleEar目录\index.yaml`

谢谢！我一两个月前还试过是可以的，突然就变成这样了。因为没有美元信用卡，所以gcloud的方法一时也用不了。

**Comment by cdhigh** [comment]
加在update的后面
Appcfg update --noxxxxxxx directory

**Comment by Steven630** [comment]
谢谢，果然现在已经部署不了了。请问现在的部署方式中，有哪个是不用绑定信用卡的吗？

**Comment by cdhigh** [comment]
都要绑定了吧

**Comment by Steven630** [comment]
好吧……假设绑了卡，是不是也只有一年免费试用？

**Comment by cdhigh** [comment]
在限额内还是永久免费的

**Comment by Steven630** [comment]
好的，不知道国内什么卡能绑上

**Comment by Sciroccogti** [comment]
可以申请那种双卡的，譬如工行VISA实测可用。

**Comment by Steven630** [comment]
> 可以申请那种双卡的，譬如工行VISA实测可用。

请问是叫“牡丹国际借记卡”吗？另外，绑卡第一步的国家没有中国选项，应该选哪里？

**Comment by Sciroccogti** [comment]
> 请问是叫“牡丹国际借记卡”吗？另外，绑卡第一步的国家没有中国选项，应该选哪里？

国际借记卡 是 借记卡 吧，可以看看环球旅行卡，这个是信用卡（我印象里只能信用卡

国家地区的话我不记得了，可能是香港

**Comment by Steven630** [comment]
> > 请问是叫“牡丹国际借记卡”吗？另外，绑卡第一步的国家没有中国选项，应该选哪里？
> 
> 国际借记卡 是 借记卡 吧，可以看看环球旅行卡，这个是信用卡（我印象里只能信用卡
> 
> 国家地区的话我不记得了，可能是香港

谢谢。卡信息的地址也要正确吗？还是只要卡号、姓名就可以了？

**Comment by Sciroccogti** [comment]
> 卡信息的地址也要正确吗？还是只要卡号、姓名就可以了？

啊太久远了确实不记得了。。你可以先随便填填，不让过再说😂

**Comment by Steven630** [comment]
谢谢！
