### ISSUE TITLE
網頁文章沒有圖片

### ISSUE THREAD

**Issue by ksc4313** [cdhigh/KindleEar#623]
我建立一個py檔來抓取多個RSS網站的文章，文章內容都正常但就是都沒有圖片，請問有辦法解決嗎？

**Comment by cdhigh** [comment]
可能被自动过滤了，可以将 fulltext_by_readability 设置为false，然后使用keep_only_tags，remove_tags_after，remove_tags_before，remove_tags等属性定制

或如果图像有特定的tag，可以在positive_classes属性里添加，也可以保留图片。
