### ISSUE TITLE
部署完成，网页显示Startup failed

### ISSUE THREAD

**Issue by jeezy711** [cdhigh/KindleEar#627]
按照顺序部署完成，但是用网页打开时提示如下：
`Startup failed

Tiny Tiny RSS was unable to start properly. This usually means a misconfiguration or an incomplete upgrade. Please fix errors indicated by the following messages:

Please set SELF_URL_PATH to the correct value detected for your server: http://XXX/
You might want to check tt-rss wiki or the forums for more information. Please search the forums before creating new topic for your question.`

部署完成，就提示这个，docker_compose.yml文件里配置的是181端口和外网IP地址。
后来查阅了wiki，重新把SELF_URL_PATH配置成带子目录的域名，并配置了nginx，结果还是上面这样。
请高手指导下！

**Comment by cdhigh** [comment]
提错了，这个是其他应用的
