### ISSUE TITLE
能否提供docker镜像？

### ISSUE THREAD

**Issue by hjianhao** [cdhigh/KindleEar#628]
这样就不用只能使用GAE了，其他服务器，NAS或者云服务器都可以使用？

**Comment by cdhigh** [comment]
有能部署在vps的类似应用

**Comment by hjianhao** [comment]
能问一下是什么应用吗？
--
从Mail.ru的Android专用app所发送 星期四, 21 一月 2021, 06:10下午 +08:00 发件人 cdhigh  notifications@github.com :

**Comment by cdhigh** [comment]
自己搜索一下吧，很多年，我也记不清了

**Comment by Sciroccogti** [comment]
这里有一个，不过好像有点问题  https://github.com/KUNzfw/KindleEar-Docker
