### ISSUE TITLE
部署程序会把文件部署到系统的哪个地方？

### ISSUE THREAD

**Issue by opptimus** [cdhigh/KindleEar#630]
部署程序会把文件部署到系统的哪个地方？
我稍稍懂一点Linux，想要导出个人配置文档，在Google Shell摸索了半天，没能找到部署的具体位置，作者能说一下部署的具体位置吗？
类似于/opt/share/kindle?这类的具体位置
谢谢！

**Comment by cdhigh** [comment]
程序文件由GAE沙盘托管，没有简单的办法直接管理（有办法，但是麻烦一点）。
配置数据则保存到DATASTORE数据库，可以在GAE后台的DATASTORE页面直接管理，或者自己可以写脚本直接下载，GAE提供这些API。
