### ISSUE TITLE
刚刚发现似乎pocket接口申请授权不可以了！是不是接口改变了？

### ISSUE THREAD

**Issue by opptimus** [cdhigh/KindleEar#631]
在高级设置的归档里接入pocket，
可以显示pocket界面，然后输入密码后显示：The link you followed here is no longer working. Would you like to start over at the home page?
但昨天还是可以申请授权的？
是我部署的出现问题了，还是pocket接口变了？我这边2台appspot都出现了这种问题！

**Comment by opptimus** [comment]
错误信息参考如下：

APIError: HTTP Status:403, X-Error-Code:158, X-Error:"User rejected code.", request: Get access token

**Comment by cdhigh** [comment]
我刚试了一下，是可以成功授权的，接口没变。

**Comment by opptimus** [comment]
> 
> 
> 我刚试了一下，是可以成功授权的，接口没变。
的确不可以授权，重现率100%,难道是我的pocket账户问题，我再试试看

**Comment by opptimus** [comment]
1.26.4 版本可以获取pocket授权
1.25.5和1.26.7均不可以获取授权

**Comment by cdhigh** [comment]
我用的是1.26.6，没问题
但是1.26.7没有改动和这个相关的部分，要不你试一下

**Comment by opptimus** [comment]
@cdhigh 
我经过反复测试，该问题的原因是：kindleEar服务的url必须是https，不能使用http(也能打开一些页面，但会有各种问题)。
作者大人可否将http强制转换成https？？
@cdhigh
