### ISSUE TITLE
网页滚动过程中加载新内容如何处理

### ISSUE THREAD

**Issue by hjianhao** [cdhigh/KindleEar#635]
现在有些网页为了提升用户体验，不采用点击页数或者下一页加载更多内容，而是随着滚动条的滚动加载新内容

这种网页有办法获取到更多的文章吗？

**Comment by cdhigh** [comment]
Gae无法执行javascript，需要分析代码，看javascript是如何获取更多内容的，然后自己写py代码手工获取。
Aisixiang.py提供了一个范例，是网页中有分页按钮的情况的处理方式，根据滚动条也类似处理，看其监听滚动条位置的回调函数即可。
