### ISSUE TITLE
请问如何分享我自己写的脚本

### ISSUE THREAD

**Issue by hjianhao** [cdhigh/KindleEar#636]
我看KindleEar里面有个网友分享，我自己学习写了一个订阅我经常看的开发者头条的订阅脚本，也想分享一下，但是好像找不到在哪里可以分享出去？

**Comment by cdhigh** [comment]
新建一个Pull requests，我合入主干

**Comment by hjianhao** [comment]
已经创建了Pull request

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: cdhigh<mailto:notifications@github.com>
发送时间: 2021年1月26日 17:30
收件人: cdhigh/KindleEar<mailto:KindleEar@noreply.github.com>
抄送: Jason Huang<mailto:hjianhao@hotmail.com>; Author<mailto:author@noreply.github.com>
主题: Re: [cdhigh/KindleEar] 请问如何分享我自己写的脚本 (#636)


新建一个Pull requests，我合入主干

―
