### ISSUE TITLE
打开ofcoder.com的网页报Too many redirections错误

### ISSUE THREAD

**Issue by hjianhao** [cdhigh/KindleEar#639]
Too many redirections:https://www.ofcoder.com/2020/08/12/theory/分布式一致性协议 - ZAB/?hmsr=toutiao.io&utm_medium=toutiao.io&utm_source=toutiao.io

我手工设置最大跳转次数到30也是一样
opener = URLOpener(self.host, timeout=self.timeout, maxredirect=30)

用浏览器打开网页正常，而且好像没有跳转

**Comment by cdhigh** [comment]
可以在本机调试环境测试一下是否一样的错误，有时候是网站封锁gae的ip，代理字符串设置可能也导致此问题

**Comment by hjianhao** [comment]
我就是本机调测的错误，还没有上GAE

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: cdhigh<mailto:notifications@github.com>
发送时间: 2021年1月29日 18:52
收件人: cdhigh/KindleEar<mailto:KindleEar@noreply.github.com>
抄送: Jason Huang<mailto:hjianhao@hotmail.com>; Author<mailto:author@noreply.github.com>
主题: Re: [cdhigh/KindleEar] 打开ofcoder.com的网页报Too many redirections错误 (#639)


可以在本机调试环境测试一下是否一样的错误，有时候是网站封锁gae的ip，代理字符串设置可能也导致此问题

―

**Comment by cdhigh** [comment]
能帮忙调试一下吗，看是什么问题，然后提一个pull requests
