### ISSUE TITLE
在使用uploader部署的最后就弹出如下图中的文字，请问有无解决方案呢？谢谢！

### ISSUE THREAD

**Issue by dianzzz** [cdhigh/KindleEar#641]
![image](https://user-images.githubusercontent.com/78651511/107121514-d1a88a00-68cd-11eb-819c-27b38877b735.png)

**Comment by cdhigh** [comment]
现在google已经不支持appcfg部署，请使用gcloud部署

**Comment by dianzzz** [comment]
> 现在google已经不支持appcfg部署，请使用gcloud部署

好的，我待会儿再试试，谢谢啦
