### ISSUE TITLE
现在投递 返回 internal server error

### ISSUE THREAD

**Issue by izumookuni** [cdhigh/KindleEar#642]
在云端 Shell使用KindleEar-Uploader脚本进行安装，安装时有错误提示Cloud Scheduler API未安装，但网页可以打开。
考虑到Cloud Scheduler API可能会收费，所以没有理会这个Error
一开始进 我的订阅 会 internal server error，后发现是没有索引导致（没有Cloud Datastore API），安装后重新索引恢复正常（四个索引都是绿色标记）。
Mail API已授权电子邮件，kindle已信任gmail邮箱。
点击现在投递 返回 internal server error
日志是和issues/122类似的UnknownQueueError

根据之前的解决方法
使用appcfg.py update KindleEar 
提示appcfg.py: error: Expected -A app_id when application property in file app.yaml is not set.

使用appcfg.py -A （具体的app_id） update KindleEar/
提示A version or backend parameter is required.

使用appcfg.py -A （具体的app_id） -V 1 update KindleEar
提示Deployments using appcfg are no longer supported. See https://cloud.google.com/appengine/docs/deprecations

于是使用gcloud app deploy KindleEar/app.yaml
Services to deploy:

descriptor:      [/home/xxx/KindleEar/app.yaml]
source:          [/home/xxx/KindleEar]
target project:  [xxx]
target service:  [default]
target version:  [20210207t031756]
target url:      [https://xxx.dt.r.appspot.com]

Do you want to continue (Y/n)?

Beginning deployment of service [default]...
╔════════════════════════════════════════════════════════════╗
╠═ Uploading 0 files to Google Cloud Storage                ═╣
╚════════════════════════════════════════════════════════════╝
File upload done.
Updating service [default]...done.
Setting traffic split for service [default]...done.
Deployed service [default] to [https://xxx.dt.r.appspot.com]

You can stream logs from the command line by running:
  $ gcloud app logs tail -s default

To view your application in the web browser run:
  $ gcloud app browse

之后点击 现在投递 仍然返回 internal server error

**Comment by izumookuni** [comment]
已自行解决，应该是没有安装Cloud Tasks API导致的。

**Comment by weidongzhou1994** [comment]
同样的问题，能请问一下怎么解决吗？

**Comment by cdhigh** [comment]
进kindleear目录
`gcloud app deploy --version=1 .`
注意后面有一个点。

**Comment by weidongzhou1994** [comment]
还是不行，怎么切换版本

**Comment by weidongzhou1994** [comment]
有没有更详细的教程，感觉自动脚本很坑啊

**Comment by cdhigh** [comment]
Readme有步骤
