### ISSUE TITLE
Alternate Google App Engine?

### ISSUE THREAD

**Issue by mizzunet** [cdhigh/KindleEar#643]
I'm a student and I don't own a CC for GCP trial whivh I need to setup Application in Google Cloud, so is it possible to use other instances, Heroku for example?

**Comment by cdhigh** [comment]
KindleEar only Works on GAE.

**Comment by mizzunet** [comment]
> KindleEar only Works on GAE.

I see. Well, could you please create  an account  for me in your site, http://kindleear.appspot.com?
