### ISSUE TITLE
请教转发器的问题

### ISSUE THREAD

**Issue by Steven630** [cdhigh/KindleEar#644]
Economist网址好像又开始屏蔽GAE的ip了。请教大神是否能像知乎日报那样，用转发器绕过屏蔽？另外，是只要将目录页转发，还是所有文字链接都需要？谢谢。

**Comment by cdhigh** [comment]
可以尝试一下，先目录，不行再全部

**Comment by Steven630** [comment]
谢谢，试试后再来请教
