### ISSUE TITLE
请问下次可否增加自动用转发器的选项

### ISSUE THREAD

**Issue by Steven630** [cdhigh/KindleEar#651]
好比needs_subscription=True
能否增加forwarder_on = True
开启后，所有页面、图片都用转发器加载，防止GAE的地址遭封。现在每次都单独加有点麻烦。

建议考虑，谢谢。

**Comment by Steven630** [comment]
那能不能只允许自己搭建过的使用这个功能呢。

比如再加个self-forwarder_address = 
没有这个参数，就无效，与默认的相同同样无效

**Comment by cdhigh** [comment]
这样的解决方案怪怪的，如果需要，还是你自己改一改版本比较好，不难。
