### ISSUE TITLE
I can't enter my password

### ISSUE THREAD

**Issue by hd7979** [cdhigh/KindleEar#652]
I can't enter my password, I follow this guide
Download KindleEar and uncompress it (Change the name of folder to 'KindleEar').
Download KindleEar-Uploader and unzip it.
Put KindleEar folder into Uploader directory, double-click uploader.bat to start process of deployment.
![image](https://user-images.githubusercontent.com/89649097/131207089-344d26f4-e61d-4361-8988-cde8768ed3b5.png)

**Comment by cdhigh** [comment]
gae no longer supports uploader, please refer to readme to use gcloud command line

**Comment by hd7979** [comment]
I can't create an app, can anyone give me an account or an app link? thank you very much

**Comment by cdhigh** [comment]
I updated the readme and FAQ, you can deploy it step by step.

**Comment by cdhigh** [comment]
I found a post in a Chinese site.
<https://bookfere.com/post/19.html#ke_2_1>
It's in Chinese, but you can translate by Google Translation.
This procedure don't need install GAE SDK and python, operate only in cloud env.

**Comment by hd7979** [comment]
thankyou very much

**Comment by hd7979** [comment]
I want to share many account, can you help me ?
![image](https://user-images.githubusercontent.com/89649097/131485990-fc019add-af0c-416c-8766-d473f918abb2.png)

**Comment by hd7979** [comment]
Some pages I can't get news even though I have the rss link of that page. For example, the page https://cafebiz.vn/trang-chu.rss reports about nonews

**Comment by cdhigh** [comment]
many sites block ip from gae nowadays.

**Comment by hd7979** [comment]
Can you help me edit Expiration in change info account ? 
![image](https://user-images.githubusercontent.com/89649097/132288699-1835041c-fa82-467d-bb13-7046779775a6.png)
thankyou very much !

**Comment by cdhigh** [comment]
Is it really necessary? 
Generally, after setting it up correctly, you rarely need to log in. 
Or you can use google or lastpass to remember the password.
I only log in once a few months.
