### ISSUE TITLE
app.yaml seems invalid, please download KindleEar again.

### ISSUE THREAD

**Issue by magruderkvnc** [cdhigh/KindleEar#656]
![Ekran görüntüsü 2021-12-20 165902](https://user-images.githubusercontent.com/31405569/146778735-e070bc0d-edc7-4475-b525-8cc147669d92.jpg)
when I try to start uploader.bat always getting error "app.yaml seems invalid, please download KindleEar again". could you help me about the situation?

**Comment by cdhigh** [comment]
uploader in my repository no longer works, please use https://github.com/bookfere/KindleEar-Uploader

**Comment by cdhigh** [comment]
3.0.0b released, Incompatible with older versions.
docs
https://cdhigh.github.io/KindleEar/
