### ISSUE TITLE
亚马逊将取消对mobi格式的支持

### ISSUE THREAD

**Issue by fqx** [cdhigh/KindleEar#657]
未来推送格式将支持ePub，希望KindleEar可以更新。

**Comment by cdhigh** [comment]
从第一个版本开始，KindleEar就支持mobi/epub，所以不需要更新。

**Comment by shujianzhao** [comment]
EPUB推送到kindle，文章排版不如mobi，特别是没有方便的目录跳转。不知是什么问题？

**Comment by cdhigh** [comment]
估计是Amazon要慢慢“引导”Kindle拥有者去购买它的平台上的书籍，否则也无法解释为何要禁止mobi推送。
KindleEar在生成书籍内容时是不区分mobi和epub的，只是最后一步打包格式有区别
