### ISSUE TITLE
404 page not found 问题的解决，供需要的朋友参考

### ISSUE THREAD

**Issue by shujianzhao** [cdhigh/KindleEar#659]
按照https://bookfere.com/post/19.html#ke_4_3的自动化上传脚本安装。一直是404.
后来查看日志，提示构建错误“gcr.io/cloud-builders/gcloud" failed: step exited with non-zero status: 1”。
网上搜了搜，有一篇教程，提到类似错误，需要给GAE账号增加构建权限，详情见下方链接。供需要的朋友参考。
https://www.learngoogle.com/tag/cloudbuild/

**Comment by cdhigh** [comment]
3.0.0b已发布，可能部署方法有些变化
https://cdhigh.github.io/KindleEar/
