### ISSUE TITLE
2022年5月30日起谷歌“安全性较低的应用的访问权限”设置失效

### ISSUE THREAD

**Issue by dingchenzy** [cdhigh/KindleEar#660]
设置失效了，是否可以用google推荐的专用应用密码？

**Comment by cdhigh** [comment]
没明白，是部署的时候还是访问的时候？
如果是部署的时候是可以使用专用密码

**Comment by Lizankai** [comment]
那还能开通smtp服务吗e

**Comment by cdhigh** [comment]
不清楚，添加了付款方式后可以
不过如果只是smtp，应该不需要添加付款方式

**Comment by cdhigh** [comment]
3.0.0b已经发布，如果不想用GAE，可以使用其他VPS平台。
