### ISSUE TITLE
喷嚏图卦的图片抓不到了

### ISSUE THREAD

**Issue by donglin2000** [cdhigh/KindleEar#663]
最近一段时间喷嚏图卦都抓不到图片了，就是这样的：

 https://www.dapenti.com:99/dapenti/f57312f5/6275ee3c.jpg

浏览器直接打开又能看到图片，不知道哪里能看到抓取的日志。

**Comment by cdhigh** [comment]
The URL to be fetched can use any port number in the following ranges: 80-90, 440-450, 1024-65535. If the port is not mentioned in the URL, the port is implied by the scheme: http://... is port 80, https://... is port 443.

这个是GAE的端口限制，99处于这个端口范围之外，可能是因为这个原因导致抓不到图片吧
如果你有转发或反向代理，可以考虑用其他服务器转一道

**Comment by cdhigh** [comment]
3.0.0b已经发布，不再受限于GAE的资源限制，另外找VPS部署就好。
https://cdhigh.github.io/KindleEar/
