### ISSUE TITLE
You will be unable to deploy applications after November 30, 2019 without adding a billing instrument to your project.

### ISSUE THREAD

**Issue by jiangbeth** [cdhigh/KindleEar#664]
请问大大，添加信用卡后如何避免扣费啊

**Comment by cdhigh** [comment]
在后台设置限额提醒，设置提醒金额为零美元，然后在免费额度用完后准备要扣费前会发邮件提醒你，你再去后台临时将应用暂停即可，这是google自己的推荐方法。
当然，如果嫌手工操作比较麻烦，GAE应用有API提供，自己找一个VPS之类的平台部署一个简单的监控应用就可以自动完成这些步骤。
不过这个监控应用就需要自己写了，很简单的应用，可能就几十行代码吧，参考API手册就好，我没有这个需求，还没有去研究。

**Comment by jiangbeth** [comment]
多谢大佬百忙之中答复

**Comment by cdhigh** [comment]
3.0.0b已经发布，现在另找一个免费的VPS部署就好。
