### ISSUE TITLE
GAE ending support for Python 2.7

### ISSUE THREAD

**Issue by fqx** [cdhigh/KindleEar#665]
### Review the lifecycle policy and support schedule for App Engine Standard generations

The AppEngine standard environment language runtimes [lifecycle policy] and [support schedule] provides information on the various stages of support for runtimes, and indicates that certain runtimes will reach End of Support on January 30, 2024.

As described in the lifecycle policy, continued use of End of Support runtimes will have significant implications for your workloads, including that, for such End of Support runtimes:

The functionality enabling creation of new deployments and re-deployments will be discontinued.*
Google will not apply security updates or patches.
Technical support on the End of Support runtime will not be available.

Migrate your application to a newer runtime if your application’s current runtime is approaching an [End of Support] date, e.g. **Python 2.7**, Java 8, PHP 5.5.

**Comment by cdhigh** [comment]
3.0.0b released, supports python3 and multiple platforms.
https://cdhigh.github.io/KindleEar/
