### ISSUE TITLE
亚马逊不再支持send_to_kindle的Mobi模式

### ISSUE THREAD

**Issue by me4p0** [cdhigh/KindleEar#666]
最近从12月1日起就不能接受了KindleEar了，邮件提醒是无不再支持发送Mobi格式，但是我改成以EPUB格式发送也不能接收到了。

感谢您使用 Send to Kindle 服务。我们注意到您在 2023年11月22日11:57 发送的文档使用的是 MOBI（.mobi、.azw、.prc）格式。

望知悉，我们将于 2023 年 11 月 1 日开始停止支持通过 Send to Kindle 发送 MOBI（.mobi、.azw、.prc）文件。此项变更将影响通过 [电子邮件版 Send to Kindle](https://www.amazon.com/gp/f.html?C=2FE3Q8PEVQ917&M=urn:rtn:msg:20231122115747a897192481d046ed838534c1e330p0na&R=36K6V6SU2BSS7&T=C&U=https%3A%2F%2Fwww.amazon.com%2Fsendtokindle%2Femail%3Fref_%3Dpe_1825130_625404990&H=K7HXA5AN9VXPHAFAUFSWJHEKT2YA&ref_=pe_1825130_625404990)、 [iOS](https://www.amazon.com/gp/f.html?C=2FE3Q8PEVQ917&M=urn:rtn:msg:20231122115747a897192481d046ed838534c1e330p0na&R=EYE2KHRWYHQ1&T=C&U=https%3A%2F%2Fwww.amazon.com%2Fsendtokindle%2Fios%3Fref_%3Dpe_1825130_625404990&H=UMHNW4Q450FIVIVAGBJAYP2VA9MA&ref_=pe_1825130_625404990)和 [安卓系统](https://www.amazon.com/gp/f.html?C=2FE3Q8PEVQ917&M=urn:rtn:msg:20231122115747a897192481d046ed838534c1e330p0na&R=2TN1W530H1T7K&T=C&U=https%3A%2F%2Fwww.amazon.com%2Fsendtokindle%2Fandroid%3Fref_%3Dpe_1825130_625404990&H=ZRUEV8CAE2WCSL54A079DDYMFAUA&ref_=pe_1825130_625404990)上的 Kindle 阅读软件以及 [Windows](https://www.amazon.com/gp/f.html?C=2FE3Q8PEVQ917&M=urn:rtn:msg:20231122115747a897192481d046ed838534c1e330p0na&R=14OH711TQ89SX&T=C&U=https%3A%2F%2Fwww.amazon.com%2Fsendtokindle%2Fpc%3Fref_%3Dpe_1825130_625404990&H=TJQHBNRX4CYE2YAIANFR4CRAZE4A&ref_=pe_1825130_625404990) 和 [Mac](https://www.amazon.com/gp/f.html?C=2FE3Q8PEVQ917&M=urn:rtn:msg:20231122115747a897192481d046ed838534c1e330p0na&R=2LAUXV4BUSXME&T=C&U=https%3A%2F%2Fwww.amazon.com%2Fsendtokindle%2Fmac%3Fref_%3Dpe_1825130_625404990&H=QH53DVWVN9G73XEOTSS4LWGHGVOA&ref_=pe_1825130_625404990) 版的 Send to Kindle 应用发送 MOBI 文件。此项变更不会影响您的 Kindle 图书馆中已存在的 MOBI 文档和其他文档格式。

MOBI 是较旧的文档格式，不支援最新的 Kindle 文件功能。如果您希望使用我们最新的文件功能，请以 [相容格式](https://www.amazon.com/gp/f.html?C=2FE3Q8PEVQ917&M=urn:rtn:msg:20231122115747a897192481d046ed838534c1e330p0na&R=PP4U5HBICUQO&T=C&U=http%3A%2F%2Fwww.amazon.cn%2FKindledocuments%2F%3Fref_%3Dpe_1825130_625404990&H=T4XACIGBYZEQ5Z8B3EQ9ALGCJK4A&ref_=pe_1825130_625404990)重新传送文档。例如, EPUB (.epub) 是一种相容的格式。

如果您有任何疑问，请访问我们的 [帮助页面](https://www.amazon.com/gp/f.html?C=2FE3Q8PEVQ917&M=urn:rtn:msg:20231122115747a897192481d046ed838534c1e330p0na&R=FZHPGM9BUHUL&T=C&U=http%3A%2F%2Fwww.amazon.cn%2FKindledocuments%2F%3Fref_%3Dpe_1825130_625404990&H=MLQXWCHRNNDF4A4XNKICNFVSTCMA&ref_=pe_1825130_625404990)，或联系我们的 [客户服务](https://www.amazon.com/gp/f.html?C=2FE3Q8PEVQ917&M=urn:rtn:msg:20231122115747a897192481d046ed838534c1e330p0na&R=398M8T6BAN07N&T=C&U=https%3A%2F%2Fwww.amazon.com%2Fdevicesupport%3Fref_%3Dpe_1825130_625404990&H=6XHZQK6N7ENK7K40FANOOJJNJD8A&ref_=pe_1825130_625404990)团队。下载或使用 Send to Kindle 即表示您同意 [此处](https://www.amazon.com/gp/r.html?C=2FE3Q8PEVQ917&M=urn:rtn:msg:20231122115747a897192481d046ed838534c1e330p0na&R=33WSF9YHOC7LO&T=C&U=https%3A%2F%2Fwww.amazon.com%2Fgp%2Fhelp%2Fcustomer%2Fdisplay.html%3FnodeId%3DThDuDmqnYd2Ouy8c6i%26ref_%3Dpe_1825130_625404990&H=VAFALSPADG3HCAPMHRU09GLFYGIA&ref_=pe_1825130_625404990)的条款。

谨启！
亚马逊 Kindle 支持团队

**Comment by me4p0** [comment]
通过将发送文档格式 Mobi修改为EPUB后可以正常推送了，算给个介绍提醒的Issue了

**Comment by cdhigh** [comment]
epub推送好像没有期刊阅读格式了
