### ISSUE TITLE
会不会考虑Docker？

### ISSUE THREAD

**Issue by pretenderlu** [cdhigh/KindleEar#667]
大佬会不会考虑做个Docker版本出来？？

**Comment by cdhigh** [comment]
其实3.0版本在一个月前就算基本完成了，但是一个月前我断网了，换了一个运营商，结果各种情况，一个月才给我搞好固定网络，这一个月我就只用手机网络提交代码，无法进行实际部署，现在网络好了，这几天我就实际部署测试，如果你愿意，也可以帮忙测试Docker，我没有接触过Docker。
帮忙文档：https://cdhigh.github.io/KindleEar/

从3.0版本开始，支持全平台部署，windows, linux, vps, 各种python云托管平台，树莓派和各种派，当然也包括Docker映像，甚至如果愿意，支持python运行环境的openwrt路由器应该也可以

**Comment by pretenderlu** [comment]
> 其实3.0版本在一个月前就算基本完成了，但是一个月前我断网了，换了一个运营商，结果各种情况，一个月才给我搞好固定网络，这一个月我就只用手机网络提交代码，无法进行实际部署，现在网络好了，这几天我就实际部署测试，如果你愿意，也可以帮忙测试Docker，我没有接触过Docker。 帮忙文档：https://cdhigh.github.io/KindleEar/
> 
> 从3.0版本开始，支持全平台部署，windows, linux, vps, 各种python云托管平台，树莓派和各种派，当然也包括Docker映像，甚至如果愿意，支持python运行环境的openwrt路由器应该也可以

好的，不过我不会开发，我只能试着部署一下，然后帮忙测试看看，嘿嘿~~

**Comment by cdhigh** [comment]
Docker镜像已经上传
请参考项目文档部署
