### ISSUE TITLE
建议开发最新版VPS Docker部署时完善邮件中转服务功能

### ISSUE THREAD

**Issue by appleftg** [cdhigh/KindleEar#669]
首先谢谢大佬开发的程序，非常实用，稳定使用多年。其中，邮件中转服务强大且方便，KindleEar中已进行了接收邮件后的处理，建议在新版中一起完善此功能，在开发VPS Docker部署时，可以使用自定义域名邮箱解析使用此功能，邮箱邮件发送到绑定KindleEar的自定义域名邮箱后，KindleEar能解析邮件并使用邮件中转服务，谢谢

**Comment by cdhigh** [comment]
是这样，GAE的邮件中转我也常用，很喜欢，除了KindleEar的正事，有时候还用它来干坏事。
比如有些服务每个账号的试用期有限，同一个email又不能重复注册，appspotmail给我提供了无限量的email地址，过期就再注册一个，可以永远的试用~
还有有些服务推荐一个用户就能获取某些升级奖励之类的，我就不停的推荐不同的appspotmail来创建新用户～

在转到VPS部署后，我也发现缺了这个功能，所以现在我还在拼命完善Bookmarklet，希望能替代邮件中转服务，我没有接触过没有听说过你说的自定义域名邮箱解析，我会搜索研究，你有什么推荐的服务吗？

**Comment by appleftg** [comment]
> 是这样，GAE的邮件中转我也常用，很喜欢，除了KindleEar的正事，有时候还用它来干坏事。 比如有些服务每个账号的试用期有限，同一个email又不能重复注册，appspotmail给我提供了无限量的email地址，过期就再注册一个，可以永远的试用~ 还有有些服务推荐一个用户就能获取某些升级奖励之类的，我就不停的推荐不同的appspotmail来创建新用户～
> 
> 在转到VPS部署后，我也发现缺了这个功能，所以现在我还在拼命完善Bookmarklet，希望能替代邮件中转服务，我没有接触过没有听说过你说的自定义域名邮箱解析，我会搜索研究，你有什么推荐的服务吗？

具体的服务不懂，之前python2版本KindleEar的时候，我在本地用docker部署KindleEar（大佬FAQ推荐版本google/cloud-sdk:273.0.0-alpine镜像），用https://github.com/appleftg/mailglove（目的将25端口接收邮件转为gae的webhook接收邮件传入KindleEar）这个项目，将自定义域名添加dns邮箱解析到本地docker  mailglove项目中转，KindleEar邮件中转系统使用正常，例如：自定义域名为kindleear.example.com，解析DNS邮件地址，通过mailglove将邮件中转成gae  webhook后传入本地gae接收，发送XXX@kindleear.example.com正常，可以按FAQ中xxx@appid.appspotmail.com邮件地址方法使用。

所以个人觉得部署在本地vps，将自定义域名邮件地址DNS解析到本地，kindleear通过25端口接收处理邮件，实现原来的邮件中转服务功能，应该是可行的。

**Comment by cdhigh** [comment]
经过几天的学习，终于明白docker是怎么回事了，也成功部署了docker。
参考docker的最佳实践，我之前的想法是错误的（合并postfix为一个镜像），一个镜像不应该实现很多功能，所以你之前的做法是正确的，postfix/mailglove就应该是另一个镜像，可以使用docker-compose一起执行。
所以我在KindleEar实现一个webhook接口，就处理mailglove转发过来的json，这样就可以不用修改mailglove来适配gae的格式，而是直接pull docker hub上的镜像。

**Comment by cdhigh** [comment]
Docker镜像和compose都已经上传

**Comment by appleftg** [comment]
> 经过几天的学习，终于明白docker是怎么回事了，也成功部署了docker。 参考docker的最佳实践，我之前的想法是错误的（合并postfix为一个镜像），一个镜像不应该实现很多功能，所以你之前的做法是正确的，postfix/mailglove就应该是另一个镜像，可以使用docker-compose一起执行。 所以我在KindleEar实现一个webhook接口，就处理mailglove转发过来的json，这样就可以不用修改mailglove来适配gae的格式，而是直接pull docker hub上的镜像。

学习能力真强，那么快就处理好了，再请教下，我用docker-compose部署，貌似正常，但是用163邮箱SMTP发送邮件时，提示“Connection unexpectedly closed”，25或465端口都试了，还是报这个错误，一样的参数用其它的程序正常可以发送邮件，请帮解决下，谢谢

**Comment by appleftg** [comment]
> Docker镜像和compose都已经上传

看到了，马上去试试，谢谢

**Comment by cdhigh** [comment]
抱歉，这个功能因为条件限制，我只有做单元测试，就是直接给KindleEar发测试包。
没有和mailglove进行集成测试，要不你看看log里面有什么内容？
要不要等一段时间我才能进行这个测试了。

**Comment by appleftg** [comment]
> 抱歉，这个功能因为条件限制，我只有做单元测试，就是直接给KindleEar发测试包。 没有和mailglove进行集成测试，要不你看看log里面有什么内容？ 要不要等一段时间我才能进行这个测试了。

您好，刚解决了用163邮箱SMTP发送邮件问题（是SMTP网页配置说明不清晰容易错配，我重新开个贴提问，方便以后查找），重新部署测试docker-compose部署，采集投递和使用自定义域名邮箱入站邮件中转服务正常，谢谢大佬的开发完善。

**Comment by cdhigh** [comment]
Mailglove镜像太大了，建议尝试将基础镜像更换为alpine重新制作，只是一个postfix服务而已，不需要完整ubuntu镜像，应该不会有什么兼容性问题

**Comment by appleftg** [comment]
> Mailglove镜像太大了，建议尝试将基础镜像更换为alpine重新制作，只是一个postfix服务而已，不需要完整ubuntu镜像，应该不会有什么兼容性问题

应该可以压缩，我不是作者，也不是很懂那一块，作者这么多年了还坚持更新，挺难得的。原来也找了很多个mail2http，用下来，还是这个合适，本地部署，不在乎这些空间了，有需求的可以根据作者的Dockerfile文件修改

**Comment by appleftg** [comment]
对了，有空还得再麻烦完善下对应的书签小应用(Bookmarklet)，【选择内容发送到Kindle】本地部署没有显示这个书签应用，谢谢

**Comment by cdhigh** [comment]
OK，选择内容发送邮件，功能是完备的，只是打开就好，现在的判断是如果不是appspot.com网域就屏蔽此功能，在网页端使用javascript屏蔽的。

**Comment by appleftg** [comment]
> OK，选择内容发送邮件，功能是完备的，只是打开就好，现在的判断是如果不是appspot.com网域就屏蔽此功能，在网页端使用javascript屏蔽的。

那好。功能挺实用的

**Comment by cdhigh** [comment]
最新代码已经打开此功能。

额外的，我现在在开发KindleEar的chrome的扩展程序，过几天应该就可以上传chrome应用商店了。
除了bookbmarklet这几个功能外，最让我开心的是我竟然成功了实现 “不需要写代码就生成任意网页的抓取脚本” 的功能。
第一次学习做chrome扩展程序，并且对前端和html/js连三脚猫的功夫都不算，能搞定挺不容易的，有几次都想放弃了～

**Comment by appleftg** [comment]
通过这段时间的交流，你的学习速度、毅力和实践转换能力让人钦佩，种下了种子就想方设法实现，迟早应该都会实现，难怪前段时间看到代码里有提到chrome扩展，又没看到说明，原来是在开发完善中，期待。再想说下，用docker本地部署比原来gae本地环境部署速度和质量都提升了很多，原来有些经rsshub的rss采集不到，有些rss内容的端口不在gae范围，这版都解决了，表示衷心感谢

**Comment by appleftg** [comment]
谢谢，还好没放弃，不然可惜了。我在重新docker部署时，还遇到两个问题，麻烦帮分析下：1.书签小应用(Bookmarklet)【发送到Kindle】，先选择希望推送的文章内容（可以包含图像文件），然后再点击此Bookmarklet，提示“Some parameter missing!”错误。2.书签小应用(Bookmarklet)【选择内容发送到Kindle】，邮件正文不显示选择图片。

**Comment by cdhigh** [comment]
1. 避免爬虫，“发送到Kindle”里面有一个“key=xxx”的查询字符串，这个密钥是在账号创建时随机生成的，因为数据库重建了，所以此密钥也变了，重新拖一次bookmarklet就好。
2. 选择内容发送到kindle现在就是这样的，只提取里面的文本内容，如果要发送图像，还需要构造html的邮件body，为便捷起见，就只发送文本，如果需要图像，“发送到kindle”可以实现，因为使用post发送数据，所以格式就灵活一些。

**Comment by appleftg** [comment]
> 1. 避免爬虫，“发送到Kindle”里面有一个“key=xxx”的查询字符串，这个密钥是在账号创建时随机生成的，因为数据库重建了，所以此密钥也变了，重新拖一次bookmarklet就好。
> 2. 选择内容发送到kindle现在就是这样的，只提取里面的文本内容，如果要发送图像，还需要构造html的邮件body，为便捷起见，就只发送文本，如果需要图像，“发送到kindle”可以实现，因为使用post发送数据，所以格式就灵活一些。不知你是否清楚，"发送到kindle" 也支持选择文本然后发送，如果选择文本就发送文本（包括里面的图像和html的文档树结构），没有选择就发送当前链接。

是的，注意到了这个功能，重新部署后重新拖的，分享码对了对的，没有选择内容发送当前链接推送正常，选择文本和图像用“发送到Kindle”推送上一版本正常，这一版本用360或ie都是提示“Some parameter missing!”，地址栏为“https://kindleear.appspotmail.com/url2book”，不知道是不是这台电脑的问题，我换台电脑试试

**Comment by appleftg** [comment]
您好，换电脑试了，也是一样，选择文本和图像用“发送到Kindle”推送提示“Some parameter missing!”错误。是不是这一版本修改了代码的影响
![image](https://github.com/cdhigh/KindleEar/assets/26489931/ebf74291-6f46-40e0-9aeb-a7c63a24ea22)

**Comment by cdhigh** [comment]
我是js白痴，因为没有见过这个语法，在写chrome扩展程序的过程中发现这个代码很怪，感觉像是笔误，所以就顺手改过来了，尚未测试。
经过搜索发现，这不是笔误，是js创建对象的一个简写语法～

**Comment by appleftg** [comment]
> 我是js白痴，因为没有见过这个语法，在写chrome扩展程序的过程中发现这个代码很怪，感觉像是笔误，所以就顺手改过来了，尚未测试。 经过搜索发现，这不是笔误，是js创建对象的一个简写语法～

我也不懂，我把书签小应用(Bookmarklet)这个分号改回原来逗号，选择文本和图像用“发送到Kindle”推送就正常了，没有提示“Some parameter missing!”错误。
