### ISSUE TITLE
建议在每篇文章后增加Wallabag稍后阅读功能（在高级设置--归档中设置）

### ISSUE THREAD

**Issue by appleftg** [cdhigh/KindleEar#671]
大佬，您好，wallabag 是一款开源的网络书签、稍后阅读工具，可以部署在自己的服务器中，感觉这样数据安全可靠些。所以建议在每篇文章后附加 '保存到 wallabag' 超链接，增加Wallabag稍后阅读功能，在高级设置--归档中设置，谢谢

**Comment by cdhigh** [comment]
行，之后有时间了解一下。

**Comment by appleftg** [comment]
> 行，之后有时间了解一下。

谢谢

**Comment by cdhigh** [comment]
最新代码已经实现此功能。

**Comment by appleftg** [comment]
谢谢。等下重新部署下，我是想用这个功能把看上的文章分享到自建的wallabag上，再生成相应的合集RSS分享链接，再用kindleear采集RSS传回来。
