### ISSUE TITLE
重新部署后密码不对

### ISSUE THREAD

**Issue by dmiming2000** [cdhigh/KindleEar#675]
原来部署了3.0，正常使用中。
今天晚上通过一键脚本进行更新部署，结果密码不对，无法登陆了。
通过“忘记密码”重置密码，也提示邮箱不存在。
有什么办法修改密码吗？

**Comment by cdhigh** [comment]
因为我修改了数据库结构（正式版发布后，如果数据库结构发生变化，我会处理好兼容性问题，但是现在我还没有发布正式版，所以数据库结构随时会改变）。

你部署在哪个平台？
如果是GAE平台，到 [后台datastore](https://console.cloud.google.com/datastore/databases) 将KeUser的数据行删除，让 KindleEar重新创建账号，恢复默认密码admin

如果是Docker平台，删除database.db或使用其他sqlite管理工具只是删除KeUser

**Comment by dmiming2000** [comment]
GAE部署的， 但没看到说的数据行呢

**Comment by dmiming2000** [comment]
已OK
