### ISSUE TITLE
recipe都推送成功，“网友分享”中的rss推送没有一个成功的。

### ISSUE THREAD

**Issue by dmiming2000** [cdhigh/KindleEar#677]
recipe都推送成功，“网友分享”中的rss推送没有一个成功的。
手工访问rss是有内容的，例如“今日话题-雪球”，推送不成功，也没有任何报错。
不知道是什么原因？

**Comment by cdhigh** [comment]
还真是这样，雪球获取不到文章内容，经过调试发现，是因为我用的一个库feedparser的bug，其分析xml内嵌复杂内容有bug，出异常导致内容为空。
python2版本的feedparser是正常的，这个是python3版本的feedparser引入的问题。

在它修复之前，我们先禁用全文RSS功能，所有的全文RSS都当作摘要RSS处理，代码库已更新，可以重新部署进行测试。

**Comment by dmiming2000** [comment]
前面的问题描述有误，是部分RSS推送成功、没有内容，部分RSS什么都没有。
重新部署后，雪球的推送成功、也有内容了。
谢谢。
