### ISSUE TITLE
如何快速同步官方的recipe

### ISSUE THREAD

**Issue by dmiming2000** [cdhigh/KindleEar#678]
将特定的recipe放到指定目录下；
然后 python3 tools/archive_builtin_recipes.py 报错，无法成功更新。

**Comment by cdhigh** [comment]
我就是用这个方法的，具体什么错误？

**Comment by dmiming2000** [comment]
Traceback (most recent call last):
  File "/home/ihadoop/kindleear/tools/archive_builtin_recipes.py", line 16, in <module>
    import main
  File "/home/ihadoop/kindleear/main.py", line 43, in <module>
    app = init_app(__name__, cfgMap, set_env, debug=False)
  File "/home/ihadoop/kindleear/application/__init__.py", line 35, in init_app
    from .back_end.task_queue_adpt import init_task_queue_service
  File "/home/ihadoop/kindleear/application/back_end/task_queue_adpt.py", line 9, in <module>
    from .task_queue_gae import *
  File "/home/ihadoop/kindleear/application/back_end/task_queue_gae.py", line 10, in <module>
    from google.cloud import tasks_v2
ImportError: cannot import name 'tasks_v2' from 'google.cloud' (unknown location)

**Comment by cdhigh** [comment]
不管是在本机还是远程shell，都需要先安装运行环境。
sudo pip3 install -r requirements.txt

**Comment by dmiming2000** [comment]
已经安装过了的，安装完之后报的这个错
另，确实是在gae的shell环境下操作的，这个操作完成之后，还需要怎么更新呢。

**Comment by dmiming2000** [comment]
chmod +x kindleear/tools/gae_deploy.sh && \
kindleear/tools/gae_deploy.sh
这样重新部署一次就可以了吧

**Comment by dmiming2000** [comment]
问题来了，更新完成之后，web界面里看到的recipe代码也是更新的。
但通过系统推送，显示“nonews”
以 The Economist Espresso为例，通过ebook-convert手工执行这个recipe确认没问题。

**Comment by cdhigh** [comment]
要养成看后台logs来定位问题的习惯

**Comment by dmiming2000** [comment]
后台logs里没什么报错，就是推送时显示“nonews”
看代码是更新到了，推送其他recipe倒是没问题

**Comment by cdhigh** [comment]
后台有报错，是429错误，应该是GAE的IP策略不允许调用 https://webcache.googleusercontent.com，因为在本机是可以的，在VPS也是可以的。
新的recipe和老的recipe相比，就是使用google的cache直接获取printversion，只有这个区别，老版本就可以使用，不需要使用新版本。

如果只有个别recipe需要更新，不需要更新到内置库，直接使用网页上传功能更便捷。

**Comment by dmiming2000** [comment]
老版本在gae上已经无法获取了，我才去更新的，辛苦了，谢谢

cdhigh ***@***.***>于2024年5月4日 周六07:37写道：
