### ISSUE TITLE
please add docker arm64 image support(请发布支持arm64的docker镜像)

### ISSUE THREAD

**Issue by lazyzyf** [cdhigh/KindleEar#679]

**Comment by cdhigh** [comment]
可以考虑，我研究一下交叉编译。

**Comment by cdhigh** [comment]
已经推送arm64的docker image，第一次学着构建跨平台image，不知对不对，也没有条件测试。
请帮忙测试是否正常运行？

**Comment by lazyzyf** [comment]
![Snipaste_2024-05-03_14-34-36](https://github.com/cdhigh/KindleEar/assets/2499877/389d6832-5ed8-486b-aff0-3a0368a40b07)
谢谢，我这边显示这个timezone error 然后就停在那里了。

**Comment by cdhigh** [comment]
我之前没有在Dockerfile里面添加 platform参数，不知是否是这个原因，再试一下？
FROM --platform=$TARGETPLATFORM python:3.9.19-alpine

**Comment by appleftg** [comment]
我用Ubuntu 18.04.6 LTS  x86 docker也是这个提示，但是使用正常。我用arm机器部署了下，没有用caddy和nginx，可以正常部署打开网页，不是日常用的机器，推送等功能推送等未测试，应试是正常的。他应该是本地部署本地访问，没有把Docker端口映射出来，所以访问失败，加个ports:  - "8000:8000"  应该就可以用IP:8000打开。
对了，大佬，麻烦顺路把arm版的image: kindleear/mailfix也一起做了，嘿嘿

docker-compose.yml参考：
services:
  kindleear:
    container_name: kindleear
    image: kindleear/kindleear
    restart: always
    volumes:
      - /home/docker/kindleear/data/:/data/
    expose:
      - "8000"
    **ports:
      - "8000:8000"**
    networks:
      - web_network
    environment:
       APP_ID: kindleear
       APP_DOMAIN: http://example.com
       LOG_LEVEL: warning
       HIDE_MAIL_TO_LOCAL: no
networks:
  web_network:
    driver: bridge




Ubuntu 18.04.6 LTS  x86 docker提示：
/usr/local/lib/python3.9/site-packages/tzlocal/unix.py:193: UserWarning: Can not find any timezone configuration, defaulting to UTC.
  warnings.warn("Can not find any timezone configuration, defaulting to UTC.")

**Comment by cdhigh** [comment]
我看了一些最佳实践，在前端使用nginx/caddy等web服务器时，不建议再映射端口(ports)，而只是使用暴露即可(expose)，这样外部不能绕过nginx/caddy而直接访问内部。
如果外部能直接访问，没有必要使用nginx/caddy了，直接按照我的部署指南里面的命令启动gunicorn即可。

**Comment by cdhigh** [comment]
arm64版本的mailfix已经上传。

**Comment by appleftg** [comment]
> 我看了一些最佳实践，在前端使用nginx/caddy等web服务器时，不建议再映射端口(ports)，而只是使用暴露即可(expose)，这样外部不能绕过nginx/caddy而直接访问内部。 如果外部能直接访问，没有必要使用nginx/caddy了，直接按照我的部署指南里面的命令启动gunicorn即可。

我其它地方使用了nginx，一起用了，没用kindleear的了。本地部署的估计可能还是本地访问的多，远程访问的少，稳就行了，本地访问不用nginx/caddy，是方便排除问题，KindleEar默认使用的80端口也可能被占用了。

**Comment by appleftg** [comment]
> arm64版本的mailfix已经上传。

大佬，真快

**Comment by cdhigh** [comment]
如果想要体验感，随便一个支持Android的大屏墨水屏都可以，安装kindle app，除了续航和开机时间，和kindle一样的。

我有一个10寸文石，开机哪个慢啊，不像kindle，随时待命。

我刚测试了我刚升级的微软免费tts，几分钟就直接生成了长度一个多小时的mp3文件，证实这个功能可以开放使用了。

不过Docker image里还不能用，等我升级下一个版本再打开。

**Comment by appleftg** [comment]
期待，原来考虑换文石leaf3c，tab10c pro，支持webdav，后来看看价格，日常，也没见过实体机，上了彩色，分辨率又变低了，好像又没必要。

**Comment by appleftg** [comment]
这个mp3文件怎么用？一起推给kinlde好像不能用它的语音吧，想了解想设计场景和使用场景

**Comment by cdhigh** [comment]
我十年前之所以要创建KindleEar，就是为了看新闻和学外语，现在，相比于看，我更喜欢听新闻，所以我经常都将视频新闻下载到手机转换为音频再听。
既然现在因为google放弃python2，我只能升级KindleEar，就干脆多做一个功能，能部分的代替我下载视频新闻的工作。

具体实现是不做成有声书，而是独立的mp3文件，单独发到另外的邮箱，每天早上就可以自动下载到手机里，吃饭的时候，路上的时候，空闲无聊的时候就可以听。
新闻资讯类的信息更适合听，因为不用思考不用回翻，错过一部分内容也无碍。

现在的神经网络语音功能已经非常成熟（微软的TTS比google的要好），拟人性很高了，基本达到实用程度。

**Comment by appleftg** [comment]
挺方便的，等Docker image更新好tts，我也试试，单独做个信息采集源推送来听，谢谢提供思路

**Comment by fqx** [comment]
> 我十年前之所以要创建KindleEar，就是为了看新闻和学外语，现在，相比于看，我更喜欢听新闻，所以我经常都将视频新闻下载到手机转换为音频再听。 既然现在因为google放弃python2，我只能升级KindleEar，就干脆多做一个功能，能部分的代替我下载视频新闻的工作。
> 
> 具体实现是不做成有声书，而是独立的mp3文件，单独发到另外的邮箱，每天早上就可以自动下载到手机里，吃饭的时候，路上的时候，空闲无聊的时候就可以听。 新闻资讯类的信息更适合听，因为不用思考不用回翻，错过一部分内容也无碍。
> 
> 现在的神经网络语音功能已经非常成熟（微软的TTS比google的要好），拟人性很高了，基本达到实用程度。

作者不考虑增加podcast的功能吗？😄

**Comment by cdhigh** [comment]
支持podcast有什么增值作用吗？
既然要发送到手机，何不直接在手机上安装一个podcast应用？

**Comment by fqx** [comment]
@cdhigh 我的意思就是作为一个podcast server使用啊。

**Comment by cdhigh** [comment]
那就更没有必要了，发邮件更好，可以离线播放，服务器还剩了空间。
