### ISSUE TITLE
KindleEar3正式版几个问题反馈

### ISSUE THREAD

**Issue by appleftg** [cdhigh/KindleEar#680]
大佬，很高兴收到正式发布版，更新后有几个问题请教一下：
**1.推送文件名变为拼音。**
更新正式版后自动转为拼音，不是原中文名称，如设置—自定义RSS—书籍标题为“每日推送”，则推送文件名为“Mei Ri Tui Song (2024-05-03_19-11)_11-11-32.epub，不是每日推送(2024-05-03_19-11)_11-11-32.epub。
**2.推送书籍内文件名不对应**
设置—自定义RSS—书籍标题为“每日推送”，文件名还是“KindleEar”。
![image](https://github.com/cdhigh/KindleEar/assets/26489931/c65d47fc-b0e2-4980-a497-8101ecf868d5)
**3.最旧文章不能选择“不限制”**
设置—自定义RSS—最旧文章，选择“不限制”保存后自动变为“一星期”。
**4.有几个RSS显示乱码，帮分析下，RSS源在TTRSS阅读器内显示正常。**
三联生活周刊，https://plink.anyfeeder.com/weixin/lifeweek
![image](https://github.com/cdhigh/KindleEar/assets/26489931/f8279955-ee3e-4226-874d-d6accde727b2)
人物，https://plink.anyfeeder.com/weixin/renwumag1980
![image](https://github.com/cdhigh/KindleEar/assets/26489931/839b1a8b-ba97-469f-a102-930fa9cda853)
二丫讲梵，https://wiki.eryajf.net/rss.xml

**Comment by cdhigh** [comment]
几个问题都已修正

**Comment by appleftg** [comment]
> 几个问题都已修正

重新部署了，正常了，谢谢
