### ISSUE TITLE
疑似邮件发送的bug

### ISSUE THREAD

**Issue by dmiming2000** [cdhigh/KindleEar#681]
部署在vps上，设置smtp方式连接gmail进行邮件发送。
同一台vps、同一应用系统：在admin账户下，可以成功发送； 新建的其他账户，无论是使用与admin同样的邮件配置、还是单独配置邮件服务器信息，邮件都发送失败。
报错：
(501, b'5.5.2 Cannot Decode response. For more information, go to\n5.5.2 https://support.google.com/a/answer/3221692 d2e1a72fcca58-6f4d2ae0dd5sm441437b3a.135 - gsmtp')

另外，自写的python代码，在同一台vps上，使用同样的配置信息发送邮件一直正常，不知道是不是kindleear的bug。

**Comment by cdhigh** [comment]
Docker镜像和github都已更新，可以测试一下此版本是否已经解决。

**Comment by dmiming2000** [comment]
已解决。
