### ISSUE TITLE
新版有没有自动部署的教程？

### ISSUE THREAD

**Issue by nietulong** [cdhigh/KindleEar#682]
如题。

**Comment by Steven630** [comment]
项目文档写了

https://cdhigh.github.io/KindleEar/Chinese/

**Comment by cdhigh** [comment]
是的，不知我写的太简单，还是太啰嗦，太技术化，还是太模糊。
因为我懂编程，所以我不明白不懂编程的同学应该需要什么样的文档，只能尽力而为。
如果有同学能帮忙优化文档就更感谢了。
文档原文在仓库的docs目录下，是标准的markdown格式。
