### ISSUE TITLE
Auto Deliver is not working.

### ISSUE THREAD

**Issue by ok97465** [cdhigh/KindleEar#685]
Hello. Thank for your great jo.
I set kindleear to auto-deliver at 6am.

<img width="685" alt="스크린샷 2024-05-22 오전 8 00 39" src="https://github.com/cdhigh/KindleEar/assets/22970578/5d3aaa15-b098-403d-bbfe-6ffe2fcc668d">

But it doesn't work.
If I manually hit Delivery in the Advanced Menu, it works fine.

Kindlear is installed on GAE.

Is there any way to resolve the issue?

Have a nice day.

**Comment by cdhigh** [comment]
1. go to [GAE cron console](https://console.cloud.google.com/cloudscheduler) to confirm that the APP ENGINE CRON job has been deployed successfully.
2. go to [GAE logs console](https://console.cloud.google.com/logs/) to confirm that there are logs for the automatic execution of `/deliver`, or to check if exists some exception records.

**Comment by ok97465** [comment]
Thank you for your reply.
I think that that the APP ENGINE CRON job has been deployed successfully.

<img width="1365" alt="스크린샷 2024-05-23 오후 9 54 44" src="https://github.com/cdhigh/KindleEar/assets/22970578/8c4d602a-c818-49c8-8ed7-910c07879a43">

But I can't interpret GAE log. Can you help me?

<img width="1125" alt="스크린샷 2024-05-23 오후 9 55 09" src="https://github.com/cdhigh/KindleEar/assets/22970578/8820334f-f9fe-4585-9144-d139548633f3">

**Comment by cdhigh** [comment]
cron works all.

1. Show all logs in [here](https://console.cloud.google.com/logs/).
2. Try to set 'Oldest article' to 'No limit' or '7 Days' for testing.
3. Which RSS did you use for?
4.

**Comment by Steven630** [comment]
I can confirm that auto-delivery isn't working.

大佬，更新了最新版本，今天还是没有自动投递。

**Comment by cdhigh** [comment]
Found the bug.
This bug doesn't exist in the Docker deployment, I didn't pay attention to it and assumed it was due to your configuration or other issues.
The code has been updated. Please redeploy and test again.

**Comment by nietulong** [comment]
[downloaded-logs-20240524-085139.csv](https://github.com/cdhigh/KindleEar/files/15425506/downloaded-logs-20240524-085139.csv)
我的也是自动推送老是不行，我已经更新到最新版本啦

**Comment by ok97465** [comment]
I updated kindle ears. But It was not working.


- Logs
[downloaded-logs-20240525-091014.json](https://github.com/cdhigh/KindleEar/files/15440896/downloaded-logs-20240525-091014.json)

- feed
https://ok97465.github.io/feed.xml
https://makersweb.net/rss
https://soooprmx.com/feed/
https://ghebook.blogspot.com/feeds/posts/default
http://moordev.tistory.com/rss
http://feeds.feedburner.com/crazytazo
https://news.hada.io/rss/blog
https://v2.velog.io/rss/mythos
http://feeds.feedburner.com/DougHellmann
https://github.com/naver/fe-news/commits/master.atom
http://feeds2.feedburner.com/rss_outsider_dev
http://jeremykun.wordpress.com/feed/
http://feeds.feedburner.com/slownews
http://pinkwink.kr/rss


- Calibre recipe
```python
import re

from calibre.web.feeds.recipes import BasicNewsRecipe

# Comment out sections you are not interested in
sections = [
    ("정치", "politics"),
    ("사회", "national"),
    ("경제", "economy"),
    ("국제", "international"),
    ("사설칼럼", "editorials"),
    ("의학과학", "science"),
    ("문화연예", "culture"),
    ("스포츠", "sports"),
    ("사람속으로", "inmul")
    # Following sections are marked as marked optional
    # as default. Uncomment to enable.
    # , (u'건강', 'health')
    # , (u'레저', 'leisure')
    # , (u'도서', 'book')
    # , (u'공연', 'show')
    # , (u'여성', 'woman')
    # , (u'여행', 'travel')
    # , (u'생활정보', 'lifeinfo')
]


class Donga(BasicNewsRecipe):
    language = "ko"
    title = "동아일보"
    description = "동아일보 기사"
    __author__ = "Minsik Cho"
    ignore_duplicate_articles = {"title", "url"}
    compress_news_images = True
    no_stylesheets = True
    oldest_article = 2
    encoding = "utf-8"

    # RSS Feed in syntax:
    # https://rss.donga.com/[sections].xml
    feeds = [(title, "https://rss.donga.com/" + section + ".xml") for (title, section) in sections]

    # Remove logo and print buttons
    remove_tags = [
        dict(name="div", attrs={"class": "popHeaderWrap"}),
        dict(name="div", attrs={"class": "etc"}),
    ]

    def print_version(self, url):
        # Original url in syntax:
        # https://www.donga.com/news/[sections]/article/all/[date]/[gid]/1
        # Return print version url with syntax:
        # https://www.donga.com/news/View?gid=[gid]&date=[date]
        reobject = re.search("(?<=/all/)([0-9]*)/([0-9]*)", url)
        date = reobject.group(1)
        gid = reobject.group(2)

        return "https://www.donga.com/news/View?gid=" + gid + "&date=" + date
```

**Comment by cdhigh** [comment]
Most of these RSS feeds have their published/updated times more than a week ago, so you need to set Oldest_articles to Unlimit in order to push these RSS feeds.

Some of them can be pushed.
I tested them with auto-push, and successful.

**Comment by ok97465** [comment]
Thank you for your efforts.
The auto deliver is working now.
