### ISSUE TITLE
文档中序号问题及能否部署本地的一些疑问

### ISSUE THREAD

**Issue by HiPlayCode** [cdhigh/KindleEar#686]
![image](https://github.com/cdhigh/KindleEar/assets/168249732/09baf5ad-a3b8-456d-9f00-197b9e810ab5)
文档的部署方法中Docker VPS部分，序号显示有问题，但是代码里的文档是正确的，不知道是否是没及时同步更新。
目前程序是部署到服务器上，通过前端页面配置一些订阅和推送的参数，后台运行。是否可以通过命令行直接设置这些参数，或者直接修改数据库文件，这样就可以直接部署本地，无需服务器，只要能联网即可。

**Comment by cdhigh** [comment]
1. 文档是自动刷新同步的，序号问题好像是markdown 解释器的bug。
2. 所有的配置都可以一两条简单的POST请求就可以完成，所以不使用web端没问题，使用任何工具比如postman或python等发post请求即可，具体POST body可以参考setting.py和subscribe.py。
