### ISSUE TITLE
has no attribute 'get_locale' 

### ISSUE THREAD

**Issue by benben17** [cdhigh/KindleEar#687]
python 3.12
mac os 14.5
执行： python main.py debug 调试模式  
File "/Users/xxx /PycharmProjects/KindleEar/application/__init__.py", line 31, in init_app
    babel.init_app(app, locale_selector=setting.get_locale)
                                        ^^^^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'application.view.setting' has no attribute 'get_locale' (most likely due to a circular import)

**Comment by cdhigh** [comment]
Windows和Linux都没问题，我不太相信是MacOS的问题，是否python3.12修改了什么import机制？
