### ISSUE TITLE
求助：邮件正文转换为邮件附件推送不成功，加了 !article也不行

### ISSUE THREAD

**Issue by nietulong** [cdhigh/KindleEar#688]
系统已经是最新了，邮件也加了白名单。发了邮件过去，没有任何反映。

**Comment by cdhigh** [comment]
GAE还是Docker？

除了白名单，确认入站邮件功能没有被禁用，同时kindle email也需要设置好。

GAE可以看后台LOGS，看是否已经有_ah/mail/address的调用，是否有什么异常记录。

Docker的话，需要使用docker compose并且开放25端口，查看gunicorn.access.log，看有没有 /mail的访问记录，查看gunicorn.error.log看是否有什么异常记录。

**Comment by nietulong** [comment]
> GAE还是Docker？
> 
> 除了白名单，确认入站邮件功能没有被禁用，同时kindle email也需要设置好。
> 
> GAE可以看后台LOGS，看是否已经有_ah/mail/address的调用，是否有什么异常记录。
> 
> Docker的话，需要使用docker compose并且开放25端口，查看gunicorn.access.log，看有没有 /mail的访问记录，查看gunicorn.error.log看是否有什么异常记录。

GAE，确认入站邮件功能没有被禁用，同时kindle email也设置好啦。
[Uploading downloaded-logs-20240527-090943.csv…]()

**Comment by nietulong** [comment]
解决啦，感谢。
