### ISSUE TITLE
使用sendgrid时出现403错误

### ISSUE THREAD

**Issue by wavierwister** [cdhigh/KindleEar#689]
作者，您好。

程序在使用GAE推送时正常，不过，在使用Sendgrid时，出现403 forbidden错误，可否帮忙看看是什么问题？以下是log：

{
insertId: "6654c5a20000a7044ba8defe"
labels: {1}
logName: "projects/febdaily/logs/stdout"
receiveTimestamp: "2024-05-27T17:40:50.353594269Z"
resource: {2}
textPayload: "[send_mail_adpt.py:77] Failed to send mail "纽约时报双语版": HTTP Error 403: Forbidden"
timestamp: "2024-05-27T17:40:50.042756Z"

谢谢！

**Comment by cdhigh** [comment]
一般是因为sendgrid的api key权限不够，或在后台注册的sender和发送邮件使用的sender不一致
登录sendgrid确认api key 权限或确认sender地址。
