### ISSUE TITLE
上传封面图像 error

### ISSUE THREAD

**Issue by Spaiol** [cdhigh/KindleEar#690]
如题，编辑好同样大小的黑白图片，单张多张点击后均报错。

**Comment by cdhigh** [comment]
后台logs显示什么异常

**Comment by Spaiol** [comment]
后台没看到什么异常，用的docker方式架设的，nginx转发https访问。点击上传/更新，新快就弹出error窗口。

**Comment by cdhigh** [comment]
data/gunicorn.error.log?
docker logs containerId?

**Comment by Spaiol** [comment]
可能是浏览器的问题，data/gunicorn.error.log和docker logs没有任何错误记录，使用edge存在上述问题，换了Safari竟然可以了。我再排查一下到底是什么问题，谢谢大佬～
<img width="458" alt="截屏2024-06-01 下午6 56 51" src="https://github.com/cdhigh/KindleEar/assets/16881909/f4b5099a-3e8c-418d-bd50-1e8caeaff9a0">

**Comment by Spaiol** [comment]
嗯，也许大概是哪里设置的问题，打扰您了～
