### ISSUE TITLE
有的recipe的退订和设置投递时间的按键失灵

### ISSUE THREAD

**Issue by zangjingwei** [cdhigh/KindleEar#692]
订阅L'express这个法语recipe后，发现退订按键和设置投递时间按键在点击后没有反应，其他按键可以正常使用。
![IMG_20240605_163651](https://github.com/cdhigh/KindleEar/assets/37979678/0f4a8c3c-0d03-4705-a34b-a57e14d9aefd)
照片中红色框里面这两点按键。

其他订阅可以正常退订，不知为何这个会有这种问题

**Comment by cdhigh** [comment]
这个bug我之前就发现了，也进行了两次修改，第一次解决了单引号问题，第二次解决双引号问题，看来是我第二次修改后测试不全，我只测试了标题包含双引号的情况，忘了重新测试单引号的情况。

**Comment by zangjingwei** [comment]
多谢解答！

**Comment by cdhigh** [comment]
代码已经更新
