### ISSUE TITLE
List style

### ISSUE THREAD

**Issue by ahmbyrm** [cdhigh/KindleEar#694]
hi,

There is no problem with RSS submission. everything works fine, but I think it would be better if you make a correction like this.

You open the RSS file on Kinle, there is a list of RSS content in the Beginning section, but the lines are mixed. List style can be reorganized. Maybe there can be a point at the beginning of the line. Can you check the image I sent in the attachment?

<img width="562" alt="Screenshot 2024-06-09 at 17 31 55" src="https://github.com/cdhigh/KindleEar/assets/6073064/35b3b6c4-bd5f-4cc3-adb1-09dbbcd5e27a">
![Uploading Screenshot 2024-06-09 at 17.31.55.png…]()

**Comment by cdhigh** [comment]
Screenshot is missing.

**Comment by cdhigh** [comment]
How about add some padding?
![increase_padding](https://github.com/cdhigh/KindleEar/assets/2580077/b5300adf-90e1-4273-ae76-9f83beb7570e)

**Comment by ahmbyrm** [comment]
The problem here is not padding. For RSS that comes as a list, there may be a sign at the beginning of the line, there may be a number. in the previous version it looked like this.

<img width="507" alt="Screenshot 2024-06-10 at 19 33 55" src="https://github.com/cdhigh/KindleEar/assets/6073064/bd1bb37e-2813-4869-8368-a9f74b72ad50">

**Comment by cdhigh** [comment]
Calibre removes list symbol in CSS to maximize the valuable space on Kindle's small screen.

**Comment by ahmbyrm** [comment]
I don't think so. KindleEar @1.26.8 does not cause problems with this version. Here is the RSS image I sent with Kindlear version 1.26.8;

![001](https://github.com/cdhigh/KindleEar/assets/6073064/93f816a4-4762-4663-8223-976d7803b5b9)
![002](https://github.com/cdhigh/KindleEar/assets/6073064/c83559b3-b77a-46d1-bd27-e93543b95ef3)

**Comment by ahmbyrm** [comment]
got it. the code you wrote is much better :)

**Comment by cdhigh** [comment]
Haha, Calibre's better~

If you really want the list item symbol to come back, you can add an item in "Advanced" / "Calibre Options":

```json
{
  "extra_css": "li {list-style-type: circle;}"
}
```

If you find this TOC annoying, you can remove it, and it will be replaced by another type of TOC:

```json
{
  "epub_inline_toc": false
}
```

**Comment by ahmbyrm** [comment]
:)

thank you.
