### ISSUE TITLE
雪球-RSS的排版问题

### ISSUE THREAD

**Issue by dmiming2000** [cdhigh/KindleEar#695]
通过RSS订阅网友分享的 今日话题-雪球， https://xueqiu.com/hots/topic/rss 
最近推送到kindle上的电子书格式很乱，有很多编码。
不知道能否抽时间修正下。
谢谢。

**Comment by cdhigh** [comment]
雪球 已修正。

关于资源的问题，recipe是网友们共同维护的，英文资源多是因为英文的网友贡献的多。
对比于KindleEar1.x版本，在3.x版本，我之所以耗费很大心血让KindleEar能直接支持Calibre的recipe也是基于资源数量考虑。

calibre的中文资源少要不是因为calibre的中文使用者不喜欢使用recipe抓取功能，要不就是写了recipe不分享出来。

calibre官方的 [recipe论坛](https://www.mobileread.com/forums/forumdisplay.php?f=228) 在这里。

**Comment by zangjingwei** [comment]
谢谢解答
