### ISSUE TITLE
疑似bug，自定义推送时间无法保存。

### ISSUE THREAD

**Issue by dmiming2000** [cdhigh/KindleEar#696]
recipe的订阅中可以按书自定义推送时间。
admin用户中可以正常使用。
但对于第二/三个用户，在自定义推送时间时，可以正常选择自定义的时间，也会提示保存成功，但实际不成功，刷新页面之后就会发现未保存，也无法按照自定义去执行。

**Comment by cdhigh** [comment]
已修正

**Comment by dmiming2000** [comment]
已经好了，谢谢。

**Comment by dmiming2000** [comment]
但很奇怪的是，现在admin账户下的在线阅读一片空白，其他账户下的在线阅读倒是正常的。
在主机上，确认admin账户下是有保存电子书籍的。

**Comment by cdhigh** [comment]
我今天打开在线阅读也发现了这个问题～

原因是昨天更新了版本，修改了一个参数，从字符型转换为整形，没有完整测试导致，Docker已经更新，版本号不变，重新pull就好～

**Comment by dmiming2000** [comment]
我不是docker版本，是vps上直接部署的

**Comment by cdhigh** [comment]
那直接clone代码就好

**Comment by dmiming2000** [comment]
希望增加一个选项，在线阅读时可以将左边的目录最小化缩起，方便阅读。

**Comment by cdhigh** [comment]
ok, 以后考虑，后端我游刃有余，但是主要是我的前端技能太差了，很多界面上的事情对我来说太难了～
估计你看到KindleEar界面就知道我是什么水平～

**Comment by dmiming2000** [comment]
好的，非常感谢。

**Comment by cdhigh** [comment]
因为水平有限，其实我刚开始就没打算PC和kindle两套界面，初始版本PC上也是和Kindle一样自动隐藏导航栏的，后来发现PC上显示效果不好，相当与横版看书，因为去除了真实网页上的各种辅助元素，只剩正文内容，导致很多文章就半屏都不到，感觉完全没有读书的感觉，后来就将PC界面的导航栏固定住，这样视觉上才大体相当于竖起来的一本书。

不过众口难调，理解

**Comment by dmiming2000** [comment]
已经很好了，辛苦了

**Comment by cdhigh** [comment]
界面参考reabble，但是他更狠，PC上分成三栏。

具体实现没有使用到他的任何代码，因为他没有开源，并且代码已经混淆，无法阅读，我花了不少功夫自己琢磨不停尝试才在Kindle上实现这些功能（PC容易，现代浏览器支持特性完备），在Kindle上实现这些功能简直折磨，Kindle浏览器功能简陋，阉割严重，无法调试，所以可以理解reabble不开源，毕竟真的有一些技术含量在里面。

**Comment by cdhigh** [comment]
如果你直接部署VPS，而不是Docker，这个版本添加在线阅读的词典功能需要额外的依赖，请更新依赖:
<code>
python update_req.py Docker
</code>
否则无法查询单词变形，离线词典mdict/stardict也无法使用

**Comment by dmiming2000** [comment]
看了下update_req.py docker，这部分代码貌似是更新docker的呀

**Comment by cdhigh** [comment]
用于更新requeriments.txt，之后就可以安装依赖，后续依赖库版本的更新我也会编码到update_req.py。
pip install -r requeriments.txt

docker配置适用于VPS，如果是arm64，可以使用
python update_req.py dockerArm

现在两个架构的依赖一样了，是因为我自己编译了hunspell放到pypi上了，不过以后保不准如果有其他平台不同的依赖项

**Comment by dmiming2000** [comment]
在看到这个回复之前，我已经这样操作了一把。
然后发现之前的配置数据都没了，哦哦

**Comment by cdhigh** [comment]
是的，同时也会修改config.py，所以修改你的config.py就好，不过数据库不会丢失，修改为正确的数据库配置然后数据就都回来了

**Comment by dmiming2000** [comment]
DATABASE_URL = "sqlite:////data/kindleear.db"
我看数据库也还是本地的数据库呀

**Comment by dmiming2000** [comment]
OK，改回来了

**Comment by dmiming2000** [comment]
疑似另外一个bug，多用户情况下：
同样一本书，例如time magzine，在admin用户下生成的书只有7M，到另外一个用户下生成的书有27.6M，导致邮件发送失败。

**Comment by cdhigh** [comment]
文件大小主要取决于图像大小，而图像大小取决于配置页的 设备 类型，图像会缩小分辨率到设备的分辨率。
两个账号的设备设置一样吗

**Comment by cdhigh** [comment]
我在界面上增加一个提示好了。

**Comment by dmiming2000** [comment]
问题已解决，非常感谢。
