### ISSUE TITLE
原来有个“我需要翻墙（针对中国用户）”的选项，新版找不到了，有些网站抓不到内容

### ISSUE THREAD

**Issue by windcat007** [cdhigh/KindleEar#697]
rt

**Comment by cdhigh** [comment]
如果需要墙内新闻，其实更建议的是在墙内找一个主机部署，比如阿里云腾讯云之类。
现在基本能支持大部分的云平台

**Comment by windcat007** [comment]
啊，那我理解错了，我还以为是境外的网站需要这个功能。
除了gae还有什么免费平台推荐吗？

**Comment by cdhigh** [comment]
就是因为gae的免费额度不够我才离开的，一旦开始正常使用，基本上每个月都会产生一些费用。

我现在使用Oracle cloud VPS，非常好用，免费额度非常慷慨，而且不用担心会被扣费（Oracle承诺不升级账号就绝不会扣费），不过根据很多网友的反馈，需要一些运气才能抢到免费机器（我抢了两台，用了一段时间我归还了一台，就当公益～）。
微软/Amazon都提供12个月的免费试用，过期后会有一些免费额度，我没有详细了解其免费额度是否够用，如果你抢不到Oracle的机器可以去了解一下。
选择大公司平台有个好处就是不用担心被乱扣费。

搜索就会发现，各种“小”公司的云平台多如牛毛，只是因为是小公司，所以一般情况下的“免费”计划都是残疾的，可能运气好能找到个别平台没有那么多陷阱，但确实很难能找到真正免费又能顺畅使用的平台。

如果能接受每个月几块钱的花费，可以考虑购买一个VPS，1核1G内存就够用了，省心省力，一劳永逸。

如果你需要KindleEar的在线阅读功能的话，就更需要VPS了，在GAE上无法开启。

如果主要是墙内信息，则购买墙内VPS，如果主要是墙外信息，则购买墙外VPS。

**Comment by windcat007** [comment]
非常感谢！！

**Comment by windcat007** [comment]
非常感谢！
