### ISSUE TITLE
疑似新版本有bug，之前可以正常推送的书籍无法推送了。

### ISSUE THREAD

**Issue by dmiming2000** [cdhigh/KindleEar#699]
vps部署，前天看到有版本更新修正了安全问题，就更新了下。
问题描述：
1、按天订阅了多本书，有几本无法正常推送，也没有报错。
后台看了下日志，提示：  There are no new feeds available: admin: []
同样的recipe，手工执行calibre的ebook-convert指令，是可以正常抓取的。
2、在高级设置里，手工推送一些杂志成功； 
但手工推送 Techcrunch等仍然失败，后台日志也是提示： There are no new feeds available: admin: []

**Comment by cdhigh** [comment]
是引入的一个bug, 已修正

**Comment by dmiming2000** [comment]
已OK
