### ISSUE TITLE
Google cloud扣费

### ISSUE THREAD

**Issue by zangjingwei** [cdhigh/KindleEar#701]
布置新的kindleear后，已经连续两个月扣费0.06美元，是推送的量多了吗？减少推送可以不扣费？

**Comment by cdhigh** [comment]
是多次重复部署导致代码库超过免费额度导致，大约一个星期前更新了部署脚本，随便将缓存的代码库删除，就不会再扣费了。
重新部署一次即可。
也可以手动到artifacts registry 里面将代码库删除。

**Comment by zangjingwei** [comment]
好的，我去重新部署一下，谢谢解答
