### ISSUE TITLE
请教Failed to execute recipe: list index out of range

### ISSUE THREAD

**Issue by Steven630** [cdhigh/KindleEar#702]
[recipe_input.py:94] Failed to execute recipe "Laos RFA": list index out of range

```
#!/usr/bin/env python3
# -*- coding:utf-8 -*-
from calibre.web.feeds.recipes import BasicNewsRecipe

class AdvancedUserRecipe1723469468(BasicNewsRecipe):
    __created_date__ = "2024-08-12"
    title = "Laos RFA"
    description = "A selection of news from and about Laos."
    encoding = "utf-8"
    language = "en"
    max_articles_per_feed = 10
    oldest_article        = 7
    auto_cleanup = False
    keep_images = False
    use_embedded_content = True

    feeds = [
        ("Laos RFA", "https://www.rfa.org/english/news/laos_news/rss2.xml"),
    ]
```

这个是全文RSS，不知道为什么失败。用的是3.0.7版本。

**Comment by cdhigh** [comment]
在Oracle测试显示403错误（Forbidden），无法调试。

你可以协助定位，在Caibre配置里面添加，然后将错误log记录贴上来。
```json
{
  "log_level": "debug"
}
```

**Comment by Steven630** [comment]
已经加了这个参数，不过日志好像没有更具体：

 [recipe_input.py:94] Failed to execute recipe "Laos RFA": list index out of range

[plumber.py:394] Failed to execute input plugin: All feeds are empty, aborting.

[worker.py:149] There are no new feeds available: admin: [Laos RFA]

**Comment by cdhigh** [comment]
那说明你的版本太老了，可以升级再试，我已经更新了部署脚本，重复升级不会再导致扣费了

**Comment by Steven630** [comment]
好的，现在是不是不能再用筛选recipe语言的代码了？

**Comment by cdhigh** [comment]
是的，主要是我不想参数太复杂

**Comment by Steven630** [comment]
"[news.py:1960] Failed feed: Laos RFA: Exception Cannot fetch https://www.rfa.org/english/news/laos_news/rss2.xml:403 [news.py:1957->...->news.py:1957->news.py:1957]"

**Comment by cdhigh** [comment]
我记起来了，之前的下标越界问题之前就修正了。
Rfa无法获取的原因是其网站有强力的反爬虫，KindleEar 只有比较简单的反爬虫欺骗手段，暂时无法突破其封锁。

**Comment by Steven630** [comment]
官方提供的全文RSS也反爬虫吗？好吧……

**Comment by cdhigh** [comment]
它这个反爬虫是针对整个网站的，可能技术人员忘了将rss地址单独列为白名单。

**Comment by Steven630** [comment]
哎，那没办法了。以前知乎转发器的原理怎么才能用到新版本呢。能否麻烦做个示范的recipe？感觉转发器还是可以解决不少ip地址被封锁的问题

**Comment by cdhigh** [comment]
1. 我已经更新代码，在http头里面再添加一行，更模拟浏览器访问，现在已经可以爬取rfa了。

2. 如果你在其他服务器上搭建有转发器，在KindleEar新版本中也可以使用，比如
假如你的转发器地址为 `http://example.com`，则修改recipe中的feed地址为下面的形式：
```python
feeds = [
    ("Laos RFA", "http://example.com/?k=xzSlE&t=60&u=https://www.rfa.org/english/news/laos_news/rss2.xml"),
]
```
只是注意的一点是转发器仅针对反爬虫里面的“封禁IP”，反爬虫还有很多其他多样化的措施。
这个issue里面的rfa的反爬虫就不是封禁IP。

3. 技术发展很快，现在的serverless技术路线更适合“转发”用途，简单来说就是一个javascript脚本，不需要配置服务器，cloudflare会将这个脚本自动部署到全球多个CDN服务器，我也更新了转发器仓库，添加cloudflare的worker实现。

4. KindleEar可以搭配RSSHUB使用，在自己写RSS抓取代码前，可以先到RSSHUB搜索是否已经有特定的内容了。

**Comment by Steven630** [comment]
太感谢了！这两天试试。最新的commit右侧显示红色的叉（failure），不知道会不会有影响？

**Comment by cdhigh** [comment]
那个是Github action的执行结果，现在表示项目文档自动更新失败（从*.md自动编译为*.html），和代码没有关系。

至于文档为何更新失败，可能某个编译依赖有变化或系统环境出错之类的，可能下次就好了。


PS：新的部署脚本每次执行都会抓取最新的Calibre Recipe，所以以后calibre的某些recipe有更新，重新执行部署脚本即可同步到你的项目。

**Comment by cdhigh** [comment]
在dashboard里面有 "Visit" 按钮，就是链接，如果出错，可以看dashboard里面的logs

直接访问链接至少会返回
```
Auth Key is invalid!
```

**Comment by Steven630** [comment]
直接访问提示 Auth Key is invalid

加上RFA的RSS链接和验证码后提示：Request failed!<br/>AbortError: The operation was aborted

**Comment by Steven630** [comment]
刚才又试了一下，应该是可以了。

**Comment by Steven630** [comment]
RFA源用了全文rss，推送到Kindle上图片说明的文字会超出Kindle边界，不知道为什么。

另外转发器打开纽约时报的链接是空白，比如：https://www.nytimes.com/2024/08/12/us/politics/us-china-working-group-trade.html

**Comment by cdhigh** [comment]
1. RFA的img越界是因为在html里面指定了width/height，我已经更新代码，将img的这些属性删除。
2. 转发nytimes其实已经成功了，只是nytimes反爬虫机制发挥作用了，返回的源码中有提示：
```
Please enable JS and disable any ad blocker
```

毕竟我们这个转发器是一个轻量化定制化的工具，不是完整的代理服务器，所以应用场景比较有限，
比如如果返回的html内容的图像文件是相对路径的话，就无法获取到图像，这时候可能你需要重载 `BasicNewsRecipe` 的函数 `image_url_processor()` 来返回正确的图像url。

不管怎么样，区区几十行代码就可以解决我们面临的特定问题，还算一个好工具吧。

**Comment by Steven630** [comment]
这两天Calibre好像更新了抓取的代码，看到mobileread作者和网友讨论Science recipe时提到会更新：https://www.mobileread.com/forums/showthread.php?t=362642

![Screenshot_20240815_223334.jpg](https://github.com/user-attachments/assets/00e5c1e2-f9d4-4b5d-915e-b301ff65debc)

**Comment by cdhigh** [comment]
Qt是桌面技术，不能在服务器环境使用。

**Comment by cdhigh** [comment]
经过搜索，发现兼容requests的库niquests已经支持http1.1/2/3，所以之后如果确实有需求，改一行代码就可以了。

**Comment by cdhigh** [comment]
好的，等他发布稳定版本，然后你需要哪个recipe在KindleEar里面无法获取，可以提issue，我看是否能解决。

**Comment by Steven630** [comment]
用这个NYT的recipe：https://github.com/kovidgoyal/calibre/blob/master/recipes/nytfeeds.recipe

抓取：https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/topic/destination/china/rss.xml

错误提示：
[simple.py:649] Could not fetch link https://www.nytimes.com/2024/09/23/opinion/iron-air-battery-china.html: NameError name 'datestring' is not defined [simple.py:604->...-><string>:68->iso8601.py:16]

[recipe_input.py:89] Failed to execute recipe "NYT News": ValueError No articles downloaded, aborting [recipe_input.py:87->...->news.py:1249->news.py:1562]

**Comment by cdhigh** [comment]
已经修正

**Comment by Steven630** [comment]
上传封面图片，20kb左右的jpg格式，总是提示error，不知道为何

**Comment by cdhigh** [comment]
如果没有具体的原因文字描述，大概率是浏览器的问题

**Comment by Steven630** [comment]
原来用的Chrome，确实换成edge就可以了。

今天NYT又有下面的错误，是触发了反爬虫机制吗

Traceback (most recent call last): File "/workspace/application/lib/urlopener.py", line 110, in open_remote_url resp = req_func(url, data=data, headers=headers, timeout=timeout, allow_redirects=True, File "/layers/google.python.pip/pip/lib/python3.10/site-packages/requests/sessions.py", line 602, in get return self.request("GET", url, **kwargs) File "/layers/google.python.pip/pip/lib/python3.10/site-packages/requests/sessions.py", line 589, in request resp = self.send(prep, **send_kwargs) File "/layers/google.python.pip/pip/lib/python3.10/site-packages/requests/sessions.py", line 703, in send r = adapter.send(request, **kwargs) File "/layers/google.python.pip/pip/lib/python3.10/site-packages/requests/adapters.py", line 682, in send raise ConnectionError(err, request=request) requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by cdhigh** [comment]
是的，可以考虑将recipe的simultaneous_downloads设置为1，关闭多线程下载。
如果还不够，再考虑设置一个合理的delay值，单位为秒，但是可以使用浮点数表示小于一秒的网络抓取间隔。

**Comment by Steven630** [comment]
> 是的，可以考虑将recipe的simultaneous_downloads设置为1，关闭多线程下载。
> 如果还不够，再考虑设置一个合理的delay值，单位为秒，但是可以使用浮点数表示小于一秒的网络抓取间隔。

好的。有的recipe重新抓一次就又可以了，能不能考虑遇到网络问题抓取失败，加个10分钟后自动重新下载的功能，让用户选择是否开启。

主页面的日志，no news提示更详细点，分为两类，一类是真的没有更新的文章，一类是因为网络或页面失败抓取失败。

**Comment by cdhigh** [comment]
如果使用GAE平台，估计被封锁的概率会大一些，因为很多应用实例会共享一个IP。
至于你提到的修改，需要有一定的修改量，等什么时候合适的机会再考虑。

**Comment by Steven630** [comment]
> 如果使用GAE平台，估计被封锁的概率会大一些，因为很多应用实例会共享一个IP。
> 至于你提到的修改，需要有一定的修改量，等什么时候合适的机会再考虑。

好的，发现Economist Espresso有时候推送不了，再手动推送一次就会成功

**Comment by Steven630** [comment]
Calibre官方src/calibre/web/site_parsers/nytimes.py 最近有更新，能否同步一下？

**Comment by cdhigh** [comment]
已经同步

**Comment by Steven630** [comment]
谢谢！

[news.py:1908] Failed to download article:Spooky Pizza Party from https://kids.nationalgeographic.com/books/article/spooky-pizza-party

National Geographic Kids提示上述错误

**Comment by cdhigh** [comment]
缺了一个文件，已补上，National Geographic可以正常推送，
Kids还是出错，需要修改其recipe或natgeo.py，可以考虑给calibre仓库提交pull request

**Comment by Steven630** [comment]
昨天更新之后我订阅的所有的recipe都推送失败，今天又同步到最新的commit，又试了一次，也是一样。

错误提示都是
[news.py:1908] Failed to download article:Mongolia and China Celebrate 75 Years of Partnership from https://thediplomat.com/2024/10/mongolia-and-china-celebrate-75-years-of-partnership/

该不会是GAE的限制吧

**Comment by cdhigh** [comment]
同步calibre代码时不小心多同步了一点，已修正。

部署脚本里面会更新pip，保持最新总是好事。

**Comment by cdhigh** [comment]
如果不想更新pip，可以删除gae_deploy.sh里面的行 `pip3 install --upgrade pip`

KeyError 'text' [simple.py:615->...->natgeo.py:161->natgeo.py:115]
要不需要更新natgeo.py，要不就是需要更新recipe文件。

**Comment by Steven630** [comment]
倒不是不想更新，就是不知道为什么更新过了同一个版本下次还会更新……

**Comment by cdhigh** [comment]
不用纠结，更新的是部署环境的pip，而不是运行环境的pip，部署环境是临时的，google随时恢复其默认值。

**Comment by Steven630** [comment]
好的，明白啦

**Comment by Steven630** [comment]
大佬，突然有个脑洞有点大的想法。目前Google Gemini的api是免费的，不知道能不能让Gemini（或者其他AI，用户设置api）总结或翻译抓取的文章内容，再一起推送呢。比如，每篇文章前生成一百字的摘要等等。是不是有点不切实际

**Comment by cdhigh** [comment]
可以考虑以后是否可以实现。

**Comment by Steven630** [comment]
谢谢！最近Calibre news.py又有更新

**Comment by cdhigh** [comment]
AI总结摘要功能已经实现，如果感兴趣，可以试用，有BUG应该是正常的。
现在很多AI都有免费额度，只有Openai/Anthropic两个服务没有免费额度（所以其代码尚未测试），
Gemini/Grok/Mistral/Groq都有免费额度，都已经测试通过。

我自己应该是不会使用 “AI总结” 功能的。
不过我一直在使用 “双语翻译” 功能，搭配 微软翻译 引擎，翻译质量尽管不好，但对外文新闻阅读帮助很大，有些句子每个字都认识，但怎么都看不懂，看翻译原来恍然大悟。

经过对比， 微软翻译 比 google翻译 质量要好不少。

**Comment by Steven630** [comment]
好快啊，这个功能GAE上也能用吗？

**Comment by cdhigh** [comment]
可以，不涉及磁盘读写

**Comment by Steven630** [comment]
谢谢！太厉害了，那么快就能实现。具体是更改recipe还是在界面里设置呢？

**Comment by cdhigh** [comment]
点每个自定义rss或recipe的汉堡菜单就看到了，就是图标为Ai的按钮。

**Comment by Steven630** [comment]
明白，这两天试一试。

prompt建议：

Please summarize the text in its original language, highlighting key information, arguments, and conclusions. Ensure clarity and accuracy while keeping the summary within {summarySize} words.

Improve and update the summary of the article based on the text below, highlighting key information, arguments, and conclusions. Keep the summary in the original language and ensure clarity and accuracy.

**Comment by Steven630** [comment]
摘要还会和正文不一致？论文这样的吗？

Improve and update the summary of the article based on the text below, highlighting key information, arguments, and conclusions. Keep the summary in the same language as the original article/the text below and ensure clarity and accuracy.

**Comment by cdhigh** [comment]
摘要和正文不一致是多有用的功能啊，比如看一篇外文之前先用自己熟悉的语言快速确认这篇文章值不值得花时间去读。

考虑文章可能太长，需要分块，所以prompt需要仔细设计，我看你对prompt比较有经验，帮忙按照这个格式完善好了。
第几块“Text block {i + 1”的信息还是建议保留，因为不同分块请求会有cookie，有部分AI服务有可能能使用到这个信息。

```python
lang = self.params.get('summary_lang', '')
if lang:
    summaryTips = f"Please refine or update the summary based on the following text block, ensuring the summary is in the language: {lang}, and make it more accurately reflect the article content:\n\n"
else:
    summaryTips = f"Please refine or update the summary based on the following text block, ensuring the summary is in the same language as the article/preset summary, and make it more accurately reflect the article content:\n\n"

summary = None
errMsg = None
for i, chunk in enumerate(chunks[:maxIterations]):
    prompt = (
        f"The current summary is:\n{summary}\n\n{summaryTips}"
        f"Text block {i + 1}:\n{chunk}\n\n"
        f"Please generate an updated summary of no more than {summarySize} words."
    )
    try:
        summary = self.aiAgent.chat(prompt)
    except Exception as e:
        errMsg = str(e)
        break
    if interval > 0:
        time.sleep(interval)

```

**Comment by Steven630** [comment]
```
lang = self.params.get('summary_lang', '') if lang: summaryTips = f"Please improve and update the existing summary of the text block(s) in the language of {lang}, distilling key information, arguments, and conclusions:\n\n" else: summaryTips = f"Please improve and update the existing summary of the text block(s) in the original language, distilling key information, arguments, and conclusions:\n\n" summary = None errMsg = None for i, chunk in enumerate(chunks[:maxIterations]): prompt = ( f"The existing summary:\n{summary}\n\n{summaryTips}" f"Text block {i + 1}:\n{chunk}\n\n" f"Please keep the summary within {summarySize} words and ensure accuracy and clarity." ) try: summary = self.aiAgent.chat(prompt) except Exception as e: errMsg = str(e) break if interval > 0: time.sleep(interval)
```

不知道这样可否

**Comment by cdhigh** [comment]
这是长文总结的refine方式，有多种方式，我认为这种方式比较好。

已经升级，提供自定义prompt选项，如果不满意，可以自己写，何况说不定有人不想总结文章，而是让AI帮忙列出文章的生词呢？

**Comment by Steven630** [comment]
> 这是长文总结的refine方式，有多种方式，我认为这种方式比较好。
> 
> 已经升级，提供自定义prompt选项，如果不满意，可以自己写，何况说不定有人不想总结文章，而是让AI帮忙列出文章的生词呢？
> 

能自定义真不错，这样就提供了无穷的可能

**Comment by Steven630** [comment]
再请教一下，如果开启了AI摘要，是会增加谷歌的backend instance hours？会有超额的风险吗？推送所需时间会变长吗。现在一般从任务启动到发送邮件一两分钟就行，开启AI之后大概需要多久？

**Comment by cdhigh** [comment]
实例小时数增加主要有两个因素
1. 开启AI后，多线程下载文章自动被禁止，变成单线程下载
2. AI的每分钟请求数不是很高，导致两次请求间需要延时

增加多少不好说，大概5倍？
测试一次然后看后台就知道了，反正如果订阅不多，其实也不用担心实例小时超限。

**Comment by Steven630** [comment]
明白了。下载文章能否继续多线程，等下载完了再单线程让AI分析？

如果某个recipe里包含多个RSS链接，可以只对其中几个摘要吗？

**Comment by Steven630** [comment]
这个issue又长了，谢谢您一直不厌其烦回答，以后我尽量一个话题一个issue。
