### ISSUE TITLE
报错 (-1, b'\x00\x00\x00')

### ISSUE THREAD

**Issue by Jun3101** [cdhigh/KindleEar#703]
你好，在群晖上重新配置了Kindleear，发送测试邮件，显示(-1, b'\x00\x00\x00')。邮箱里可以看到邮件。AMAZON上也可以收到推送的文档，但是Kindle上却打不开这个文档，会停留在“已加入队列”这个状态，有点奇怪。其它的书籍推送，KINDLE是可以打开的。请问这个是怎么回事呢？

**Comment by cdhigh** [comment]
你的意思是只有测试邮件出问题？
我感觉是amazon认为这个邮件是垃圾邮件之类的？
可能因为测试邮件内容太简单了，根本不像书籍或新闻之类的？

**Comment by Jun3101** [comment]
不是的，推送也是这样的。我推了个南方周末，可以看到，就是打不开。
![屏幕截图 2024-11-17 115706](https://github.com/user-attachments/assets/5c501653-e2d0-43ad-ad17-7da1d113bc74)

**Comment by Jun3101** [comment]
开始用QQ邮箱，不知道是不是加密的原因，报错。现在更换到163，不加密，可以推送成功了。不过还是奇怪，在KINDLE上还是打不开，一直停留在”已加入队列“。我检查了推送的EPUB，是正常的。我再看看吧，再次感谢。

**Comment by cdhigh** [comment]
可以考虑sendgrid或mailjet

**Comment by Jun3101** [comment]
好像是KO3的系统更新有了问题了，书伴上也有人在抱怨，where is my life也打不开了，前两天还是可以的。再次感谢！过几天如果有更新了，再反馈给你。
