### ISSUE TITLE
RSS订阅，推送说no news

### ISSUE THREAD

**Issue by Jun3101** [cdhigh/KindleEar#704]
你好，
比如这个 https://rsshub.app/ftchinese/simplified/hotstoryby7day，

推送的时候显示no news。不知道是哪里设置不对。
能订阅，显示是有内容的。

KindleEar的版本是3.2。

**Comment by cdhigh** [comment]
我测试是正常的，不管是否使用 "全文RSS"。
rsshub生成的rss建议使用 "全文RSS"。

还有，修改“最旧文章”配置看看？

**Comment by Jun3101** [comment]
使用了全文RSS了，最旧文章选了不限制，还是显示no news，真的有点儿奇怪了。网友分享也不行，现在看下来，只有南方周末和人民日报可以，难道是因为墙了？

**Comment by cdhigh** [comment]
能看log吗，看是什么错误

**Comment by Jun3101** [comment]
> 能看log吗，看是什么错误

不好意思，不熟docker，怎么看？我试试去查一下。

**Comment by cdhigh** [comment]
刚升级了3.2.1，支持设置代理服务器，看是否能解决。
不过免费稳定的代理服务器不好找，需要自己搭建或购买。

**Comment by Jun3101** [comment]
可以了，我再多测试一些网址看看，谢谢！
