### ISSUE TITLE
chorme插件发送到kindle报错

### ISSUE THREAD

**Issue by A11Might** [cdhigh/KindleEar#705]
使用docker部署了kindleear，使用chorme插件发送到kindle功能报错Internal Server Error
- 插件配置的网址是http://localhost
- docker日志
![image](https://github.com/user-attachments/assets/ff780728-1dc3-4bbd-bef4-7d0e16ff8025)

**Comment by cdhigh** [comment]
已经修正，docker已更新

**Comment by A11Might** [comment]
> 已经修正，docker已更新

使用`ke-docker.sh`脚本重新安装后，发送到kindle功能报错Fetch url failed:，但我在容器中请求目标链接是可以的，不确定是否是配置问题
- 插件配置
![image](https://github.com/user-attachments/assets/08a30b21-82ce-4d48-a47f-fd697ba1827e)

另外插件时已经完成了相关配置，但使用时还有弹出让填写配置的选项

**Comment by cdhigh** [comment]
1. 尝试使用高级设置里面的代理服务器页面上面的测试栏看KindleEar是否能正常抓取对应的网页
2. 插件的配置问题是否和权限/缓存什么的有关？
