### ISSUE TITLE
RSS订阅，单独订阅时不能单独指定发送时间

### ISSUE THREAD

**Issue by Jun3101** [cdhigh/KindleEar#706]
RSS订阅，单独订阅时不能单独指定发送时间。而新闻源recipe是可以的。请问能否增加RSS指定发送时间的功能？

**Comment by cdhigh** [comment]
其实也有历史因素在里面，python2版本时将所有的自定义RSS都当成一本单独的“书籍”，不能单独推送某个自定义RSS，现在python3版本添加了可以独立推送单个自定义RSS的功能，但是也只是在生成和推送时单独处理而已。
里面的数据结构等基本还沿用以前的结构，所以这个功能需要稍多一些的改动，暂时不会支持这个特性。

如果需要指定自定义RSS的发送时间，有两个方法，任选一个：
方法1： 新建一个账号
方法2： 将rss地址放入一个recipe，然后上传到KindleEar，就几行语句，也不难，不需要会Python，比如：

```python
from calibre.web.feeds.news import BasicNewsRecipe
class RecipeName(BasicNewsRecipe):
    title = 'xxx'
    description = 'xxx'
    oldest_article = 7
    language = 'zh'
    feeds = ['https://host/rss.xml']
```

**Comment by Jun3101** [comment]
搞定了，还有一个小问题，就是文章的标题，刚推送到Kindle上，可以看到是哪个内容。当下载出现封面后，就看不到了。这个有没有什么办法，或者不要封面？封面显示具体的推送？比如FT中文网一周十大热门文章之类的？

**Comment by cdhigh** [comment]
现在就有不推送封面的设置，不过只适用于recipe，设置属性 cover_url = False 就可以

```python
from calibre.web.feeds.news import BasicNewsRecipe
class RecipeName(BasicNewsRecipe):
    title = 'xxx'
    description = 'xxx'
    oldest_article = 7
    language = 'zh'
    cover_url = False
    feeds = ['https://host/rss.xml']
```

**Comment by Jun3101** [comment]
万分感谢！！！
