### ISSUE TITLE
单独推送应该怎么设置？

### ISSUE THREAD

**Issue by Jun3101** [cdhigh/KindleEar#707]
单独推送和设置里基本推送，应该怎么设置？

自动推送如果打开的话，是什么优先级高呢？
我关掉了自动推送，发现单独推送也没有打开。

另外，单独推送的时间，是哪个时区的？

谢谢！

**Comment by cdhigh** [comment]
自动推送的意思是你不用每次点击就可以定时推送，是总开关。
单独推送的意思是这个源产生单独一本书籍。
时区设置在页面上有。

**Comment by cdhigh** [comment]
正确

**Comment by Jun3101** [comment]
遇上一个奇怪的事，https://feedx.net/rss/nytimesdual.xml，纽约时报双语版，我手动推送都是正常的，但是每天早上自动推送，就说no news，已经两天了，这个是什么原因呢，谢谢！

from calibre.web.feeds.news import BasicNewsRecipe
class RecipeName(BasicNewsRecipe):
    title = '纽约时报双语版'
    description = 'feedx'
    oldest_article = 7
    language = 'zh'
    cover_url = False
    feeds = ['https://feedx.net/rss/nytimesdual.xml']

**Comment by Jun3101** [comment]
看不到log，是需要专门打开吗？
![屏幕截图 2024-11-27 184043](https://github.com/user-attachments/assets/23703389-5f07-4d9c-9989-707e9af726bb)

**Comment by cdhigh** [comment]
改了USE_DOCKER_LOGS，发现启动不了，我已经撤销了此更改，还是需要查看 /data/gunicorn.error.log

**Comment by Jun3101** [comment]
昨天重新部置了代理服务器，今天推送正常了。谢谢！
