### ISSUE TITLE
Failed to save the recipe. Error:No module named 'calibre.scraper'

### ISSUE THREAD

**Issue by Steven630** [cdhigh/KindleEar#708]
上传最新Economist的时候出现错误：Failed to save the recipe. Error:No module named 'calibre.scraper'

**Comment by cdhigh** [comment]
scraper是qt的web引擎，无法在没有gui的web服务器上运行

**Comment by Steven630** [comment]
> scraper是qt的web引擎，无法在没有gui的web服务器上运行

那有什么其他的办法吗

**Comment by Steven630** [comment]
> 自己修改一个不使用scraper的版本就好

请教该怎么改？
看recipe里面好像也没有出现scraper这个词啊

**Comment by cdhigh** [comment]
如果没有，可能是间接导入的，反正一个recipe就几个导入，顺藤摸瓜很快就可以找到，顺便训练一下读代码跟踪代码的能力，这个能力比写代码的能力还重要～

**Comment by cdhigh** [comment]
修改成功了吗？
大体上就是使用urlopener替代Browser即可
read_url() 修改为 urlopener.open()

我已经升级版本，新增一个假的scraper，可以测试一下。

**Comment by Steven630** [comment]
谢谢！我这两天测试一下

**Comment by Steven630** [comment]
这次可以了，谢谢大佬
