### ISSUE TITLE
微信公众号文章图片无法获取

### ISSUE THREAD

**Issue by DereckZhang** [cdhigh/KindleEar#93]
发现一个问题，微信公众账号里的文章，把链接发送到xxx@appid.appspotmail.com后其中的图片无法抓取。。。如“http://mp.weixin.qq.com/s?__biz=MzA5NDU1MTYxNw==&mid=200298264&idx=1&sn=1f79891c0f3634c8d42960b03c5ec91d&key=bdc0fc08be7dd6d4c8246cf3fc6f6f2c84225648b932e7e713f18646ec7cb7053db671625ff5a120b315be688ebde01a&ascene=7&uin=NTE1MjYzNjk1”试过大量微信公众账号的文章都不行，有解决的办法吗？

**Comment by freeshineit** [comment]
应该是赖加载和防盗链设置
